# Generator of w03-positive.cypher (python3, stdlib only). Re-running rewrites the fixture byte-for-byte.
import hashlib, json
OUT='/home/user/biotech-meta/docs/schema/ontology-lab/final-proposal-team/run-2026-10-04-fable51-01/workers/W03/fixtures/w03-positive.cypher'
def h(uid): return 'sha256:'+hashlib.sha256(uid.encode()).hexdigest()
def q(v):
    if v is None: return 'null'
    if isinstance(v,bool): return 'true' if v else 'false'
    if isinstance(v,(int,float)): return repr(v)
    if isinstance(v,list): return '['+', '.join(q(x) for x in v)+']'
    if isinstance(v,str) and v.startswith('@'): return v[1:]   # raw cypher expression
    return "'"+v.replace("\\","\\\\").replace("'","\\'")+"'"
def props(d): return ', '.join(f'{k}: {q(v)}' for k,v in d.items())
def setp(var,d): return ', '.join(f'{var}.{k} = {q(v)}' for k,v in d.items())
S=[]
def st(comment, body):
    S.append(f'// {comment}\n// status: run (embedded Neo4j 5.26.31 Community, 2026-10-04)\n{body};\n')
def idOf(uid): return uid.split(':',2)[2]
T0="@datetime('2026-10-04T01:30:00Z')"
def node(labels, uid, d):
    d=dict(d); d.setdefault('id', idOf(uid)); d.setdefault('createdAt', T0)
    st(f'node {uid}', f"MERGE (n:{':'.join(labels)} {{uid: {q(uid)}}})\nSET {setp('n',d)}")
def ent(lbl, uid, d, extra=()):
    d=dict(d); d.setdefault('entityType', lbl); d.setdefault('privacyClass','PUBLIC')
    node([lbl,*extra,'Entity'], uid, d)
def rel(a, t, b, d=None, la='', lb=''):
    p=f' {{{props(d)}}}' if d else ''
    st(f'{a} -[{t}]-> {b}', f"MATCH (a{la} {{uid: {q(a)}}}), (b{lb} {{uid: {q(b)}}})\nMERGE (a)-[r:{t}]->(b)" + (f"\nSET {setp('r',d)}" if d else ''))

S.append('''// =====================================================================================================================
// W03 positive fixture (run-2026-10-04-fable51-01). Generated by the W03 worker from public records retrieved 2026-10-04
// (PubMed MCP, Firecrawl scrape of Reactome ContentService and EBI OLS, ICD-10 MCP) plus inherited repository citations.
// Every statement binds its own nodes by uid; no variable crosses a ';'. Nodes carry primary label and archetype label.
// Snapshots use contentHashBasis SYNTHETIC_FIXTURE: 'sha256:<hex>' is sha256 over the snapshot uid, not over captured bytes.
// Exact quotes are as returned by the capturing tool (the PubMed MCP drops the superscript '+' of NAD+, so 'NADin' is
// the captured text, not a typo introduced here). Other owners' node types (Source, SourceSnapshot, SourceLocator,
// Assertion, Adjudication, Identifier: W00; ChemicalSubstance, IngredientMaterial: W02; Biomarker: W07; StudyArm,
// StudyIntervention: W09) appear only with the minimum properties the W03 cases need.
// Load order: this file, then w03-projection-job.cypher, then w03-validation.cypher (expected: zero failing rows).
// =====================================================================================================================
''')

# ---------------- provenance ----------------
sources=[
 ('hu:source:doi-10-1038-s41514-017-0016-9','https://doi.org/10.1038/s41514-017-0016-9','PEER_REVIEWED_PUBLICATION','Dellinger et al. 2017 NPJ Aging Mech Dis (PMID 29184669)'),
 ('hu:source:doi-10-1038-ncomms12948','https://doi.org/10.1038/ncomms12948','PEER_REVIEWED_PUBLICATION','Trammell et al. 2016 Nat Commun (PMID 27721479)'),
 ('hu:source:doi-10-1016-j-cmet-2018-03-018','https://doi.org/10.1016/j.cmet.2018.03.018','PEER_REVIEWED_PUBLICATION','Liu et al. 2018 Cell Metab (PMID 29685734)'),
 ('hu:source:doi-10-1016-j-celrep-2019-07-043','https://doi.org/10.1016/j.celrep.2019.07.043','PEER_REVIEWED_PUBLICATION','Elhassan et al. 2019 Cell Rep (PMID 31412242)'),
 ('hu:source:doi-10-1126-science-aaf2693','https://doi.org/10.1126/science.aaf2693','PEER_REVIEWED_PUBLICATION','Zhang et al. 2016 Science (PMID 27127236)'),
 ('hu:source:reactome-contentservice-r-hsa-196807','https://reactome.org/ContentService/data/query/R-HSA-196807','TERMINOLOGY_RECORD','Reactome ContentService record R-HSA-196807'),
 ('hu:source:ols4-mondo-0012520','https://www.ebi.ac.uk/ols4/api/ontologies/mondo/terms/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FMONDO_0012520','TERMINOLOGY_RECORD','EBI OLS4 MONDO term MONDO:0012520'),
 ('hu:source:ols4-mondo-search-insulin-resistance','https://www.ebi.ac.uk/ols4/api/search?q=insulin%20resistance&ontology=mondo&rows=5','TERMINOLOGY_RECORD','EBI OLS4 MONDO search insulin resistance'),
 ('hu:source:icd10cm-mcp-e88-81','icd10-mcp:FY2027/lookup_code/E88.81','TERMINOLOGY_RECORD','ICD-10-CM FY2027 via ICD-10 Codes MCP: E88.81 and children'),
 ('hu:source:icd10cm-mcp-m62-84','icd10-mcp:FY2027/lookup_code/M62.84','TERMINOLOGY_RECORD','ICD-10-CM FY2027 via ICD-10 Codes MCP: M62.84'),
 ('hu:source:hgnc-rest-sirt1','https://rest.genenames.org/fetch/symbol/SIRT1','TERMINOLOGY_RECORD','HGNC REST record SIRT1'),
]
for uid,uri,kind,title in sources:
    ent('Source', uid, {'name': title, 'canonicalUri': uri, 'sourceKind': kind})
snaps=[  # uid, source, retrievedAt, completeness, publishedAt, note
 ('hu:snapshot:pmid29184669-pubmed-abstract-2026-10-04','hu:source:doi-10-1038-s41514-017-0016-9','2026-10-04T00:50:00Z','PARTIAL_EXCERPT','2017-11-24T00:00:00Z','NEW_RETRIEVAL PubMed MCP metadata+abstract'),
 ('hu:snapshot:pmid29184669-pmc-fulltext-2026-10-03','hu:source:doi-10-1038-s41514-017-0016-9','2026-10-03T00:00:00Z','PARTIAL_EXCERPT','2017-11-24T00:00:00Z','INHERITED_REPO_CITATION round 0003'),
 ('hu:snapshot:pmc5062546-fulltext-2026-10-04','hu:source:doi-10-1038-ncomms12948','2026-10-04T00:52:00Z','COMPLETE','2016-10-10T00:00:00Z','NEW_RETRIEVAL PubMed MCP PMC full text'),
 ('hu:snapshot:pmc5932087-fulltext-2026-10-04','hu:source:doi-10-1016-j-cmet-2018-03-018','2026-10-04T00:55:00Z','COMPLETE','2018-05-01T00:00:00Z','NEW_RETRIEVAL PubMed MCP PMC full text'),
 ('hu:snapshot:pmid31412242-pubmed-abstract-2026-10-04','hu:source:doi-10-1016-j-celrep-2019-07-043','2026-10-04T01:00:00Z','PARTIAL_EXCERPT','2019-08-13T00:00:00Z','NEW_RETRIEVAL PubMed MCP abstract'),
 ('hu:snapshot:pmc6702140-fulltext-2026-10-03','hu:source:doi-10-1016-j-celrep-2019-07-043','2026-10-03T00:00:00Z','PARTIAL_EXCERPT','2019-08-13T00:00:00Z','INHERITED_REPO_CITATION round 0003'),
 ('hu:snapshot:pmid27127236-pubmed-abstract-2026-10-04','hu:source:doi-10-1126-science-aaf2693','2026-10-04T01:01:00Z','PARTIAL_EXCERPT','2016-04-28T00:00:00Z','NEW_RETRIEVAL PubMed MCP abstract'),
 ('hu:snapshot:reactome-r-hsa-196807-release-97-2026-10-04','hu:source:reactome-contentservice-r-hsa-196807','2026-10-04T00:57:00Z','COMPLETE',None,'NEW_RETRIEVAL Firecrawl scrape (direct curl BLOCKED 403)'),
 ('hu:snapshot:ols4-mondo-0012520-2026-10-04','hu:source:ols4-mondo-0012520','2026-10-04T00:59:00Z','COMPLETE',None,'NEW_RETRIEVAL Firecrawl scrape, MONDO release 2026-09-01'),
 ('hu:snapshot:ols4-mondo-search-ir-2026-10-04','hu:source:ols4-mondo-search-insulin-resistance','2026-10-04T00:58:00Z','PARTIAL_EXCERPT',None,'NEW_RETRIEVAL Firecrawl scrape, first 5 of 35 hits'),
 ('hu:snapshot:icd10cm-e88-81-fy2027-2026-10-04','hu:source:icd10cm-mcp-e88-81','2026-10-04T00:58:00Z','COMPLETE',None,'NEW_RETRIEVAL ICD-10 MCP lookup/hierarchy/validate'),
 ('hu:snapshot:icd10cm-m62-84-fy2027-2026-10-04','hu:source:icd10cm-mcp-m62-84','2026-10-04T00:58:00Z','COMPLETE',None,'NEW_RETRIEVAL ICD-10 MCP lookup'),
 ('hu:snapshot:hgnc-sirt1-2026-10-04','hu:source:hgnc-rest-sirt1','2026-10-04T01:02:00Z','COMPLETE',None,'NEW_RETRIEVAL Firecrawl scrape'),
]
for uid,src,ret,comp,pub,note in snaps:
    d={'artifactType':'SourceSnapshot','retrievedAt':f"@datetime('{ret}')",'observedAt':f"@datetime('{ret}')",'contentHash':h(uid),'contentHashBasis':'SYNTHETIC_FIXTURE','captureCompleteness':comp,'captureNote':note,'privacyClass':'PUBLIC'}
    if pub: d['publishedAt']=f"@datetime('{pub}')"
    node(['SourceSnapshot','InformationArtifact'], uid, d)
    rel(src,'HAS_SNAPSHOT',uid)
locs=[ # uid, snapshot, selectorKind, exact, section
 ('hu:locator:pmid29184669-abstract-nad-whole-blood','hu:snapshot:pmid29184669-pubmed-abstract-2026-10-04','TEXT_QUOTE','Analysis of NADin whole blood demonstrated that NRPT significantly increases the concentration of NADin a dose-dependent manner.','Abstract'),
 ('hu:locator:pmid29184669-introduction-sirtuins','hu:snapshot:pmid29184669-pmc-fulltext-2026-10-03','TEXT_QUOTE','NR providing NAD+ to all seven sirtuins','Introduction'),
 ('hu:locator:pmc5062546-methods-mice-gavage','hu:snapshot:pmc5062546-fulltext-2026-10-04','TEXT_QUOTE','Body weight-matched groups were randomly assigned to be given either 185 mg NR Cl per kg body weight','Methods: Mice'),
 ('hu:locator:pmc5062546-results-hepatic-nad','hu:snapshot:pmc5062546-fulltext-2026-10-04','TEXT_QUOTE','NR elevated hepatic NADby more than fourfold with a peak at 6 h post gavage','Results'),
 ('hu:locator:pmc5062546-results-heart-naad','hu:snapshot:pmc5062546-fulltext-2026-10-04','TEXT_QUOTE','NR led to striking elevation of NAAD in the heart, a tissue that increases NADmetabolism without increasing steady-state NAD','Results'),
 ('hu:locator:pmc5062546-intro-naad-reports-metabolism','hu:snapshot:pmc5062546-fulltext-2026-10-04','TEXT_QUOTE','NAAD sensitively reports on increased NADmetabolism in mouse liver and heart','Introduction'),
 ('hu:locator:pmc5062546-results-bsa-factor','hu:snapshot:pmc5062546-fulltext-2026-10-04','TEXT_QUOTE','On the basis of weight/surface area, the conversion between human adult dose and mouse dose is a factor of 12.3','Results'),
 ('hu:locator:pmc5932087-results-oral-200-liver-not-muscle','hu:snapshot:pmc5932087-fulltext-2026-10-04','TEXT_QUOTE','the 200 mg/kg dose resulted in M+2 NAD in liver but not muscle or kidney after oral administration','Results'),
 ('hu:locator:pmc5932087-abstract-concentration-limitation','hu:snapshot:pmc5932087-fulltext-2026-10-04','TEXT_QUOTE','A limitation in understanding NAD metabolism has been reliance on concentration measurements.','Summary'),
 ('hu:locator:pmid31412242-abstract-design','hu:snapshot:pmid31412242-pubmed-abstract-2026-10-04','TEXT_QUOTE','We supplemented 12 aged men with 1 g NR per day for 21 days in a placebo-controlled, randomized, double-blind, crossover trial.','Abstract'),
 ('hu:locator:pmid31412242-abstract-naad-muscle','hu:snapshot:pmid31412242-pubmed-abstract-2026-10-04','TEXT_QUOTE','NR elevated the muscle NADmetabolome, evident by increased nicotinic acid adenine dinucleotide and nicotinamide clearance products','Abstract'),
 ('hu:locator:pmid31412242-abstract-bioenergetics','hu:snapshot:pmid31412242-pubmed-abstract-2026-10-04','TEXT_QUOTE','without altering mitochondrial bioenergetics','Abstract'),
 ('hu:locator:pmc6702140-results-acetylation','hu:snapshot:pmc6702140-fulltext-2026-10-03','TEXT_QUOTE','did not detect NR-mediated changes to muscle protein acetylation','Results'),
 ('hu:locator:pmid27127236-title','hu:snapshot:pmid27127236-pubmed-abstract-2026-10-04','TEXT_QUOTE','NAD⁺ repletion improves mitochondrial and stem cell function and enhances life span in mice.','Title'),
 ('hu:locator:reactome-r-hsa-196807-stidversion','hu:snapshot:reactome-r-hsa-196807-release-97-2026-10-04','TEXT_QUOTE','"stIdVersion":"R-HSA-196807.8"','JSON field stIdVersion'),
 ('hu:locator:reactome-r-hsa-196807-ortholog-mmu','hu:snapshot:reactome-r-hsa-196807-release-97-2026-10-04','TEXT_QUOTE','"stId":"R-MMU-196807","stIdVersion":"R-MMU-196807.1","isInDisease":false,"isInferred":true','JSON field orthologousEvent'),
 ('hu:locator:reactome-r-hsa-196807-doi','hu:snapshot:reactome-r-hsa-196807-release-97-2026-10-04','TEXT_QUOTE','"doi":"10.3180/R-HSA-196807.7"','JSON field doi'),
 ('hu:locator:ols4-mondo-0012520-id','hu:snapshot:ols4-mondo-0012520-2026-10-04','TEXT_QUOTE','"obo_id" : "MONDO:0012520"','JSON field obo_id'),
 ('hu:locator:ols4-mondo-search-ir-hp','hu:snapshot:ols4-mondo-search-ir-2026-10-04','TEXT_QUOTE','"label":"Insulin resistance","obo_id":"HP:0000855"','JSON docs[0]'),
 ('hu:locator:icd10cm-e88-81-validate-fy2022','hu:snapshot:icd10cm-e88-81-fy2027-2026-10-04','TEXT_QUOTE','Code E88.81 is valid for HIPAA-covered transactions in FY2022, the fiscal year of the date of service, but in the current FY2027 code set it is a category header only','validate_code message'),
 ('hu:locator:icd10cm-e88-819-lookup','hu:snapshot:icd10cm-e88-81-fy2027-2026-10-04','TEXT_QUOTE','"code":"E88.819","short_description":"Insulin resistance, unspecified"','lookup_code E88.819 (first_fy 2024)'),
 ('hu:locator:icd10cm-e88-811-hierarchy','hu:snapshot:icd10cm-e88-81-fy2027-2026-10-04','TEXT_QUOTE','"code":"E88.811","short_description":"Insulin resistance syndrome, Type A"','get_hierarchy E88.81'),
 ('hu:locator:icd10cm-m62-84-lookup','hu:snapshot:icd10cm-m62-84-fy2027-2026-10-04','TEXT_QUOTE','"code":"M62.84","short_description":"Sarcopenia"','lookup_code M62.84'),
 ('hu:locator:hgnc-sirt1-id','hu:snapshot:hgnc-sirt1-2026-10-04','TEXT_QUOTE','<str name="hgnc_id">HGNC:14929</str>','XML hgnc_id'),
]
for uid,snap,kind,exact,section in locs:
    import unicodedata, re as _re
    norm=_re.sub(r'\s+',' ',unicodedata.normalize('NFC',exact)).strip()
    node(['SourceLocator','InformationArtifact'], uid, {'artifactType':'SourceLocator','selectorKind':kind,'exact':exact,'section':section,'normalizationVersion':'NFC-WS1','quoteHash':'sha256:'+hashlib.sha256(norm.encode()).hexdigest(),'privacyClass':'PUBLIC'})
    rel(snap,'HAS_LOCATOR',uid)

# ---------------- reference entities ----------------
ent('Species','hu:species:homo-sapiens',{'name':'Homo sapiens','scientificName':'Homo sapiens','ncbiTaxonomyId':'9606'})
ent('Species','hu:species:mus-musculus',{'name':'Mus musculus','scientificName':'Mus musculus','ncbiTaxonomyId':'10090'})
ent('AnatomicalContext','hu:anatomical-context:whole-blood',{'name':'whole blood','contextKind':'SPECIMEN_MATRIX'})
ent('AnatomicalContext','hu:anatomical-context:skeletal-muscle',{'name':'skeletal muscle tissue','contextKind':'TISSUE'})
ent('AnatomicalContext','hu:anatomical-context:muscle-stem-cell',{'name':'muscle stem cell (MuSC)','contextKind':'CELL_TYPE'})
# Organs carry the AnatomicalContext label (one identity per organ)
node(['Organ','AnatomicalContext','Entity'],'hu:anatomical-context:liver',{'name':'liver','contextKind':'ORGAN','organSystem':'digestive system','entityType':'Organ','privacyClass':'PUBLIC'})
node(['Organ','AnatomicalContext','Entity'],'hu:anatomical-context:heart',{'name':'heart','contextKind':'ORGAN','organSystem':'cardiovascular system','entityType':'Organ','privacyClass':'PUBLIC'})

ent('ChemicalSubstance','hu:substance:nicotinamide-riboside',{'name':'nicotinamide riboside (cation)','preferredName':'nicotinamide riboside'})
ent('ChemicalSubstance','hu:substance:nadide',{'name':'NAD+ (Nadide)','preferredName':'Nadide','pubchemCid':'5892','inchikey':'BAWFJGJZGIEFAR-NNYOXOHSSA-N','molecularFormula':'C21H27N7O14P2'})
ent('ChemicalSubstance','hu:substance:naad',{'name':'nicotinic acid adenine dinucleotide (NAAD)','preferredName':'deamido-NAD+'})
for uid,name in [('hu:material:trammell-2016-nr-cl-gmp','NR Cl produced under GMP conditions (Trammell 2016 Methods)'),
                 ('hu:material:liu-2018-labeled-nr','doubly labeled NR as administered (Liu 2018)'),
                 ('hu:material:zhang-2016-nr-as-supplied','NR as administered in Zhang 2016 (material and dose not extracted)'),
                 ('hu:material:elhassan-2019-nr-as-supplied','NR as administered in Elhassan 2019 (material not extracted)')]:
    ent('IngredientMaterial',uid,{'name':name,'materialKind':'UNRESOLVED_MATERIAL'})   # material-to-substance link is W02's asserted REALIZES_SUBSTANCE; not needed here
# Study-side stubs (W09); exposure for the Dellinger context is read from the arm
node(['StudyArm','VersionedState'],'hu:study-arm:nct02678611-nrpt-1x',{'name':'NRPT 1X','stateType':'StudyArm','payloadHash':h('hu:study-arm:nct02678611-nrpt-1x'),'privacyClass':'PUBLIC'})
node(['StudyIntervention','VersionedState'],'hu:study-intervention:nct02678611-nrpt-1x',{'name':'NRPT 1X: 250 mg NR + 50 mg pterostilbene daily, 8 weeks','stateType':'StudyIntervention','payloadHash':h('hu:study-intervention:nct02678611-nrpt-1x'),'privacyClass':'PUBLIC'})

# Measurands (W07 Biomarker): analyte in matrix
bms=[('hu:biomarker:nad-plus-whole-blood','NAD+ in whole blood','hu:anatomical-context:whole-blood','hu:substance:nadide'),
     ('hu:biomarker:nad-plus-liver','NAD+ in liver','hu:anatomical-context:liver','hu:substance:nadide'),
     ('hu:biomarker:nad-plus-heart','NAD+ in heart','hu:anatomical-context:heart','hu:substance:nadide'),
     ('hu:biomarker:naad-heart','NAAD in heart','hu:anatomical-context:heart','hu:substance:naad'),
     ('hu:biomarker:naad-skeletal-muscle','NAAD in skeletal muscle','hu:anatomical-context:skeletal-muscle','hu:substance:naad'),
     ('hu:biomarker:muscle-protein-acetylation','pan-lysine protein acetylation in skeletal muscle','hu:anatomical-context:skeletal-muscle',None)]
for uid,name,mx,an in bms:
    ent('Biomarker',uid,{'name':name})
    rel(uid,'MEASURED_IN_MATRIX',mx)
    if an: rel(uid,'HAS_ANALYTE',an)   # candidate edge, seam W03-SR-03 (owner W07)

ent('MolecularEntity','hu:molecular-entity:sirtuin-deacetylase-family',{'name':'Sirtuin deacetylases (SIRT1-7)','entityKind':'PROTEIN_FAMILY'})
ent('MolecularEntity','hu:molecular-entity:sirt1-human',{'name':'sirtuin 1 (human)','entityKind':'GENE','geneSymbol':'SIRT1','hgncId':'HGNC:14929','uniprotId':'Q96EB6','ensemblId':'ENSG00000096717','speciesTaxonId':'9606'})
ent('Mechanism','hu:mechanism:nad-plus-biosynthetic-flux',{'name':'NAD+ biosynthetic flux from precursors','mechanismClass':'METABOLIC_FLUX','biologicalLayer':'METABOLIC'})
ent('Mechanism','hu:mechanism:mitochondrial-oxidative-function',{'name':'Mitochondrial oxidative function','mechanismClass':'ORGANELLE_FUNCTION','biologicalLayer':'ORGANELLE'})
rel('hu:biomarker:naad-heart','REFLECTS_MECHANISM','hu:mechanism:nad-plus-biosynthetic-flux',{'notes':'curated readout-of link (NAAD rise reports NAD+ synthesis); never a measured flux'})

# Pathways (Reactome): unversioned stable id is identity; revision travels on snapshot and curated links
ent('Pathway','hu:pathway:reactome-r-hsa-196807',{'name':'Nicotinate metabolism (Homo sapiens)','pathwayClass':'METABOLISM','sourceDatabase':'REACTOME','externalId':'R-HSA-196807','pathwayRevision':'8','pathwayRelease':'97','revisionObservedAt':"@datetime('2026-10-04T00:57:00Z')",'speciesTaxonId':'9606','orthologyInferred':False})
ent('Pathway','hu:pathway:reactome-r-mmu-196807',{'name':'Nicotinate metabolism (Mus musculus, inferred)','pathwayClass':'METABOLISM','sourceDatabase':'REACTOME','externalId':'R-MMU-196807','pathwayRevision':'1','pathwayRelease':'97','revisionObservedAt':"@datetime('2026-10-04T00:57:00Z')",'speciesTaxonId':'10090','orthologyInferred':True})
rel('hu:mechanism:nad-plus-biosynthetic-flux','INVOLVES_PATHWAY','hu:pathway:reactome-r-hsa-196807',{'regulatorySign':'UNKNOWN','referenceSnapshotUid':'hu:snapshot:reactome-r-hsa-196807-release-97-2026-10-04','referenceRecordId':'R-HSA-196807','referenceRevision':'8','referenceRelease':'97','notes':'BellLabs curation: the NR-to-NAD+ reactions (NMRK1/NMRK2, NMNAT) are events of this pathway record'})

# Conditions
ent('Condition','hu:condition:insulin-resistance',{'name':'insulin resistance','conditionClass':'METABOLIC'})
ent('Condition','hu:condition:sarcopenia',{'name':'sarcopenia','conditionClass':'MUSCULOSKELETAL'})
ent('Condition','hu:condition:insulin-resistance-syndrome-type-a',{'name':'insulin-resistance syndrome type A','conditionClass':'METABOLIC','mondoId':'MONDO:0012520','orphaCode':'ORPHA:2297','omimId':'610549','isRare':True})

# Identifier records (W00) and asserted HAS_IDENTIFIER links
idents=[('hu:identifier:icd10cm-e88-81','ICD10CM','E88.81','CMS/NCHS'),('hu:identifier:icd10cm-e88-819','ICD10CM','E88.819','CMS/NCHS'),
        ('hu:identifier:icd10cm-e88-811','ICD10CM','E88.811','CMS/NCHS'),('hu:identifier:icd10cm-m62-84','ICD10CM','M62.84','CMS/NCHS'),
        ('hu:identifier:hpo-hp-0000855','HPO','HP:0000855','Human Phenotype Ontology'),('hu:identifier:mondo-0012520','MONDO','MONDO:0012520','Monarch Initiative'),
        ('hu:identifier:reactome-r-hsa-196807','REACTOME_STID','R-HSA-196807','Reactome'),('hu:identifier:reactome-r-mmu-196807','REACTOME_STID','R-MMU-196807','Reactome'),
        ('hu:identifier:doi-10-3180-r-hsa-196807-7','DOI','10.3180/R-HSA-196807.7','Reactome via DataCite'),('hu:identifier:hgnc-14929','HGNC','HGNC:14929','HGNC')]
for uid,scheme,val,issuer in idents:
    ent('Identifier',uid,{'name':f'{scheme} {val}','scheme':scheme,'value':val,'issuer':issuer})
links=[ # subject, identifier, locator, validFrom, vfBasis, vfPrec, validTo, vtBasis, vtPrec, isPrimary
 ('hu:condition:insulin-resistance','hu:identifier:icd10cm-e88-81','hu:locator:icd10cm-e88-81-validate-fy2022',None,'UNKNOWN',None,'2023-10-01T00:00:00Z','INFERRED','DAY',False),
 ('hu:condition:insulin-resistance','hu:identifier:icd10cm-e88-819','hu:locator:icd10cm-e88-819-lookup','2023-10-01T00:00:00Z','INFERRED','DAY',None,'UNKNOWN',None,False),
 ('hu:condition:insulin-resistance','hu:identifier:hpo-hp-0000855','hu:locator:ols4-mondo-search-ir-hp',None,'UNKNOWN',None,None,'UNKNOWN',None,True),
 ('hu:condition:insulin-resistance-syndrome-type-a','hu:identifier:mondo-0012520','hu:locator:ols4-mondo-0012520-id',None,'UNKNOWN',None,None,'UNKNOWN',None,True),
 ('hu:condition:insulin-resistance-syndrome-type-a','hu:identifier:icd10cm-e88-811','hu:locator:icd10cm-e88-811-hierarchy','2023-10-01T00:00:00Z','INFERRED','DAY',None,'UNKNOWN',None,False),
 ('hu:condition:sarcopenia','hu:identifier:icd10cm-m62-84','hu:locator:icd10cm-m62-84-lookup',None,'UNKNOWN',None,None,'UNKNOWN',None,True),
 ('hu:pathway:reactome-r-hsa-196807','hu:identifier:reactome-r-hsa-196807','hu:locator:reactome-r-hsa-196807-stidversion',None,'UNKNOWN',None,None,'UNKNOWN',None,True),
 ('hu:pathway:reactome-r-hsa-196807','hu:identifier:doi-10-3180-r-hsa-196807-7','hu:locator:reactome-r-hsa-196807-doi',None,'UNKNOWN',None,None,'UNKNOWN',None,False),
 ('hu:pathway:reactome-r-mmu-196807','hu:identifier:reactome-r-mmu-196807','hu:locator:reactome-r-hsa-196807-ortholog-mmu',None,'UNKNOWN',None,None,'UNKNOWN',None,True),
 ('hu:molecular-entity:sirt1-human','hu:identifier:hgnc-14929','hu:locator:hgnc-sirt1-id',None,'UNKNOWN',None,None,'UNKNOWN',None,True),
]
for i,(s,ident,loc,vf,vfb,vfp,vt,vtb,vtp,prim) in enumerate(links):
    au=f"hu:assertion:has-identifier-{idOf(s)}-{idOf(ident)}"
    ad={'predicate':'HAS_IDENTIFIER','predicateClass':'IDENTITY','status':'ACCEPTED','recordedAt':T0,'polarity':'POSITIVE','assertionBasis':'UNSTATED','speechAct':'STATES','validFromBasis':vfb,'validToBasis':vtb,'privacyClass':'PUBLIC'}
    if vf: ad.update({'validFrom':f"@datetime('{vf}')",'validFromPrecision':vfp})
    if vt: ad.update({'validTo':f"@datetime('{vt}')",'validToPrecision':vtp})
    if 'INFERRED' in (vfb,vtb): ad['derivationRule']='icd10cm-fiscal-year-start/v1 (FY N begins N-1-10-01; first_fy/last_fy from the ICD-10 MCP)'
    node(['Assertion'],au,ad)
    rel(au,'HAS_SUBJECT',s); rel(au,'HAS_OBJECT',ident); rel(au,'SUPPORTED_BY',loc)
    ed={'relationshipUid':f"hu:rel:{idOf(au)}",'assertionUid':au,'validFromBasis':vfb,'validToBasis':vtb,'recordedFrom':T0,'isPrimary':prim}
    if vf: ed.update({'validFrom':f"@datetime('{vf}')",'validFromPrecision':vfp})
    if vt: ed.update({'validTo':f"@datetime('{vt}')",'validToPrecision':vtp})
    rel(s,'HAS_IDENTIFIER',ident,ed)

# ---------------- evidence contexts ----------------
ctxs=[ # uid, setting, species, site, material, arm, extra
 ('hu:mech-context:dellinger-2017-nrpt-1x-whole-blood','HUMAN_INTERVENTIONAL','hu:species:homo-sapiens','hu:anatomical-context:whole-blood',None,'hu:study-arm:nct02678611-nrpt-1x',{'modelDescriptor':'healthy adults aged 60-80, randomized placebo-controlled','ageDescriptor':'60-80 years'}),
 ('hu:mech-context:trammell-2016-liver-abstract-only','IN_VIVO_MAMMAL','hu:species:mus-musculus','hu:anatomical-context:liver','hu:material:trammell-2016-nr-cl-gmp',None,{'modelDescriptor':'mice (first-pass capture from abstract)','exposureStatus':'NOT_EXTRACTED'}),
 ('hu:mech-context:trammell-2016-185mgkg-gavage-liver','IN_VIVO_MAMMAL','hu:species:mus-musculus','hu:anatomical-context:liver','hu:material:trammell-2016-nr-cl-gmp',None,{'modelDescriptor':'C57Bl/6J, chow diet (Teklad 7013); single gavage, tissue harvested 0.25-12 h after','sexScope':'MALE','ageDescriptor':'12 weeks','sampleSize':3,'exposureAmount':185.0,'exposureUnit':'mg/kg','exposureBasis':'SINGLE_DOSE','route':'GAVAGE','hedValue':15.04,'hedUnitCode':'mg/kg','hedMethod':'BSA-factor-12.3-as-stated-in-source/derived'}),
 ('hu:mech-context:trammell-2016-185mgkg-gavage-heart','IN_VIVO_MAMMAL','hu:species:mus-musculus','hu:anatomical-context:heart','hu:material:trammell-2016-nr-cl-gmp',None,{'modelDescriptor':'C57Bl/6J, chow diet; single gavage','sexScope':'MALE','ageDescriptor':'12 weeks','exposureAmount':185.0,'exposureUnit':'mg/kg','exposureBasis':'SINGLE_DOSE','route':'GAVAGE'}),
 ('hu:mech-context:liu-2018-oral-200mgkg-liver','IN_VIVO_MAMMAL','hu:species:mus-musculus','hu:anatomical-context:liver','hu:material:liu-2018-labeled-nr',None,{'modelDescriptor':'C57BL/6 mice; isotope tracer (M+2 NAD labeling) after oral bolus','sexScope':'UNKNOWN','exposureAmount':200.0,'exposureUnit':'mg/kg','exposureBasis':'SINGLE_DOSE','route':'GAVAGE','hedValue':16.26,'hedUnitCode':'mg/kg','hedMethod':'BSA-Km/FDA-2005 (mouse factor 12.3)'}),
 ('hu:mech-context:liu-2018-oral-200mgkg-muscle','IN_VIVO_MAMMAL','hu:species:mus-musculus','hu:anatomical-context:skeletal-muscle','hu:material:liu-2018-labeled-nr',None,{'modelDescriptor':'C57BL/6 mice; isotope tracer (M+2 NAD labeling) after oral bolus','sexScope':'UNKNOWN','exposureAmount':200.0,'exposureUnit':'mg/kg','exposureBasis':'SINGLE_DOSE','route':'GAVAGE'}),
 ('hu:mech-context:zhang-2016-aged-mice-musc','IN_VIVO_MAMMAL','hu:species:mus-musculus','hu:anatomical-context:muscle-stem-cell','hu:material:zhang-2016-nr-as-supplied',None,{'modelDescriptor':'aged mice','exposureStatus':'NOT_EXTRACTED'}),
 ('hu:mech-context:elhassan-2019-nr-1g-21d-muscle','HUMAN_INTERVENTIONAL','hu:species:homo-sapiens','hu:anatomical-context:skeletal-muscle','hu:material:elhassan-2019-nr-as-supplied',None,{'modelDescriptor':'aged men, randomized placebo-controlled double-blind crossover','sexScope':'MALE','sampleSize':12,'exposureAmount':1000.0,'exposureUnit':'mg/d','exposureBasis':'ABSOLUTE_PER_DAY','route':'ORAL','exposureDurationIso':'P21D'}),
]
for uid,setting,sp,site,mat,arm,extra in ctxs:
    d={'occurrenceType':'MechanismEvidenceContext','setting':setting,'privacyClass':'PUBLIC'}; d.update(extra)
    node(['MechanismEvidenceContext','Occurrence'],uid,d)
    rel(uid,'IN_SPECIES',sp); rel(uid,'MEASURED_IN',site)
    if mat: rel(uid,'EXPOSED_TO',mat)
    if arm: rel(uid,'IN_STUDY_ARM',arm)

# ---------------- mechanism step assertions ----------------
NR='hu:substance:nicotinamide-riboside'
A=[ # uid, subj, pred, obj, basis, pol, ctx, locs, speechAct, assertionBasis, recordedAt, derivedFrom
 ('hu:assertion:dellinger-nrpt-1x-increases-nad-whole-blood','hu:study-intervention:nct02678611-nrpt-1x','INCREASES_LEVEL_OF','hu:biomarker:nad-plus-whole-blood','DIRECT_MEASUREMENT','POSITIVE','hu:mech-context:dellinger-2017-nrpt-1x-whole-blood',['hu:locator:pmid29184669-abstract-nad-whole-blood'],'STATES','STUDY_RESULT',T0,[]),
 ('hu:assertion:basis-paper-nr-provides-nad-synthesis-hypothesis',NR,'INDUCES_PROCESS','hu:mechanism:nad-plus-biosynthetic-flux','HYPOTHESIS','POSITIVE',None,['hu:locator:pmid29184669-introduction-sirtuins'],'SPECULATES','MECHANISM_REASONING',T0,[]),
 ('hu:assertion:trammell-nr-increases-nad-liver-v1',NR,'INCREASES_LEVEL_OF','hu:biomarker:nad-plus-liver','DIRECT_MEASUREMENT','POSITIVE','hu:mech-context:trammell-2016-liver-abstract-only',['hu:locator:pmc5062546-results-hepatic-nad'],'STATES','STUDY_RESULT',T0,[]),
 ('hu:assertion:trammell-nr-increases-nad-liver-v2',NR,'INCREASES_LEVEL_OF','hu:biomarker:nad-plus-liver','DIRECT_MEASUREMENT','POSITIVE','hu:mech-context:trammell-2016-185mgkg-gavage-liver',['hu:locator:pmc5062546-results-hepatic-nad','hu:locator:pmc5062546-methods-mice-gavage'],'STATES','STUDY_RESULT',"@datetime('2026-10-04T02:00:00Z')",[]),
 ('hu:assertion:trammell-nr-increases-naad-heart',NR,'INCREASES_LEVEL_OF','hu:biomarker:naad-heart','DIRECT_MEASUREMENT','POSITIVE','hu:mech-context:trammell-2016-185mgkg-gavage-heart',['hu:locator:pmc5062546-results-heart-naad'],'STATES','STUDY_RESULT',T0,[]),
 ('hu:assertion:trammell-nr-heart-nad-level-unchanged',NR,'INCREASES_LEVEL_OF','hu:biomarker:nad-plus-heart','DIRECT_MEASUREMENT','NEGATIVE','hu:mech-context:trammell-2016-185mgkg-gavage-heart',['hu:locator:pmc5062546-results-heart-naad'],'STATES','STUDY_RESULT',T0,[]),
 ('hu:assertion:trammell-nr-nad-synthesis-heart-inferred',NR,'INDUCES_PROCESS','hu:mechanism:nad-plus-biosynthetic-flux','INFERRED_FROM_MEASUREMENT','POSITIVE',None,['hu:locator:pmc5062546-intro-naad-reports-metabolism'],'STATES','STUDY_RESULT',T0,['hu:assertion:trammell-nr-increases-naad-heart']),
 ('hu:assertion:liu-oral-nr-nad-synthesis-liver',NR,'INDUCES_PROCESS','hu:mechanism:nad-plus-biosynthetic-flux','DIRECT_MEASUREMENT','POSITIVE','hu:mech-context:liu-2018-oral-200mgkg-liver',['hu:locator:pmc5932087-results-oral-200-liver-not-muscle'],'STATES','STUDY_RESULT',T0,[]),
 ('hu:assertion:liu-oral-nr-nad-synthesis-muscle-not-detected',NR,'INDUCES_PROCESS','hu:mechanism:nad-plus-biosynthetic-flux','DIRECT_MEASUREMENT','NEGATIVE','hu:mech-context:liu-2018-oral-200mgkg-muscle',['hu:locator:pmc5932087-results-oral-200-liver-not-muscle'],'STATES','STUDY_RESULT',T0,[]),
 ('hu:assertion:zhang-nr-improves-mito-function-aged-mice',NR,'IMPROVES','hu:mechanism:mitochondrial-oxidative-function','DIRECT_MEASUREMENT','POSITIVE','hu:mech-context:zhang-2016-aged-mice-musc',['hu:locator:pmid27127236-title'],'STATES','STUDY_RESULT',T0,[]),
 ('hu:assertion:elhassan-nr-mito-function-no-change-muscle',NR,'IMPROVES','hu:mechanism:mitochondrial-oxidative-function','DIRECT_MEASUREMENT','NEGATIVE','hu:mech-context:elhassan-2019-nr-1g-21d-muscle',['hu:locator:pmid31412242-abstract-bioenergetics','hu:locator:pmid31412242-abstract-design'],'STATES','STUDY_RESULT',T0,[]),
 ('hu:assertion:elhassan-nr-increases-naad-muscle',NR,'INCREASES_LEVEL_OF','hu:biomarker:naad-skeletal-muscle','DIRECT_MEASUREMENT','POSITIVE','hu:mech-context:elhassan-2019-nr-1g-21d-muscle',['hu:locator:pmid31412242-abstract-naad-muscle'],'STATES','STUDY_RESULT',T0,[]),
 ('hu:assertion:elhassan-nr-acetylation-no-change-muscle',NR,'DECREASES_LEVEL_OF','hu:biomarker:muscle-protein-acetylation','DIRECT_MEASUREMENT','NEGATIVE','hu:mech-context:elhassan-2019-nr-1g-21d-muscle',['hu:locator:pmc6702140-results-acetylation'],'STATES','STUDY_RESULT',T0,[]),
 ('hu:assertion:elhassan-nr-sirtuin-activity-inferred-null',NR,'INCREASES_ACTIVITY_OF','hu:molecular-entity:sirtuin-deacetylase-family','INFERRED_FROM_MEASUREMENT','NEGATIVE',None,['hu:locator:pmc6702140-results-acetylation'],'STATES','STUDY_RESULT',T0,['hu:assertion:elhassan-nr-acetylation-no-change-muscle']),
]
for uid,s,p,o,b,pol,ctx,ls,sa,ab,rec,df in A:
    node(['Assertion'],uid,{'predicate':p,'predicateClass':'MECHANISM','basisKind':b,'polarity':pol,'status':'ACCEPTED','recordedAt':rec,'speechAct':sa,'assertionBasis':ab,'validFromBasis':'UNKNOWN','validToBasis':'UNKNOWN','privacyClass':'PUBLIC'})
    rel(uid,'HAS_SUBJECT',s); rel(uid,'HAS_OBJECT',o)
    for l in ls: rel(uid,'SUPPORTED_BY',l)
    if ctx: rel(uid,'OBSERVED_IN_CONTEXT',ctx)
    for d in df: rel(uid,'DERIVED_FROM_ASSERTION',d)

# Correction: v2 (full-text extraction with exposure) supersedes v1 (abstract-only capture); valid time untouched
rel('hu:assertion:trammell-nr-increases-nad-liver-v2','SUPERSEDES','hu:assertion:trammell-nr-increases-nad-liver-v1',{'supersessionKind':'EXTRACTION_FIX','recordedAt':"@datetime('2026-10-04T02:00:00Z')"})
st('close v1: status projection SUPERSEDED, recordedTo written once',
   "MATCH (a:Assertion {uid: 'hu:assertion:trammell-nr-increases-nad-liver-v1'})\nSET a.status = 'SUPERSEDED', a.recordedTo = datetime('2026-10-04T02:00:00Z')")

# Capture-fidelity policy adjudication for ACCEPTED assertions (INV-103); not a truth verdict
st('capture-fidelity policy adjudication',
"""MATCH (a:Assertion)
WHERE a.status IN ['ACCEPTED', 'REJECTED', 'DISPUTED']
  AND NOT EXISTS { MATCH (:Adjudication {adjudicationKind: 'CAPTURE_FIDELITY'})-[:EVALUATES]->(a) }
MERGE (j:Adjudication:EvidenceAssessment {uid: 'hu:adjudication:w03-fixture-capture-fidelity-policy-2026-10-04'})
ON CREATE SET j.id = 'w03-fixture-capture-fidelity-policy-2026-10-04', j.assessmentType = 'ADJUDICATION', j.adjudicationKind = 'CAPTURE_FIDELITY',
    j.verdict = 'SUPPORTED', j.reviewerType = 'POLICY', j.methodVersion = 'fixture-capture-policy-1', j.status = 'ACCEPTED',
    j.reviewedAt = datetime('2026-10-04T03:00:00Z'), j.recordedAt = datetime('2026-10-04T03:00:00Z'), j.createdAt = datetime('2026-10-04T03:00:00Z'),
    j.privacyClass = 'INTERNAL'
MERGE (j)-[:EVALUATES]->(a)""")

open(OUT,'w').write('\n'.join(S))
print(len(S),'statements')
