// =====================================================================================================================
// W10 fixture 03: surrogate status is bound to a context of use and does not transfer (INV-205). Load the inherited
// study-vs-product-mismatch.cypher first (it holds the NRPT LDL-C outcome classified BIOMARKER_NOT_SURROGATE / SAFETY with
// contextMatch PARTIAL against the FDA hypercholesterolemia context).
// Adds: the FDA table rows as TEXT_QUOTE locators (Firecrawl scrape 2026-10-04, page revision 2026-04-29) - LDL-C appears
// in TWO contexts (hypercholesterolemia / lipid-lowering; LAL deficiency / enzyme replacement), each its own
// EndpointClassification; a v2 of the inherited hypercholesterolemia context SUPERSEDES {RE_REVIEW} v1 to cite the row
// span instead of a SECTION locator; NADPARK (NCT03816020): registered biomarker primary (FDG-PET PDRP ->
// BIOMARKER_NOT_SURROGATE, PHARMACODYNAMIC_RESPONSE, NOT_ESTABLISHED) and clinical secondary (MDS-UPDRS -> CLINICAL_OUTCOME).
// Expected: V-214, V-214b, W10-V08 zero rows. Generated by gen_w10.py.
// =====================================================================================================================

// status: run
MERGE (src:Source {uid: 'hu:source:fda-surrogate-endpoint-table'})
  ON CREATE SET src.id = 'fda-surrogate-endpoint-table', src.entityType = 'Source', src.canonicalUri = 'https://www.fda.gov/drugs/development-resources/table-surrogate-endpoints-were-basis-drug-approval-or-licensure', src.sourceKind = 'REGULATORY_GUIDANCE', src.title = null, src.createdAt = datetime('2026-10-04T02:00:00Z'), src.privacyClass = 'PUBLIC'
SET src:Entity
MERGE (snap:SourceSnapshot {uid: 'hu:snapshot:fda-surrogate-table-2026-10-04'})
  ON CREATE SET snap.id = 'fda-surrogate-table-2026-10-04', snap.artifactType = 'SourceSnapshot', snap.canonicalUri = 'https://www.fda.gov/drugs/development-resources/table-surrogate-endpoints-were-basis-drug-approval-or-licensure',
    snap.retrievedAt = datetime('2026-10-04T01:20:00Z'), snap.observedAt = datetime('2026-10-04T01:20:00Z'), snap.publishedAt = datetime('2026-04-29T00:00:00Z'),
    snap.contentHash = 'synthetic:hu:snapshot:fda-surrogate-table-2026-10-04', snap.contentHashBasis = 'SYNTHETIC_FIXTURE', snap.captureCompleteness = 'PARTIAL_EXCERPT',
    snap.createdAt = datetime('2026-10-04T02:00:00Z'), snap.privacyClass = 'PUBLIC'
SET snap:InformationArtifact
MERGE (src)-[:HAS_SNAPSHOT]->(snap)
MERGE (l0:SourceLocator {uid: 'hu:locator:fda-surrogate-table-2026-10-04-hypercholesterolemia-row'})
  ON CREATE SET l0.id = 'fda-surrogate-table-2026-10-04-hypercholesterolemia-row', l0.artifactType = 'SourceLocator', l0.uri = 'https://www.fda.gov/drugs/development-resources/table-surrogate-endpoints-were-basis-drug-approval-or-licensure', l0.selectorKind = 'TEXT_QUOTE', l0.section = 'Table 1. Adult Surrogate Endpoints - Non-Cancer Related', l0.exact = '| Hypercholesterolemia | Patients with heterozygous familial and nonfamilial hypercholesterolemia | Serum LDL cholesterol | Traditional | Lipid-lowering |', l0.quoteHash = 'sha256:cdae8ee2c0054f85a4179b07706110957ddefd5b4ec52a9fb4cd26268001a0c7', l0.normalizationVersion = 'NFC-WS1', l0.createdAt = datetime('2026-10-04T02:00:00Z'), l0.privacyClass = 'PUBLIC'
SET l0:InformationArtifact
MERGE (snap)-[:HAS_LOCATOR]->(l0)
MERGE (l1:SourceLocator {uid: 'hu:locator:fda-surrogate-table-2026-10-04-lal-row'})
  ON CREATE SET l1.id = 'fda-surrogate-table-2026-10-04-lal-row', l1.artifactType = 'SourceLocator', l1.uri = 'https://www.fda.gov/drugs/development-resources/table-surrogate-endpoints-were-basis-drug-approval-or-licensure', l1.selectorKind = 'TEXT_QUOTE', l1.section = 'Table 1. Adult Surrogate Endpoints - Non-Cancer Related', l1.exact = '| Lysosomal Acid Lipase (LAL) deficiency | Patients with LAL deficiency | Serum LDL-c levels | Traditional | Hydrolytic lysosomal cholesteryl ester and triacylglycerol-specific enzyme |', l1.quoteHash = 'sha256:965cf8eb6afbf89caf113c584c7e1ec89c4d1053a7bac69e66bd30e7022530ee', l1.normalizationVersion = 'NFC-WS1', l1.createdAt = datetime('2026-10-04T02:00:00Z'), l1.privacyClass = 'PUBLIC'
SET l1:InformationArtifact
MERGE (snap)-[:HAS_LOCATOR]->(l1)
MERGE (l2:SourceLocator {uid: 'hu:locator:fda-surrogate-table-2026-10-04-context-dependent'})
  ON CREATE SET l2.id = 'fda-surrogate-table-2026-10-04-context-dependent', l2.artifactType = 'SourceLocator', l2.uri = 'https://www.fda.gov/drugs/development-resources/table-surrogate-endpoints-were-basis-drug-approval-or-licensure', l2.selectorKind = 'TEXT_QUOTE', l2.section = 'What are the key considerations of the surrogate endpoint table?', l2.exact = 'A particular surrogate endpoint that may be appropriate for use in a particular drug or biologic clinical development program, should not be assumed to be appropriate for use in a different program that is in a different clinical setting.', l2.quoteHash = 'sha256:e05b3d00aa1c0a3afeb672c3950e03e6ef6ab9e3a09d593281da12077ed9ab76', l2.normalizationVersion = 'NFC-WS1', l2.createdAt = datetime('2026-10-04T02:00:00Z'), l2.privacyClass = 'PUBLIC'
SET l2:InformationArtifact
MERGE (snap)-[:HAS_LOCATOR]->(l2);

// status: run
MERGE (src:Source {uid: 'hu:source:fda-about-biomarkers-and-qualification'})
  ON CREATE SET src.id = 'fda-about-biomarkers-and-qualification', src.entityType = 'Source', src.canonicalUri = 'https://www.fda.gov/drugs/biomarker-qualification-program/about-biomarkers-and-qualification', src.sourceKind = 'REGULATORY_GUIDANCE', src.title = null, src.createdAt = datetime('2026-10-04T02:00:00Z'), src.privacyClass = 'PUBLIC'
SET src:Entity
MERGE (snap:SourceSnapshot {uid: 'hu:snapshot:fda-about-biomarkers-2026-10-04'})
  ON CREATE SET snap.id = 'fda-about-biomarkers-2026-10-04', snap.artifactType = 'SourceSnapshot', snap.canonicalUri = 'https://www.fda.gov/drugs/biomarker-qualification-program/about-biomarkers-and-qualification',
    snap.retrievedAt = datetime('2026-10-04T01:20:00Z'), snap.observedAt = datetime('2026-10-04T01:20:00Z'), snap.publishedAt = null,
    snap.contentHash = 'synthetic:hu:snapshot:fda-about-biomarkers-2026-10-04', snap.contentHashBasis = 'SYNTHETIC_FIXTURE', snap.captureCompleteness = 'PARTIAL_EXCERPT',
    snap.createdAt = datetime('2026-10-04T02:00:00Z'), snap.privacyClass = 'PUBLIC'
SET snap:InformationArtifact
MERGE (src)-[:HAS_SNAPSHOT]->(snap)
MERGE (l0:SourceLocator {uid: 'hu:locator:fda-about-biomarkers-2026-10-04-best-categories'})
  ON CREATE SET l0.id = 'fda-about-biomarkers-2026-10-04-best-categories', l0.artifactType = 'SourceLocator', l0.uri = 'https://www.fda.gov/drugs/biomarker-qualification-program/about-biomarkers-and-qualification', l0.selectorKind = 'TEXT_QUOTE', l0.section = 'Biomarker Categories: BEST Glossary', l0.exact = 'BEST defines seven biomarker categories: susceptibility/risk, diagnostic, monitoring, prognostic, predictive, pharmacodynamic/response, and safety.', l0.quoteHash = 'sha256:dbbaf37f71d0ece9bb71ed251492a2fd58bcc065d67779781a9101fd23b9e02a', l0.normalizationVersion = 'NFC-WS1', l0.createdAt = datetime('2026-10-04T02:00:00Z'), l0.privacyClass = 'PUBLIC'
SET l0:InformationArtifact
MERGE (snap)-[:HAS_LOCATOR]->(l0);

// status: run
MERGE (src:Source {uid: 'hu:source:ctgov-nct03816020'})
  ON CREATE SET src.id = 'ctgov-nct03816020', src.entityType = 'Source', src.canonicalUri = 'https://clinicaltrials.gov/study/NCT03816020', src.sourceKind = 'REGULATORY_RECORD', src.title = null, src.createdAt = datetime('2026-10-04T02:00:00Z'), src.privacyClass = 'PUBLIC'
SET src:Entity
MERGE (snap:SourceSnapshot {uid: 'hu:snapshot:ctgov-nct03816020-2026-10-04'})
  ON CREATE SET snap.id = 'ctgov-nct03816020-2026-10-04', snap.artifactType = 'SourceSnapshot', snap.canonicalUri = 'https://clinicaltrials.gov/study/NCT03816020',
    snap.retrievedAt = datetime('2026-10-04T01:20:00Z'), snap.observedAt = datetime('2026-10-04T01:20:00Z'), snap.publishedAt = null,
    snap.contentHash = 'synthetic:hu:snapshot:ctgov-nct03816020-2026-10-04', snap.contentHashBasis = 'SYNTHETIC_FIXTURE', snap.captureCompleteness = 'PARTIAL_EXCERPT',
    snap.createdAt = datetime('2026-10-04T02:00:00Z'), snap.privacyClass = 'PUBLIC'
SET snap:InformationArtifact
MERGE (src)-[:HAS_SNAPSHOT]->(snap)
MERGE (l0:SourceLocator {uid: 'hu:locator:ctgov-nct03816020-2026-10-04-primary-outcome'})
  ON CREATE SET l0.id = 'ctgov-nct03816020-2026-10-04-primary-outcome', l0.artifactType = 'SourceLocator', l0.uri = 'https://clinicaltrials.gov/study/NCT03816020', l0.selectorKind = 'TEXT_QUOTE', l0.section = 'Primary Outcome Measures', l0.exact = 'The primary outcome will be the between-group difference in Parkinson\'s disease related pattern (PDRP) measured by FDG-PET comparing baseline and 3-4 week follow-up measurement.', l0.quoteHash = 'sha256:1d956631fa19f06cc90a7b025d625691fff2fb221adfe6d4b915ac524ef46bd5', l0.normalizationVersion = 'NFC-WS1', l0.createdAt = datetime('2026-10-04T02:00:00Z'), l0.privacyClass = 'PUBLIC'
SET l0:InformationArtifact
MERGE (snap)-[:HAS_LOCATOR]->(l0)
MERGE (l1:SourceLocator {uid: 'hu:locator:ctgov-nct03816020-2026-10-04-secondary-outcome'})
  ON CREATE SET l1.id = 'ctgov-nct03816020-2026-10-04-secondary-outcome', l1.artifactType = 'SourceLocator', l1.uri = 'https://clinicaltrials.gov/study/NCT03816020', l1.selectorKind = 'TEXT_QUOTE', l1.section = 'Secondary Outcome Measures', l1.exact = 'Clinical changes measured by MDS-UPDRS from using NR', l1.quoteHash = 'sha256:ec0bc52bc93d204c48dd35a2c13386f2f559e91711bbe4b56e33359594a1c885', l1.normalizationVersion = 'NFC-WS1', l1.createdAt = datetime('2026-10-04T02:00:00Z'), l1.privacyClass = 'PUBLIC'
SET l1:InformationArtifact
MERGE (snap)-[:HAS_LOCATOR]->(l1);

// status: run
MERGE (src:Source {uid: 'hu:source:doi-10.1016-j.cmet.2022.02.001'})
  ON CREATE SET src.id = 'doi-10.1016-j.cmet.2022.02.001', src.entityType = 'Source', src.canonicalUri = 'https://doi.org/10.1016/j.cmet.2022.02.001', src.sourceKind = 'PEER_REVIEWED_PUBLICATION', src.title = null, src.createdAt = datetime('2026-10-04T02:00:00Z'), src.privacyClass = 'PUBLIC'
SET src:Entity
MERGE (snap:SourceSnapshot {uid: 'hu:snapshot:pmid35235774-abstract-2026-10-04'})
  ON CREATE SET snap.id = 'pmid35235774-abstract-2026-10-04', snap.artifactType = 'SourceSnapshot', snap.canonicalUri = 'https://doi.org/10.1016/j.cmet.2022.02.001',
    snap.retrievedAt = datetime('2026-10-04T01:20:00Z'), snap.observedAt = datetime('2026-10-04T01:20:00Z'), snap.publishedAt = datetime('2022-03-01T00:00:00Z'),
    snap.contentHash = 'synthetic:hu:snapshot:pmid35235774-abstract-2026-10-04', snap.contentHashBasis = 'SYNTHETIC_FIXTURE', snap.captureCompleteness = 'PARTIAL_EXCERPT',
    snap.createdAt = datetime('2026-10-04T02:00:00Z'), snap.privacyClass = 'PUBLIC'
SET snap:InformationArtifact
MERGE (src)-[:HAS_SNAPSHOT]->(snap)
MERGE (l0:SourceLocator {uid: 'hu:locator:pmid35235774-abstract-responders'})
  ON CREATE SET l0.id = 'pmid35235774-abstract-responders', l0.artifactType = 'SourceLocator', l0.uri = 'https://doi.org/10.1016/j.cmet.2022.02.001', l0.selectorKind = 'TEXT_QUOTE', l0.section = 'Abstract', l0.exact = 'NR recipients showing increased brain NAD levels exhibited altered cerebral metabolism, measured byfluoro-deoxyglucose positron emission tomography, and this was associated with mild clinical improvement.', l0.quoteHash = 'sha256:c6c79bbc7f515b634ef1bcd5f8d286bc18aed39b04521997c5e5740ec9400b76', l0.normalizationVersion = 'NFC-WS1', l0.createdAt = datetime('2026-10-04T02:00:00Z'), l0.privacyClass = 'PUBLIC'
SET l0:InformationArtifact
MERGE (snap)-[:HAS_LOCATOR]->(l0);

// status: run
MERGE (st:Study {uid: 'hu:study:nct03816020-nadpark'})
  ON CREATE SET st.id = 'nct03816020-nadpark', st.entityType = 'Study', st.name = 'NADPARK: nicotinamide riboside in drug-naive Parkinson disease',
    st.studyKind = 'INTERVENTIONAL_RANDOMIZED', st.createdAt = datetime('2026-10-04T02:00:00Z'), st.privacyClass = 'PUBLIC'
SET st:Entity
WITH st
UNWIND [
  {uid: 'hu:outcome:nadpark-pdrp-fdg-pet', name: 'Between-group difference in Parkinson disease related pattern (PDRP), FDG-PET, baseline to 3-4 weeks', mk: 'BIOMARKER', tp: '4 weeks'},
  {uid: 'hu:outcome:nadpark-mds-updrs', name: 'Motor symptom change measured by MDS-UPDRS', mk: 'CLINICIAN_REPORTED_OUTCOME', tp: '4 weeks'}
] AS r
MERGE (od:OutcomeDefinition {uid: r.uid})
  ON CREATE SET od.id = split(r.uid, ':')[2], od.stateType = 'OutcomeDefinition', od.payloadHash = 'sha256:' + split(r.uid, ':')[2],
    od.name = r.name, od.measureKind = r.mk, od.timepoint = r.tp, od.createdAt = datetime('2026-10-04T02:00:00Z'), od.privacyClass = 'PUBLIC'
SET od:VersionedState
MERGE (st)-[:DEFINES_OUTCOME]->(od);

// status: run
MATCH (s {uid: 'hu:outcome:nadpark-pdrp-fdg-pet'})
MERGE (a:Assertion {uid: 'hu:assertion:w10-nadpark-pdrp-priority-registry'})
  ON CREATE SET a.id = 'w10-nadpark-pdrp-priority-registry', a.predicate = 'DECLARES_OUTCOME_PRIORITY', a.status = 'ACCEPTED', a.polarity = 'POSITIVE', a.validFromBasis = 'UNKNOWN', a.validToBasis = 'UNKNOWN', a.privacyClass = 'PUBLIC', a.contentHash = 'sha256:58e63317e349f3476884733a580b6ba7228febff348f0c6dc6acfd886a3e5dad', a.valueString = 'PRIMARY', a.recordedAt = datetime('2026-10-04T02:00:00Z'), a.createdAt = datetime('2026-10-04T02:00:00Z')
MERGE (a)-[:HAS_SUBJECT]->(s)
WITH a
UNWIND ['hu:locator:ctgov-nct03816020-2026-10-04-primary-outcome'] AS lu
MATCH (l:SourceLocator {uid: lu})
MERGE (a)-[:SUPPORTED_BY]->(l);

// status: run
MATCH (s {uid: 'hu:outcome:nadpark-mds-updrs'})
MERGE (a:Assertion {uid: 'hu:assertion:w10-nadpark-updrs-priority-registry'})
  ON CREATE SET a.id = 'w10-nadpark-updrs-priority-registry', a.predicate = 'DECLARES_OUTCOME_PRIORITY', a.status = 'ACCEPTED', a.polarity = 'POSITIVE', a.validFromBasis = 'UNKNOWN', a.validToBasis = 'UNKNOWN', a.privacyClass = 'PUBLIC', a.contentHash = 'sha256:786787cd02c2b3f6bffd56a0f615176f557c06c14a25e8b33777979a8ee60ca5', a.valueString = 'SECONDARY', a.recordedAt = datetime('2026-10-04T02:00:00Z'), a.createdAt = datetime('2026-10-04T02:00:00Z')
MERGE (a)-[:HAS_SUBJECT]->(s)
WITH a
UNWIND ['hu:locator:ctgov-nct03816020-2026-10-04-secondary-outcome'] AS lu
MATCH (l:SourceLocator {uid: lu})
MERGE (a)-[:SUPPORTED_BY]->(l);

// status: run
UNWIND ['hu:assertion:w10-nadpark-pdrp-priority-registry', 'hu:assertion:w10-nadpark-updrs-priority-registry'] AS au
MATCH (a:Assertion {uid: au})
MERGE (j:Adjudication {uid: 'hu:adjudication:w10-fixture-03-capture-policy'})
  ON CREATE SET j.id = 'w10-fixture-03-capture-policy', j.assessmentType = 'Adjudication', j.adjudicationKind = 'CAPTURE_FIDELITY', j.verdict = 'SUPPORTED',
    j.reviewerType = 'POLICY', j.methodVersion = 'w10-fixture-capture-policy-1', j.status = 'ACCEPTED', j.privacyClass = 'INTERNAL',
    j.rationale = 'Fixture capture policy: recorded propositions match the cited quotes; says nothing about truth.',
    j.reviewedAt = datetime('2026-10-04T02:00:00Z'), j.recordedAt = datetime('2026-10-04T02:00:00Z'), j.createdAt = datetime('2026-10-04T02:00:00Z')
SET j:EvidenceAssessment
MERGE (j)-[:EVALUATES]->(a);

// status: run
MERGE (ec:EndpointClassification {uid: 'hu:endpoint-classification:w10-ldl-c-fda-hypercholesterolemia-lipid-lowering-v2'})
  ON CREATE SET ec.id = 'w10-ldl-c-fda-hypercholesterolemia-lipid-lowering-v2', ec.assessmentType = 'EndpointClassification', ec.methodVersion = 'endpoint-class-v0.1', ec.status = 'PROPOSED', ec.privacyClass = 'PUBLIC', ec.endpointClass = 'SURROGATE_ENDPOINT', ec.biomarkerCategory = null, ec.surrogateValidationLevel = 'VALIDATED', ec.contextDiseaseOrUse = 'Hypercholesterolemia', ec.contextPopulation = 'Patients with heterozygous familial and nonfamilial hypercholesterolemia', ec.contextInterventionMechanism = 'Lipid-lowering', ec.contextApprovalType = 'TRADITIONAL', ec.contextMatch = null, ec.rationale = 'FDA surrogate endpoint table row (2026-04-29 revision): serum LDL cholesterol, traditional approval, lipid-lowering mechanism. FD&C Act 507(e)(9): traditional = known to predict clinical benefit.', ec.recordedAt = datetime('2026-10-04T02:00:00Z'), ec.createdAt = datetime('2026-10-04T02:00:00Z')
SET ec:EvidenceAssessment
WITH ec
MATCH (t0 {uid: 'hu:biomarker:ldl-c-serum'})
MERGE (ec)-[:CLASSIFIES_BIOMARKER]->(t0)
WITH ec
MATCH (t1 {uid: 'hu:locator:fda-surrogate-table-2026-10-04-hypercholesterolemia-row'})
MERGE (ec)-[:SUPPORTED_BY]->(t1)
WITH ec
MATCH (t2 {uid: 'hu:locator:fda-surrogate-table-2026-10-04-context-dependent'})
MERGE (ec)-[:SUPPORTED_BY]->(t2);

// status: run
MATCH (newer:EndpointClassification {uid: 'hu:endpoint-classification:w10-ldl-c-fda-hypercholesterolemia-lipid-lowering-v2'}), (older:EndpointClassification {uid: 'hu:endpoint-classification:ldl-c-fda-hypercholesterolemia-lipid-lowering'})
MERGE (newer)-[r:SUPERSEDES]->(older)
  ON CREATE SET r.supersessionKind = 'RE_REVIEW', r.recordedAt = newer.recordedAt
SET older.recordedTo = coalesce(older.recordedTo, newer.recordedAt);

// status: run
MERGE (ec:EndpointClassification {uid: 'hu:endpoint-classification:w10-ldl-c-fda-lal-deficiency-enzyme'})
  ON CREATE SET ec.id = 'w10-ldl-c-fda-lal-deficiency-enzyme', ec.assessmentType = 'EndpointClassification', ec.methodVersion = 'endpoint-class-v0.1', ec.status = 'PROPOSED', ec.privacyClass = 'PUBLIC', ec.endpointClass = 'SURROGATE_ENDPOINT', ec.biomarkerCategory = null, ec.surrogateValidationLevel = 'VALIDATED', ec.contextDiseaseOrUse = 'Lysosomal Acid Lipase (LAL) deficiency', ec.contextPopulation = 'Patients with LAL deficiency', ec.contextInterventionMechanism = 'Hydrolytic lysosomal cholesteryl ester and triacylglycerol-specific enzyme', ec.contextApprovalType = 'TRADITIONAL', ec.contextMatch = null, ec.rationale = 'Same analyte (serum LDL-C), different disease and mechanism: a second, separate context of use.', ec.recordedAt = datetime('2026-10-04T02:00:00Z'), ec.createdAt = datetime('2026-10-04T02:00:00Z')
SET ec:EvidenceAssessment
WITH ec
MATCH (t0 {uid: 'hu:biomarker:ldl-c-serum'})
MERGE (ec)-[:CLASSIFIES_BIOMARKER]->(t0)
WITH ec
MATCH (t1 {uid: 'hu:locator:fda-surrogate-table-2026-10-04-lal-row'})
MERGE (ec)-[:SUPPORTED_BY]->(t1);

// status: run
MERGE (ec:EndpointClassification {uid: 'hu:endpoint-classification:w10-nadpark-pdrp-fdg-pet'})
  ON CREATE SET ec.id = 'w10-nadpark-pdrp-fdg-pet', ec.assessmentType = 'EndpointClassification', ec.methodVersion = 'endpoint-class-v0.1', ec.status = 'PROPOSED', ec.privacyClass = 'PUBLIC', ec.endpointClass = 'BIOMARKER_NOT_SURROGATE', ec.biomarkerCategory = 'PHARMACODYNAMIC_RESPONSE', ec.surrogateValidationLevel = 'NOT_ESTABLISHED', ec.contextDiseaseOrUse = 'Parkinson disease (drug-naive, newly diagnosed)', ec.contextPopulation = 'Newly diagnosed drug-naive PD patients', ec.contextInterventionMechanism = 'NAD+ precursor (nicotinamide riboside)', ec.contextApprovalType = null, ec.contextMatch = 'NONE', ec.rationale = 'Imaging pattern used as the registered primary outcome to detect a response to NR; no Parkinson disease row exists in the retrieved FDA table (absence in one table is not proof that no context exists anywhere).', ec.recordedAt = datetime('2026-10-04T02:00:00Z'), ec.createdAt = datetime('2026-10-04T02:00:00Z')
SET ec:EvidenceAssessment
WITH ec
MATCH (t0 {uid: 'hu:outcome:nadpark-pdrp-fdg-pet'})
MERGE (ec)-[:CLASSIFIES_OUTCOME]->(t0)
WITH ec
MATCH (t1 {uid: 'hu:locator:ctgov-nct03816020-2026-10-04-primary-outcome'})
MERGE (ec)-[:SUPPORTED_BY]->(t1)
WITH ec
MATCH (t2 {uid: 'hu:locator:fda-about-biomarkers-2026-10-04-best-categories'})
MERGE (ec)-[:SUPPORTED_BY]->(t2);

// status: run
MERGE (ec:EndpointClassification {uid: 'hu:endpoint-classification:w10-nadpark-mds-updrs'})
  ON CREATE SET ec.id = 'w10-nadpark-mds-updrs', ec.assessmentType = 'EndpointClassification', ec.methodVersion = 'endpoint-class-v0.1', ec.status = 'PROPOSED', ec.privacyClass = 'PUBLIC', ec.endpointClass = 'CLINICAL_OUTCOME', ec.biomarkerCategory = null, ec.surrogateValidationLevel = null, ec.contextDiseaseOrUse = 'Parkinson disease', ec.contextPopulation = 'Newly diagnosed drug-naive PD patients', ec.contextInterventionMechanism = null, ec.contextApprovalType = null, ec.contextMatch = null, ec.rationale = 'MDS-UPDRS is a clinician-reported clinical outcome assessment of motor function (how a patient functions); registered as secondary. A biomarker primary with a clinical secondary: the secondary is the patient-important outcome.', ec.recordedAt = datetime('2026-10-04T02:00:00Z'), ec.createdAt = datetime('2026-10-04T02:00:00Z')
SET ec:EvidenceAssessment
WITH ec
MATCH (t0 {uid: 'hu:outcome:nadpark-mds-updrs'})
MERGE (ec)-[:CLASSIFIES_OUTCOME]->(t0)
WITH ec
MATCH (t1 {uid: 'hu:locator:ctgov-nct03816020-2026-10-04-secondary-outcome'})
MERGE (ec)-[:SUPPORTED_BY]->(t1);

