// =====================================================================================================================
// W10 fixture 05: a claim-level synthesis re-versioned by new results (CQ-ST-09, KCR-2a). Real record: the vitamin D /
// acute respiratory infection meta-analysis by Martineau, Jolliffe et al., versioned three times by its authors
// (BMJ 2017 PMID 28202713: OR 0.88; Lancet D&E 2021 PMID 33798465: OR 0.92; Lancet D&E 2025 PMID 39993397: OR 0.94, CI
// 0.88-1.00, "no statistically significant protection"; PubMed connector 2026-10-04). BellLabs' synthesis v1 -> v2 -> v3
// SUPERSEDES each predecessor and is TRIGGERED_BY the update publication {criterionCode, effectOnVerdict, evidencePublishedAt}.
// All three versions are RECORDED on 2026-10-04 (recorded time is never backdated, INV-502); the domain chronology lives on
// evidencePublishedAt / evidenceCutoff. The 2025 age 1-15 subgroup enters v3 only as HYPOTHESIS_GENERATING.
// Pooled estimates are Assertions with the CANDIDATE predicate REPORTS_POOLED_ESTIMATE (W10-SR-07).
// Expected: V-219, V-219b, V-219c zero rows; W10-V12, W10-V13 zero rows. Generated by gen_w10.py.
// =====================================================================================================================

// status: run
MERGE (src:Source {uid: 'hu:source:doi-10.1136-bmj.i6583'})
  ON CREATE SET src.id = 'doi-10.1136-bmj.i6583', src.entityType = 'Source', src.canonicalUri = 'https://doi.org/10.1136/bmj.i6583', src.sourceKind = 'PEER_REVIEWED_PUBLICATION', src.title = null, src.createdAt = datetime('2026-10-04T02:00:00Z'), src.privacyClass = 'PUBLIC'
SET src:Entity
MERGE (snap:SourceSnapshot {uid: 'hu:snapshot:pmid28202713-abstract-2026-10-04'})
  ON CREATE SET snap.id = 'pmid28202713-abstract-2026-10-04', snap.artifactType = 'SourceSnapshot', snap.canonicalUri = 'https://doi.org/10.1136/bmj.i6583',
    snap.retrievedAt = datetime('2026-10-04T01:20:00Z'), snap.observedAt = datetime('2026-10-04T01:20:00Z'), snap.publishedAt = datetime('2017-02-15T00:00:00Z'),
    snap.contentHash = 'synthetic:hu:snapshot:pmid28202713-abstract-2026-10-04', snap.contentHashBasis = 'SYNTHETIC_FIXTURE', snap.captureCompleteness = 'PARTIAL_EXCERPT',
    snap.createdAt = datetime('2026-10-04T02:00:00Z'), snap.privacyClass = 'PUBLIC'
SET snap:InformationArtifact
MERGE (src)-[:HAS_SNAPSHOT]->(snap)
MERGE (l0:SourceLocator {uid: 'hu:locator:pmid28202713-abstract-pooled-or'})
  ON CREATE SET l0.id = 'pmid28202713-abstract-pooled-or', l0.artifactType = 'SourceLocator', l0.uri = 'https://doi.org/10.1136/bmj.i6583', l0.selectorKind = 'TEXT_QUOTE', l0.section = 'Abstract: Results', l0.exact = 'Vitamin D supplementation reduced the risk of acute respiratory tract infection among all participants (adjusted odds ratio 0.88, 95% confidence interval 0.81 to 0.96; P for heterogeneity <0.001).', l0.quoteHash = 'sha256:02037dc2d7c97a02c20c852f7b8b63721288bce2f99203b61357b58559efd5e5', l0.normalizationVersion = 'NFC-WS1', l0.createdAt = datetime('2026-10-04T02:00:00Z'), l0.privacyClass = 'PUBLIC'
SET l0:InformationArtifact
MERGE (snap)-[:HAS_LOCATOR]->(l0)
MERGE (l1:SourceLocator {uid: 'hu:locator:pmid28202713-abstract-quality'})
  ON CREATE SET l1.id = 'pmid28202713-abstract-quality', l1.artifactType = 'SourceLocator', l1.uri = 'https://doi.org/10.1136/bmj.i6583', l1.selectorKind = 'TEXT_QUOTE', l1.section = 'Abstract: Results', l1.exact = 'The body of evidence contributing to these analyses was assessed as being of high quality.', l1.quoteHash = 'sha256:3f12fbdbe83dabae2b37d3bf55e8d6cd1851d30020401914857b1924ad16701d', l1.normalizationVersion = 'NFC-WS1', l1.createdAt = datetime('2026-10-04T02:00:00Z'), l1.privacyClass = 'PUBLIC'
SET l1:InformationArtifact
MERGE (snap)-[:HAS_LOCATOR]->(l1);

// status: run
MERGE (src:Source {uid: 'hu:source:doi-10.1016-s2213-8587-21-00051-6'})
  ON CREATE SET src.id = 'doi-10.1016-s2213-8587-21-00051-6', src.entityType = 'Source', src.canonicalUri = 'https://doi.org/10.1016/S2213-8587(21)00051-6', src.sourceKind = 'PEER_REVIEWED_PUBLICATION', src.title = null, src.createdAt = datetime('2026-10-04T02:00:00Z'), src.privacyClass = 'PUBLIC'
SET src:Entity
MERGE (snap:SourceSnapshot {uid: 'hu:snapshot:pmid33798465-abstract-2026-10-04'})
  ON CREATE SET snap.id = 'pmid33798465-abstract-2026-10-04', snap.artifactType = 'SourceSnapshot', snap.canonicalUri = 'https://doi.org/10.1016/S2213-8587(21)00051-6',
    snap.retrievedAt = datetime('2026-10-04T01:20:00Z'), snap.observedAt = datetime('2026-10-04T01:20:00Z'), snap.publishedAt = datetime('2021-03-30T00:00:00Z'),
    snap.contentHash = 'synthetic:hu:snapshot:pmid33798465-abstract-2026-10-04', snap.contentHashBasis = 'SYNTHETIC_FIXTURE', snap.captureCompleteness = 'PARTIAL_EXCERPT',
    snap.createdAt = datetime('2026-10-04T02:00:00Z'), snap.privacyClass = 'PUBLIC'
SET snap:InformationArtifact
MERGE (src)-[:HAS_SNAPSHOT]->(snap)
MERGE (l0:SourceLocator {uid: 'hu:locator:pmid33798465-abstract-pooled-or'})
  ON CREATE SET l0.id = 'pmid33798465-abstract-pooled-or', l0.artifactType = 'SourceLocator', l0.uri = 'https://doi.org/10.1016/S2213-8587(21)00051-6', l0.selectorKind = 'TEXT_QUOTE', l0.section = 'Abstract: Findings', l0.exact = 'with an OR of 0·92 (95% CI 0·86-0·99; 37 studies; I=35·6%, p=0·018).', l0.quoteHash = 'sha256:6bd8c5a4ba591d6ed561fc3cbf6addf940eaf00f5a7bb160a8ca45c23e9891b5', l0.normalizationVersion = 'NFC-WS1', l0.createdAt = datetime('2026-10-04T02:00:00Z'), l0.privacyClass = 'PUBLIC'
SET l0:InformationArtifact
MERGE (snap)-[:HAS_LOCATOR]->(l0);

// status: run
MERGE (src:Source {uid: 'hu:source:doi-10.1016-s2213-8587-24-00348-6'})
  ON CREATE SET src.id = 'doi-10.1016-s2213-8587-24-00348-6', src.entityType = 'Source', src.canonicalUri = 'https://doi.org/10.1016/S2213-8587(24)00348-6', src.sourceKind = 'PEER_REVIEWED_PUBLICATION', src.title = null, src.createdAt = datetime('2026-10-04T02:00:00Z'), src.privacyClass = 'PUBLIC'
SET src:Entity
MERGE (snap:SourceSnapshot {uid: 'hu:snapshot:pmc12056739-2026-10-04'})
  ON CREATE SET snap.id = 'pmc12056739-2026-10-04', snap.artifactType = 'SourceSnapshot', snap.canonicalUri = 'https://doi.org/10.1016/S2213-8587(24)00348-6',
    snap.retrievedAt = datetime('2026-10-04T01:20:00Z'), snap.observedAt = datetime('2026-10-04T01:20:00Z'), snap.publishedAt = datetime('2025-02-21T00:00:00Z'),
    snap.contentHash = 'synthetic:hu:snapshot:pmc12056739-2026-10-04', snap.contentHashBasis = 'SYNTHETIC_FIXTURE', snap.captureCompleteness = 'PARTIAL_EXCERPT',
    snap.createdAt = datetime('2026-10-04T02:00:00Z'), snap.privacyClass = 'PUBLIC'
SET snap:InformationArtifact
MERGE (src)-[:HAS_SNAPSHOT]->(snap)
MERGE (l0:SourceLocator {uid: 'hu:locator:pmc12056739-findings-pooled-or'})
  ON CREATE SET l0.id = 'pmc12056739-findings-pooled-or', l0.artifactType = 'SourceLocator', l0.uri = 'https://doi.org/10.1016/S2213-8587(24)00348-6', l0.selectorKind = 'TEXT_QUOTE', l0.section = 'Summary: Findings', l0.exact = 'For the primary comparison of any vitamin D versus placebo, the intervention did not statistically significantly affect overall ARI risk (OR 0·94 [95% CI 0·88–1·00], p=0·057; 40 studies; 61 589 participants;=26·4%).', l0.quoteHash = 'sha256:1ffa51b91f8731e0854e61dbe2fe53aed665023c0a43bfbdb0fdff5e903c9211', l0.normalizationVersion = 'NFC-WS1', l0.createdAt = datetime('2026-10-04T02:00:00Z'), l0.privacyClass = 'PUBLIC'
SET l0:InformationArtifact
MERGE (snap)-[:HAS_LOCATOR]->(l0)
MERGE (l1:SourceLocator {uid: 'hu:locator:pmc12056739-results-subgroup-age-1-15'})
  ON CREATE SET l1.id = 'pmc12056739-results-subgroup-age-1-15', l1.artifactType = 'SourceLocator', l1.uri = 'https://doi.org/10.1016/S2213-8587(24)00348-6', l1.selectorKind = 'TEXT_QUOTE', l1.section = 'Results', l1.exact = 'A statistically significant protective effect of vitamin D was seen for participants aged 1–15 years (OR 0·74 [95% CI 0·60–0·92]; 11 944 participants in 16 studies)', l1.quoteHash = 'sha256:1d214c8769f943f199d55545a7bda5477083ddafbd67292e6f9567a70ce93455', l1.normalizationVersion = 'NFC-WS1', l1.createdAt = datetime('2026-10-04T02:00:00Z'), l1.privacyClass = 'PUBLIC'
SET l1:InformationArtifact
MERGE (snap)-[:HAS_LOCATOR]->(l1)
MERGE (l2:SourceLocator {uid: 'hu:locator:pmc12056739-results-grade-moderate'})
  ON CREATE SET l2.id = 'pmc12056739-results-grade-moderate', l2.artifactType = 'SourceLocator', l2.uri = 'https://doi.org/10.1016/S2213-8587(24)00348-6', l2.selectorKind = 'TEXT_QUOTE', l2.section = 'Results', l2.exact = 'the quality of the body of evidence contributing to analyses of the primary efficacy outcome and major secondary outcomes was downgraded to moderate', l2.quoteHash = 'sha256:a8c8457b695960bdd10bd9c61694535d481f814715b4828293e3bd2734bbe9b5', l2.normalizationVersion = 'NFC-WS1', l2.createdAt = datetime('2026-10-04T02:00:00Z'), l2.privacyClass = 'PUBLIC'
SET l2:InformationArtifact
MERGE (snap)-[:HAS_LOCATOR]->(l2)
MERGE (l3:SourceLocator {uid: 'hu:locator:pmc12056739-interpretation'})
  ON CREATE SET l3.id = 'pmc12056739-interpretation', l3.artifactType = 'SourceLocator', l3.uri = 'https://doi.org/10.1016/S2213-8587(24)00348-6', l3.selectorKind = 'TEXT_QUOTE', l3.section = 'Summary: Interpretation', l3.exact = 'the 95% CI for this effect estimate now includes 1·00, indicating no statistically significant protection.', l3.quoteHash = 'sha256:83015759865fad7d140f9df22c0d9badf270abcac046d202232104ef4594ded7', l3.normalizationVersion = 'NFC-WS1', l3.createdAt = datetime('2026-10-04T02:00:00Z'), l3.privacyClass = 'PUBLIC'
SET l3:InformationArtifact
MERGE (snap)-[:HAS_LOCATOR]->(l3);

// status: run
UNWIND [
  {uid: 'hu:publication:pmid-28202713', pmid: '28202713', doi: '10.1136/bmj.i6583', at: '2017-02-15', name: 'Vitamin D supplementation to prevent acute respiratory tract infections: systematic review and meta-analysis of individual participant data'},
  {uid: 'hu:publication:pmid-33798465', pmid: '33798465', doi: '10.1016/S2213-8587(21)00051-6', at: '2021-03-30', name: 'Vitamin D supplementation to prevent acute respiratory infections: a systematic review and meta-analysis of aggregate data from randomised controlled trials'},
  {uid: 'hu:publication:pmid-39993397', pmid: '39993397', doi: '10.1016/S2213-8587(24)00348-6', at: '2025-02-21', name: 'Vitamin D supplementation to prevent acute respiratory infections: systematic review and meta-analysis of stratified aggregate data'}
] AS r
MERGE (p:Publication {uid: r.uid})
  ON CREATE SET p.id = split(r.uid, ':')[2], p.artifactType = 'Publication', p.publicationKind = 'ARTICLE', p.name = r.name, p.pmid = r.pmid, p.doi = r.doi,
    p.publishedAt = datetime(r.at + 'T00:00:00Z'), p.publishedAtPrecision = 'DAY', p.createdAt = datetime('2026-10-04T02:00:00Z'), p.privacyClass = 'PUBLIC'
SET p:InformationArtifact;

// status: run
MERGE (c:Claim {uid: 'hu:claim:w10-vitamin-d-prevents-acute-respiratory-infection'})
  ON CREATE SET c.id = 'w10-vitamin-d-prevents-acute-respiratory-infection', c.entityType = 'Claim', c.claimText = 'Vitamin D supplementation reduces the risk of acute respiratory infection',
    c.createdAt = datetime('2026-10-04T02:00:00Z'), c.privacyClass = 'PUBLIC'
SET c:Entity;

// status: run
MATCH (s {uid: 'hu:publication:pmid-28202713'})
MERGE (a:Assertion {uid: 'hu:assertion:w10-pmid28202713-pooled-or-any-ari'})
  ON CREATE SET a.id = 'w10-pmid28202713-pooled-or-any-ari', a.predicate = 'REPORTS_POOLED_ESTIMATE', a.status = 'ACCEPTED', a.polarity = 'POSITIVE', a.validFromBasis = 'UNKNOWN', a.validToBasis = 'UNKNOWN', a.privacyClass = 'PUBLIC', a.contentHash = 'sha256:a9f601822318d608dd7cf5d1d9c083167ea42ab62da71801cd9f2e46c42822b3', a.valueNumber = 0.88, a.unitCode = '1', a.valueString = null, a.recordedAt = datetime('2026-10-04T02:00:00Z'), a.createdAt = datetime('2026-10-04T02:00:00Z')
MERGE (a)-[:HAS_SUBJECT]->(s)
WITH a
UNWIND ['hu:locator:pmid28202713-abstract-pooled-or'] AS lu
MATCH (l:SourceLocator {uid: lu})
MERGE (a)-[:SUPPORTED_BY]->(l);

// status: run
MATCH (s {uid: 'hu:publication:pmid-33798465'})
MERGE (a:Assertion {uid: 'hu:assertion:w10-pmid33798465-pooled-or-any-ari'})
  ON CREATE SET a.id = 'w10-pmid33798465-pooled-or-any-ari', a.predicate = 'REPORTS_POOLED_ESTIMATE', a.status = 'ACCEPTED', a.polarity = 'POSITIVE', a.validFromBasis = 'UNKNOWN', a.validToBasis = 'UNKNOWN', a.privacyClass = 'PUBLIC', a.contentHash = 'sha256:c6a3747a4a9b32b7bfae4cee9f547cd020507b10705caea8845566c1301da73f', a.valueNumber = 0.92, a.unitCode = '1', a.recordedAt = datetime('2026-10-04T02:00:00Z'), a.createdAt = datetime('2026-10-04T02:00:00Z')
MERGE (a)-[:HAS_SUBJECT]->(s)
WITH a
UNWIND ['hu:locator:pmid33798465-abstract-pooled-or'] AS lu
MATCH (l:SourceLocator {uid: lu})
MERGE (a)-[:SUPPORTED_BY]->(l);

// status: run
MATCH (s {uid: 'hu:publication:pmid-39993397'})
MERGE (a:Assertion {uid: 'hu:assertion:w10-pmid39993397-pooled-or-any-ari'})
  ON CREATE SET a.id = 'w10-pmid39993397-pooled-or-any-ari', a.predicate = 'REPORTS_POOLED_ESTIMATE', a.status = 'ACCEPTED', a.polarity = 'POSITIVE', a.validFromBasis = 'UNKNOWN', a.validToBasis = 'UNKNOWN', a.privacyClass = 'PUBLIC', a.contentHash = 'sha256:8d2320f428c33aeb1268a880e1286716972369ea4d42d1625afb3c80f86ebc63', a.valueNumber = 0.94, a.unitCode = '1', a.recordedAt = datetime('2026-10-04T02:00:00Z'), a.createdAt = datetime('2026-10-04T02:00:00Z')
MERGE (a)-[:HAS_SUBJECT]->(s)
WITH a
UNWIND ['hu:locator:pmc12056739-findings-pooled-or'] AS lu
MATCH (l:SourceLocator {uid: lu})
MERGE (a)-[:SUPPORTED_BY]->(l);

// status: run
MATCH (s {uid: 'hu:publication:pmid-39993397'})
MERGE (a:Assertion {uid: 'hu:assertion:w10-pmid39993397-subgroup-age-1-15-or'})
  ON CREATE SET a.id = 'w10-pmid39993397-subgroup-age-1-15-or', a.predicate = 'REPORTS_POOLED_ESTIMATE', a.status = 'ACCEPTED', a.polarity = 'POSITIVE', a.validFromBasis = 'UNKNOWN', a.validToBasis = 'UNKNOWN', a.privacyClass = 'PUBLIC', a.contentHash = 'sha256:2d89b767509833970c90a877b77d4679ec61431d3382f3688420db29278e1568', a.valueNumber = 0.74, a.unitCode = '1', a.recordedAt = datetime('2026-10-04T02:00:00Z'), a.createdAt = datetime('2026-10-04T02:00:00Z')
MERGE (a)-[:HAS_SUBJECT]->(s)
WITH a
UNWIND ['hu:locator:pmc12056739-results-subgroup-age-1-15'] AS lu
MATCH (l:SourceLocator {uid: lu})
MERGE (a)-[:SUPPORTED_BY]->(l);

// status: run
UNWIND ['hu:assertion:w10-pmid28202713-pooled-or-any-ari', 'hu:assertion:w10-pmid33798465-pooled-or-any-ari', 'hu:assertion:w10-pmid39993397-pooled-or-any-ari', 'hu:assertion:w10-pmid39993397-subgroup-age-1-15-or'] AS au
MATCH (a:Assertion {uid: au})
MERGE (j:Adjudication {uid: 'hu:adjudication:w10-fixture-05-capture-policy'})
  ON CREATE SET j.id = 'w10-fixture-05-capture-policy', j.assessmentType = 'Adjudication', j.adjudicationKind = 'CAPTURE_FIDELITY', j.verdict = 'SUPPORTED',
    j.reviewerType = 'POLICY', j.methodVersion = 'w10-fixture-capture-policy-1', j.status = 'ACCEPTED', j.privacyClass = 'INTERNAL',
    j.rationale = 'Fixture capture policy: recorded propositions match the cited quotes; says nothing about truth.',
    j.reviewedAt = datetime('2026-10-04T02:13:00Z'), j.recordedAt = datetime('2026-10-04T02:13:00Z'), j.createdAt = datetime('2026-10-04T02:13:00Z')
SET j:EvidenceAssessment
MERGE (j)-[:EVALUATES]->(a);

// status: run
MATCH (c:Claim {uid: 'hu:claim:w10-vitamin-d-prevents-acute-respiratory-infection'})
MERGE (syn:EvidenceSynthesis {uid: 'hu:synthesis:w10-vitamin-d-ari-prevention-v1'})
  ON CREATE SET syn.id = 'w10-vitamin-d-ari-prevention-v1', syn.assessmentType = 'EvidenceSynthesis', syn.methodVersion = 'synthesis-v0.1', syn.status = 'ACCEPTED', syn.privacyClass = 'PUBLIC', syn.claimText = 'Vitamin D supplementation reduces the risk of acute respiratory infection', syn.verdict = 'SUPPORTED', syn.rationale = '2017 IPD meta-analysis of 25 RCTs: adjusted OR 0.88 (0.81-0.96); high-quality evidence per the authors.', syn.recordedAt = datetime('2026-10-04T02:10:00Z'), syn.createdAt = datetime('2026-10-04T02:10:00Z'), syn.evidenceCutoff = date('2017-02-15')
SET syn:EvidenceAssessment
MERGE (syn)-[:ASSESSES_CLAIM]->(c);

// status: run
MATCH (c:Claim {uid: 'hu:claim:w10-vitamin-d-prevents-acute-respiratory-infection'})
MERGE (syn:EvidenceSynthesis {uid: 'hu:synthesis:w10-vitamin-d-ari-prevention-v2'})
  ON CREATE SET syn.id = 'w10-vitamin-d-ari-prevention-v2', syn.assessmentType = 'EvidenceSynthesis', syn.methodVersion = 'synthesis-v0.1', syn.status = 'ACCEPTED', syn.privacyClass = 'PUBLIC', syn.claimText = 'Vitamin D supplementation reduces the risk of acute respiratory infection', syn.verdict = 'SUPPORTED', syn.rationale = '2021 update, 46 RCTs: OR 0.92 (0.86-0.99), p=0.018; still protective, smaller effect, more heterogeneity.', syn.recordedAt = datetime('2026-10-04T02:11:00Z'), syn.createdAt = datetime('2026-10-04T02:11:00Z'), syn.evidenceCutoff = date('2021-03-30')
SET syn:EvidenceAssessment
MERGE (syn)-[:ASSESSES_CLAIM]->(c);

// status: run
MATCH (c:Claim {uid: 'hu:claim:w10-vitamin-d-prevents-acute-respiratory-infection'})
MERGE (syn:EvidenceSynthesis {uid: 'hu:synthesis:w10-vitamin-d-ari-prevention-v3'})
  ON CREATE SET syn.id = 'w10-vitamin-d-ari-prevention-v3', syn.assessmentType = 'EvidenceSynthesis', syn.methodVersion = 'synthesis-v0.1', syn.status = 'ACCEPTED', syn.privacyClass = 'PUBLIC', syn.claimText = 'Vitamin D supplementation reduces the risk of acute respiratory infection', syn.verdict = 'INSUFFICIENT', syn.rationale = '2025 update, 40 studies in the primary comparison: OR 0.94 (0.88-1.00), p=0.057; the CI now includes 1. Age 1-15 subgroup is hypothesis-generating only.', syn.recordedAt = datetime('2026-10-04T02:12:00Z'), syn.createdAt = datetime('2026-10-04T02:12:00Z'), syn.evidenceCutoff = date('2025-02-21')
SET syn:EvidenceAssessment
MERGE (syn)-[:ASSESSES_CLAIM]->(c);

// status: run
UNWIND [
  {syn: 'hu:synthesis:w10-vitamin-d-ari-prevention-v1', a: 'hu:assertion:w10-pmid28202713-pooled-or-any-ari', role: 'CONFIRMATORY'},
  {syn: 'hu:synthesis:w10-vitamin-d-ari-prevention-v2', a: 'hu:assertion:w10-pmid33798465-pooled-or-any-ari', role: 'CONFIRMATORY'},
  {syn: 'hu:synthesis:w10-vitamin-d-ari-prevention-v3', a: 'hu:assertion:w10-pmid39993397-pooled-or-any-ari', role: 'CONFIRMATORY'},
  {syn: 'hu:synthesis:w10-vitamin-d-ari-prevention-v3', a: 'hu:assertion:w10-pmid39993397-subgroup-age-1-15-or', role: 'HYPOTHESIS_GENERATING'}
] AS x
MATCH (syn:EvidenceSynthesis {uid: x.syn}), (a:Assertion {uid: x.a})
MERGE (syn)-[i:INCLUDES_RESULT]->(a)
  ON CREATE SET i.inputRole = x.role;

// status: run
UNWIND [
  {newer: 'hu:synthesis:w10-vitamin-d-ari-prevention-v2', older: 'hu:synthesis:w10-vitamin-d-ari-prevention-v1', pub: 'hu:publication:pmid-33798465', crit: 'SYSTEMATIC_REVIEW_UPDATE', eff: 'WEAKENED', at: '2021-03-30'},
  {newer: 'hu:synthesis:w10-vitamin-d-ari-prevention-v3', older: 'hu:synthesis:w10-vitamin-d-ari-prevention-v2', pub: 'hu:publication:pmid-39993397', crit: 'POOLED_ESTIMATE_CI_INCLUDES_NULL', eff: 'WEAKENED', at: '2025-02-21'}
] AS x
MATCH (n:EvidenceSynthesis {uid: x.newer}), (o:EvidenceSynthesis {uid: x.older}), (p:Publication {uid: x.pub})
MERGE (n)-[s:SUPERSEDES]->(o)
  ON CREATE SET s.supersessionKind = 'RE_REVIEW', s.recordedAt = n.recordedAt
SET o.recordedTo = coalesce(o.recordedTo, n.recordedAt), o.status = 'SUPERSEDED'
MERGE (n)-[t:TRIGGERED_BY]->(p)
  ON CREATE SET t.criterionCode = x.crit, t.effectOnVerdict = x.eff, t.evidencePublishedAt = date(x.at);

// status: run
UNWIND [
  {syn: 'hu:synthesis:w10-vitamin-d-ari-prevention-v1', locs: ['hu:locator:pmid28202713-abstract-pooled-or']},
  {syn: 'hu:synthesis:w10-vitamin-d-ari-prevention-v2', locs: ['hu:locator:pmid33798465-abstract-pooled-or']},
  {syn: 'hu:synthesis:w10-vitamin-d-ari-prevention-v3', locs: ['hu:locator:pmc12056739-findings-pooled-or', 'hu:locator:pmc12056739-interpretation']}
] AS x
MATCH (syn:EvidenceSynthesis {uid: x.syn})
UNWIND x.locs AS lu
MATCH (l:SourceLocator {uid: lu})
MERGE (syn)-[:SUPPORTED_BY]->(l);

// status: run
MATCH (syn:EvidenceSynthesis {uid: 'hu:synthesis:w10-vitamin-d-ari-prevention-v1'}), (l:SourceLocator {uid: 'hu:locator:pmid28202713-abstract-quality'})
MERGE (es:EvidenceStrengthAssessment {uid: 'hu:assessment:w10-strength-vitamin-d-ari-v1-grade-as-reported'})
  ON CREATE SET es.id = 'w10-strength-vitamin-d-ari-v1-grade-as-reported', es.assessmentType = 'EvidenceStrengthAssessment', es.methodVersion = 'grade-as-reported-by-review-v0', es.status = 'ACCEPTED', es.privacyClass = 'PUBLIC', es.scheme = 'GRADE', es.level = 'high', es.criteria = [], es.rationale = 'Level copied from the review authors\' own GRADE statement (not recomputed by BellLabs); method names the copy rule.', es.recordedAt = datetime('2026-10-04T02:10:00Z'), es.createdAt = datetime('2026-10-04T02:10:00Z')
SET es:EvidenceAssessment
MERGE (es)-[:ASSESSES_STRENGTH_OF]->(syn)
MERGE (es)-[:SUPPORTED_BY]->(l);

// status: run
MATCH (syn:EvidenceSynthesis {uid: 'hu:synthesis:w10-vitamin-d-ari-prevention-v3'}), (l:SourceLocator {uid: 'hu:locator:pmc12056739-results-grade-moderate'})
MERGE (es:EvidenceStrengthAssessment {uid: 'hu:assessment:w10-strength-vitamin-d-ari-v3-grade-as-reported'})
  ON CREATE SET es.id = 'w10-strength-vitamin-d-ari-v3-grade-as-reported', es.assessmentType = 'EvidenceStrengthAssessment', es.methodVersion = 'grade-as-reported-by-review-v0', es.status = 'ACCEPTED', es.privacyClass = 'PUBLIC', es.scheme = 'GRADE', es.level = 'moderate', es.criteria = ['publication bias suspected: funnel plot left-sided asymmetry (Egger p=0.0020)'], es.rationale = 'Level copied from the review authors\' own GRADE statement (not recomputed by BellLabs); method names the copy rule.', es.recordedAt = datetime('2026-10-04T02:12:00Z'), es.createdAt = datetime('2026-10-04T02:12:00Z')
SET es:EvidenceAssessment
MERGE (es)-[:ASSESSES_STRENGTH_OF]->(syn)
MERGE (es)-[:SUPPORTED_BY]->(l);

