// =====================================================================================================================
// W10 fixture 04: null primary with a favorable secondary and a favorable post hoc subgroup (INV-206) and the
// clinically-meaningful minimal pair (CQ-ST-10). Standalone; MERGEs the ATLAS shapes with the same uids as
// W09 fixtures/02-null-primary-favorable-secondary.cypher (quotes and hashes copied from that file: INHERITED, retrieved by
// W09 2026-10-04). The subgroup result is SYNTHETIC (W09's device; no subgroup was retrieved).
// Expected: V-215, V-216 zero rows; W10-V09, W10-V10, W10-V11, W10-V11b zero rows. Generated by gen_w10.py.
// =====================================================================================================================

// status: run
MERGE (src:Source {uid: 'hu:source:pmc9133463'})
  ON CREATE SET src.id = 'pmc9133463', src.entityType = 'Source', src.canonicalUri = 'https://pmc.ncbi.nlm.nih.gov/articles/PMC9133463/', src.sourceKind = 'PEER_REVIEWED_PUBLICATION',
    src.createdAt = datetime('2026-10-04T02:00:00Z'), src.privacyClass = 'PUBLIC'
SET src:Entity
MERGE (snap:SourceSnapshot {uid: 'hu:snapshot:pmc9133463-2026-10-04'})
  ON CREATE SET snap.id = 'pmc9133463-2026-10-04', snap.artifactType = 'SourceSnapshot', snap.canonicalUri = 'https://pmc.ncbi.nlm.nih.gov/articles/PMC9133463/',
    snap.retrievedAt = datetime('2026-10-04T00:58:00Z'), snap.observedAt = datetime('2026-10-04T00:58:00Z'), snap.contentHash = 'synthetic:hu:snapshot:pmc9133463-2026-10-04',
    snap.contentHashBasis = 'SYNTHETIC_FIXTURE', snap.captureCompleteness = 'PARTIAL_EXCERPT', snap.createdAt = datetime('2026-10-04T02:00:00Z'), snap.privacyClass = 'PUBLIC'
SET snap:InformationArtifact
MERGE (src)-[:HAS_SNAPSHOT]->(snap)
WITH snap
UNWIND [
  {uid: 'hu:locator:pmc9133463-abstract-primary-null', section: 'Summary', exact: 'do not notice a significant improvement on peak power output (primary endpoint)', h: 'sha256:15185dddbee081a05c11051274191ba86fd35b8ad6a4245c45b688a546221e61'},
  {uid: 'hu:locator:pmc9133463-results-hamstring', section: 'Results: muscle strength', exact: 'Average peak torque in the hamstring skeletal muscle was significantly increased in both UA 500 mg (+12%, p = 0.027 compared with placebo)', h: 'sha256:2b7331f868baaaf7a53b8191dd4fbca6bd358e00c5d7e52edc00cdded41cb536'},
  {uid: 'hu:locator:pmc9133463-abstract-clinically-meaningful', section: 'Summary', exact: 'We observe clinically meaningful improvements with Urolithin A on aerobic endurance (peak oxygen oxygen consumption [VO2]) and physical performance (6 min walk test)', h: 'sha256:35b5cbe6f58f8b50224f79b5a9fd0bc3cbb5c38fb1c690149adb137f98de8e93'}
] AS r
MERGE (l:SourceLocator {uid: r.uid})
  ON CREATE SET l.id = split(r.uid, ':')[2], l.artifactType = 'SourceLocator', l.uri = 'https://pmc.ncbi.nlm.nih.gov/articles/PMC9133463/', l.selectorKind = 'TEXT_QUOTE',
    l.section = r.section, l.exact = r.exact, l.quoteHash = r.h, l.normalizationVersion = 'NFC-WS1', l.createdAt = datetime('2026-10-04T02:00:00Z'), l.privacyClass = 'PUBLIC'
SET l:InformationArtifact
MERGE (snap)-[:HAS_LOCATOR]->(l);

// status: run
MERGE (st:Study {uid: 'hu:study:nct03464500-atlas'})
  ON CREATE SET st.id = 'nct03464500-atlas', st.entityType = 'Study', st.name = 'ATLAS: urolithin A (Mitopure) in middle-aged overweight adults',
    st.studyKind = 'INTERVENTIONAL_RANDOMIZED', st.createdAt = datetime('2026-10-04T02:00:00Z'), st.privacyClass = 'PUBLIC'
SET st:Entity
WITH st
UNWIND [
  {uid: 'hu:outcome:atlas-power-output-d120', name: 'Change in power output on cycle ergometer, baseline to day 120', mk: 'PERFORMANCE_OUTCOME'},
  {uid: 'hu:outcome:atlas-isokinetic-strength-d120', name: 'Change in isokinetic lower body muscle strength, baseline to day 120', mk: 'PERFORMANCE_OUTCOME'},
  {uid: 'hu:outcome:atlas-6mwt-d120', name: 'Change in 6-minute walk distance, baseline to day 120', mk: 'PERFORMANCE_OUTCOME'}
] AS r
MERGE (od:OutcomeDefinition {uid: r.uid})
  ON CREATE SET od.id = split(r.uid, ':')[2], od.stateType = 'OutcomeDefinition', od.payloadHash = 'sha256:synthetic-' + split(r.uid, ':')[2],
    od.name = r.name, od.measureKind = r.mk, od.timepoint = '4 months', od.createdAt = datetime('2026-10-04T02:00:00Z'), od.privacyClass = 'PUBLIC'
SET od:VersionedState
MERGE (st)-[:DEFINES_OUTCOME]->(od);

// status: run
UNWIND [
  {uid: 'hu:study-result:atlas-power-ua-vs-placebo-d120', od: 'hu:outcome:atlas-power-output-d120', ak: 'PRIMARY_PRESPECIFIED', ck: 'BETWEEN_ARM', sc: 'NOT_SIGNIFICANT', loc: 'hu:locator:pmc9133463-abstract-primary-null', name: null},
  {uid: 'hu:study-result:atlas-hamstring-ua500-vs-placebo', od: 'hu:outcome:atlas-isokinetic-strength-d120', ak: 'SECONDARY_PRESPECIFIED', ck: 'BETWEEN_ARM', sc: 'SIGNIFICANT_FAVORABLE', loc: 'hu:locator:pmc9133463-results-hamstring', name: null},
  {uid: 'hu:study-result:atlas-hamstring-ua500-within-arm', od: 'hu:outcome:atlas-isokinetic-strength-d120', ak: 'SECONDARY_PRESPECIFIED', ck: 'WITHIN_ARM_CHANGE', sc: 'NOT_REPORTED', loc: 'hu:locator:pmc9133463-results-hamstring', name: null},
  {uid: 'hu:study-result:atlas-6mwt-ua-vs-placebo', od: 'hu:outcome:atlas-6mwt-d120', ak: 'SECONDARY_PRESPECIFIED', ck: 'BETWEEN_ARM', sc: 'NOT_REPORTED', loc: 'hu:locator:pmc9133463-abstract-clinically-meaningful', name: null},
  {uid: 'hu:study-result:atlas-synthetic-subgroup-low-vo2max', od: 'hu:outcome:atlas-power-output-d120', ak: 'SUBGROUP_POST_HOC', ck: 'BETWEEN_ARM', sc: 'SIGNIFICANT_FAVORABLE', loc: null, name: 'SYNTHETIC subgroup (not from any source; W09 fixture 02 device)'}
] AS r
MATCH (od:OutcomeDefinition {uid: r.od})
MERGE (res:StudyResult {uid: r.uid})
  ON CREATE SET res.id = split(r.uid, ':')[2], res.artifactType = 'StudyResult', res.name = r.name, res.analysisKind = r.ak, res.comparisonKind = r.ck,
    res.statisticalConclusion = r.sc, res.createdAt = datetime('2026-10-04T02:00:00Z'), res.privacyClass = 'PUBLIC'
SET res:InformationArtifact
MERGE (res)-[:RESULT_FOR]->(od)
WITH res, r
MATCH (l:SourceLocator {uid: coalesce(r.loc, 'none')})
MERGE (res)-[:SUPPORTED_BY]->(l);

// status: run
MATCH (s {uid: 'hu:study-result:atlas-6mwt-ua-vs-placebo'})
MERGE (a:Assertion {uid: 'hu:assertion:atlas-6mwt-clinically-meaningful-authors'})
  ON CREATE SET a.id = 'atlas-6mwt-clinically-meaningful-authors', a.predicate = 'RESULT_CLINICALLY_MEANINGFUL', a.status = 'ACCEPTED', a.polarity = 'POSITIVE', a.validFromBasis = 'UNKNOWN', a.validToBasis = 'UNKNOWN', a.privacyClass = 'PUBLIC', a.contentHash = 'sha256:ef1c5b193d08bb5653934f492ca306d743e0b7caffad8e9da109860935f34520', a.valueBoolean = true, a.assertionBasis = 'STUDY_RESULT', a.speechAct = 'STATES', a.recordedAt = datetime('2026-10-04T02:00:00Z'), a.createdAt = datetime('2026-10-04T02:00:00Z')
MERGE (a)-[:HAS_SUBJECT]->(s)
WITH a
UNWIND ['hu:locator:pmc9133463-abstract-clinically-meaningful'] AS lu
MATCH (l:SourceLocator {uid: lu})
MERGE (a)-[:SUPPORTED_BY]->(l);

// status: run
UNWIND ['hu:assertion:atlas-6mwt-clinically-meaningful-authors'] AS au
MATCH (a:Assertion {uid: au})
MERGE (j:Adjudication {uid: 'hu:adjudication:w10-fixture-04-capture-policy'})
  ON CREATE SET j.id = 'w10-fixture-04-capture-policy', j.assessmentType = 'Adjudication', j.adjudicationKind = 'CAPTURE_FIDELITY', j.verdict = 'SUPPORTED',
    j.reviewerType = 'POLICY', j.methodVersion = 'w10-fixture-capture-policy-1', j.status = 'ACCEPTED', j.privacyClass = 'INTERNAL',
    j.rationale = 'Fixture capture policy: recorded propositions match the cited quotes; says nothing about truth.',
    j.reviewedAt = datetime('2026-10-04T02:00:00Z'), j.recordedAt = datetime('2026-10-04T02:00:00Z'), j.createdAt = datetime('2026-10-04T02:00:00Z')
SET j:EvidenceAssessment
MERGE (j)-[:EVALUATES]->(a);

// status: run
MATCH (res:StudyResult {uid: 'hu:study-result:atlas-power-ua-vs-placebo-d120'})
MERGE (ri:ResultInterpretation {uid: 'hu:assessment:w10-ri-atlas-power-primary'})
  ON CREATE SET ri.id = 'w10-ri-atlas-power-primary', ri.assessmentType = 'ResultInterpretation', ri.methodVersion = 'result-interpretation-v0.1', ri.status = 'PROPOSED', ri.privacyClass = 'PUBLIC', ri.interpretation = 'INCONCLUSIVE', ri.meaningfulnessVerdict = 'UNDETERMINED', ri.thresholdValue = null, ri.thresholdUnit = null, ri.rationale = 'Primary peak power output not significant; no equivalence margin or MCID source in the packet, so not EVIDENCE_OF_NO_MEANINGFUL_EFFECT.', ri.recordedAt = datetime('2026-10-04T02:00:00Z'), ri.createdAt = datetime('2026-10-04T02:00:00Z')
SET ri:EvidenceAssessment
MERGE (ri)-[:INTERPRETS_RESULT_OF]->(res);

// status: run
MATCH (res:StudyResult {uid: 'hu:study-result:atlas-6mwt-ua-vs-placebo'})
MERGE (ri:ResultInterpretation {uid: 'hu:assessment:w10-ri-atlas-6mwt'})
  ON CREATE SET ri.id = 'w10-ri-atlas-6mwt', ri.assessmentType = 'ResultInterpretation', ri.methodVersion = 'result-interpretation-v0.1', ri.status = 'PROPOSED', ri.privacyClass = 'PUBLIC', ri.interpretation = 'INCONCLUSIVE', ri.meaningfulnessVerdict = 'UNDETERMINED', ri.thresholdValue = null, ri.thresholdUnit = null, ri.rationale = 'Authors call the 6MWT change clinically meaningful (Assertion); the quoted span gives no between-arm test and no MCID source is linked, so BellLabs meaningfulness is UNDETERMINED.', ri.recordedAt = datetime('2026-10-04T02:00:00Z'), ri.createdAt = datetime('2026-10-04T02:00:00Z')
SET ri:EvidenceAssessment
MERGE (ri)-[:INTERPRETS_RESULT_OF]->(res);

// status: run
MERGE (c:Claim {uid: 'hu:claim:w10-ua-improves-muscle-function-middle-aged'})
  ON CREATE SET c.id = 'w10-ua-improves-muscle-function-middle-aged', c.entityType = 'Claim', c.claimText = 'Urolithin A 500-1000 mg/day for 4 months improves muscle function in middle-aged adults',
    c.createdAt = datetime('2026-10-04T02:00:00Z'), c.privacyClass = 'PUBLIC'
SET c:Entity;

// status: run
MATCH (c:Claim {uid: 'hu:claim:w10-ua-improves-muscle-function-middle-aged'})
MERGE (syn:EvidenceSynthesis {uid: 'hu:synthesis:w10-ua-muscle-function-middle-aged-v1'})
  ON CREATE SET syn.id = 'w10-ua-muscle-function-middle-aged-v1', syn.assessmentType = 'EvidenceSynthesis', syn.methodVersion = 'synthesis-v0.1', syn.status = 'PROPOSED', syn.privacyClass = 'PUBLIC', syn.claimText = 'Urolithin A 500-1000 mg/day for 4 months improves muscle function in middle-aged adults', syn.verdict = 'INSUFFICIENT', syn.rationale = 'Null primary (peak power output) is the confirmatory input; a favorable secondary between-arm strength result is supportive only; a post hoc subgroup is hypothesis-generating only (INV-206). The within-arm +12% is not an input.', syn.recordedAt = datetime('2026-10-04T02:00:00Z'), syn.createdAt = datetime('2026-10-04T02:00:00Z'), syn.evidenceCutoff = date('2022-05-31')
SET syn:EvidenceAssessment
MERGE (syn)-[:ASSESSES_CLAIM]->(c);

// status: run
MATCH (syn:EvidenceSynthesis {uid: 'hu:synthesis:w10-ua-muscle-function-middle-aged-v1'})
UNWIND [
  {r: 'hu:study-result:atlas-power-ua-vs-placebo-d120', role: 'CONFIRMATORY'},
  {r: 'hu:study-result:atlas-hamstring-ua500-vs-placebo', role: 'SUPPORTIVE'},
  {r: 'hu:study-result:atlas-synthetic-subgroup-low-vo2max', role: 'HYPOTHESIS_GENERATING'}
] AS x
MATCH (res:StudyResult {uid: x.r})
MERGE (syn)-[i:INCLUDES_RESULT]->(res)
  ON CREATE SET i.inputRole = x.role;

