// =====================================================================================================================
// W10 fixture 01: 13-dimension EvidenceApplicability re-assessment (NRPT 1X arm of NCT02678611 -> current US Basis
// formulation) built on the shapes of docs/schema/examples/study-vs-product-mismatch.cypher (LOAD THAT FILE FIRST).
// New, retrieved 2026-10-04: Basis Supplement Facts page (Tavily extract) and PMC5701244 Methods (PubMed connector).
// What it shows: one evidence target, one use target, one FOR_USE_CONTEXT profile, 13 dimension nodes (11 required + 2
// explanation-only) with NOT_ASSESSED explicit; SCHEDULE resolved by the label directions; DOSE ratio blocked by mass
// basis (UNSPECIFIED vs SALT_FORM) with ratio null and verdict PARTIAL; MATERIAL_IDENTITY UNKNOWN citing the two competing
// ResolutionHypothesis records; re-assessment SUPERSEDES {RE_REVIEW} the inherited v1 (recordedTo written once).
// Expected: V-201..V-209 zero rows; QS-3a weakest = [MATERIAL_IDENTITY (UNKNOWN), STUDY_DESIGN_AND_QUALITY (NOT_ASSESSED)].
// Generated by gen_w10.py; do not edit by hand.
// =====================================================================================================================

// status: run
MERGE (src:Source {uid: 'hu:source:elysium-basis-supplement-facts'})
  ON CREATE SET src.id = 'elysium-basis-supplement-facts', src.entityType = 'Source', src.canonicalUri = 'https://www.elysiumhealth.com/pages/basis-supplement-facts', src.sourceKind = 'MANUFACTURER_LABEL_PAGE', src.title = null, src.createdAt = datetime('2026-10-04T02:00:00Z'), src.privacyClass = 'PUBLIC'
SET src:Entity
MERGE (snap:SourceSnapshot {uid: 'hu:snapshot:elysium-basis-supplement-facts-2026-10-04'})
  ON CREATE SET snap.id = 'elysium-basis-supplement-facts-2026-10-04', snap.artifactType = 'SourceSnapshot', snap.canonicalUri = 'https://www.elysiumhealth.com/pages/basis-supplement-facts',
    snap.retrievedAt = datetime('2026-10-04T01:20:00Z'), snap.observedAt = datetime('2026-10-04T01:20:00Z'), snap.publishedAt = null,
    snap.contentHash = 'synthetic:hu:snapshot:elysium-basis-supplement-facts-2026-10-04', snap.contentHashBasis = 'SYNTHETIC_FIXTURE', snap.captureCompleteness = 'PARTIAL_EXCERPT',
    snap.createdAt = datetime('2026-10-04T02:00:00Z'), snap.privacyClass = 'PUBLIC'
SET snap:InformationArtifact
MERGE (src)-[:HAS_SNAPSHOT]->(snap)
MERGE (l0:SourceLocator {uid: 'hu:locator:elysium-basis-label-directions-2026-10-04'})
  ON CREATE SET l0.id = 'elysium-basis-label-directions-2026-10-04', l0.artifactType = 'SourceLocator', l0.uri = 'https://www.elysiumhealth.com/pages/basis-supplement-facts', l0.selectorKind = 'TEXT_QUOTE', l0.section = 'Supplement Facts: Suggested Use', l0.exact = 'Take two (2) capsules every morning with or without food.', l0.quoteHash = 'sha256:bb39bdbafea05b4cd7e091b4dbab55693dd89748f2c24bfac9ab3ef402a939e0', l0.normalizationVersion = 'NFC-WS1', l0.createdAt = datetime('2026-10-04T02:00:00Z'), l0.privacyClass = 'PUBLIC'
SET l0:InformationArtifact
MERGE (snap)-[:HAS_LOCATOR]->(l0)
MERGE (l1:SourceLocator {uid: 'hu:locator:elysium-basis-label-amount-2026-10-04'})
  ON CREATE SET l1.id = 'elysium-basis-label-amount-2026-10-04', l1.artifactType = 'SourceLocator', l1.uri = 'https://www.elysiumhealth.com/pages/basis-supplement-facts', l1.selectorKind = 'TEXT_QUOTE', l1.section = 'Supplement Facts', l1.exact = 'Serving Size: 2 Vegetarian Capsules, Servings: 30, Amount Per Serving: Elysium NR (Nicotinamide Riboside Chloride) 250 mg', l1.quoteHash = 'sha256:6b69ecda14ebbee7080f7eec59b961a2c7a48fa9b5f228e9661a7188c5242c2e', l1.normalizationVersion = 'NFC-WS1', l1.createdAt = datetime('2026-10-04T02:00:00Z'), l1.privacyClass = 'PUBLIC'
SET l1:InformationArtifact
MERGE (snap)-[:HAS_LOCATOR]->(l1)
MERGE (l2:SourceLocator {uid: 'hu:locator:elysium-basis-label-other-ingredients-2026-10-04'})
  ON CREATE SET l2.id = 'elysium-basis-label-other-ingredients-2026-10-04', l2.artifactType = 'SourceLocator', l2.uri = 'https://www.elysiumhealth.com/pages/basis-supplement-facts', l2.selectorKind = 'TEXT_QUOTE', l2.section = 'Supplement Facts: Other Ingredients', l2.exact = 'Other Ingredients | Microcrystalline Cellulose, Hypromellose, Vegetable Magnesium Stearate and Silica', l2.quoteHash = 'sha256:976e087c374208bc3a6c4f8545a88184ebb85a4e78f24b58214940e532b5fd97', l2.normalizationVersion = 'NFC-WS1', l2.createdAt = datetime('2026-10-04T02:00:00Z'), l2.privacyClass = 'PUBLIC'
SET l2:InformationArtifact
MERGE (snap)-[:HAS_LOCATOR]->(l2);

// status: run
MERGE (src:Source {uid: 'hu:source:doi-10.1038-s41514-017-0016-9'})
  ON CREATE SET src.id = 'doi-10.1038-s41514-017-0016-9', src.entityType = 'Source', src.canonicalUri = 'https://doi.org/10.1038/s41514-017-0016-9', src.sourceKind = 'PEER_REVIEWED_PUBLICATION', src.title = null, src.createdAt = datetime('2026-10-04T02:00:00Z'), src.privacyClass = 'PUBLIC'
SET src:Entity
MERGE (snap:SourceSnapshot {uid: 'hu:snapshot:pmc5701244-2026-10-04'})
  ON CREATE SET snap.id = 'pmc5701244-2026-10-04', snap.artifactType = 'SourceSnapshot', snap.canonicalUri = 'https://doi.org/10.1038/s41514-017-0016-9',
    snap.retrievedAt = datetime('2026-10-04T01:20:00Z'), snap.observedAt = datetime('2026-10-04T01:20:00Z'), snap.publishedAt = datetime('2017-11-24T00:00:00Z'),
    snap.contentHash = 'synthetic:hu:snapshot:pmc5701244-2026-10-04', snap.contentHashBasis = 'SYNTHETIC_FIXTURE', snap.captureCompleteness = 'PARTIAL_EXCERPT',
    snap.createdAt = datetime('2026-10-04T02:00:00Z'), snap.privacyClass = 'PUBLIC'
SET snap:InformationArtifact
MERGE (src)-[:HAS_SNAPSHOT]->(snap)
MERGE (l0:SourceLocator {uid: 'hu:locator:pmc5701244-methods-intervention-capsule-2026-10-04'})
  ON CREATE SET l0.id = 'pmc5701244-methods-intervention-capsule-2026-10-04', l0.artifactType = 'SourceLocator', l0.uri = 'https://doi.org/10.1038/s41514-017-0016-9', l0.selectorKind = 'TEXT_QUOTE', l0.section = 'Methods: Intervention', l0.exact = 'The investigational product NRPT contained 125 mg of NR and 25 mg of pterostilbene per capsule.', l0.quoteHash = 'sha256:91796443c7af20450624c3bd9530978681d9812b06cf0e1ed1cf4997f41bded2', l0.normalizationVersion = 'NFC-WS1', l0.createdAt = datetime('2026-10-04T02:00:00Z'), l0.privacyClass = 'PUBLIC'
SET l0:InformationArtifact
MERGE (snap)-[:HAS_LOCATOR]->(l0)
MERGE (l1:SourceLocator {uid: 'hu:locator:pmc5701244-methods-four-capsules-2026-10-04'})
  ON CREATE SET l1.id = 'pmc5701244-methods-four-capsules-2026-10-04', l1.artifactType = 'SourceLocator', l1.uri = 'https://doi.org/10.1038/s41514-017-0016-9', l1.selectorKind = 'TEXT_QUOTE', l1.section = 'Methods: Intervention', l1.exact = 'All subjects took four capsules daily.', l1.quoteHash = 'sha256:90ace62d8701dbf2b074816d01308fca446fd051d598aaad119093547c4c0b2a', l1.normalizationVersion = 'NFC-WS1', l1.createdAt = datetime('2026-10-04T02:00:00Z'), l1.privacyClass = 'PUBLIC'
SET l1:InformationArtifact
MERGE (snap)-[:HAS_LOCATOR]->(l1)
MERGE (l2:SourceLocator {uid: 'hu:locator:pmc5701244-methods-primary-objective-2026-10-04'})
  ON CREATE SET l2.id = 'pmc5701244-methods-primary-objective-2026-10-04', l2.artifactType = 'SourceLocator', l2.uri = 'https://doi.org/10.1038/s41514-017-0016-9', l2.selectorKind = 'TEXT_QUOTE', l2.section = 'Methods: Clinical trial', l2.exact = 'The primary objective of this study was to evaluate the safety and tolerability of two doses of NRPT in elderly participants during and after eight weeks of treatment.', l2.quoteHash = 'sha256:311279459bb91a3cb90da7648486435cf6e6e906a10aa33b7ad8c918d8a078c0', l2.normalizationVersion = 'NFC-WS1', l2.createdAt = datetime('2026-10-04T02:00:00Z'), l2.privacyClass = 'PUBLIC'
SET l2:InformationArtifact
MERGE (snap)-[:HAS_LOCATOR]->(l2);

// status: run
MERGE (p:UseContextProfile {uid: 'hu:use-profile:basis-us-label-directions-one-serving-daily'})
  ON CREATE SET p.id = 'basis-us-label-directions-one-serving-daily', p.entityType = 'UseContextProfile', p.name = 'Basis US label directions: one serving (2 capsules) every morning',
    p.populationDescriptor = 'healthy adults (label: intended for healthy adults; not pregnant or nursing)',
    p.doseDescriptor = 'label directions: take two capsules (one serving) every morning with or without food',
    p.durationDescriptor = 'open-ended daily use (no duration on label)', p.servingsPerDay = 1.0, p.intendedDurationIso = null,
    p.createdAt = datetime('2026-10-04T02:00:00Z'), p.privacyClass = 'PUBLIC'
SET p:Entity;

// status: run
MERGE (act:Activity {uid: 'hu:activity:w10-applicability-review-2026-10-04'})
  ON CREATE SET act.id = 'w10-applicability-review-2026-10-04', act.occurrenceType = 'Activity', act.activityKind = 'ADJUDICATION', act.methodVersion = 'applicability-v0.2-candidate',
    act.startedAt = datetime('2026-10-04T01:50:00Z'), act.endedAt = datetime('2026-10-04T02:00:00Z'), act.createdAt = datetime('2026-10-04T02:00:00Z'), act.privacyClass = 'INTERNAL'
SET act:Occurrence;

// status: run
MATCH (et {uid: 'hu:study-intervention:nct02678611-nrpt-1x'})
MATCH (ut {uid: 'hu:formulation:basis-us-current-2026-07-10'})
MERGE (ea:EvidenceApplicability {uid: 'hu:applicability:w10-nct02678611-1x-to-basis-current-v2'})
  ON CREATE SET ea.id = 'w10-nct02678611-1x-to-basis-current-v2', ea.assessmentType = 'EvidenceApplicability', ea.methodVersion = 'applicability-v0.2-candidate', ea.status = 'PROPOSED', ea.privacyClass = 'PUBLIC', ea.summary = 'Re-assessment after reading the current label directions: schedule now matches (one serving per day); dose stays PARTIAL because the trial does not state salt vs cation mass; trial NR material still unresolved (weakest); design and quality not assessed.', ea.overallScore = null, ea.recordedAt = datetime('2026-10-04T02:00:00Z'), ea.createdAt = datetime('2026-10-04T02:00:00Z')
SET ea:EvidenceAssessment
MERGE (ea)-[:HAS_EVIDENCE_TARGET]->(et)
MERGE (ea)-[:ASSESSES_APPLICABILITY_TO]->(ut);

// status: run
MATCH (ea:EvidenceApplicability {uid: 'hu:applicability:w10-nct02678611-1x-to-basis-current-v2'}), (p:UseContextProfile {uid: 'hu:use-profile:basis-us-label-directions-one-serving-daily'})
MERGE (ea)-[:FOR_USE_CONTEXT]->(p);

// status: run
MATCH (ea:EvidenceApplicability {uid: 'hu:applicability:w10-nct02678611-1x-to-basis-current-v2'})
UNWIND ['hu:study-result:nct02678611-nad-1x-d30', 'hu:publication:pmid-29184669'] AS bu
MATCH (b {uid: bu})
MERGE (ea)-[:BASED_ON_EVIDENCE]->(b);

// status: run
MATCH (newer:EvidenceApplicability {uid: 'hu:applicability:w10-nct02678611-1x-to-basis-current-v2'}), (older:EvidenceApplicability {uid: 'hu:applicability:nct02678611-1x-to-basis-current'})
MERGE (newer)-[s:SUPERSEDES]->(older)
  ON CREATE SET s.supersessionKind = 'RE_REVIEW', s.recordedAt = newer.recordedAt
SET older.recordedTo = coalesce(older.recordedTo, newer.recordedAt);

// status: run
MATCH (ea:EvidenceApplicability {uid: 'hu:applicability:w10-nct02678611-1x-to-basis-current-v2'})
UNWIND [
  {uid: 'hu:applicability-dimension:w10-nct02678611-1x-to-basis-current-v2-material-identity', id: 'w10-nct02678611-1x-to-basis-current-v2-material-identity', dimension: 'MATERIAL_IDENTITY', dimensionClass: 'CATEGORICAL', verdict: 'UNKNOWN', identityLevel: 'SAME_SUBSTANCE_MATERIAL_UNRESOLVED', evidenceCategory: null, targetCategory: null, evidenceValue: null, targetValue: null, unitCode: null, evidenceQuantityBasis: null, targetQuantityBasis: null, evidenceMassBasis: null, targetMassBasis: null, ratio: null, missingFacts: ['supplier and specification of the NR administered in NCT02678611 (Jan-Jul 2016)', 'pterostilbene material administered in NCT02678611', 'whether Elysium NR-E existed in 2016 and matches the trial NR'], rationale: 'Two competing ResolutionHypothesis records (ChromaDex NIAGEN; Elysium NR-E). The correction says only that Elysium provided the investigational product; ChromaDex says it supplied Elysium NR until mid-2016.'},
  {uid: 'hu:applicability-dimension:w10-nct02678611-1x-to-basis-current-v2-active-composition', id: 'w10-nct02678611-1x-to-basis-current-v2-active-composition', dimension: 'ACTIVE_COMPOSITION', dimensionClass: 'CATEGORICAL', verdict: 'MATCH', identityLevel: null, evidenceCategory: 'SAME_ACTIVES', targetCategory: 'SAME_ACTIVES', evidenceValue: null, targetValue: null, unitCode: null, evidenceQuantityBasis: null, targetQuantityBasis: null, evidenceMassBasis: null, targetMassBasis: null, ratio: null, missingFacts: [], rationale: 'Trial capsule: NR + pterostilbene; label: Elysium NR + PT.'},
  {uid: 'hu:applicability-dimension:w10-nct02678611-1x-to-basis-current-v2-dose', id: 'w10-nct02678611-1x-to-basis-current-v2-dose', dimension: 'DOSE', dimensionClass: 'CONTINUOUS', verdict: 'PARTIAL', identityLevel: null, evidenceCategory: null, targetCategory: null, evidenceValue: 250.0, targetValue: 250.0, unitCode: 'mg/d', evidenceQuantityBasis: 'PER_DAY', targetQuantityBasis: 'PER_DAY', evidenceMassBasis: 'UNSPECIFIED', targetMassBasis: 'SALT_FORM', ratio: null, missingFacts: ['mass basis of "125 mg of NR" per capsule in PMID 29184669 Methods (NR chloride salt or NR cation not stated)'], rationale: 'Quantity bases now match (label 250 mg per serving x 1 serving/day from the use profile = 250 mg/d). Mass bases do not: the paper says \'125 mg of NR\' per capsule without naming the salt; the label declares nicotinamide riboside chloride. Ratio withheld (INV-203); verdict at most PARTIAL.'},
  {uid: 'hu:applicability-dimension:w10-nct02678611-1x-to-basis-current-v2-dosage-form', id: 'w10-nct02678611-1x-to-basis-current-v2-dosage-form', dimension: 'DOSAGE_FORM', dimensionClass: 'CATEGORICAL', verdict: 'PARTIAL', identityLevel: null, evidenceCategory: 'CAPSULE', targetCategory: 'CAPSULE', evidenceValue: null, targetValue: null, unitCode: null, evidenceQuantityBasis: null, targetQuantityBasis: null, evidenceMassBasis: null, targetMassBasis: null, ratio: null, missingFacts: [], rationale: 'Both oral capsules. Trial: gelatin capsules with MCC, silicon dioxide, magnesium stearate; current label: hypromellose (vegetarian) capsules with MCC, vegetable magnesium stearate, silica. Shell material differs.'},
  {uid: 'hu:applicability-dimension:w10-nct02678611-1x-to-basis-current-v2-route', id: 'w10-nct02678611-1x-to-basis-current-v2-route', dimension: 'ROUTE', dimensionClass: 'CATEGORICAL', verdict: 'MATCH', identityLevel: null, evidenceCategory: 'ORAL', targetCategory: 'ORAL', evidenceValue: null, targetValue: null, unitCode: null, evidenceQuantityBasis: null, targetQuantityBasis: null, evidenceMassBasis: null, targetMassBasis: null, ratio: null, missingFacts: [], rationale: 'Oral in both.'},
  {uid: 'hu:applicability-dimension:w10-nct02678611-1x-to-basis-current-v2-schedule', id: 'w10-nct02678611-1x-to-basis-current-v2-schedule', dimension: 'SCHEDULE', dimensionClass: 'CONTINUOUS', verdict: 'MATCH', identityLevel: null, evidenceCategory: 'ONCE_DAILY_WITH_BREAKFAST', targetCategory: 'ONCE_DAILY_MORNING_WITH_OR_WITHOUT_FOOD', evidenceValue: 1.0, targetValue: 1.0, unitCode: '/d', evidenceQuantityBasis: 'PER_DAY', targetQuantityBasis: 'PER_DAY', evidenceMassBasis: null, targetMassBasis: null, ratio: 1.0, missingFacts: [], rationale: 'One administration per day on both sides (identity ratio 1.0; no band applied). Food timing differs (with breakfast vs with or without food).'},
  {uid: 'hu:applicability-dimension:w10-nct02678611-1x-to-basis-current-v2-duration', id: 'w10-nct02678611-1x-to-basis-current-v2-duration', dimension: 'DURATION', dimensionClass: 'CONTINUOUS', verdict: 'PARTIAL', identityLevel: null, evidenceCategory: null, targetCategory: 'OPEN_ENDED', evidenceValue: 56.0, targetValue: null, unitCode: 'd', evidenceQuantityBasis: null, targetQuantityBasis: null, evidenceMassBasis: null, targetMassBasis: null, ratio: null, missingFacts: [], rationale: 'Studied 8 weeks (+30-day follow-up); the label implies open-ended daily use. Extrapolation beyond 56 days.'},
  {uid: 'hu:applicability-dimension:w10-nct02678611-1x-to-basis-current-v2-population', id: 'w10-nct02678611-1x-to-basis-current-v2-population', dimension: 'POPULATION', dimensionClass: 'CATEGORICAL', verdict: 'PARTIAL', identityLevel: null, evidenceCategory: 'OVERLAPS', targetCategory: 'HEALTHY_ADULTS', evidenceValue: null, targetValue: null, unitCode: null, evidenceQuantityBasis: null, targetQuantityBasis: null, evidenceMassBasis: null, targetMassBasis: null, ratio: null, missingFacts: [], rationale: 'Trial: healthy adults 60-80, BMI 18-35, no lipid-lowering drugs or B3 supplements; label: healthy adults.'},
  {uid: 'hu:applicability-dimension:w10-nct02678611-1x-to-basis-current-v2-comparator', id: 'w10-nct02678611-1x-to-basis-current-v2-comparator', dimension: 'COMPARATOR', dimensionClass: 'CATEGORICAL', verdict: 'MATCH', identityLevel: null, evidenceCategory: 'PLACEBO', targetCategory: 'NO_TREATMENT', evidenceValue: null, targetValue: null, unitCode: null, evidenceQuantityBasis: null, targetQuantityBasis: null, evidenceMassBasis: null, targetMassBasis: null, ratio: null, missingFacts: [], rationale: 'Placebo comparator answers a take-or-not decision.'},
  {uid: 'hu:applicability-dimension:w10-nct02678611-1x-to-basis-current-v2-outcome-relevance', id: 'w10-nct02678611-1x-to-basis-current-v2-outcome-relevance', dimension: 'OUTCOME_RELEVANCE', dimensionClass: 'CATEGORICAL', verdict: 'PARTIAL', identityLevel: null, evidenceCategory: 'BIOMARKER_NOT_SURROGATE', targetCategory: null, evidenceValue: null, targetValue: null, unitCode: null, evidenceQuantityBasis: null, targetQuantityBasis: null, evidenceMassBasis: null, targetMassBasis: null, ratio: null, missingFacts: [], rationale: 'The favorable finding is whole-blood NAD+, a pharmacodynamic biomarker with no established surrogate context; the registered primary objective was safety.'},
  {uid: 'hu:applicability-dimension:w10-nct02678611-1x-to-basis-current-v2-study-design-and-quality', id: 'w10-nct02678611-1x-to-basis-current-v2-study-design-and-quality', dimension: 'STUDY_DESIGN_AND_QUALITY', dimensionClass: 'CATEGORICAL', verdict: 'NOT_ASSESSED', identityLevel: null, evidenceCategory: null, targetCategory: null, evidenceValue: null, targetValue: null, unitCode: null, evidenceQuantityBasis: null, targetQuantityBasis: null, evidenceMassBasis: null, targetMassBasis: null, ratio: null, missingFacts: [], rationale: null},
  {uid: 'hu:applicability-dimension:w10-nct02678611-1x-to-basis-current-v2-background-context', id: 'w10-nct02678611-1x-to-basis-current-v2-background-context', dimension: 'BACKGROUND_CONTEXT', dimensionClass: 'EXPLANATION_ONLY', verdict: 'NOT_SCORED', identityLevel: null, evidenceCategory: null, targetCategory: null, evidenceValue: null, targetValue: null, unitCode: null, evidenceQuantityBasis: null, targetQuantityBasis: null, evidenceMassBasis: null, targetMassBasis: null, ratio: null, missingFacts: [], rationale: 'Participants avoided vitamin B3 supplements and multivitamins and excluded lipid-lowering drug users; consumers may not.'},
  {uid: 'hu:applicability-dimension:w10-nct02678611-1x-to-basis-current-v2-recency-and-corrections', id: 'w10-nct02678611-1x-to-basis-current-v2-recency-and-corrections', dimension: 'RECENCY_AND_CORRECTIONS', dimensionClass: 'EXPLANATION_ONLY', verdict: 'NOT_SCORED', identityLevel: null, evidenceCategory: null, targetCategory: null, evidenceValue: null, targetValue: null, unitCode: null, evidenceQuantityBasis: null, targetQuantityBasis: null, evidenceMassBasis: null, targetMassBasis: null, ratio: null, missingFacts: [], rationale: 'Author Correction (2018) added that Elysium provided the investigational product; the registry lists one site, the paper three; the registry shows no posted results while a results article exists.'}
] AS row
MERGE (d:ApplicabilityDimension {uid: row.uid})
  ON CREATE SET d.id = row.id, d.dimension = row.dimension, d.dimensionClass = row.dimensionClass, d.verdict = row.verdict, d.identityLevel = row.identityLevel, d.evidenceCategory = row.evidenceCategory, d.targetCategory = row.targetCategory, d.evidenceValue = row.evidenceValue, d.targetValue = row.targetValue, d.unitCode = row.unitCode, d.evidenceQuantityBasis = row.evidenceQuantityBasis, d.targetQuantityBasis = row.targetQuantityBasis, d.evidenceMassBasis = row.evidenceMassBasis, d.targetMassBasis = row.targetMassBasis, d.ratio = row.ratio, d.missingFacts = row.missingFacts, d.rationale = row.rationale, d.assessmentType = 'ApplicabilityDimension', d.methodVersion = ea.methodVersion, d.status = ea.status,
    d.privacyClass = 'PUBLIC', d.recordedAt = datetime('2026-10-04T02:00:00Z'), d.createdAt = datetime('2026-10-04T02:00:00Z')
SET d:EvidenceAssessment
MERGE (ea)-[:HAS_DIMENSION]->(d);

// status: run
UNWIND [
  {d: 'hu:applicability-dimension:w10-nct02678611-1x-to-basis-current-v2-material-identity', t: 'hu:locator:pmid30155270-intervention-source'},
  {d: 'hu:applicability-dimension:w10-nct02678611-1x-to-basis-current-v2-material-identity', t: 'hu:locator:cen-2018-supply-until-mid-2016'},
  {d: 'hu:applicability-dimension:w10-nct02678611-1x-to-basis-current-v2-material-identity', t: 'hu:locator:elysium-basis-label-amount-2026-10-04'},
  {d: 'hu:applicability-dimension:w10-nct02678611-1x-to-basis-current-v2-active-composition', t: 'hu:locator:pmc5701244-methods-intervention-capsule-2026-10-04'},
  {d: 'hu:applicability-dimension:w10-nct02678611-1x-to-basis-current-v2-active-composition', t: 'hu:locator:elysium-basis-label-amount-2026-10-04'},
  {d: 'hu:applicability-dimension:w10-nct02678611-1x-to-basis-current-v2-dose', t: 'hu:locator:pmc5701244-methods-intervention-capsule-2026-10-04'},
  {d: 'hu:applicability-dimension:w10-nct02678611-1x-to-basis-current-v2-dose', t: 'hu:locator:pmc5701244-methods-four-capsules-2026-10-04'},
  {d: 'hu:applicability-dimension:w10-nct02678611-1x-to-basis-current-v2-dose', t: 'hu:locator:elysium-basis-label-amount-2026-10-04'},
  {d: 'hu:applicability-dimension:w10-nct02678611-1x-to-basis-current-v2-dose', t: 'hu:locator:elysium-basis-label-directions-2026-10-04'},
  {d: 'hu:applicability-dimension:w10-nct02678611-1x-to-basis-current-v2-dosage-form', t: 'hu:locator:pmc5701244-methods-intervention-capsule-2026-10-04'},
  {d: 'hu:applicability-dimension:w10-nct02678611-1x-to-basis-current-v2-dosage-form', t: 'hu:locator:elysium-basis-label-other-ingredients-2026-10-04'},
  {d: 'hu:applicability-dimension:w10-nct02678611-1x-to-basis-current-v2-route', t: 'hu:locator:pmc5701244-methods-four-capsules-2026-10-04'},
  {d: 'hu:applicability-dimension:w10-nct02678611-1x-to-basis-current-v2-route', t: 'hu:locator:elysium-basis-label-directions-2026-10-04'},
  {d: 'hu:applicability-dimension:w10-nct02678611-1x-to-basis-current-v2-schedule', t: 'hu:locator:pmc5701244-methods-four-capsules-2026-10-04'},
  {d: 'hu:applicability-dimension:w10-nct02678611-1x-to-basis-current-v2-schedule', t: 'hu:locator:elysium-basis-label-directions-2026-10-04'},
  {d: 'hu:applicability-dimension:w10-nct02678611-1x-to-basis-current-v2-duration', t: 'hu:locator:pmid29184669-results-trial-overview'},
  {d: 'hu:applicability-dimension:w10-nct02678611-1x-to-basis-current-v2-duration', t: 'hu:locator:elysium-basis-label-directions-2026-10-04'},
  {d: 'hu:applicability-dimension:w10-nct02678611-1x-to-basis-current-v2-population', t: 'hu:locator:ctgov-nct02678611-eligibility'},
  {d: 'hu:applicability-dimension:w10-nct02678611-1x-to-basis-current-v2-population', t: 'hu:locator:elysium-basis-label-directions-2026-10-04'},
  {d: 'hu:applicability-dimension:w10-nct02678611-1x-to-basis-current-v2-comparator', t: 'hu:locator:pmc5701244-methods-four-capsules-2026-10-04'},
  {d: 'hu:applicability-dimension:w10-nct02678611-1x-to-basis-current-v2-outcome-relevance', t: 'hu:locator:pmc5701244-methods-primary-objective-2026-10-04'},
  {d: 'hu:applicability-dimension:w10-nct02678611-1x-to-basis-current-v2-outcome-relevance', t: 'hu:locator:pmid29184669-results-nad'}
] AS row
MATCH (d:ApplicabilityDimension {uid: row.d}), (t {uid: row.t})
MERGE (d)-[:SUPPORTED_BY]->(t);

// status: run
UNWIND [
  {d: 'hu:applicability-dimension:w10-nct02678611-1x-to-basis-current-v2-material-identity', t: 'hu:assertion:chromadex-says-supplied-elysium-nr-until-mid-2016'},
  {d: 'hu:applicability-dimension:w10-nct02678611-1x-to-basis-current-v2-material-identity', t: 'hu:assertion:elysium-provides-nct02678611-nrpt-1x'}
] AS row
MATCH (d:ApplicabilityDimension {uid: row.d}), (t {uid: row.t})
MERGE (d)-[:CONSIDERS]->(t);

// status: run
UNWIND [
  {d: 'hu:applicability-dimension:w10-nct02678611-1x-to-basis-current-v2-material-identity', t: 'hu:resolution:nct02678611-nr-is-chromadex-niagen'},
  {d: 'hu:applicability-dimension:w10-nct02678611-1x-to-basis-current-v2-material-identity', t: 'hu:resolution:nct02678611-nr-is-elysium-nr-e'},
  {d: 'hu:applicability-dimension:w10-nct02678611-1x-to-basis-current-v2-outcome-relevance', t: 'hu:endpoint-classification:nct02678611-nad-whole-blood'}
] AS row
MATCH (d:ApplicabilityDimension {uid: row.d}), (t {uid: row.t})
MERGE (d)-[:CONSIDERS_ASSESSMENT]->(t);

// status: run
MATCH (ea:EvidenceApplicability {uid: 'hu:applicability:w10-nct02678611-1x-to-basis-current-v2'})-[:HAS_DIMENSION]->(d:ApplicabilityDimension)
WITH ea, collect(d) AS dims
SET ea.identityMatch = head([d IN dims WHERE d.dimension = 'MATERIAL_IDENTITY' | d.verdict]),
    ea.doseMatch = head([d IN dims WHERE d.dimension = 'DOSE' | d.verdict]),
    ea.routeMatch = head([d IN dims WHERE d.dimension = 'ROUTE' | d.verdict]),
    ea.scheduleMatch = head([d IN dims WHERE d.dimension = 'SCHEDULE' | d.verdict]),
    ea.durationMatch = head([d IN dims WHERE d.dimension = 'DURATION' | d.verdict]),
    ea.populationMatch = head([d IN dims WHERE d.dimension = 'POPULATION' | d.verdict]),
    ea.outcomeMatch = head([d IN dims WHERE d.dimension = 'OUTCOME_RELEVANCE' | d.verdict]);

// status: run
MATCH (act:Activity {uid: 'hu:activity:w10-applicability-review-2026-10-04'}), (ea:EvidenceApplicability {uid: 'hu:applicability:w10-nct02678611-1x-to-basis-current-v2'})
MERGE (ea)-[:WAS_GENERATED_BY]->(act);

