import hashlib, json, unicodedata, re
def nfcws1(s): return re.sub(r'\s+',' ',unicodedata.normalize('NFC',s)).strip()
def sha(s): return 'sha256:'+hashlib.sha256(s.encode('utf-8')).hexdigest()
def cy(s): return "'" + s.replace('\\','\\\\').replace("'","\\'").replace('\n','\\n') + "'"
def seghash(cfg): return sha(json.dumps(cfg, sort_keys=True, separators=(',',':')))
def chunks(text, size, overlap):
    out=[]; i=0; step=size-overlap; idx=0
    while i < len(text):
        out.append((idx, i, min(i+size, len(text)), text[i:i+size])); idx+=1
        if i+size >= len(text): break
        i += step
    return out
T1 = ("David Sinclair: Well, I'm always happy to tell you what I do and what my father does. "
      "My 82 -year-old father, we take a gram of NMN every day.\n"
      "Andrew Huberman: So it's a gram of resveratrol and a gram of NMN.\n"
      "David Sinclair: Right.\n"
      "David Sinclair: Now another important point, which is I'm not the same as everybody else. I have different microbiome, age, sex.\n")
T2 = T1.replace("82 -year-old", "82-year-old")
Q1 = "My 82 -year-old father, we take a gram of NMN every day."
Q2 = "My 82-year-old father, we take a gram of NMN every day."
s1, e1 = T1.index(Q1), T1.index(Q1)+len(Q1)
s2, e2 = T2.index(Q2), T2.index(Q2)+len(Q2)
G1cfg = {"strategy":"fixed-window","chunkSize":80,"overlap":0,"methodVersion":"w20-window-v1;unit=CODE_POINT"}
G2cfg = {"strategy":"fixed-window","chunkSize":160,"overlap":20,"methodVersion":"w20-window-v1;unit=CODE_POINT"}
h1, h2 = seghash(G1cfg), seghash(G2cfg)
P = {}
P['T1hash']=sha(T1); P['T2hash']=sha(T2); P['s1']=s1; P['e1']=e1; P['s2']=s2; P['e2']=e2
P['q1hash']=sha(nfcws1(Q1)); P['q2hash']=sha(nfcws1(Q2)); P['h1']=h1; P['h2']=h2
C1 = chunks(T1,80,0); C2 = chunks(T1,160,20); C3 = chunks(T2,160,20)
def overlapping(C, s, e): return [c for c in C if c[1] < e and s < c[2]]
P['G1_overlap']=[(c[0],c[1],c[2], c[1]<=s1 and e1<=c[2]) for c in overlapping(C1,s1,e1)]
P['G2_overlap']=[(c[0],c[1],c[2], c[1]<=s1 and e1<=c[2]) for c in overlapping(C2,s1,e1)]
P['G3_overlap']=[(c[0],c[1],c[2], c[1]<=s2 and e2<=c[2]) for c in overlapping(C3,s2,e2)]
P['nC1']=len(C1); P['nC2']=len(C2); P['nC3']=len(C3)
json.dump(P, open('gen01-params.json','w'), indent=1)
L=[]
w=L.append
w("// W20 fixture 01: re-segmentation of an unchanged capture versus a corrected capture (CQ-PV-02, CQ-PV-03, INV-404).")
w("// SYNTHETIC_FIXTURE: modelled on the real Huberman Lab episode 52 transcript-page case (round 0006 D1, O-3),")
w("// but the Source is on an .invalid domain and the 'corrected' second capture is invented. Generated by gen01.py;")
w("// offsets are Unicode code points (start inclusive, end exclusive) and were computed, not typed by hand.")
w("// Every statement binds its own nodes by uid; no variable crosses a ';'.")
w("")
w("// ---------- 0. agents and activities ----------")
w("MERGE (n:Agent:Entity {uid: 'hu:agent:w20-fixture-pipeline'}) SET n.entityType = 'Agent', n.name = 'W20 fixture pipeline', n.agentKind = 'AUTOMATED_AGENT', n.toolVersion = 'w20-fixture-0.1', n.createdAt = datetime('2026-10-04T01:00:00Z')")
for uid, kind, start, mv in [
  ('hu:activity:w20f01-capture-1','CAPTURE','2026-10-03T00:00:00Z','w20-capture-v1'),
  ('hu:activity:w20f01-extract-1','TEXT_EXTRACTION','2026-10-03T00:05:00Z','html-text-extract-v2'),
  ('hu:activity:w20f01-segment-g1','SEGMENTATION','2026-10-03T00:10:00Z','w20-window-v1'),
  ('hu:activity:w20f01-segment-g2','SEGMENTATION','2026-10-20T00:00:00Z','w20-window-v1'),
  ('hu:activity:w20f01-capture-2','CAPTURE','2026-11-02T00:00:00Z','w20-capture-v1'),
  ('hu:activity:w20f01-extract-2','TEXT_EXTRACTION','2026-11-02T00:05:00Z','html-text-extract-v2'),
  ('hu:activity:w20f01-segment-g3','SEGMENTATION','2026-11-02T00:10:00Z','w20-window-v1'),
  ('hu:activity:w20f01-reanchor-1','REANCHORING','2026-11-02T00:20:00Z','quote-reanchor-nfcws1-v1')]:
    w(f";\nMERGE (n:Activity:Occurrence {{uid: '{uid}'}}) SET n.occurrenceType = 'Activity', n.activityKind = '{kind}', n.startedAt = datetime('{start}'), n.endedAt = datetime('{start}'), n.methodVersion = '{mv}', n.createdAt = datetime('{start}')")
w(";\nMATCH (a:Activity {uid: 'hu:activity:w20f01-segment-g1'}), (g:Agent {uid: 'hu:agent:w20-fixture-pipeline'}) MERGE (a)-[:WAS_ASSOCIATED_WITH]->(g)")
w(";\n// ---------- 1. Document (Source specialization), first capture, text version ----------")
w("MERGE (d:Document:Source:Entity {uid: 'hu:document:w20f01-transcript-page'})\nSET d.documentId = 'w20f01-transcript-page', d.entityType = 'Document', d.title = 'Synthetic transcript page, episode 52 (fixture only)',\n    d.canonicalUri = 'https://transcripts.example.invalid/episode-52', d.url = 'https://transcripts.example.invalid/episode-52',\n    d.type = 'TRANSCRIPT_PAGE', d.sourceKind = 'PODCAST_TRANSCRIPT_PAGE', d.documentKey = 'w20f01', d.documentDomain = 'NEWS_MEDIA', d.languageCode = 'en',\n    d.fixtureProvenance = 'SYNTHETIC', d.privacyClass = 'PUBLIC', d.createdAt = datetime('2026-10-03T00:00:00Z'), d.updatedAt = datetime('2026-10-03T00:00:00Z')")
w(";\nMATCH (d:Document {uid: 'hu:document:w20f01-transcript-page'}), (act:Activity {uid: 'hu:activity:w20f01-capture-1'})\nMERGE (s:SourceSnapshot:InformationArtifact {uid: 'hu:snapshot:w20f01-page-2026-10-03'})\nSET s.artifactType = 'SourceSnapshot', s.canonicalUri = d.canonicalUri, s.retrievedAt = datetime('2026-10-03T00:00:00Z'), s.observedAt = datetime('2026-10-03T00:00:00Z'),\n    s.contentHash = 'sha256:679755704dd94340c363a46c4b5cb726e6a3843253fd7ae5cdabb0aa04b18834', s.contentHashBasis = 'SYNTHETIC_FIXTURE', s.captureCompleteness = 'COMPLETE',\n    s.publisherRevisionNotice = 'This transcript is under review (synthetic).', s.mimeType = 'text/html', s.language = 'en', s.createdAt = datetime('2026-10-03T00:00:00Z')\nMERGE (d)-[:HAS_SNAPSHOT]->(s)\nMERGE (s)-[:WAS_GENERATED_BY]->(act)")
w(f";\nMATCH (d:Document {{uid: 'hu:document:w20f01-transcript-page'}}), (s:SourceSnapshot {{uid: 'hu:snapshot:w20f01-page-2026-10-03'}}), (act:Activity {{uid: 'hu:activity:w20f01-extract-1'}})\nMERGE (tv:DocumentTextVersion:InformationArtifact {{uid: 'hu:text-version:w20f01-tv1'}})\nSET tv.documentTextVersionId = 'w20f01-tv1', tv.artifactType = 'DocumentTextVersion', tv.versionLabel = 'html-text-extract-v2',\n    tv.text = {cy(T1)},\n    tv.textVersionHash = '{P['T1hash']}', tv.contentHash = '{P['T1hash']}', tv.source = 'html-text-extract', tv.normalizationVersion = NULL, tv.languageCode = 'en',\n    tv.observedAt = s.observedAt, tv.createdAt = datetime('2026-10-03T00:05:00Z'), tv.updatedAt = datetime('2026-10-03T00:05:00Z')\nMERGE (d)-[:HAS_TEXT_VERSION]->(tv)\nMERGE (tv)-[:TEXT_OF_SNAPSHOT]->(s)\nMERGE (tv)-[:WAS_GENERATED_BY]->(act)")
w(f";\n// ---------- 2. locator (TEXT_POSITION + quote anchor), assertion, capture-fidelity adjudication ----------\nMATCH (s:SourceSnapshot {{uid: 'hu:snapshot:w20f01-page-2026-10-03'}}), (tv:DocumentTextVersion {{uid: 'hu:text-version:w20f01-tv1'}})\nMERGE (l:SourceLocator:InformationArtifact {{uid: 'hu:locator:w20f01-l1-nmn-gram'}})\nSET l.artifactType = 'SourceLocator', l.uri = s.canonicalUri, l.selectorKind = 'TEXT_POSITION',\n    l.exact = {cy(Q1)}, l.prefix = 'and what my father does. ', l.suffix = '\\nAndrew Huberman: So it',\n    l.quoteHash = '{P['q1hash']}', l.normalizationVersion = 'NFC-WS1', l.startOffset = {s1}, l.endOffset = {e1},\n    l.speakerLabelInSource = 'David Sinclair', l.createdAt = datetime('2026-10-03T00:30:00Z')\nMERGE (s)-[:HAS_LOCATOR]->(l)\nMERGE (l)-[:LOCATOR_IN_TEXT_VERSION]->(tv)")
w(";\nMERGE (sub:ChemicalSubstance:Entity {uid: 'hu:substance:w20f01-nmn'}) SET sub.entityType = 'ChemicalSubstance', sub.name = 'NMN (fixture stub)', sub.createdAt = datetime('2026-10-03T00:00:00Z')")
w(";\nMATCH (l:SourceLocator {uid: 'hu:locator:w20f01-l1-nmn-gram'}), (sub:ChemicalSubstance {uid: 'hu:substance:w20f01-nmn'}), (act:Activity {uid: 'hu:activity:w20f01-extract-1'})\nMERGE (a:Assertion {uid: 'hu:assertion:w20f01-a1-nmn-gram-daily'})\nSET a.predicate = 'SELF_REPORTED_DAILY_INTAKE', a.status = 'ACCEPTED', a.recordedAt = datetime('2026-10-03T01:00:00Z'), a.valueNumber = 1.0, a.unitCode = 'g',\n    a.quantityBasis = 'PER_DAY', a.polarity = 'POSITIVE', a.assertionBasis = 'PERSONAL_EXPERIENCE', a.speechAct = 'REPORTS_PRACTICE',\n    a.contentHash = 'sha256:fb8ed2f17fcbc00ecaaf7e08473f0395639b128b418290310818dc1e5e33cf99', a.createdAt = datetime('2026-10-03T01:00:00Z')\nMERGE (a)-[:HAS_SUBJECT]->(sub)\nMERGE (a)-[:SUPPORTED_BY]->(l)\nMERGE (a)-[:WAS_GENERATED_BY]->(act)")
w(";\nMATCH (a:Assertion {uid: 'hu:assertion:w20f01-a1-nmn-gram-daily'})\nMERGE (j:Adjudication:EvidenceAssessment {uid: 'hu:adjudication:w20f01-cf-a1'})\nSET j.assessmentType = 'Adjudication', j.adjudicationKind = 'CAPTURE_FIDELITY', j.verdict = 'SUPPORTED', j.reviewerType = 'HUMAN', j.methodVersion = 'w20-fixture-review-v1',\n    j.status = 'ACCEPTED', j.reviewedAt = datetime('2026-10-03T02:00:00Z'), j.recordedAt = datetime('2026-10-03T02:00:00Z'), j.createdAt = datetime('2026-10-03T02:00:00Z')\nMERGE (j)-[:EVALUATES]->(a)")
w(";\n// derived document-level shortcut (live SUPPORTED_BY_DOCUMENT) naming its locator\nMATCH (a:Assertion {uid: 'hu:assertion:w20f01-a1-nmn-gram-daily'}), (d:Document {uid: 'hu:document:w20f01-transcript-page'})\nMERGE (a)-[r:SUPPORTED_BY_DOCUMENT]->(d)\nSET r.derivationRule = 'support-via-locator-document-v1', r.derivedFromAssertionUids = ['hu:assertion:w20f01-a1-nmn-gram-daily'], r.locatorUid = 'hu:locator:w20f01-l1-nmn-gram', r.derivedAt = datetime('2026-10-03T03:00:00Z')")
def seg_block(guid, gid, tvuid, cfg, h, C, act, at, docuid):
    out=[]
    out.append(f";\n// segmentation {guid}: config {json.dumps(cfg, sort_keys=True)}\nMATCH (tv:DocumentTextVersion {{uid: '{tvuid}'}}), (act:Activity {{uid: '{act}'}})\nMERGE (g:Segmentation:InformationArtifact {{uid: '{guid}'}})\nSET g.segmentationId = '{gid}', g.artifactType = 'Segmentation', g.segmentationHash = '{h}', g.chunkSize = {cfg['chunkSize']}, g.overlap = {cfg['overlap']},\n    g.strategy = '{cfg['strategy']}', g.methodVersion = '{cfg['methodVersion']}', g.createdAt = datetime('{at}'), g.updatedAt = datetime('{at}')\nMERGE (tv)-[:HAS_SEGMENTATION]->(g)\nMERGE (g)-[:WAS_GENERATED_BY]->(act)")
    for (idx,cs,ce,txt) in C:
        cuid = f"hu:chunk:{gid}-c{idx}"
        out.append(f";\nMATCH (tv:DocumentTextVersion {{uid: '{tvuid}'}}), (d:Document {{uid: '{docuid}'}})\nMERGE (c:Chunk:InformationArtifact {{uid: '{cuid}'}})\nSET c.chunkId = '{gid}-c{idx}', c.chunkKey = '{gid}#{idx}', c.artifactType = 'Chunk', c.index = {idx}, c.text = {cy(txt)}, c.segmentationHash = '{h}',\n    c.charStart = {cs}, c.charEnd = {ce}, c.contentHash = '{sha(txt)}', c.createdAt = datetime('{at}'), c.updatedAt = datetime('{at}')\nMERGE (c)-[:FROM_TEXT_VERSION]->(tv)\nMERGE (d)-[hc:HAS_CHUNK]->(c) SET hc.derivationRule = 'chunk-of-document-text-version-v1', hc.derivedAt = datetime('{at}')")
    for k in range(len(C)-1):
        out.append(f";\nMATCH (a:Chunk {{uid: 'hu:chunk:{gid}-c{k}'}}), (b:Chunk {{uid: 'hu:chunk:{gid}-c{k+1}'}}) MERGE (a)-[:NEXT_CHUNK]->(b)")
    return out
def resolve_block(luid, gid, overlaps, h, at, auid=None, act=None):
    out=[]
    for (idx,cs,ce,whole) in overlaps:
        out.append(f";\nMATCH (l:SourceLocator {{uid: '{luid}'}}), (c:Chunk {{uid: 'hu:chunk:{gid}-c{idx}'}})\nMERGE (l)-[r:RESOLVES_TO_CHUNK]->(c)\nSET r.derivationRule = 'offset-overlap-v1', r.segmentationHash = '{h}', r.coversWholeSpan = {str(whole).lower()}, r.derivedAt = datetime('{at}'), r.activityUid = '{act}'")
        if auid:
            out.append(f";\nMATCH (a:Assertion {{uid: '{auid}'}}), (c:Chunk {{uid: 'hu:chunk:{gid}-c{idx}'}})\nMERGE (a)-[r:SUPPORTED_BY_CHUNK]->(c)\nSET r.derivationRule = 'support-via-locator-chunk-v1', r.derivedFromAssertionUids = ['{auid}'], r.locatorUid = '{luid}', r.segmentationHash = '{h}', r.derivedAt = datetime('{at}'), r.activityUid = '{act}'")
    return out
w(";\n// ---------- 3. segmentation G1 (chunkSize 80, overlap 0) and derived links ----------")
L += seg_block('hu:segmentation:w20f01-g1','w20f01-g1','hu:text-version:w20f01-tv1',G1cfg,h1,C1,'hu:activity:w20f01-segment-g1','2026-10-03T00:10:00Z','hu:document:w20f01-transcript-page')
L += resolve_block('hu:locator:w20f01-l1-nmn-gram','w20f01-g1',P['G1_overlap'],h1,'2026-10-03T00:40:00Z','hu:assertion:w20f01-a1-nmn-gram-daily','hu:activity:w20f01-segment-g1')
w(";\n// ---------- 4. RE-SEGMENTATION of the UNCHANGED capture: new Segmentation G2 (160/20), new chunks, regenerated links ----------")
L += seg_block('hu:segmentation:w20f01-g2','w20f01-g2','hu:text-version:w20f01-tv1',G2cfg,h2,C2,'hu:activity:w20f01-segment-g2','2026-10-20T00:00:00Z','hu:document:w20f01-transcript-page')
L += resolve_block('hu:locator:w20f01-l1-nmn-gram','w20f01-g2',P['G2_overlap'],h2,'2026-10-20T00:05:00Z','hu:assertion:w20f01-a1-nmn-gram-daily','hu:activity:w20f01-segment-g2')
w(";\n// retire G1: derived chunks and their derived edges are deleted; the locator, snapshot, text version and assertion are untouched\nMATCH (c:Chunk) WHERE c.segmentationHash = '" + h1 + "' AND EXISTS { MATCH (c)-[:FROM_TEXT_VERSION]->(:DocumentTextVersion {uid: 'hu:text-version:w20f01-tv1'}) } DETACH DELETE c")
w(";\nMATCH (g:Segmentation {uid: 'hu:segmentation:w20f01-g1'}) DETACH DELETE g")
w(";\n// ---------- 5. CORRECTED capture: new snapshot, new text version, new locator REANCHORS the old one ----------")
w(";\nMATCH (d:Document {uid: 'hu:document:w20f01-transcript-page'}), (act:Activity {uid: 'hu:activity:w20f01-capture-2'})\nMERGE (s:SourceSnapshot:InformationArtifact {uid: 'hu:snapshot:w20f01-page-2026-11-02'})\nSET s.artifactType = 'SourceSnapshot', s.canonicalUri = d.canonicalUri, s.retrievedAt = datetime('2026-11-02T00:00:00Z'), s.observedAt = datetime('2026-11-02T00:00:00Z'),\n    s.contentHash = 'sha256:d6e39b8a93ea90b37124200fd1e85c31ba418291259722025eaa29a3b08cdbc5', s.contentHashBasis = 'SYNTHETIC_FIXTURE', s.captureCompleteness = 'COMPLETE',\n    s.publisherRevisionNotice = NULL, s.mimeType = 'text/html', s.language = 'en', s.createdAt = datetime('2026-11-02T00:00:00Z')\nMERGE (d)-[:HAS_SNAPSHOT]->(s)\nMERGE (s)-[:WAS_GENERATED_BY]->(act)")
w(f";\nMATCH (d:Document {{uid: 'hu:document:w20f01-transcript-page'}}), (s:SourceSnapshot {{uid: 'hu:snapshot:w20f01-page-2026-11-02'}}), (act:Activity {{uid: 'hu:activity:w20f01-extract-2'}})\nMERGE (tv:DocumentTextVersion:InformationArtifact {{uid: 'hu:text-version:w20f01-tv2'}})\nSET tv.documentTextVersionId = 'w20f01-tv2', tv.artifactType = 'DocumentTextVersion', tv.versionLabel = 'html-text-extract-v2',\n    tv.text = {cy(T2)},\n    tv.textVersionHash = '{P['T2hash']}', tv.contentHash = '{P['T2hash']}', tv.source = 'html-text-extract', tv.languageCode = 'en',\n    tv.observedAt = s.observedAt, tv.createdAt = datetime('2026-11-02T00:05:00Z'), tv.updatedAt = datetime('2026-11-02T00:05:00Z')\nMERGE (d)-[:HAS_TEXT_VERSION]->(tv)\nMERGE (tv)-[:TEXT_OF_SNAPSHOT]->(s)\nMERGE (tv)-[:WAS_GENERATED_BY]->(act)")
w(f";\nMATCH (s:SourceSnapshot {{uid: 'hu:snapshot:w20f01-page-2026-11-02'}}), (tv:DocumentTextVersion {{uid: 'hu:text-version:w20f01-tv2'}}), (act:Activity {{uid: 'hu:activity:w20f01-reanchor-1'}})\nMERGE (l:SourceLocator:InformationArtifact {{uid: 'hu:locator:w20f01-l2-nmn-gram-reanchored'}})\nSET l.artifactType = 'SourceLocator', l.uri = s.canonicalUri, l.selectorKind = 'TEXT_POSITION',\n    l.exact = {cy(Q2)}, l.prefix = 'and what my father does. ', l.suffix = '\\nAndrew Huberman: So it',\n    l.quoteHash = '{P['q2hash']}', l.normalizationVersion = 'NFC-WS1', l.startOffset = {s2}, l.endOffset = {e2},\n    l.speakerLabelInSource = 'David Sinclair', l.createdAt = datetime('2026-11-02T00:20:00Z')\nMERGE (s)-[:HAS_LOCATOR]->(l)\nMERGE (l)-[:LOCATOR_IN_TEXT_VERSION]->(tv)\nMERGE (l)-[:WAS_GENERATED_BY]->(act)")
w(";\nMATCH (newL:SourceLocator {uid: 'hu:locator:w20f01-l2-nmn-gram-reanchored'}), (oldL:SourceLocator {uid: 'hu:locator:w20f01-l1-nmn-gram'})\nMERGE (newL)-[x:REANCHORS]->(oldL) SET x.anchorMatch = 'FUZZY', x.activityUid = 'hu:activity:w20f01-reanchor-1'")
w(";\n// segmentation of the corrected text with the SAME configuration as G2: same segmentationHash, different chunks")
L += seg_block('hu:segmentation:w20f01-g3','w20f01-g3','hu:text-version:w20f01-tv2',G2cfg,h2,C3,'hu:activity:w20f01-segment-g3','2026-11-02T00:10:00Z','hu:document:w20f01-transcript-page')
L += resolve_block('hu:locator:w20f01-l2-nmn-gram-reanchored','w20f01-g3',P['G3_overlap'],h2,'2026-11-02T00:25:00Z',None,'hu:activity:w20f01-reanchor-1')
w(";\n// NOTE: no SUPPORTED_BY_CHUNK from A1 into the corrected text version: A1 is SUPPORTED_BY L1 only; whether a re-anchored locator\n// joins an assertion's support is a W00 rule (W20-SR-06). The path chunk <- L2 -REANCHORS-> L1 <- A1 is the answer route.\n")
open('w20-01-resegmentation-vs-correction.cypher','w').write('\n'.join(L).replace('\n;\n',';\n'))
print(json.dumps(P, indent=1))
