// W20 fixture 01: re-segmentation of an unchanged capture versus a corrected capture (CQ-PV-02, CQ-PV-03, INV-404).
// SYNTHETIC_FIXTURE: modelled on the real Huberman Lab episode 52 transcript-page case (round 0006 D1, O-3),
// but the Source is on an .invalid domain and the 'corrected' second capture is invented. Generated by gen01.py;
// offsets are Unicode code points (start inclusive, end exclusive) and were computed, not typed by hand.
// Every statement binds its own nodes by uid; no variable crosses a ';'.

// ---------- 0. agents and activities ----------
MERGE (n:Agent:Entity {uid: 'hu:agent:w20-fixture-pipeline'}) SET n.entityType = 'Agent', n.name = 'W20 fixture pipeline', n.agentKind = 'AUTOMATED_AGENT', n.toolVersion = 'w20-fixture-0.1', n.createdAt = datetime('2026-10-04T01:00:00Z');
MERGE (n:Activity:Occurrence {uid: 'hu:activity:w20f01-capture-1'}) SET n.occurrenceType = 'Activity', n.activityKind = 'CAPTURE', n.startedAt = datetime('2026-10-03T00:00:00Z'), n.endedAt = datetime('2026-10-03T00:00:00Z'), n.methodVersion = 'w20-capture-v1', n.createdAt = datetime('2026-10-03T00:00:00Z');
MERGE (n:Activity:Occurrence {uid: 'hu:activity:w20f01-extract-1'}) SET n.occurrenceType = 'Activity', n.activityKind = 'TEXT_EXTRACTION', n.startedAt = datetime('2026-10-03T00:05:00Z'), n.endedAt = datetime('2026-10-03T00:05:00Z'), n.methodVersion = 'html-text-extract-v2', n.createdAt = datetime('2026-10-03T00:05:00Z');
MERGE (n:Activity:Occurrence {uid: 'hu:activity:w20f01-segment-g1'}) SET n.occurrenceType = 'Activity', n.activityKind = 'SEGMENTATION', n.startedAt = datetime('2026-10-03T00:10:00Z'), n.endedAt = datetime('2026-10-03T00:10:00Z'), n.methodVersion = 'w20-window-v1', n.createdAt = datetime('2026-10-03T00:10:00Z');
MERGE (n:Activity:Occurrence {uid: 'hu:activity:w20f01-segment-g2'}) SET n.occurrenceType = 'Activity', n.activityKind = 'SEGMENTATION', n.startedAt = datetime('2026-10-20T00:00:00Z'), n.endedAt = datetime('2026-10-20T00:00:00Z'), n.methodVersion = 'w20-window-v1', n.createdAt = datetime('2026-10-20T00:00:00Z');
MERGE (n:Activity:Occurrence {uid: 'hu:activity:w20f01-capture-2'}) SET n.occurrenceType = 'Activity', n.activityKind = 'CAPTURE', n.startedAt = datetime('2026-11-02T00:00:00Z'), n.endedAt = datetime('2026-11-02T00:00:00Z'), n.methodVersion = 'w20-capture-v1', n.createdAt = datetime('2026-11-02T00:00:00Z');
MERGE (n:Activity:Occurrence {uid: 'hu:activity:w20f01-extract-2'}) SET n.occurrenceType = 'Activity', n.activityKind = 'TEXT_EXTRACTION', n.startedAt = datetime('2026-11-02T00:05:00Z'), n.endedAt = datetime('2026-11-02T00:05:00Z'), n.methodVersion = 'html-text-extract-v2', n.createdAt = datetime('2026-11-02T00:05:00Z');
MERGE (n:Activity:Occurrence {uid: 'hu:activity:w20f01-segment-g3'}) SET n.occurrenceType = 'Activity', n.activityKind = 'SEGMENTATION', n.startedAt = datetime('2026-11-02T00:10:00Z'), n.endedAt = datetime('2026-11-02T00:10:00Z'), n.methodVersion = 'w20-window-v1', n.createdAt = datetime('2026-11-02T00:10:00Z');
MERGE (n:Activity:Occurrence {uid: 'hu:activity:w20f01-reanchor-1'}) SET n.occurrenceType = 'Activity', n.activityKind = 'REANCHORING', n.startedAt = datetime('2026-11-02T00:20:00Z'), n.endedAt = datetime('2026-11-02T00:20:00Z'), n.methodVersion = 'quote-reanchor-nfcws1-v1', n.createdAt = datetime('2026-11-02T00:20:00Z');
MATCH (a:Activity {uid: 'hu:activity:w20f01-segment-g1'}), (g:Agent {uid: 'hu:agent:w20-fixture-pipeline'}) MERGE (a)-[:WAS_ASSOCIATED_WITH]->(g);
// ---------- 1. Document (Source specialization), first capture, text version ----------
MERGE (d:Document:Source:Entity {uid: 'hu:document:w20f01-transcript-page'})
SET d.documentId = 'w20f01-transcript-page', d.entityType = 'Document', d.title = 'Synthetic transcript page, episode 52 (fixture only)',
    d.canonicalUri = 'https://transcripts.example.invalid/episode-52', d.url = 'https://transcripts.example.invalid/episode-52',
    d.type = 'TRANSCRIPT_PAGE', d.sourceKind = 'PODCAST_TRANSCRIPT_PAGE', d.documentKey = 'w20f01', d.documentDomain = 'NEWS_MEDIA', d.languageCode = 'en',
    d.fixtureProvenance = 'SYNTHETIC', d.privacyClass = 'PUBLIC', d.createdAt = datetime('2026-10-03T00:00:00Z'), d.updatedAt = datetime('2026-10-03T00:00:00Z');
MATCH (d:Document {uid: 'hu:document:w20f01-transcript-page'}), (act:Activity {uid: 'hu:activity:w20f01-capture-1'})
MERGE (s:SourceSnapshot:InformationArtifact {uid: 'hu:snapshot:w20f01-page-2026-10-03'})
SET s.artifactType = 'SourceSnapshot', s.canonicalUri = d.canonicalUri, s.retrievedAt = datetime('2026-10-03T00:00:00Z'), s.observedAt = datetime('2026-10-03T00:00:00Z'),
    s.contentHash = 'sha256:679755704dd94340c363a46c4b5cb726e6a3843253fd7ae5cdabb0aa04b18834', s.contentHashBasis = 'SYNTHETIC_FIXTURE', s.captureCompleteness = 'COMPLETE',
    s.publisherRevisionNotice = 'This transcript is under review (synthetic).', s.mimeType = 'text/html', s.language = 'en', s.createdAt = datetime('2026-10-03T00:00:00Z')
MERGE (d)-[:HAS_SNAPSHOT]->(s)
MERGE (s)-[:WAS_GENERATED_BY]->(act);
MATCH (d:Document {uid: 'hu:document:w20f01-transcript-page'}), (s:SourceSnapshot {uid: 'hu:snapshot:w20f01-page-2026-10-03'}), (act:Activity {uid: 'hu:activity:w20f01-extract-1'})
MERGE (tv:DocumentTextVersion:InformationArtifact {uid: 'hu:text-version:w20f01-tv1'})
SET tv.documentTextVersionId = 'w20f01-tv1', tv.artifactType = 'DocumentTextVersion', tv.versionLabel = 'html-text-extract-v2',
    tv.text = 'David Sinclair: Well, I\'m always happy to tell you what I do and what my father does. My 82 -year-old father, we take a gram of NMN every day.\nAndrew Huberman: So it\'s a gram of resveratrol and a gram of NMN.\nDavid Sinclair: Right.\nDavid Sinclair: Now another important point, which is I\'m not the same as everybody else. I have different microbiome, age, sex.\n',
    tv.textVersionHash = 'sha256:e185465a99a01244239d7dbfbe62acf840a186b36052fd2150fc742e9bec76b7', tv.contentHash = 'sha256:e185465a99a01244239d7dbfbe62acf840a186b36052fd2150fc742e9bec76b7', tv.source = 'html-text-extract', tv.normalizationVersion = NULL, tv.languageCode = 'en',
    tv.observedAt = s.observedAt, tv.createdAt = datetime('2026-10-03T00:05:00Z'), tv.updatedAt = datetime('2026-10-03T00:05:00Z')
MERGE (d)-[:HAS_TEXT_VERSION]->(tv)
MERGE (tv)-[:TEXT_OF_SNAPSHOT]->(s)
MERGE (tv)-[:WAS_GENERATED_BY]->(act);
// ---------- 2. locator (TEXT_POSITION + quote anchor), assertion, capture-fidelity adjudication ----------
MATCH (s:SourceSnapshot {uid: 'hu:snapshot:w20f01-page-2026-10-03'}), (tv:DocumentTextVersion {uid: 'hu:text-version:w20f01-tv1'})
MERGE (l:SourceLocator:InformationArtifact {uid: 'hu:locator:w20f01-l1-nmn-gram'})
SET l.artifactType = 'SourceLocator', l.uri = s.canonicalUri, l.selectorKind = 'TEXT_POSITION',
    l.exact = 'My 82 -year-old father, we take a gram of NMN every day.', l.prefix = 'and what my father does. ', l.suffix = '\nAndrew Huberman: So it',
    l.quoteHash = 'sha256:96fe6eb5c9177e4e2c18035be1bd8bfce8f7325882994ff8274de98cf4516e56', l.normalizationVersion = 'NFC-WS1', l.startOffset = 86, l.endOffset = 142,
    l.speakerLabelInSource = 'David Sinclair', l.createdAt = datetime('2026-10-03T00:30:00Z')
MERGE (s)-[:HAS_LOCATOR]->(l)
MERGE (l)-[:LOCATOR_IN_TEXT_VERSION]->(tv);
MERGE (sub:ChemicalSubstance:Entity {uid: 'hu:substance:w20f01-nmn'}) SET sub.entityType = 'ChemicalSubstance', sub.name = 'NMN (fixture stub)', sub.createdAt = datetime('2026-10-03T00:00:00Z');
MATCH (l:SourceLocator {uid: 'hu:locator:w20f01-l1-nmn-gram'}), (sub:ChemicalSubstance {uid: 'hu:substance:w20f01-nmn'}), (act:Activity {uid: 'hu:activity:w20f01-extract-1'})
MERGE (a:Assertion {uid: 'hu:assertion:w20f01-a1-nmn-gram-daily'})
SET a.predicate = 'SELF_REPORTED_DAILY_INTAKE', a.status = 'ACCEPTED', a.recordedAt = datetime('2026-10-03T01:00:00Z'), a.valueNumber = 1.0, a.unitCode = 'g',
    a.quantityBasis = 'PER_DAY', a.polarity = 'POSITIVE', a.assertionBasis = 'PERSONAL_EXPERIENCE', a.speechAct = 'REPORTS_PRACTICE',
    a.contentHash = 'sha256:fb8ed2f17fcbc00ecaaf7e08473f0395639b128b418290310818dc1e5e33cf99', a.createdAt = datetime('2026-10-03T01:00:00Z')
MERGE (a)-[:HAS_SUBJECT]->(sub)
MERGE (a)-[:SUPPORTED_BY]->(l)
MERGE (a)-[:WAS_GENERATED_BY]->(act);
MATCH (a:Assertion {uid: 'hu:assertion:w20f01-a1-nmn-gram-daily'})
MERGE (j:Adjudication:EvidenceAssessment {uid: 'hu:adjudication:w20f01-cf-a1'})
SET j.assessmentType = 'Adjudication', j.adjudicationKind = 'CAPTURE_FIDELITY', j.verdict = 'SUPPORTED', j.reviewerType = 'HUMAN', j.methodVersion = 'w20-fixture-review-v1',
    j.status = 'ACCEPTED', j.reviewedAt = datetime('2026-10-03T02:00:00Z'), j.recordedAt = datetime('2026-10-03T02:00:00Z'), j.createdAt = datetime('2026-10-03T02:00:00Z')
MERGE (j)-[:EVALUATES]->(a);
// derived document-level shortcut (live SUPPORTED_BY_DOCUMENT) naming its locator
MATCH (a:Assertion {uid: 'hu:assertion:w20f01-a1-nmn-gram-daily'}), (d:Document {uid: 'hu:document:w20f01-transcript-page'})
MERGE (a)-[r:SUPPORTED_BY_DOCUMENT]->(d)
SET r.derivationRule = 'support-via-locator-document-v1', r.derivedFromAssertionUids = ['hu:assertion:w20f01-a1-nmn-gram-daily'], r.locatorUid = 'hu:locator:w20f01-l1-nmn-gram', r.derivedAt = datetime('2026-10-03T03:00:00Z');
// ---------- 3. segmentation G1 (chunkSize 80, overlap 0) and derived links ----------;
// segmentation hu:segmentation:w20f01-g1: config {"chunkSize": 80, "methodVersion": "w20-window-v1;unit=CODE_POINT", "overlap": 0, "strategy": "fixed-window"}
MATCH (tv:DocumentTextVersion {uid: 'hu:text-version:w20f01-tv1'}), (act:Activity {uid: 'hu:activity:w20f01-segment-g1'})
MERGE (g:Segmentation:InformationArtifact {uid: 'hu:segmentation:w20f01-g1'})
SET g.segmentationId = 'w20f01-g1', g.artifactType = 'Segmentation', g.segmentationHash = 'sha256:aeb865ec0fd9d09f5e55ccbedfb420b12851690c85a089dded28605d6805237c', g.chunkSize = 80, g.overlap = 0,
    g.strategy = 'fixed-window', g.methodVersion = 'w20-window-v1;unit=CODE_POINT', g.createdAt = datetime('2026-10-03T00:10:00Z'), g.updatedAt = datetime('2026-10-03T00:10:00Z')
MERGE (tv)-[:HAS_SEGMENTATION]->(g)
MERGE (g)-[:WAS_GENERATED_BY]->(act);
MATCH (tv:DocumentTextVersion {uid: 'hu:text-version:w20f01-tv1'}), (d:Document {uid: 'hu:document:w20f01-transcript-page'})
MERGE (c:Chunk:InformationArtifact {uid: 'hu:chunk:w20f01-g1-c0'})
SET c.chunkId = 'w20f01-g1-c0', c.chunkKey = 'w20f01-g1#0', c.artifactType = 'Chunk', c.index = 0, c.text = 'David Sinclair: Well, I\'m always happy to tell you what I do and what my father ', c.segmentationHash = 'sha256:aeb865ec0fd9d09f5e55ccbedfb420b12851690c85a089dded28605d6805237c',
    c.charStart = 0, c.charEnd = 80, c.contentHash = 'sha256:0cca7a79ab3d375cbf5aa001a3e1226affcaaac8730957aa056db8c2d72a967a', c.createdAt = datetime('2026-10-03T00:10:00Z'), c.updatedAt = datetime('2026-10-03T00:10:00Z')
MERGE (c)-[:FROM_TEXT_VERSION]->(tv)
MERGE (d)-[hc:HAS_CHUNK]->(c) SET hc.derivationRule = 'chunk-of-document-text-version-v1', hc.derivedAt = datetime('2026-10-03T00:10:00Z');
MATCH (tv:DocumentTextVersion {uid: 'hu:text-version:w20f01-tv1'}), (d:Document {uid: 'hu:document:w20f01-transcript-page'})
MERGE (c:Chunk:InformationArtifact {uid: 'hu:chunk:w20f01-g1-c1'})
SET c.chunkId = 'w20f01-g1-c1', c.chunkKey = 'w20f01-g1#1', c.artifactType = 'Chunk', c.index = 1, c.text = 'does. My 82 -year-old father, we take a gram of NMN every day.\nAndrew Huberman: ', c.segmentationHash = 'sha256:aeb865ec0fd9d09f5e55ccbedfb420b12851690c85a089dded28605d6805237c',
    c.charStart = 80, c.charEnd = 160, c.contentHash = 'sha256:7f954d298613ae0af06a6dc6aec7f30a5fd07cc42b15512ae49a6d0b4fcc1a62', c.createdAt = datetime('2026-10-03T00:10:00Z'), c.updatedAt = datetime('2026-10-03T00:10:00Z')
MERGE (c)-[:FROM_TEXT_VERSION]->(tv)
MERGE (d)-[hc:HAS_CHUNK]->(c) SET hc.derivationRule = 'chunk-of-document-text-version-v1', hc.derivedAt = datetime('2026-10-03T00:10:00Z');
MATCH (tv:DocumentTextVersion {uid: 'hu:text-version:w20f01-tv1'}), (d:Document {uid: 'hu:document:w20f01-transcript-page'})
MERGE (c:Chunk:InformationArtifact {uid: 'hu:chunk:w20f01-g1-c2'})
SET c.chunkId = 'w20f01-g1-c2', c.chunkKey = 'w20f01-g1#2', c.artifactType = 'Chunk', c.index = 2, c.text = 'So it\'s a gram of resveratrol and a gram of NMN.\nDavid Sinclair: Right.\nDavid Si', c.segmentationHash = 'sha256:aeb865ec0fd9d09f5e55ccbedfb420b12851690c85a089dded28605d6805237c',
    c.charStart = 160, c.charEnd = 240, c.contentHash = 'sha256:635809849c136c5942b2fd4d152f0ed8297e4fe7f7169ef990e1a9395823038a', c.createdAt = datetime('2026-10-03T00:10:00Z'), c.updatedAt = datetime('2026-10-03T00:10:00Z')
MERGE (c)-[:FROM_TEXT_VERSION]->(tv)
MERGE (d)-[hc:HAS_CHUNK]->(c) SET hc.derivationRule = 'chunk-of-document-text-version-v1', hc.derivedAt = datetime('2026-10-03T00:10:00Z');
MATCH (tv:DocumentTextVersion {uid: 'hu:text-version:w20f01-tv1'}), (d:Document {uid: 'hu:document:w20f01-transcript-page'})
MERGE (c:Chunk:InformationArtifact {uid: 'hu:chunk:w20f01-g1-c3'})
SET c.chunkId = 'w20f01-g1-c3', c.chunkKey = 'w20f01-g1#3', c.artifactType = 'Chunk', c.index = 3, c.text = 'nclair: Now another important point, which is I\'m not the same as everybody else', c.segmentationHash = 'sha256:aeb865ec0fd9d09f5e55ccbedfb420b12851690c85a089dded28605d6805237c',
    c.charStart = 240, c.charEnd = 320, c.contentHash = 'sha256:a330bc6f6395f2c859c8d445fb22f92a15f9fea4c2a1bbef2a8d592035680def', c.createdAt = datetime('2026-10-03T00:10:00Z'), c.updatedAt = datetime('2026-10-03T00:10:00Z')
MERGE (c)-[:FROM_TEXT_VERSION]->(tv)
MERGE (d)-[hc:HAS_CHUNK]->(c) SET hc.derivationRule = 'chunk-of-document-text-version-v1', hc.derivedAt = datetime('2026-10-03T00:10:00Z');
MATCH (tv:DocumentTextVersion {uid: 'hu:text-version:w20f01-tv1'}), (d:Document {uid: 'hu:document:w20f01-transcript-page'})
MERGE (c:Chunk:InformationArtifact {uid: 'hu:chunk:w20f01-g1-c4'})
SET c.chunkId = 'w20f01-g1-c4', c.chunkKey = 'w20f01-g1#4', c.artifactType = 'Chunk', c.index = 4, c.text = '. I have different microbiome, age, sex.\n', c.segmentationHash = 'sha256:aeb865ec0fd9d09f5e55ccbedfb420b12851690c85a089dded28605d6805237c',
    c.charStart = 320, c.charEnd = 361, c.contentHash = 'sha256:0576da0fd8776fd7dccdb17582b4897018b69fc9b570882e5d9a68be6a4185e5', c.createdAt = datetime('2026-10-03T00:10:00Z'), c.updatedAt = datetime('2026-10-03T00:10:00Z')
MERGE (c)-[:FROM_TEXT_VERSION]->(tv)
MERGE (d)-[hc:HAS_CHUNK]->(c) SET hc.derivationRule = 'chunk-of-document-text-version-v1', hc.derivedAt = datetime('2026-10-03T00:10:00Z');
MATCH (a:Chunk {uid: 'hu:chunk:w20f01-g1-c0'}), (b:Chunk {uid: 'hu:chunk:w20f01-g1-c1'}) MERGE (a)-[:NEXT_CHUNK]->(b);
MATCH (a:Chunk {uid: 'hu:chunk:w20f01-g1-c1'}), (b:Chunk {uid: 'hu:chunk:w20f01-g1-c2'}) MERGE (a)-[:NEXT_CHUNK]->(b);
MATCH (a:Chunk {uid: 'hu:chunk:w20f01-g1-c2'}), (b:Chunk {uid: 'hu:chunk:w20f01-g1-c3'}) MERGE (a)-[:NEXT_CHUNK]->(b);
MATCH (a:Chunk {uid: 'hu:chunk:w20f01-g1-c3'}), (b:Chunk {uid: 'hu:chunk:w20f01-g1-c4'}) MERGE (a)-[:NEXT_CHUNK]->(b);
MATCH (l:SourceLocator {uid: 'hu:locator:w20f01-l1-nmn-gram'}), (c:Chunk {uid: 'hu:chunk:w20f01-g1-c1'})
MERGE (l)-[r:RESOLVES_TO_CHUNK]->(c)
SET r.derivationRule = 'offset-overlap-v1', r.segmentationHash = 'sha256:aeb865ec0fd9d09f5e55ccbedfb420b12851690c85a089dded28605d6805237c', r.coversWholeSpan = true, r.derivedAt = datetime('2026-10-03T00:40:00Z'), r.activityUid = 'hu:activity:w20f01-segment-g1';
MATCH (a:Assertion {uid: 'hu:assertion:w20f01-a1-nmn-gram-daily'}), (c:Chunk {uid: 'hu:chunk:w20f01-g1-c1'})
MERGE (a)-[r:SUPPORTED_BY_CHUNK]->(c)
SET r.derivationRule = 'support-via-locator-chunk-v1', r.derivedFromAssertionUids = ['hu:assertion:w20f01-a1-nmn-gram-daily'], r.locatorUid = 'hu:locator:w20f01-l1-nmn-gram', r.segmentationHash = 'sha256:aeb865ec0fd9d09f5e55ccbedfb420b12851690c85a089dded28605d6805237c', r.derivedAt = datetime('2026-10-03T00:40:00Z'), r.activityUid = 'hu:activity:w20f01-segment-g1';
// ---------- 4. RE-SEGMENTATION of the UNCHANGED capture: new Segmentation G2 (160/20), new chunks, regenerated links ----------;
// segmentation hu:segmentation:w20f01-g2: config {"chunkSize": 160, "methodVersion": "w20-window-v1;unit=CODE_POINT", "overlap": 20, "strategy": "fixed-window"}
MATCH (tv:DocumentTextVersion {uid: 'hu:text-version:w20f01-tv1'}), (act:Activity {uid: 'hu:activity:w20f01-segment-g2'})
MERGE (g:Segmentation:InformationArtifact {uid: 'hu:segmentation:w20f01-g2'})
SET g.segmentationId = 'w20f01-g2', g.artifactType = 'Segmentation', g.segmentationHash = 'sha256:ef2138d97a7bbf3be5d020fb003a6de74a92a71c9319957d170af1c6dbb1eaa6', g.chunkSize = 160, g.overlap = 20,
    g.strategy = 'fixed-window', g.methodVersion = 'w20-window-v1;unit=CODE_POINT', g.createdAt = datetime('2026-10-20T00:00:00Z'), g.updatedAt = datetime('2026-10-20T00:00:00Z')
MERGE (tv)-[:HAS_SEGMENTATION]->(g)
MERGE (g)-[:WAS_GENERATED_BY]->(act);
MATCH (tv:DocumentTextVersion {uid: 'hu:text-version:w20f01-tv1'}), (d:Document {uid: 'hu:document:w20f01-transcript-page'})
MERGE (c:Chunk:InformationArtifact {uid: 'hu:chunk:w20f01-g2-c0'})
SET c.chunkId = 'w20f01-g2-c0', c.chunkKey = 'w20f01-g2#0', c.artifactType = 'Chunk', c.index = 0, c.text = 'David Sinclair: Well, I\'m always happy to tell you what I do and what my father does. My 82 -year-old father, we take a gram of NMN every day.\nAndrew Huberman: ', c.segmentationHash = 'sha256:ef2138d97a7bbf3be5d020fb003a6de74a92a71c9319957d170af1c6dbb1eaa6',
    c.charStart = 0, c.charEnd = 160, c.contentHash = 'sha256:2f17ba1336a53354b0547a3f3e1e460e664c28fe2dbd4bc512251965eed6e1a9', c.createdAt = datetime('2026-10-20T00:00:00Z'), c.updatedAt = datetime('2026-10-20T00:00:00Z')
MERGE (c)-[:FROM_TEXT_VERSION]->(tv)
MERGE (d)-[hc:HAS_CHUNK]->(c) SET hc.derivationRule = 'chunk-of-document-text-version-v1', hc.derivedAt = datetime('2026-10-20T00:00:00Z');
MATCH (tv:DocumentTextVersion {uid: 'hu:text-version:w20f01-tv1'}), (d:Document {uid: 'hu:document:w20f01-transcript-page'})
MERGE (c:Chunk:InformationArtifact {uid: 'hu:chunk:w20f01-g2-c1'})
SET c.chunkId = 'w20f01-g2-c1', c.chunkKey = 'w20f01-g2#1', c.artifactType = 'Chunk', c.index = 1, c.text = 'y.\nAndrew Huberman: So it\'s a gram of resveratrol and a gram of NMN.\nDavid Sinclair: Right.\nDavid Sinclair: Now another important point, which is I\'m not the sa', c.segmentationHash = 'sha256:ef2138d97a7bbf3be5d020fb003a6de74a92a71c9319957d170af1c6dbb1eaa6',
    c.charStart = 140, c.charEnd = 300, c.contentHash = 'sha256:c47c73a69271059949e1989c2baf8a476cdc5ec236a688fa3ff0b88e903993ca', c.createdAt = datetime('2026-10-20T00:00:00Z'), c.updatedAt = datetime('2026-10-20T00:00:00Z')
MERGE (c)-[:FROM_TEXT_VERSION]->(tv)
MERGE (d)-[hc:HAS_CHUNK]->(c) SET hc.derivationRule = 'chunk-of-document-text-version-v1', hc.derivedAt = datetime('2026-10-20T00:00:00Z');
MATCH (tv:DocumentTextVersion {uid: 'hu:text-version:w20f01-tv1'}), (d:Document {uid: 'hu:document:w20f01-transcript-page'})
MERGE (c:Chunk:InformationArtifact {uid: 'hu:chunk:w20f01-g2-c2'})
SET c.chunkId = 'w20f01-g2-c2', c.chunkKey = 'w20f01-g2#2', c.artifactType = 'Chunk', c.index = 2, c.text = 'ch is I\'m not the same as everybody else. I have different microbiome, age, sex.\n', c.segmentationHash = 'sha256:ef2138d97a7bbf3be5d020fb003a6de74a92a71c9319957d170af1c6dbb1eaa6',
    c.charStart = 280, c.charEnd = 361, c.contentHash = 'sha256:3c1c74b33cedbf0d0766b035435b895d136de9f2d3a1e634e7f391127efac336', c.createdAt = datetime('2026-10-20T00:00:00Z'), c.updatedAt = datetime('2026-10-20T00:00:00Z')
MERGE (c)-[:FROM_TEXT_VERSION]->(tv)
MERGE (d)-[hc:HAS_CHUNK]->(c) SET hc.derivationRule = 'chunk-of-document-text-version-v1', hc.derivedAt = datetime('2026-10-20T00:00:00Z');
MATCH (a:Chunk {uid: 'hu:chunk:w20f01-g2-c0'}), (b:Chunk {uid: 'hu:chunk:w20f01-g2-c1'}) MERGE (a)-[:NEXT_CHUNK]->(b);
MATCH (a:Chunk {uid: 'hu:chunk:w20f01-g2-c1'}), (b:Chunk {uid: 'hu:chunk:w20f01-g2-c2'}) MERGE (a)-[:NEXT_CHUNK]->(b);
MATCH (l:SourceLocator {uid: 'hu:locator:w20f01-l1-nmn-gram'}), (c:Chunk {uid: 'hu:chunk:w20f01-g2-c0'})
MERGE (l)-[r:RESOLVES_TO_CHUNK]->(c)
SET r.derivationRule = 'offset-overlap-v1', r.segmentationHash = 'sha256:ef2138d97a7bbf3be5d020fb003a6de74a92a71c9319957d170af1c6dbb1eaa6', r.coversWholeSpan = true, r.derivedAt = datetime('2026-10-20T00:05:00Z'), r.activityUid = 'hu:activity:w20f01-segment-g2';
MATCH (a:Assertion {uid: 'hu:assertion:w20f01-a1-nmn-gram-daily'}), (c:Chunk {uid: 'hu:chunk:w20f01-g2-c0'})
MERGE (a)-[r:SUPPORTED_BY_CHUNK]->(c)
SET r.derivationRule = 'support-via-locator-chunk-v1', r.derivedFromAssertionUids = ['hu:assertion:w20f01-a1-nmn-gram-daily'], r.locatorUid = 'hu:locator:w20f01-l1-nmn-gram', r.segmentationHash = 'sha256:ef2138d97a7bbf3be5d020fb003a6de74a92a71c9319957d170af1c6dbb1eaa6', r.derivedAt = datetime('2026-10-20T00:05:00Z'), r.activityUid = 'hu:activity:w20f01-segment-g2';
MATCH (l:SourceLocator {uid: 'hu:locator:w20f01-l1-nmn-gram'}), (c:Chunk {uid: 'hu:chunk:w20f01-g2-c1'})
MERGE (l)-[r:RESOLVES_TO_CHUNK]->(c)
SET r.derivationRule = 'offset-overlap-v1', r.segmentationHash = 'sha256:ef2138d97a7bbf3be5d020fb003a6de74a92a71c9319957d170af1c6dbb1eaa6', r.coversWholeSpan = false, r.derivedAt = datetime('2026-10-20T00:05:00Z'), r.activityUid = 'hu:activity:w20f01-segment-g2';
MATCH (a:Assertion {uid: 'hu:assertion:w20f01-a1-nmn-gram-daily'}), (c:Chunk {uid: 'hu:chunk:w20f01-g2-c1'})
MERGE (a)-[r:SUPPORTED_BY_CHUNK]->(c)
SET r.derivationRule = 'support-via-locator-chunk-v1', r.derivedFromAssertionUids = ['hu:assertion:w20f01-a1-nmn-gram-daily'], r.locatorUid = 'hu:locator:w20f01-l1-nmn-gram', r.segmentationHash = 'sha256:ef2138d97a7bbf3be5d020fb003a6de74a92a71c9319957d170af1c6dbb1eaa6', r.derivedAt = datetime('2026-10-20T00:05:00Z'), r.activityUid = 'hu:activity:w20f01-segment-g2';
// retire G1: derived chunks and their derived edges are deleted; the locator, snapshot, text version and assertion are untouched
MATCH (c:Chunk) WHERE c.segmentationHash = 'sha256:aeb865ec0fd9d09f5e55ccbedfb420b12851690c85a089dded28605d6805237c' AND EXISTS { MATCH (c)-[:FROM_TEXT_VERSION]->(:DocumentTextVersion {uid: 'hu:text-version:w20f01-tv1'}) } DETACH DELETE c;
MATCH (g:Segmentation {uid: 'hu:segmentation:w20f01-g1'}) DETACH DELETE g;
// ---------- 5. CORRECTED capture: new snapshot, new text version, new locator REANCHORS the old one ----------;
MATCH (d:Document {uid: 'hu:document:w20f01-transcript-page'}), (act:Activity {uid: 'hu:activity:w20f01-capture-2'})
MERGE (s:SourceSnapshot:InformationArtifact {uid: 'hu:snapshot:w20f01-page-2026-11-02'})
SET s.artifactType = 'SourceSnapshot', s.canonicalUri = d.canonicalUri, s.retrievedAt = datetime('2026-11-02T00:00:00Z'), s.observedAt = datetime('2026-11-02T00:00:00Z'),
    s.contentHash = 'sha256:d6e39b8a93ea90b37124200fd1e85c31ba418291259722025eaa29a3b08cdbc5', s.contentHashBasis = 'SYNTHETIC_FIXTURE', s.captureCompleteness = 'COMPLETE',
    s.publisherRevisionNotice = NULL, s.mimeType = 'text/html', s.language = 'en', s.createdAt = datetime('2026-11-02T00:00:00Z')
MERGE (d)-[:HAS_SNAPSHOT]->(s)
MERGE (s)-[:WAS_GENERATED_BY]->(act);
MATCH (d:Document {uid: 'hu:document:w20f01-transcript-page'}), (s:SourceSnapshot {uid: 'hu:snapshot:w20f01-page-2026-11-02'}), (act:Activity {uid: 'hu:activity:w20f01-extract-2'})
MERGE (tv:DocumentTextVersion:InformationArtifact {uid: 'hu:text-version:w20f01-tv2'})
SET tv.documentTextVersionId = 'w20f01-tv2', tv.artifactType = 'DocumentTextVersion', tv.versionLabel = 'html-text-extract-v2',
    tv.text = 'David Sinclair: Well, I\'m always happy to tell you what I do and what my father does. My 82-year-old father, we take a gram of NMN every day.\nAndrew Huberman: So it\'s a gram of resveratrol and a gram of NMN.\nDavid Sinclair: Right.\nDavid Sinclair: Now another important point, which is I\'m not the same as everybody else. I have different microbiome, age, sex.\n',
    tv.textVersionHash = 'sha256:3f3899a5f97a4853ff189884c9951099dd6807bd3d3b4c74a0982be3218b0058', tv.contentHash = 'sha256:3f3899a5f97a4853ff189884c9951099dd6807bd3d3b4c74a0982be3218b0058', tv.source = 'html-text-extract', tv.languageCode = 'en',
    tv.observedAt = s.observedAt, tv.createdAt = datetime('2026-11-02T00:05:00Z'), tv.updatedAt = datetime('2026-11-02T00:05:00Z')
MERGE (d)-[:HAS_TEXT_VERSION]->(tv)
MERGE (tv)-[:TEXT_OF_SNAPSHOT]->(s)
MERGE (tv)-[:WAS_GENERATED_BY]->(act);
MATCH (s:SourceSnapshot {uid: 'hu:snapshot:w20f01-page-2026-11-02'}), (tv:DocumentTextVersion {uid: 'hu:text-version:w20f01-tv2'}), (act:Activity {uid: 'hu:activity:w20f01-reanchor-1'})
MERGE (l:SourceLocator:InformationArtifact {uid: 'hu:locator:w20f01-l2-nmn-gram-reanchored'})
SET l.artifactType = 'SourceLocator', l.uri = s.canonicalUri, l.selectorKind = 'TEXT_POSITION',
    l.exact = 'My 82-year-old father, we take a gram of NMN every day.', l.prefix = 'and what my father does. ', l.suffix = '\nAndrew Huberman: So it',
    l.quoteHash = 'sha256:050569ee00d1ec26a66248376413b4218a7c30d3f08b947b2e16f8c5ed983e8e', l.normalizationVersion = 'NFC-WS1', l.startOffset = 86, l.endOffset = 141,
    l.speakerLabelInSource = 'David Sinclair', l.createdAt = datetime('2026-11-02T00:20:00Z')
MERGE (s)-[:HAS_LOCATOR]->(l)
MERGE (l)-[:LOCATOR_IN_TEXT_VERSION]->(tv)
MERGE (l)-[:WAS_GENERATED_BY]->(act);
MATCH (newL:SourceLocator {uid: 'hu:locator:w20f01-l2-nmn-gram-reanchored'}), (oldL:SourceLocator {uid: 'hu:locator:w20f01-l1-nmn-gram'})
MERGE (newL)-[x:REANCHORS]->(oldL) SET x.anchorMatch = 'FUZZY', x.activityUid = 'hu:activity:w20f01-reanchor-1';
// segmentation of the corrected text with the SAME configuration as G2: same segmentationHash, different chunks;
// segmentation hu:segmentation:w20f01-g3: config {"chunkSize": 160, "methodVersion": "w20-window-v1;unit=CODE_POINT", "overlap": 20, "strategy": "fixed-window"}
MATCH (tv:DocumentTextVersion {uid: 'hu:text-version:w20f01-tv2'}), (act:Activity {uid: 'hu:activity:w20f01-segment-g3'})
MERGE (g:Segmentation:InformationArtifact {uid: 'hu:segmentation:w20f01-g3'})
SET g.segmentationId = 'w20f01-g3', g.artifactType = 'Segmentation', g.segmentationHash = 'sha256:ef2138d97a7bbf3be5d020fb003a6de74a92a71c9319957d170af1c6dbb1eaa6', g.chunkSize = 160, g.overlap = 20,
    g.strategy = 'fixed-window', g.methodVersion = 'w20-window-v1;unit=CODE_POINT', g.createdAt = datetime('2026-11-02T00:10:00Z'), g.updatedAt = datetime('2026-11-02T00:10:00Z')
MERGE (tv)-[:HAS_SEGMENTATION]->(g)
MERGE (g)-[:WAS_GENERATED_BY]->(act);
MATCH (tv:DocumentTextVersion {uid: 'hu:text-version:w20f01-tv2'}), (d:Document {uid: 'hu:document:w20f01-transcript-page'})
MERGE (c:Chunk:InformationArtifact {uid: 'hu:chunk:w20f01-g3-c0'})
SET c.chunkId = 'w20f01-g3-c0', c.chunkKey = 'w20f01-g3#0', c.artifactType = 'Chunk', c.index = 0, c.text = 'David Sinclair: Well, I\'m always happy to tell you what I do and what my father does. My 82-year-old father, we take a gram of NMN every day.\nAndrew Huberman: S', c.segmentationHash = 'sha256:ef2138d97a7bbf3be5d020fb003a6de74a92a71c9319957d170af1c6dbb1eaa6',
    c.charStart = 0, c.charEnd = 160, c.contentHash = 'sha256:07f6347c6629b6c4af7c79aa73ac9f10b0531786787bc520019d654cf50433b0', c.createdAt = datetime('2026-11-02T00:10:00Z'), c.updatedAt = datetime('2026-11-02T00:10:00Z')
MERGE (c)-[:FROM_TEXT_VERSION]->(tv)
MERGE (d)-[hc:HAS_CHUNK]->(c) SET hc.derivationRule = 'chunk-of-document-text-version-v1', hc.derivedAt = datetime('2026-11-02T00:10:00Z');
MATCH (tv:DocumentTextVersion {uid: 'hu:text-version:w20f01-tv2'}), (d:Document {uid: 'hu:document:w20f01-transcript-page'})
MERGE (c:Chunk:InformationArtifact {uid: 'hu:chunk:w20f01-g3-c1'})
SET c.chunkId = 'w20f01-g3-c1', c.chunkKey = 'w20f01-g3#1', c.artifactType = 'Chunk', c.index = 1, c.text = '.\nAndrew Huberman: So it\'s a gram of resveratrol and a gram of NMN.\nDavid Sinclair: Right.\nDavid Sinclair: Now another important point, which is I\'m not the sam', c.segmentationHash = 'sha256:ef2138d97a7bbf3be5d020fb003a6de74a92a71c9319957d170af1c6dbb1eaa6',
    c.charStart = 140, c.charEnd = 300, c.contentHash = 'sha256:6c7937523874d29bf6bae25158d915a81b4adbdbafa91d425a08f9723cf82818', c.createdAt = datetime('2026-11-02T00:10:00Z'), c.updatedAt = datetime('2026-11-02T00:10:00Z')
MERGE (c)-[:FROM_TEXT_VERSION]->(tv)
MERGE (d)-[hc:HAS_CHUNK]->(c) SET hc.derivationRule = 'chunk-of-document-text-version-v1', hc.derivedAt = datetime('2026-11-02T00:10:00Z');
MATCH (tv:DocumentTextVersion {uid: 'hu:text-version:w20f01-tv2'}), (d:Document {uid: 'hu:document:w20f01-transcript-page'})
MERGE (c:Chunk:InformationArtifact {uid: 'hu:chunk:w20f01-g3-c2'})
SET c.chunkId = 'w20f01-g3-c2', c.chunkKey = 'w20f01-g3#2', c.artifactType = 'Chunk', c.index = 2, c.text = 'h is I\'m not the same as everybody else. I have different microbiome, age, sex.\n', c.segmentationHash = 'sha256:ef2138d97a7bbf3be5d020fb003a6de74a92a71c9319957d170af1c6dbb1eaa6',
    c.charStart = 280, c.charEnd = 360, c.contentHash = 'sha256:ec0b84ef160c5765482fad2ebfff0aa9d4bb1690fc51b7353d2c21b592939ce5', c.createdAt = datetime('2026-11-02T00:10:00Z'), c.updatedAt = datetime('2026-11-02T00:10:00Z')
MERGE (c)-[:FROM_TEXT_VERSION]->(tv)
MERGE (d)-[hc:HAS_CHUNK]->(c) SET hc.derivationRule = 'chunk-of-document-text-version-v1', hc.derivedAt = datetime('2026-11-02T00:10:00Z');
MATCH (a:Chunk {uid: 'hu:chunk:w20f01-g3-c0'}), (b:Chunk {uid: 'hu:chunk:w20f01-g3-c1'}) MERGE (a)-[:NEXT_CHUNK]->(b);
MATCH (a:Chunk {uid: 'hu:chunk:w20f01-g3-c1'}), (b:Chunk {uid: 'hu:chunk:w20f01-g3-c2'}) MERGE (a)-[:NEXT_CHUNK]->(b);
MATCH (l:SourceLocator {uid: 'hu:locator:w20f01-l2-nmn-gram-reanchored'}), (c:Chunk {uid: 'hu:chunk:w20f01-g3-c0'})
MERGE (l)-[r:RESOLVES_TO_CHUNK]->(c)
SET r.derivationRule = 'offset-overlap-v1', r.segmentationHash = 'sha256:ef2138d97a7bbf3be5d020fb003a6de74a92a71c9319957d170af1c6dbb1eaa6', r.coversWholeSpan = true, r.derivedAt = datetime('2026-11-02T00:25:00Z'), r.activityUid = 'hu:activity:w20f01-reanchor-1';
MATCH (l:SourceLocator {uid: 'hu:locator:w20f01-l2-nmn-gram-reanchored'}), (c:Chunk {uid: 'hu:chunk:w20f01-g3-c1'})
MERGE (l)-[r:RESOLVES_TO_CHUNK]->(c)
SET r.derivationRule = 'offset-overlap-v1', r.segmentationHash = 'sha256:ef2138d97a7bbf3be5d020fb003a6de74a92a71c9319957d170af1c6dbb1eaa6', r.coversWholeSpan = false, r.derivedAt = datetime('2026-11-02T00:25:00Z'), r.activityUid = 'hu:activity:w20f01-reanchor-1';
// NOTE: no SUPPORTED_BY_CHUNK from A1 into the corrected text version: A1 is SUPPORTED_BY L1 only; whether a re-anchored locator
// joins an assertion's support is a W00 rule (W20-SR-06). The path chunk <- L2 -REANCHORS-> L1 <- A1 is the answer route.
