// W20 fixture 04: real text-version pairs (NEW_RETRIEVAL 2026-10-04). Snapshots hash the STORED EXCERPT TEXT actually returned by the tools
// (contentHashBasis STORED_EXCERPT_TEXT, captureCompleteness PARTIAL_EXCERPT); '\n[...]\n' joins two returned passages and is part of the stored text.
// NiCE trial (PMID 38871717, PMCID PMC11176364, DOI 10.1038/s41467-024-49092-5): PMC HTML vs PubMed-connector JATS-derived text vs publisher PDF text.
// Huberman Lab 52: publisher transcript page vs YouTube transcript cues. No audio was heard; neither text is verified against audio.
// Generated by gen04.py. Every statement binds its own nodes by uid.
MERGE (n:Agent:Entity {uid: 'hu:agent:tavily-extract'}) SET n.entityType = 'Agent', n.name = 'Tavily extract API', n.agentKind = 'AUTOMATED_AGENT', n.toolVersion = 'unknown', n.createdAt = datetime('2026-10-04T01:05:00Z');
MERGE (n:Agent:Entity {uid: 'hu:agent:pubmed-mcp'}) SET n.entityType = 'Agent', n.name = 'PubMed MCP connector', n.agentKind = 'AUTOMATED_AGENT', n.toolVersion = 'unknown', n.createdAt = datetime('2026-10-04T01:05:00Z');
MERGE (n:Agent:Entity {uid: 'hu:agent:firecrawl-pdf'}) SET n.entityType = 'Agent', n.name = 'Firecrawl scrape (pdf parser)', n.agentKind = 'AUTOMATED_AGENT', n.toolVersion = 'unknown', n.createdAt = datetime('2026-10-04T01:05:00Z');
MERGE (n:Activity:Occurrence {uid: 'hu:activity:w20f04-capture-tavily'}) SET n.occurrenceType = 'Activity', n.activityKind = 'CAPTURE', n.startedAt = datetime('2026-10-04T00:56:00Z'), n.methodVersion = 'unknown', n.externalRunSystem = 'w20-session', n.createdAt = datetime('2026-10-04T01:05:00Z');
MATCH (a:Activity {uid: 'hu:activity:w20f04-capture-tavily'}), (g:Agent {uid: 'hu:agent:tavily-extract'}) MERGE (a)-[:WAS_ASSOCIATED_WITH]->(g);
MERGE (n:Activity:Occurrence {uid: 'hu:activity:w20f04-extract-tavily'}) SET n.occurrenceType = 'Activity', n.activityKind = 'TEXT_EXTRACTION', n.startedAt = datetime('2026-10-04T00:56:00Z'), n.methodVersion = 'unknown', n.externalRunSystem = 'w20-session', n.createdAt = datetime('2026-10-04T01:05:00Z');
MATCH (a:Activity {uid: 'hu:activity:w20f04-extract-tavily'}), (g:Agent {uid: 'hu:agent:tavily-extract'}) MERGE (a)-[:WAS_ASSOCIATED_WITH]->(g);
MERGE (n:Activity:Occurrence {uid: 'hu:activity:w20f04-capture-pubmed-mcp'}) SET n.occurrenceType = 'Activity', n.activityKind = 'CAPTURE', n.startedAt = datetime('2026-10-04T00:56:00Z'), n.methodVersion = 'unknown', n.externalRunSystem = 'w20-session', n.createdAt = datetime('2026-10-04T01:05:00Z');
MATCH (a:Activity {uid: 'hu:activity:w20f04-capture-pubmed-mcp'}), (g:Agent {uid: 'hu:agent:pubmed-mcp'}) MERGE (a)-[:WAS_ASSOCIATED_WITH]->(g);
MERGE (n:Activity:Occurrence {uid: 'hu:activity:w20f04-extract-pubmed-mcp'}) SET n.occurrenceType = 'Activity', n.activityKind = 'TEXT_EXTRACTION', n.startedAt = datetime('2026-10-04T00:56:00Z'), n.methodVersion = 'unknown', n.externalRunSystem = 'w20-session', n.createdAt = datetime('2026-10-04T01:05:00Z');
MATCH (a:Activity {uid: 'hu:activity:w20f04-extract-pubmed-mcp'}), (g:Agent {uid: 'hu:agent:pubmed-mcp'}) MERGE (a)-[:WAS_ASSOCIATED_WITH]->(g);
MERGE (n:Activity:Occurrence {uid: 'hu:activity:w20f04-capture-firecrawl'}) SET n.occurrenceType = 'Activity', n.activityKind = 'CAPTURE', n.startedAt = datetime('2026-10-04T00:56:00Z'), n.methodVersion = 'unknown', n.externalRunSystem = 'w20-session', n.createdAt = datetime('2026-10-04T01:05:00Z');
MATCH (a:Activity {uid: 'hu:activity:w20f04-capture-firecrawl'}), (g:Agent {uid: 'hu:agent:firecrawl-pdf'}) MERGE (a)-[:WAS_ASSOCIATED_WITH]->(g);
MERGE (n:Activity:Occurrence {uid: 'hu:activity:w20f04-extract-firecrawl'}) SET n.occurrenceType = 'Activity', n.activityKind = 'TEXT_EXTRACTION', n.startedAt = datetime('2026-10-04T00:56:00Z'), n.methodVersion = 'unknown', n.externalRunSystem = 'w20-session', n.createdAt = datetime('2026-10-04T01:05:00Z');
MATCH (a:Activity {uid: 'hu:activity:w20f04-extract-firecrawl'}), (g:Agent {uid: 'hu:agent:firecrawl-pdf'}) MERGE (a)-[:WAS_ASSOCIATED_WITH]->(g);
MERGE (p:Publication:InformationArtifact {uid: 'hu:publication:nice-trial-2024-ncomms'}) SET p.artifactType = 'Publication', p.name = 'Nicotinamide riboside for peripheral artery disease: the NICE randomized clinical trial', p.publishedAt = datetime('2024-06-13T00:00:00Z'), p.createdAt = datetime('2026-10-04T01:05:00Z');
MERGE (e:Episode:Entity {uid: 'hu:episode:huberman-lab-52-sinclair'}) SET e.entityType = 'Episode', e.name = 'Huberman Lab 52: Dr. David Sinclair', e.createdAt = datetime('2026-10-04T01:05:00Z');
MERGE (d:Document:Source:Entity {uid: 'hu:document:pmc-pmc11176364-html'})
SET d.documentId = 'pmc-pmc11176364-html', d.entityType = 'Document', d.title = 'Nicotinamide riboside for peripheral artery disease: the NICE randomized clinical trial (PMC article page)', d.canonicalUri = 'https://pmc.ncbi.nlm.nih.gov/articles/PMC11176364/', d.url = 'https://pmc.ncbi.nlm.nih.gov/articles/PMC11176364/',
    d.type = 'SCIENTIFIC_ARTICLE', d.sourceKind = 'PEER_REVIEWED_PUBLICATION', d.fileFormat = 'text/html', d.languageCode = 'en', d.privacyClass = 'PUBLIC', d.createdAt = datetime('2026-10-04T01:05:00Z'), d.updatedAt = datetime('2026-10-04T01:05:00Z');
MATCH (d:Document {uid: 'hu:document:pmc-pmc11176364-html'}), (w:Publication {uid: 'hu:publication:nice-trial-2024-ncomms'}) MERGE (d)-[:RENDITION_OF]->(w);
MATCH (d:Document {uid: 'hu:document:pmc-pmc11176364-html'}), (act:Activity {uid: 'hu:activity:w20f04-capture-tavily'})
MERGE (s:SourceSnapshot:InformationArtifact {uid: 'hu:snapshot:pmc11176364-html-tavily-2026-10-04'})
SET s.artifactType = 'SourceSnapshot', s.canonicalUri = d.canonicalUri, s.retrievedAt = datetime('2026-10-04T00:58:00Z'), s.observedAt = datetime('2026-10-04T00:58:00Z'),
    s.contentHash = 'sha256:5c2913056613f2bbd9c81b617287182cdb9eb4188b1d249880c4294c7a7ae79a', s.contentHashBasis = 'STORED_EXCERPT_TEXT', s.captureCompleteness = 'PARTIAL_EXCERPT', s.mimeType = 'text/plain', s.language = 'en', s.createdAt = datetime('2026-10-04T01:05:00Z')
MERGE (d)-[:HAS_SNAPSHOT]->(s)
MERGE (s)-[:WAS_GENERATED_BY]->(act);
MATCH (d:Document {uid: 'hu:document:pmc-pmc11176364-html'}), (s:SourceSnapshot {uid: 'hu:snapshot:pmc11176364-html-tavily-2026-10-04'}), (act:Activity {uid: 'hu:activity:w20f04-extract-tavily'})
MERGE (tv:DocumentTextVersion:InformationArtifact {uid: 'hu:text-version:pmc11176364-html-tavily-2026-10-04'})
SET tv.documentTextVersionId = 'pmc11176364-html-tavily-2026-10-04', tv.artifactType = 'DocumentTextVersion', tv.versionLabel = 'pmc-html-tavily-extract-text', tv.source = 'tavily-extract (advanced, text)',
    tv.text = 'Resveratrol, a naturally occurring polyphenol, may increase SIRT1 affinity for NAD+17. Therefore, the NICotinamidE riboside with and without resveratrol to improve functioning in PAD (NICE) clinical trial tested the hypotheses that NR alone improves 6-min walk distance, compared to placebo, and that NR + resveratrol improves 6-min walk distance, compared to placebo, in people with PAD.\nHere we show that NR meaningfully improves 6-min walk, and resveratrol does not add benefit to NR alone in PAD.\n[...]\nPrimary outcomes\nCompared to placebo, NR improved 6-min walk by 17.6 meters (90% CI: + 1.77, +∞, P = 0.08) at 6-month follow-up, meeting the pre-specified criterion for statistical significance (Table 2 and Fig. 2A).',
    tv.textVersionHash = 'sha256:5c2913056613f2bbd9c81b617287182cdb9eb4188b1d249880c4294c7a7ae79a', tv.contentHash = 'sha256:5c2913056613f2bbd9c81b617287182cdb9eb4188b1d249880c4294c7a7ae79a', tv.languageCode = 'en', tv.observedAt = s.observedAt, tv.createdAt = datetime('2026-10-04T01:05:00Z'), tv.updatedAt = datetime('2026-10-04T01:05:00Z')
MERGE (d)-[:HAS_TEXT_VERSION]->(tv)
MERGE (tv)-[:TEXT_OF_SNAPSHOT]->(s)
MERGE (tv)-[:WAS_GENERATED_BY]->(act);
MATCH (s:SourceSnapshot {uid: 'hu:snapshot:pmc11176364-html-tavily-2026-10-04'}), (tv:DocumentTextVersion {uid: 'hu:text-version:pmc11176364-html-tavily-2026-10-04'})
MERGE (l:SourceLocator:InformationArtifact {uid: 'hu:locator:pmc11176364-html-tavily-2026-10-04-q1'})
SET l.artifactType = 'SourceLocator', l.uri = s.canonicalUri, l.selectorKind = 'TEXT_POSITION',
    l.exact = 'Compared to placebo, NR improved 6-min walk by 17.6 meters (90% CI: + 1.77, +∞, P = 0.08) at 6-month follow-up, meeting the pre-specified criterion for statistical significance (Table 2 and Fig. 2A).', l.quoteHash = 'sha256:52bb34c1208737e2d8690bdfab53c21267cd8cd442ab430ce659021abc9af2ff', l.normalizationVersion = 'NFC-WS1', l.startOffset = 524, l.endOffset = 723, l.createdAt = datetime('2026-10-04T01:05:00Z')
MERGE (s)-[:HAS_LOCATOR]->(l)
MERGE (l)-[:LOCATOR_IN_TEXT_VERSION]->(tv);
MERGE (d:Document:Source:Entity {uid: 'hu:document:pmc-pmc11176364-fulltext-connector'})
SET d.documentId = 'pmc-pmc11176364-fulltext-connector', d.entityType = 'Document', d.title = 'Nicotinamide riboside for peripheral artery disease: the NICE randomized clinical trial (PMC full text via PubMed connector)', d.canonicalUri = 'mcp:pubmed/get_full_text_article/PMC11176364', d.url = 'mcp:pubmed/get_full_text_article/PMC11176364',
    d.type = 'SCIENTIFIC_ARTICLE', d.sourceKind = 'PEER_REVIEWED_PUBLICATION', d.fileFormat = 'application/json', d.languageCode = 'en', d.privacyClass = 'PUBLIC', d.createdAt = datetime('2026-10-04T01:05:00Z'), d.updatedAt = datetime('2026-10-04T01:05:00Z');
MATCH (d:Document {uid: 'hu:document:pmc-pmc11176364-fulltext-connector'}), (w:Publication {uid: 'hu:publication:nice-trial-2024-ncomms'}) MERGE (d)-[:RENDITION_OF]->(w);
MATCH (d:Document {uid: 'hu:document:pmc-pmc11176364-fulltext-connector'}), (act:Activity {uid: 'hu:activity:w20f04-capture-pubmed-mcp'})
MERGE (s:SourceSnapshot:InformationArtifact {uid: 'hu:snapshot:pmc11176364-connector-2026-10-04'})
SET s.artifactType = 'SourceSnapshot', s.canonicalUri = d.canonicalUri, s.retrievedAt = datetime('2026-10-04T00:57:00Z'), s.observedAt = datetime('2026-10-04T00:57:00Z'),
    s.contentHash = 'sha256:7c5f199c49668f3e22e330ed1474370b7212da99d21baa7c3ad68f7ef41ae6eb', s.contentHashBasis = 'STORED_EXCERPT_TEXT', s.captureCompleteness = 'PARTIAL_EXCERPT', s.mimeType = 'text/plain', s.language = 'en', s.createdAt = datetime('2026-10-04T01:05:00Z')
MERGE (d)-[:HAS_SNAPSHOT]->(s)
MERGE (s)-[:WAS_GENERATED_BY]->(act);
MATCH (d:Document {uid: 'hu:document:pmc-pmc11176364-fulltext-connector'}), (s:SourceSnapshot {uid: 'hu:snapshot:pmc11176364-connector-2026-10-04'}), (act:Activity {uid: 'hu:activity:w20f04-extract-pubmed-mcp'})
MERGE (tv:DocumentTextVersion:InformationArtifact {uid: 'hu:text-version:pmc11176364-connector-fulltext-2026-10-04'})
SET tv.documentTextVersionId = 'pmc11176364-connector-fulltext-2026-10-04', tv.artifactType = 'DocumentTextVersion', tv.versionLabel = 'pmc-jats-derived-text-pubmed-mcp', tv.source = 'pubmed-mcp get_full_text_article (JATS-derived plain text; converter version not disclosed)',
    tv.text = 'Resveratrol, a naturally occurring polyphenol, may increase SIRT1 affinity for NAD+. Therefore, theotinamidriboside with and without resveratrol to improve functioning in PAD () clinical trial tested the hypotheses that NR alone improves 6-min walk distance, compared to placebo, and that NR + resveratrol improves 6-min walk distance, compared to placebo, in people with PAD.\n\nHere we show that NR meaningfully improves 6-min walk, and resveratrol does not add benefit to NR alone in PAD.\n[...]\nPrimary outcomes\n\nCompared to placebo, NR improved 6-min walk by 17.6 meters (90% CI: + 1.77, +∞,= 0.08) at 6-month follow-up, meeting the pre-specified criterion for statistical significance (Tableand Fig.).',
    tv.textVersionHash = 'sha256:7c5f199c49668f3e22e330ed1474370b7212da99d21baa7c3ad68f7ef41ae6eb', tv.contentHash = 'sha256:7c5f199c49668f3e22e330ed1474370b7212da99d21baa7c3ad68f7ef41ae6eb', tv.languageCode = 'en', tv.observedAt = s.observedAt, tv.createdAt = datetime('2026-10-04T01:05:00Z'), tv.updatedAt = datetime('2026-10-04T01:05:00Z')
MERGE (d)-[:HAS_TEXT_VERSION]->(tv)
MERGE (tv)-[:TEXT_OF_SNAPSHOT]->(s)
MERGE (tv)-[:WAS_GENERATED_BY]->(act);
MATCH (s:SourceSnapshot {uid: 'hu:snapshot:pmc11176364-connector-2026-10-04'}), (tv:DocumentTextVersion {uid: 'hu:text-version:pmc11176364-connector-fulltext-2026-10-04'})
MERGE (l:SourceLocator:InformationArtifact {uid: 'hu:locator:pmc11176364-connector-fulltext-2026-10-04-q1'})
SET l.artifactType = 'SourceLocator', l.uri = s.canonicalUri, l.selectorKind = 'TEXT_POSITION',
    l.exact = 'Compared to placebo, NR improved 6-min walk by 17.6 meters (90% CI: + 1.77, +∞,= 0.08) at 6-month follow-up, meeting the pre-specified criterion for statistical significance (Tableand Fig.).', l.quoteHash = 'sha256:1b2ef40c745c9598681a3132913c9e3e332891533d33b276f27f0131860e5bd1', l.normalizationVersion = 'NFC-WS1', l.startOffset = 514, l.endOffset = 704, l.createdAt = datetime('2026-10-04T01:05:00Z')
MERGE (s)-[:HAS_LOCATOR]->(l)
MERGE (l)-[:LOCATOR_IN_TEXT_VERSION]->(tv);
MERGE (d:Document:Source:Entity {uid: 'hu:document:nature-s41467-024-49092-5-pdf'})
SET d.documentId = 'nature-s41467-024-49092-5-pdf', d.entityType = 'Document', d.title = 'Nicotinamide riboside for peripheral artery disease: the NICE randomized clinical trial (publisher PDF)', d.canonicalUri = 'https://www.nature.com/articles/s41467-024-49092-5.pdf', d.url = 'https://www.nature.com/articles/s41467-024-49092-5.pdf',
    d.type = 'SCIENTIFIC_ARTICLE', d.sourceKind = 'PEER_REVIEWED_PUBLICATION', d.fileFormat = 'application/pdf', d.languageCode = 'en', d.privacyClass = 'PUBLIC', d.createdAt = datetime('2026-10-04T01:05:00Z'), d.updatedAt = datetime('2026-10-04T01:05:00Z');
MATCH (d:Document {uid: 'hu:document:nature-s41467-024-49092-5-pdf'}), (w:Publication {uid: 'hu:publication:nice-trial-2024-ncomms'}) MERGE (d)-[:RENDITION_OF]->(w);
MATCH (d:Document {uid: 'hu:document:nature-s41467-024-49092-5-pdf'}), (act:Activity {uid: 'hu:activity:w20f04-capture-firecrawl'})
MERGE (s:SourceSnapshot:InformationArtifact {uid: 'hu:snapshot:nature-49092-pdf-firecrawl-2026-10-04'})
SET s.artifactType = 'SourceSnapshot', s.canonicalUri = d.canonicalUri, s.retrievedAt = datetime('2026-10-04T01:00:00Z'), s.observedAt = datetime('2026-10-04T01:00:00Z'),
    s.contentHash = 'sha256:5b69af5bd28b3d3f05bd2672ea206febf59226c53df069931b811fba2c92eaae', s.contentHashBasis = 'STORED_EXCERPT_TEXT', s.captureCompleteness = 'PARTIAL_EXCERPT', s.mimeType = 'text/plain', s.language = 'en', s.createdAt = datetime('2026-10-04T01:05:00Z')
MERGE (d)-[:HAS_SNAPSHOT]->(s)
MERGE (s)-[:WAS_GENERATED_BY]->(act);
MATCH (d:Document {uid: 'hu:document:nature-s41467-024-49092-5-pdf'}), (s:SourceSnapshot {uid: 'hu:snapshot:nature-49092-pdf-firecrawl-2026-10-04'}), (act:Activity {uid: 'hu:activity:w20f04-extract-firecrawl'})
MERGE (tv:DocumentTextVersion:InformationArtifact {uid: 'hu:text-version:nature-49092-pdf-firecrawl-md-2026-10-04'})
SET tv.documentTextVersionId = 'nature-49092-pdf-firecrawl-md-2026-10-04', tv.artifactType = 'DocumentTextVersion', tv.versionLabel = 'pdf-firecrawl-markdown-pages-1-3', tv.source = 'firecrawl pdf parser (markdown; parser version not disclosed)',
    tv.text = 'Resveratrol, a naturally occurring polyphenol, may increase SIRT1\naffinity for NAD+<sup>17</sup>. Therefore, the NICotinamidE riboside with and\nwithout resveratrol to improve functioning in PAD (NICE) clinical trial\ntested the hypotheses that NR alone improves 6-min walk distance,\ncompared to placebo, and that NR + resveratrol improves 6-min walk\ndistance, compared to placebo, in people with PAD.\n\nHere we show that NR meaningfully improves 6-min walk, and\nresveratrol does not add benefit toNR aloneinPAD.\n[...]\n### Primary outcomes\n\nCompared to placebo, NR improved 6-min walk by 17.6 meters (90%\nCI: + 1.77, +∞, P = 0.08) at 6-month follow-up, meeting the pre-specified\ncriterion for statistical significance (Table 2 and Fig. 2A).',
    tv.textVersionHash = 'sha256:5b69af5bd28b3d3f05bd2672ea206febf59226c53df069931b811fba2c92eaae', tv.contentHash = 'sha256:5b69af5bd28b3d3f05bd2672ea206febf59226c53df069931b811fba2c92eaae', tv.languageCode = 'en', tv.observedAt = s.observedAt, tv.createdAt = datetime('2026-10-04T01:05:00Z'), tv.updatedAt = datetime('2026-10-04T01:05:00Z')
MERGE (d)-[:HAS_TEXT_VERSION]->(tv)
MERGE (tv)-[:TEXT_OF_SNAPSHOT]->(s)
MERGE (tv)-[:WAS_GENERATED_BY]->(act);
MATCH (s:SourceSnapshot {uid: 'hu:snapshot:nature-49092-pdf-firecrawl-2026-10-04'}), (tv:DocumentTextVersion {uid: 'hu:text-version:nature-49092-pdf-firecrawl-md-2026-10-04'})
MERGE (l:SourceLocator:InformationArtifact {uid: 'hu:locator:nature-49092-pdf-firecrawl-md-2026-10-04-q1'})
SET l.artifactType = 'SourceLocator', l.uri = s.canonicalUri, l.selectorKind = 'TEXT_POSITION',
    l.exact = 'Compared to placebo, NR improved 6-min walk by 17.6 meters (90%\nCI: + 1.77, +∞, P = 0.08) at 6-month follow-up, meeting the pre-specified\ncriterion for statistical significance (Table 2 and Fig. 2A).', l.quoteHash = 'sha256:52bb34c1208737e2d8690bdfab53c21267cd8cd442ab430ce659021abc9af2ff', l.normalizationVersion = 'NFC-WS1', l.startOffset = 538, l.endOffset = 737, l.createdAt = datetime('2026-10-04T01:05:00Z')
MERGE (s)-[:HAS_LOCATOR]->(l)
MERGE (l)-[:LOCATOR_IN_TEXT_VERSION]->(tv);
MERGE (d:Document:Source:Entity {uid: 'hu:document:hubermanlab-com-episode-52-page'})
SET d.documentId = 'hubermanlab-com-episode-52-page', d.entityType = 'Document', d.title = 'Dr. David Sinclair: The Biology of Slowing & Reversing Aging', d.canonicalUri = 'https://www.hubermanlab.com/episode/dr-david-sinclair-the-biology-of-slowing-and-reversing-aging', d.url = 'https://www.hubermanlab.com/episode/dr-david-sinclair-the-biology-of-slowing-and-reversing-aging',
    d.type = 'TRANSCRIPT_PAGE', d.sourceKind = 'PODCAST_TRANSCRIPT_PAGE', d.fileFormat = 'text/html', d.languageCode = 'en', d.privacyClass = 'PUBLIC', d.createdAt = datetime('2026-10-04T01:05:00Z'), d.updatedAt = datetime('2026-10-04T01:05:00Z');
MATCH (d:Document {uid: 'hu:document:hubermanlab-com-episode-52-page'}), (w:Episode {uid: 'hu:episode:huberman-lab-52-sinclair'}) MERGE (d)-[:RENDITION_OF]->(w);
MATCH (d:Document {uid: 'hu:document:hubermanlab-com-episode-52-page'}), (act:Activity {uid: 'hu:activity:w20f04-capture-tavily'})
MERGE (s:SourceSnapshot:InformationArtifact {uid: 'hu:snapshot:hubermanlab-52-page-tavily-2026-10-04'})
SET s.artifactType = 'SourceSnapshot', s.canonicalUri = d.canonicalUri, s.retrievedAt = datetime('2026-10-04T01:02:00Z'), s.observedAt = datetime('2026-10-04T01:02:00Z'),
    s.contentHash = 'sha256:54f15992eab487f104503a219f39d8ad293ac31d067414db387f84674f238b66', s.contentHashBasis = 'STORED_EXCERPT_TEXT', s.captureCompleteness = 'PARTIAL_EXCERPT', s.mimeType = 'text/plain', s.language = 'en', s.createdAt = datetime('2026-10-04T01:05:00Z')
MERGE (d)-[:HAS_SNAPSHOT]->(s)
MERGE (s)-[:WAS_GENERATED_BY]->(act);
MATCH (d:Document {uid: 'hu:document:hubermanlab-com-episode-52-page'}), (s:SourceSnapshot {uid: 'hu:snapshot:hubermanlab-52-page-tavily-2026-10-04'}), (act:Activity {uid: 'hu:activity:w20f04-extract-tavily'})
MERGE (tv:DocumentTextVersion:InformationArtifact {uid: 'hu:text-version:hubermanlab-52-page-tavily-2026-10-04'})
SET tv.documentTextVersionId = 'hubermanlab-52-page-tavily-2026-10-04', tv.artifactType = 'DocumentTextVersion', tv.versionLabel = 'publisher-transcript-page-tavily-text', tv.source = 'tavily-extract (basic, text)',
    tv.text = 'David Sinclair:\nWell, I\'m always happy to tell you what I do and what my father does. My 82 -year-old father, we take a gram of NMN every day.\nAndrew Huberman:\nSo it\'s a gram of resveratrol and a gram of NMN.\nDavid Sinclair:\nRight.\nAndrew Huberman:\nOkay. A thousand milligrams.\nDavid Sinclair:\nNow another important point, which is I\'m not the same as everybody else. I have different microbiome, age, sex.',
    tv.textVersionHash = 'sha256:54f15992eab487f104503a219f39d8ad293ac31d067414db387f84674f238b66', tv.contentHash = 'sha256:54f15992eab487f104503a219f39d8ad293ac31d067414db387f84674f238b66', tv.languageCode = 'en', tv.observedAt = s.observedAt, tv.createdAt = datetime('2026-10-04T01:05:00Z'), tv.updatedAt = datetime('2026-10-04T01:05:00Z')
MERGE (d)-[:HAS_TEXT_VERSION]->(tv)
MERGE (tv)-[:TEXT_OF_SNAPSHOT]->(s)
MERGE (tv)-[:WAS_GENERATED_BY]->(act);
MATCH (s:SourceSnapshot {uid: 'hu:snapshot:hubermanlab-52-page-tavily-2026-10-04'}), (tv:DocumentTextVersion {uid: 'hu:text-version:hubermanlab-52-page-tavily-2026-10-04'})
MERGE (l:SourceLocator:InformationArtifact {uid: 'hu:locator:hubermanlab-52-page-tavily-2026-10-04-q1'})
SET l.artifactType = 'SourceLocator', l.uri = s.canonicalUri, l.selectorKind = 'TEXT_POSITION',
    l.exact = 'My 82 -year-old father, we take a gram of NMN every day.', l.quoteHash = 'sha256:96fe6eb5c9177e4e2c18035be1bd8bfce8f7325882994ff8274de98cf4516e56', l.normalizationVersion = 'NFC-WS1', l.startOffset = 86, l.endOffset = 142, l.createdAt = datetime('2026-10-04T01:05:00Z')
MERGE (s)-[:HAS_LOCATOR]->(l)
MERGE (l)-[:LOCATOR_IN_TEXT_VERSION]->(tv);
MERGE (d:Document:Source:Entity {uid: 'hu:document:youtube-n9IxomBusuw-watch-page'})
SET d.documentId = 'youtube-n9IxomBusuw-watch-page', d.entityType = 'Document', d.title = 'The Biology of Slowing & Reversing Aging | Dr. David Sinclair', d.canonicalUri = 'https://www.youtube.com/watch?v=n9IxomBusuw', d.url = 'https://www.youtube.com/watch?v=n9IxomBusuw',
    d.type = 'VIDEO_PAGE', d.sourceKind = 'VIDEO_RENDITION', d.fileFormat = 'text/html', d.languageCode = 'en', d.privacyClass = 'PUBLIC', d.createdAt = datetime('2026-10-04T01:05:00Z'), d.updatedAt = datetime('2026-10-04T01:05:00Z');
MATCH (d:Document {uid: 'hu:document:youtube-n9IxomBusuw-watch-page'}), (w:Episode {uid: 'hu:episode:huberman-lab-52-sinclair'}) MERGE (d)-[:RENDITION_OF]->(w);
MATCH (d:Document {uid: 'hu:document:youtube-n9IxomBusuw-watch-page'}), (act:Activity {uid: 'hu:activity:w20f04-capture-tavily'})
MERGE (s:SourceSnapshot:InformationArtifact {uid: 'hu:snapshot:youtube-n9IxomBusuw-tavily-2026-10-04'})
SET s.artifactType = 'SourceSnapshot', s.canonicalUri = d.canonicalUri, s.retrievedAt = datetime('2026-10-04T01:02:30Z'), s.observedAt = datetime('2026-10-04T01:02:30Z'),
    s.contentHash = 'sha256:a08c3d013f94807f8f4700f5e2dda28db5b9c6b02a98196464f9ada8a536e699', s.contentHashBasis = 'STORED_EXCERPT_TEXT', s.captureCompleteness = 'PARTIAL_EXCERPT', s.mimeType = 'text/plain', s.language = 'en', s.createdAt = datetime('2026-10-04T01:05:00Z')
MERGE (d)-[:HAS_SNAPSHOT]->(s)
MERGE (s)-[:WAS_GENERATED_BY]->(act);
MATCH (d:Document {uid: 'hu:document:youtube-n9IxomBusuw-watch-page'}), (s:SourceSnapshot {uid: 'hu:snapshot:youtube-n9IxomBusuw-tavily-2026-10-04'}), (act:Activity {uid: 'hu:activity:w20f04-extract-tavily'})
MERGE (tv:DocumentTextVersion:InformationArtifact {uid: 'hu:text-version:youtube-n9IxomBusuw-transcript-tavily-2026-10-04'})
SET tv.documentTextVersionId = 'youtube-n9IxomBusuw-transcript-tavily-2026-10-04', tv.artifactType = 'DocumentTextVersion', tv.versionLabel = 'youtube-transcript-cues-tavily-text (caption track origin unknown)', tv.source = 'tavily-extract (advanced, text) of the rendered transcript; auto-generated vs uploaded track NOT established',
    tv.text = '[1:02:45] - Well, I\'m always happy to tell you what I do and what my father does, my 82-year-old father, we take a gram of NMN every day.\n[1:02:53] - So it\'s a gram resveratrol and a gram of NMN. - Right. - Okay a thousand milligrams.\n[1:02:58] - Now another important point, which is, I\'m not the same as everybody else.\n[1:03:04] I have a different microbiome, age, sex, right?',
    tv.textVersionHash = 'sha256:a08c3d013f94807f8f4700f5e2dda28db5b9c6b02a98196464f9ada8a536e699', tv.contentHash = 'sha256:a08c3d013f94807f8f4700f5e2dda28db5b9c6b02a98196464f9ada8a536e699', tv.languageCode = 'en', tv.observedAt = s.observedAt, tv.createdAt = datetime('2026-10-04T01:05:00Z'), tv.updatedAt = datetime('2026-10-04T01:05:00Z')
MERGE (d)-[:HAS_TEXT_VERSION]->(tv)
MERGE (tv)-[:TEXT_OF_SNAPSHOT]->(s)
MERGE (tv)-[:WAS_GENERATED_BY]->(act);
MATCH (s:SourceSnapshot {uid: 'hu:snapshot:youtube-n9IxomBusuw-tavily-2026-10-04'}), (tv:DocumentTextVersion {uid: 'hu:text-version:youtube-n9IxomBusuw-transcript-tavily-2026-10-04'})
MERGE (l:SourceLocator:InformationArtifact {uid: 'hu:locator:youtube-n9IxomBusuw-transcript-tavily-2026-10-04-q1'})
SET l.artifactType = 'SourceLocator', l.uri = 'https://www.youtube.com/watch?v=n9IxomBusuw&t=3765s', l.selectorKind = 'MEDIA_TIME',
    l.exact = 'my 82-year-old father, we take a gram of NMN every day.', l.quoteHash = 'sha256:c00f9f5c27e17d455016fad171042e91aa60bac6993e04764af024e7f4ab9e20', l.normalizationVersion = 'NFC-WS1',
    l.mediaStartSeconds = 3765.0, l.mediaEndSeconds = 3773.0, l.mediaTimeBasis = 'RENDITION_TRANSCRIPT_CUE', l.createdAt = datetime('2026-10-04T01:05:00Z')
MERGE (s)-[:HAS_LOCATOR]->(l);
