// Generated by gen-params.mjs from the final SDL: every primary label carries the labels its @node declares (one archetype per node).
// V-F5-LBL-Source
MATCH (n:Source) WHERE NOT (n:Entity) RETURN 'V-F5-LBL' AS check, 'Source' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-SourceSnapshot
MATCH (n:SourceSnapshot) WHERE NOT (n:InformationArtifact) RETURN 'V-F5-LBL' AS check, 'SourceSnapshot' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-SourceLocator
MATCH (n:SourceLocator) WHERE NOT (n:InformationArtifact) RETURN 'V-F5-LBL' AS check, 'SourceLocator' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-SourceRevisionEvent
MATCH (n:SourceRevisionEvent) WHERE NOT (n:Occurrence) RETURN 'V-F5-LBL' AS check, 'SourceRevisionEvent' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-Adjudication
MATCH (n:Adjudication) WHERE NOT (n:EvidenceAssessment) RETURN 'V-F5-LBL' AS check, 'Adjudication' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-ResolutionHypothesis
MATCH (n:ResolutionHypothesis) WHERE NOT (n:EvidenceAssessment) RETURN 'V-F5-LBL' AS check, 'ResolutionHypothesis' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-Agent
MATCH (n:Agent) WHERE NOT (n:Entity) RETURN 'V-F5-LBL' AS check, 'Agent' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-Activity
MATCH (n:Activity) WHERE NOT (n:Occurrence) RETURN 'V-F5-LBL' AS check, 'Activity' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-Identifier
MATCH (n:Identifier) WHERE NOT (n:Entity) RETURN 'V-F5-LBL' AS check, 'Identifier' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-TradeItemIdentifier
MATCH (n:TradeItemIdentifier) WHERE NOT (n:Identifier AND n:Entity) RETURN 'V-F5-LBL' AS check, 'TradeItemIdentifier' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-Mention
MATCH (n:Mention) WHERE NOT (n:InformationArtifact) RETURN 'V-F5-LBL' AS check, 'Mention' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-EquivalenceAssessment
MATCH (n:EquivalenceAssessment) WHERE NOT (n:EvidenceAssessment) RETURN 'V-F5-LBL' AS check, 'EquivalenceAssessment' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-Organization
MATCH (n:Organization) WHERE NOT (n:Entity) RETURN 'V-F5-LBL' AS check, 'Organization' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-LegalEntity
MATCH (n:LegalEntity) WHERE NOT (n:Organization AND n:Entity) RETURN 'V-F5-LBL' AS check, 'LegalEntity' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-ConsumerBrand
MATCH (n:ConsumerBrand) WHERE NOT (n:Entity) RETURN 'V-F5-LBL' AS check, 'ConsumerBrand' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-Facility
MATCH (n:Facility) WHERE NOT (n:Entity) RETURN 'V-F5-LBL' AS check, 'Facility' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-OrganizationSnapshot
MATCH (n:OrganizationSnapshot) WHERE NOT (n:VersionedState) RETURN 'V-F5-LBL' AS check, 'OrganizationSnapshot' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-Person
MATCH (n:Person) WHERE NOT (n:Entity) RETURN 'V-F5-LBL' AS check, 'Person' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-PseudonymousActor
MATCH (n:PseudonymousActor) WHERE NOT (n:Entity) RETURN 'V-F5-LBL' AS check, 'PseudonymousActor' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-AnonymousActor
MATCH (n:AnonymousActor) WHERE NOT (n:Entity) RETURN 'V-F5-LBL' AS check, 'AnonymousActor' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-CohortParticipant
MATCH (n:CohortParticipant) WHERE NOT (n:PseudonymousActor AND n:Entity) RETURN 'V-F5-LBL' AS check, 'CohortParticipant' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-IngredientMaterial
MATCH (n:IngredientMaterial) WHERE NOT (n:Entity) RETURN 'V-F5-LBL' AS check, 'IngredientMaterial' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-BrandedIngredientMaterial
MATCH (n:BrandedIngredientMaterial) WHERE NOT (n:IngredientMaterial AND n:Entity) RETURN 'V-F5-LBL' AS check, 'BrandedIngredientMaterial' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-BotanicalPreparation
MATCH (n:BotanicalPreparation) WHERE NOT (n:IngredientMaterial AND n:Entity) RETURN 'V-F5-LBL' AS check, 'BotanicalPreparation' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-MicrobialPreparation
MATCH (n:MicrobialPreparation) WHERE NOT (n:IngredientMaterial AND n:Entity) RETURN 'V-F5-LBL' AS check, 'MicrobialPreparation' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-MaterialMixture
MATCH (n:MaterialMixture) WHERE NOT (n:IngredientMaterial AND n:Entity) RETURN 'V-F5-LBL' AS check, 'MaterialMixture' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-ChemicalSubstance
MATCH (n:ChemicalSubstance) WHERE NOT (n:Entity) RETURN 'V-F5-LBL' AS check, 'ChemicalSubstance' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-ChemicalForm
MATCH (n:ChemicalForm) WHERE NOT (n:Entity) RETURN 'V-F5-LBL' AS check, 'ChemicalForm' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-BotanicalTaxon
MATCH (n:BotanicalTaxon) WHERE NOT (n:Entity) RETURN 'V-F5-LBL' AS check, 'BotanicalTaxon' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-MicrobialTaxon
MATCH (n:MicrobialTaxon) WHERE NOT (n:Entity) RETURN 'V-F5-LBL' AS check, 'MicrobialTaxon' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-MicrobialStrain
MATCH (n:MicrobialStrain) WHERE NOT (n:Entity) RETURN 'V-F5-LBL' AS check, 'MicrobialStrain' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-Constituent
MATCH (n:Constituent) WHERE NOT (n:Entity) RETURN 'V-F5-LBL' AS check, 'Constituent' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-Nutrient
MATCH (n:Nutrient) WHERE NOT (n:Entity) RETURN 'V-F5-LBL' AS check, 'Nutrient' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-MechanismEvidenceContext
MATCH (n:MechanismEvidenceContext) WHERE NOT (n:Occurrence) RETURN 'V-F5-LBL' AS check, 'MechanismEvidenceContext' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-Mechanism
MATCH (n:Mechanism) WHERE NOT (n:Entity) RETURN 'V-F5-LBL' AS check, 'Mechanism' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-Pathway
MATCH (n:Pathway) WHERE NOT (n:Entity) RETURN 'V-F5-LBL' AS check, 'Pathway' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-MolecularEntity
MATCH (n:MolecularEntity) WHERE NOT (n:Entity) RETURN 'V-F5-LBL' AS check, 'MolecularEntity' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-Species
MATCH (n:Species) WHERE NOT (n:Entity) RETURN 'V-F5-LBL' AS check, 'Species' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-AnatomicalContext
MATCH (n:AnatomicalContext) WHERE NOT (n:Entity) RETURN 'V-F5-LBL' AS check, 'AnatomicalContext' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-Organ
MATCH (n:Organ) WHERE NOT (n:AnatomicalContext AND n:Entity) RETURN 'V-F5-LBL' AS check, 'Organ' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-Outcome
MATCH (n:Outcome) WHERE NOT (n:Entity) RETURN 'V-F5-LBL' AS check, 'Outcome' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-Condition
MATCH (n:Condition) WHERE NOT (n:Entity) RETURN 'V-F5-LBL' AS check, 'Condition' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-RiskFactor
MATCH (n:RiskFactor) WHERE NOT (n:Entity) RETURN 'V-F5-LBL' AS check, 'RiskFactor' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-Product
MATCH (n:Product) WHERE NOT (n:Entity) RETURN 'V-F5-LBL' AS check, 'Product' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-ProductVariant
MATCH (n:ProductVariant) WHERE NOT (n:Entity) RETURN 'V-F5-LBL' AS check, 'ProductVariant' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-PackageConfiguration
MATCH (n:PackageConfiguration) WHERE NOT (n:VersionedState) RETURN 'V-F5-LBL' AS check, 'PackageConfiguration' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-ProductSnapshot
MATCH (n:ProductSnapshot) WHERE NOT (n:VersionedState) RETURN 'V-F5-LBL' AS check, 'ProductSnapshot' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-FormulationVersion
MATCH (n:FormulationVersion) WHERE NOT (n:VersionedState) RETURN 'V-F5-LBL' AS check, 'FormulationVersion' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-IngredientComponent
MATCH (n:IngredientComponent) WHERE NOT (n:VersionedState) RETURN 'V-F5-LBL' AS check, 'IngredientComponent' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-LabelSnapshot
MATCH (n:LabelSnapshot) WHERE NOT (n:SourceSnapshot AND n:InformationArtifact) RETURN 'V-F5-LBL' AS check, 'LabelSnapshot' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-LabelDeclaration
MATCH (n:LabelDeclaration) WHERE NOT (n:InformationArtifact) RETURN 'V-F5-LBL' AS check, 'LabelDeclaration' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-QuantityDeclaration
MATCH (n:QuantityDeclaration) WHERE NOT (n:InformationArtifact) RETURN 'V-F5-LBL' AS check, 'QuantityDeclaration' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-ServingDefinition
MATCH (n:ServingDefinition) WHERE NOT (n:VersionedState) RETURN 'V-F5-LBL' AS check, 'ServingDefinition' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-FoodItem
MATCH (n:FoodItem) WHERE NOT (n:IngredientMaterial AND n:Entity) RETURN 'V-F5-LBL' AS check, 'FoodItem' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-Exposure
MATCH (n:Exposure) WHERE NOT (n:Entity) RETURN 'V-F5-LBL' AS check, 'Exposure' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-Lifestyle
MATCH (n:Lifestyle) WHERE NOT (n:Entity) RETURN 'V-F5-LBL' AS check, 'Lifestyle' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-Treatment
MATCH (n:Treatment) WHERE NOT (n:Entity) RETURN 'V-F5-LBL' AS check, 'Treatment' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-Procedure
MATCH (n:Procedure) WHERE NOT (n:Entity) RETURN 'V-F5-LBL' AS check, 'Procedure' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-Biomarker
MATCH (n:Biomarker) WHERE NOT (n:Entity) RETURN 'V-F5-LBL' AS check, 'Biomarker' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-Metric
MATCH (n:Metric) WHERE NOT (n:Entity) RETURN 'V-F5-LBL' AS check, 'Metric' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-LabTest
MATCH (n:LabTest) WHERE NOT (n:Entity) RETURN 'V-F5-LBL' AS check, 'LabTest' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-PanelDefinition
MATCH (n:PanelDefinition) WHERE NOT (n:VersionedState) RETURN 'V-F5-LBL' AS check, 'PanelDefinition' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-MeasurementMethod
MATCH (n:MeasurementMethod) WHERE NOT (n:Entity) RETURN 'V-F5-LBL' AS check, 'MeasurementMethod' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-Specimen
MATCH (n:Specimen) WHERE NOT (n:Entity) RETURN 'V-F5-LBL' AS check, 'Specimen' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-ReferenceSystem
MATCH (n:ReferenceSystem) WHERE NOT (n:Entity) RETURN 'V-F5-LBL' AS check, 'ReferenceSystem' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-Algorithm
MATCH (n:Algorithm) WHERE NOT (n:Entity) RETURN 'V-F5-LBL' AS check, 'Algorithm' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-AssayVersion
MATCH (n:AssayVersion) WHERE NOT (n:VersionedState) RETURN 'V-F5-LBL' AS check, 'AssayVersion' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-AlgorithmVersion
MATCH (n:AlgorithmVersion) WHERE NOT (n:VersionedState) RETURN 'V-F5-LBL' AS check, 'AlgorithmVersion' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-ReferenceIntervalVersion
MATCH (n:ReferenceIntervalVersion) WHERE NOT (n:VersionedState) RETURN 'V-F5-LBL' AS check, 'ReferenceIntervalVersion' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-ComparabilityAssessment
MATCH (n:ComparabilityAssessment) WHERE NOT (n:EvidenceAssessment) RETURN 'V-F5-LBL' AS check, 'ComparabilityAssessment' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-ReferenceRange
MATCH (n:ReferenceRange) WHERE NOT (n:InformationArtifact) RETURN 'V-F5-LBL' AS check, 'ReferenceRange' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-TechnologyPlatform
MATCH (n:TechnologyPlatform) WHERE NOT (n:Entity) RETURN 'V-F5-LBL' AS check, 'TechnologyPlatform' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-ToolOrInstrument
MATCH (n:ToolOrInstrument) WHERE NOT (n:Entity) RETURN 'V-F5-LBL' AS check, 'ToolOrInstrument' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-Device
MATCH (n:Device) WHERE NOT (n:Entity) RETURN 'V-F5-LBL' AS check, 'Device' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-Modality
MATCH (n:Modality) WHERE NOT (n:Entity) RETURN 'V-F5-LBL' AS check, 'Modality' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-Sensor
MATCH (n:Sensor) WHERE NOT (n:Entity) RETURN 'V-F5-LBL' AS check, 'Sensor' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-FirmwareVersion
MATCH (n:FirmwareVersion) WHERE NOT (n:VersionedState) RETURN 'V-F5-LBL' AS check, 'FirmwareVersion' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-Study
MATCH (n:Study) WHERE NOT (n:Entity) RETURN 'V-F5-LBL' AS check, 'Study' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-TrialRegistration
MATCH (n:TrialRegistration) WHERE NOT (n:Entity) RETURN 'V-F5-LBL' AS check, 'TrialRegistration' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-RegistrationVersion
MATCH (n:RegistrationVersion) WHERE NOT (n:InformationArtifact) RETURN 'V-F5-LBL' AS check, 'RegistrationVersion' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-ProtocolVersion
MATCH (n:ProtocolVersion) WHERE NOT (n:InformationArtifact) RETURN 'V-F5-LBL' AS check, 'ProtocolVersion' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-StudyArm
MATCH (n:StudyArm) WHERE NOT (n:VersionedState) RETURN 'V-F5-LBL' AS check, 'StudyArm' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-StudyIntervention
MATCH (n:StudyIntervention) WHERE NOT (n:VersionedState) RETURN 'V-F5-LBL' AS check, 'StudyIntervention' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-InterventionComponent
MATCH (n:InterventionComponent) WHERE NOT (n:VersionedState) RETURN 'V-F5-LBL' AS check, 'InterventionComponent' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-StudyPopulation
MATCH (n:StudyPopulation) WHERE NOT (n:VersionedState) RETURN 'V-F5-LBL' AS check, 'StudyPopulation' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-OutcomeDefinition
MATCH (n:OutcomeDefinition) WHERE NOT (n:VersionedState) RETURN 'V-F5-LBL' AS check, 'OutcomeDefinition' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-StudyResult
MATCH (n:StudyResult) WHERE NOT (n:InformationArtifact) RETURN 'V-F5-LBL' AS check, 'StudyResult' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-AdverseEventResult
MATCH (n:AdverseEventResult) WHERE NOT (n:StudyResult AND n:InformationArtifact) RETURN 'V-F5-LBL' AS check, 'AdverseEventResult' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-Publication
MATCH (n:Publication) WHERE NOT (n:InformationArtifact) RETURN 'V-F5-LBL' AS check, 'Publication' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-Dataset
MATCH (n:Dataset) WHERE NOT (n:Entity) RETURN 'V-F5-LBL' AS check, 'Dataset' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-EvidenceApplicability
MATCH (n:EvidenceApplicability) WHERE NOT (n:EvidenceAssessment) RETURN 'V-F5-LBL' AS check, 'EvidenceApplicability' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-ApplicabilityDimension
MATCH (n:ApplicabilityDimension) WHERE NOT (n:EvidenceAssessment) RETURN 'V-F5-LBL' AS check, 'ApplicabilityDimension' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-UseContextProfile
MATCH (n:UseContextProfile) WHERE NOT (n:Entity) RETURN 'V-F5-LBL' AS check, 'UseContextProfile' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-EndpointClassification
MATCH (n:EndpointClassification) WHERE NOT (n:EvidenceAssessment) RETURN 'V-F5-LBL' AS check, 'EndpointClassification' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-ResultInterpretation
MATCH (n:ResultInterpretation) WHERE NOT (n:EvidenceAssessment) RETURN 'V-F5-LBL' AS check, 'ResultInterpretation' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-EvidenceSynthesis
MATCH (n:EvidenceSynthesis) WHERE NOT (n:EvidenceAssessment) RETURN 'V-F5-LBL' AS check, 'EvidenceSynthesis' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-EvidenceStrengthAssessment
MATCH (n:EvidenceStrengthAssessment) WHERE NOT (n:EvidenceAssessment) RETURN 'V-F5-LBL' AS check, 'EvidenceStrengthAssessment' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-ManufacturingSpecification
MATCH (n:ManufacturingSpecification) WHERE NOT (n:Entity) RETURN 'V-F5-LBL' AS check, 'ManufacturingSpecification' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-SpecificationVersion
MATCH (n:SpecificationVersion) WHERE NOT (n:VersionedState) RETURN 'V-F5-LBL' AS check, 'SpecificationVersion' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-ManufacturingProcess
MATCH (n:ManufacturingProcess) WHERE NOT (n:Entity) RETURN 'V-F5-LBL' AS check, 'ManufacturingProcess' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-ManufacturingStep
MATCH (n:ManufacturingStep) WHERE NOT (n:Entity) RETURN 'V-F5-LBL' AS check, 'ManufacturingStep' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-ManufacturingCapability
MATCH (n:ManufacturingCapability) WHERE NOT (n:VersionedState) RETURN 'V-F5-LBL' AS check, 'ManufacturingCapability' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-ProductLot
MATCH (n:ProductLot) WHERE NOT (n:Entity) RETURN 'V-F5-LBL' AS check, 'ProductLot' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-TestSample
MATCH (n:TestSample) WHERE NOT (n:Entity) RETURN 'V-F5-LBL' AS check, 'TestSample' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-TestExecution
MATCH (n:TestExecution) WHERE NOT (n:Occurrence) RETURN 'V-F5-LBL' AS check, 'TestExecution' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-TestMethod
MATCH (n:TestMethod) WHERE NOT (n:Entity) RETURN 'V-F5-LBL' AS check, 'TestMethod' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-TestingLaboratory
MATCH (n:TestingLaboratory) WHERE NOT (n:Organization AND n:Entity) RETURN 'V-F5-LBL' AS check, 'TestingLaboratory' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-MeasuredResult
MATCH (n:MeasuredResult) WHERE NOT (n:InformationArtifact) RETURN 'V-F5-LBL' AS check, 'MeasuredResult' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-SpecificationCriterion
MATCH (n:SpecificationCriterion) WHERE NOT (n:VersionedState) RETURN 'V-F5-LBL' AS check, 'SpecificationCriterion' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-PassFailInterpretation
MATCH (n:PassFailInterpretation) WHERE NOT (n:EvidenceAssessment) RETURN 'V-F5-LBL' AS check, 'PassFailInterpretation' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-LotTestSummary
MATCH (n:LotTestSummary) WHERE NOT (n:InformationArtifact) RETURN 'V-F5-LBL' AS check, 'LotTestSummary' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-CertificateOfAnalysis
MATCH (n:CertificateOfAnalysis) WHERE NOT (n:InformationArtifact) RETURN 'V-F5-LBL' AS check, 'CertificateOfAnalysis' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-CertificationProgram
MATCH (n:CertificationProgram) WHERE NOT (n:Entity) RETURN 'V-F5-LBL' AS check, 'CertificationProgram' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-CertificationListing
MATCH (n:CertificationListing) WHERE NOT (n:VersionedState) RETURN 'V-F5-LBL' AS check, 'CertificationListing' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-CertificationScope
MATCH (n:CertificationScope) WHERE NOT (n:VersionedState) RETURN 'V-F5-LBL' AS check, 'CertificationScope' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-RegulatoryAgency
MATCH (n:RegulatoryAgency) WHERE NOT (n:Organization AND n:Entity) RETURN 'V-F5-LBL' AS check, 'RegulatoryAgency' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-RegulatoryPathway
MATCH (n:RegulatoryPathway) WHERE NOT (n:Entity) RETURN 'V-F5-LBL' AS check, 'RegulatoryPathway' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-RegulatoryPathwayVersion
MATCH (n:RegulatoryPathwayVersion) WHERE NOT (n:VersionedState) RETURN 'V-F5-LBL' AS check, 'RegulatoryPathwayVersion' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-RegulatoryStep
MATCH (n:RegulatoryStep) WHERE NOT (n:Entity) RETURN 'V-F5-LBL' AS check, 'RegulatoryStep' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-RegulatorySubmission
MATCH (n:RegulatorySubmission) WHERE NOT (n:InformationArtifact) RETURN 'V-F5-LBL' AS check, 'RegulatorySubmission' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-RegulatoryResponse
MATCH (n:RegulatoryResponse) WHERE NOT (n:InformationArtifact) RETURN 'V-F5-LBL' AS check, 'RegulatoryResponse' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-RegulatoryStatus
MATCH (n:RegulatoryStatus) WHERE NOT (n:VersionedState) RETURN 'V-F5-LBL' AS check, 'RegulatoryStatus' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-OrphanDesignation
MATCH (n:OrphanDesignation) WHERE NOT (n:RegulatoryStatus AND n:VersionedState) RETURN 'V-F5-LBL' AS check, 'OrphanDesignation' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-DrugApproval
MATCH (n:DrugApproval) WHERE NOT (n:RegulatoryStatus AND n:VersionedState) RETURN 'V-F5-LBL' AS check, 'DrugApproval' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-RegulatoryInspection
MATCH (n:RegulatoryInspection) WHERE NOT (n:Occurrence) RETURN 'V-F5-LBL' AS check, 'RegulatoryInspection' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-PatentFamily
MATCH (n:PatentFamily) WHERE NOT (n:Entity) RETURN 'V-F5-LBL' AS check, 'PatentFamily' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-Trademark
MATCH (n:Trademark) WHERE NOT (n:Entity) RETURN 'V-F5-LBL' AS check, 'Trademark' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-PatentApplication
MATCH (n:PatentApplication) WHERE NOT (n:InformationArtifact) RETURN 'V-F5-LBL' AS check, 'PatentApplication' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-GrantedPatent
MATCH (n:GrantedPatent) WHERE NOT (n:InformationArtifact) RETURN 'V-F5-LBL' AS check, 'GrantedPatent' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-PatentClaim
MATCH (n:PatentClaim) WHERE NOT (n:InformationArtifact) RETURN 'V-F5-LBL' AS check, 'PatentClaim' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-PatentLicense
MATCH (n:PatentLicense) WHERE NOT (n:VersionedState) RETURN 'V-F5-LBL' AS check, 'PatentLicense' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-IpRightStatus
MATCH (n:IpRightStatus) WHERE NOT (n:VersionedState) RETURN 'V-F5-LBL' AS check, 'IpRightStatus' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-MerchantListing
MATCH (n:MerchantListing) WHERE NOT (n:Entity) RETURN 'V-F5-LBL' AS check, 'MerchantListing' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-Offer
MATCH (n:Offer) WHERE NOT (n:VersionedState) RETURN 'V-F5-LBL' AS check, 'Offer' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-PriceObservation
MATCH (n:PriceObservation) WHERE NOT (n:Occurrence) RETURN 'V-F5-LBL' AS check, 'PriceObservation' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-SubscriptionPlan
MATCH (n:SubscriptionPlan) WHERE NOT (n:VersionedState) RETURN 'V-F5-LBL' AS check, 'SubscriptionPlan' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-Bundle
MATCH (n:Bundle) WHERE NOT (n:Entity) RETURN 'V-F5-LBL' AS check, 'Bundle' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-BundleComponent
MATCH (n:BundleComponent) WHERE NOT (n:VersionedState) RETURN 'V-F5-LBL' AS check, 'BundleComponent' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-InventoryItem
MATCH (n:InventoryItem) WHERE NOT (n:Entity) RETURN 'V-F5-LBL' AS check, 'InventoryItem' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-IndividualUnit
MATCH (n:IndividualUnit) WHERE NOT (n:Entity) RETURN 'V-F5-LBL' AS check, 'IndividualUnit' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-AffiliateLink
MATCH (n:AffiliateLink) WHERE NOT (n:InformationArtifact) RETURN 'V-F5-LBL' AS check, 'AffiliateLink' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-CommerceMatch
MATCH (n:CommerceMatch) WHERE NOT (n:EvidenceAssessment) RETURN 'V-F5-LBL' AS check, 'CommerceMatch' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-Protocol
MATCH (n:Protocol) WHERE NOT (n:Entity) RETURN 'V-F5-LBL' AS check, 'Protocol' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-ProtocolEdition
MATCH (n:ProtocolEdition) WHERE NOT (n:VersionedState) RETURN 'V-F5-LBL' AS check, 'ProtocolEdition' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-ProtocolStep
MATCH (n:ProtocolStep) WHERE NOT (n:Entity) RETURN 'V-F5-LBL' AS check, 'ProtocolStep' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-Constraint
MATCH (n:Constraint) WHERE NOT (n:Entity) RETURN 'V-F5-LBL' AS check, 'Constraint' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-MeasurementPlan
MATCH (n:MeasurementPlan) WHERE NOT (n:Entity) RETURN 'V-F5-LBL' AS check, 'MeasurementPlan' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-ProtocolAdjustmentRule
MATCH (n:ProtocolAdjustmentRule) WHERE NOT (n:Entity) RETURN 'V-F5-LBL' AS check, 'ProtocolAdjustmentRule' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-Target
MATCH (n:Target) WHERE NOT (n:Entity) RETURN 'V-F5-LBL' AS check, 'Target' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-FunctionalGoal
MATCH (n:FunctionalGoal) WHERE NOT (n:Entity) RETURN 'V-F5-LBL' AS check, 'FunctionalGoal' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-Observation
MATCH (n:Observation) WHERE NOT (n:DiagnosticResult AND n:InformationArtifact) RETURN 'V-F5-LBL' AS check, 'Observation' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-ProtocolResult
MATCH (n:ProtocolResult) WHERE NOT (n:InformationArtifact) RETURN 'V-F5-LBL' AS check, 'ProtocolResult' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-AdverseEffect
MATCH (n:AdverseEffect) WHERE NOT (n:Entity) RETURN 'V-F5-LBL' AS check, 'AdverseEffect' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-SafetySignal
MATCH (n:SafetySignal) WHERE NOT (n:EvidenceAssessment) RETURN 'V-F5-LBL' AS check, 'SafetySignal' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-ContraindicationAssertion
MATCH (n:ContraindicationAssertion) WHERE NOT (n:Assertion) RETURN 'V-F5-LBL' AS check, 'ContraindicationAssertion' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-InteractionAssertion
MATCH (n:InteractionAssertion) WHERE NOT (n:Assertion) RETURN 'V-F5-LBL' AS check, 'InteractionAssertion' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-UseConstraint
MATCH (n:UseConstraint) WHERE NOT (n:Entity) RETURN 'V-F5-LBL' AS check, 'UseConstraint' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-Community
MATCH (n:Community) WHERE NOT (n:Entity) RETURN 'V-F5-LBL' AS check, 'Community' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-Conference
MATCH (n:Conference) WHERE NOT (n:Entity) RETURN 'V-F5-LBL' AS check, 'Conference' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-Event
MATCH (n:Event) WHERE NOT (n:Occurrence) RETURN 'V-F5-LBL' AS check, 'Event' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-NarrativeArc
MATCH (n:NarrativeArc) WHERE NOT (n:EvidenceAssessment) RETURN 'V-F5-LBL' AS check, 'NarrativeArc' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-EventImpactAssessment
MATCH (n:EventImpactAssessment) WHERE NOT (n:EvidenceAssessment) RETURN 'V-F5-LBL' AS check, 'EventImpactAssessment' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-SourceAuthorityAssessment
MATCH (n:SourceAuthorityAssessment) WHERE NOT (n:EvidenceAssessment) RETURN 'V-F5-LBL' AS check, 'SourceAuthorityAssessment' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-SourceCoverageRequirement
MATCH (n:SourceCoverageRequirement) WHERE NOT (n:InformationArtifact) RETURN 'V-F5-LBL' AS check, 'SourceCoverageRequirement' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-SourceDiscoveryRecord
MATCH (n:SourceDiscoveryRecord) WHERE NOT (n:Activity AND n:Occurrence) RETURN 'V-F5-LBL' AS check, 'SourceDiscoveryRecord' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-Document
MATCH (n:Document) WHERE NOT (n:Source AND n:Entity) RETURN 'V-F5-LBL' AS check, 'Document' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-DocumentTextVersion
MATCH (n:DocumentTextVersion) WHERE NOT (n:InformationArtifact) RETURN 'V-F5-LBL' AS check, 'DocumentTextVersion' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-Segmentation
MATCH (n:Segmentation) WHERE NOT (n:InformationArtifact) RETURN 'V-F5-LBL' AS check, 'Segmentation' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-Chunk
MATCH (n:Chunk) WHERE NOT (n:InformationArtifact) RETURN 'V-F5-LBL' AS check, 'Chunk' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-Platform
MATCH (n:Platform) WHERE NOT (n:Entity) RETURN 'V-F5-LBL' AS check, 'Platform' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-Channel
MATCH (n:Channel) WHERE NOT (n:Entity) RETURN 'V-F5-LBL' AS check, 'Channel' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-Series
MATCH (n:Series) WHERE NOT (n:Entity) RETURN 'V-F5-LBL' AS check, 'Series' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-Episode
MATCH (n:Episode) WHERE NOT (n:Entity) RETURN 'V-F5-LBL' AS check, 'Episode' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-EpisodeSegment
MATCH (n:EpisodeSegment) WHERE NOT (n:InformationArtifact) RETURN 'V-F5-LBL' AS check, 'EpisodeSegment' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-Claim
MATCH (n:Claim) WHERE NOT (n:Entity) RETURN 'V-F5-LBL' AS check, 'Claim' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-ClaimOccurrence
MATCH (n:ClaimOccurrence) WHERE NOT (n:Assertion) RETURN 'V-F5-LBL' AS check, 'ClaimOccurrence' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-RelationshipAssertion
MATCH (n:RelationshipAssertion) WHERE NOT (n:Assertion) RETURN 'V-F5-LBL' AS check, 'RelationshipAssertion' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-ClaimEvidenceAssessment
MATCH (n:ClaimEvidenceAssessment) WHERE NOT (n:EvidenceAssessment) RETURN 'V-F5-LBL' AS check, 'ClaimEvidenceAssessment' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-RetellingFidelityAssessment
MATCH (n:RetellingFidelityAssessment) WHERE NOT (n:EvidenceAssessment) RETURN 'V-F5-LBL' AS check, 'RetellingFidelityAssessment' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-ConflictRelevanceAssessment
MATCH (n:ConflictRelevanceAssessment) WHERE NOT (n:EvidenceAssessment) RETURN 'V-F5-LBL' AS check, 'ConflictRelevanceAssessment' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-MediaAsset
MATCH (n:MediaAsset) WHERE NOT (n:InformationArtifact) RETURN 'V-F5-LBL' AS check, 'MediaAsset' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-MediaVariant
MATCH (n:MediaVariant) WHERE NOT (n:InformationArtifact) RETURN 'V-F5-LBL' AS check, 'MediaVariant' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-MediaAnnotation
MATCH (n:MediaAnnotation) WHERE NOT (n:InformationArtifact) RETURN 'V-F5-LBL' AS check, 'MediaAnnotation' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-GraphView
MATCH (n:GraphView) WHERE NOT (n:InformationArtifact) RETURN 'V-F5-LBL' AS check, 'GraphView' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-FigurePanel
MATCH (n:FigurePanel) WHERE NOT (n:InformationArtifact) RETURN 'V-F5-LBL' AS check, 'FigurePanel' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-ProductLabelRegion
MATCH (n:ProductLabelRegion) WHERE NOT (n:InformationArtifact) RETURN 'V-F5-LBL' AS check, 'ProductLabelRegion' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-MediaSuitabilityAssessment
MATCH (n:MediaSuitabilityAssessment) WHERE NOT (n:EvidenceAssessment) RETURN 'V-F5-LBL' AS check, 'MediaSuitabilityAssessment' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-MediaRightsRecord
MATCH (n:MediaRightsRecord) WHERE NOT (n:VersionedState) RETURN 'V-F5-LBL' AS check, 'MediaRightsRecord' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-AnswerRecord
MATCH (n:AnswerRecord) WHERE NOT (n:Occurrence) RETURN 'V-F5-LBL' AS check, 'AnswerRecord' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-PolicyVersion
MATCH (n:PolicyVersion) WHERE NOT (n:VersionedState) RETURN 'V-F5-LBL' AS check, 'PolicyVersion' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-LBL-DecisionCriterion
MATCH (n:DecisionCriterion) WHERE NOT (n:Entity) RETURN 'V-F5-LBL' AS check, 'DecisionCriterion' AS label, n.uid AS uid, labels(n) AS labels;
// V-F5-ARCH-1: exactly one archetype label per node that carries any
MATCH (n) WITH n, [l IN labels(n) WHERE l IN ["Entity","VersionedState","Occurrence","InformationArtifact","Assertion","EvidenceAssessment"]] AS a WHERE size(a) <> 1 AND size(labels(n)) > 0 RETURN 'V-F5-ARCH-1' AS check, n.uid AS uid, labels(n) AS labels;
// V-F5-ARCH-2: a uid-bearing node carries an archetype label (otherwise the archetype uid constraint cannot see it)
MATCH (n) WHERE n.uid IS NOT NULL AND none(l IN labels(n) WHERE l IN ["Entity","VersionedState","Occurrence","InformationArtifact","Assertion","EvidenceAssessment"]) RETURN 'V-F5-ARCH-2' AS check, n.uid AS uid, labels(n) AS labels;
