// W16 fixture 07: public description vs private execution kept outside the graph (LEAK PROBE: expected to FAIL V-113, V-520, V-521, V-524, V-534p)
// Run: run-2026-10-04-fable51-01 · worker W16 · generated by a scratchpad script; every statement binds its own nodes by uid.
// Nodes carry primary + archetype labels (D-001). Snapshot hashes use contentHashBasis SYNTHETIC_FIXTURE ('synthetic:<uid>');
// payloadHash values are real sha256 over the W16-CANON-1 JSON canonicalization of the fixture payload.
// Sources: W16-S01 Blueprint live page (HBOT results: 'Wiped out all systematic inflammation in my body, hsCRP below detectable levels.'); SYNTHETIC leak probes
// Expected outcomes: see ../06-fixtures-and-queries.md section 07. Validators: 00-w16-validators.cypher.
MERGE (n:Protocol:Entity {uid: 'hu:protocol:blueprint-bryan-johnson'}) SET n += {id: 'blueprint-bryan-johnson', createdAt: datetime('2026-10-04T01:00:00Z'), privacyClass: 'PUBLIC', entityType: 'Protocol', name: 'Bryan Johnson Protocol (Blueprint page)', protocolType: 'SUPPLEMENT_PROTOCOL', publicUrl: 'https://blueprint.bryanjohnson.com/blogs/news/bryan-johnsons-protocol'};
MERGE (n:Person:Entity {uid: 'hu:person:bryan-johnson'}) SET n += {id: 'bryan-johnson', createdAt: datetime('2026-10-04T01:00:00Z'), privacyClass: 'PUBLIC', entityType: 'Person', name: 'Bryan Johnson'};
MERGE (n:Metric:Entity {uid: 'hu:metric:hscrp'}) SET n += {id: 'hscrp', createdAt: datetime('2026-10-04T01:00:00Z'), privacyClass: 'PUBLIC', entityType: 'Metric', name: 'C reactive protein [Mass/volume] in Serum or Plasma by High sensitivity method'};
MERGE (n:Source:Entity {uid: 'hu:source:blueprint-protocol-page'}) SET n += {id: 'blueprint-protocol-page', createdAt: datetime('2026-10-04T01:00:00Z'), privacyClass: 'PUBLIC', entityType: 'Source', canonicalUri: 'https://blueprint.bryanjohnson.com/blogs/news/bryan-johnsons-protocol', title: 'Bryan Johnson\'s Protocol', sourceKind: 'SELF_DISCLOSURE_PAGE'};
MERGE (n:SourceSnapshot:InformationArtifact {uid: 'hu:snapshot:blueprint-protocol-2026-10-04'}) SET n += {id: 'blueprint-protocol-2026-10-04', createdAt: datetime('2026-10-04T01:00:00Z'), privacyClass: 'PUBLIC', artifactType: 'SourceSnapshot', canonicalUri: 'https://blueprint.bryanjohnson.com/blogs/news/bryan-johnsons-protocol', observedAt: datetime('2026-10-04T00:56:00Z'), retrievedAt: datetime('2026-10-04T00:56:00Z'), publishedAt: null, contentHash: 'synthetic:hu:snapshot:blueprint-protocol-2026-10-04', contentHashBasis: 'SYNTHETIC_FIXTURE', captureCompleteness: 'PARTIAL_EXCERPT'};
MERGE (n:SourceLocator:InformationArtifact {uid: 'hu:locator:blueprint-protocol-2026-10-04-hbot-results'}) SET n += {id: 'blueprint-protocol-2026-10-04-hbot-results', createdAt: datetime('2026-10-04T01:00:00Z'), privacyClass: 'PUBLIC', artifactType: 'SourceLocator', selectorKind: 'TEXT_QUOTE', exact: 'Wiped out all systematic inflammation in my body, hsCRP below detectable levels.'};
MATCH (a:Source {uid: 'hu:source:blueprint-protocol-page'}), (b:SourceSnapshot {uid: 'hu:snapshot:blueprint-protocol-2026-10-04'}) MERGE (a)-[r:HAS_SNAPSHOT]->(b);
MATCH (a:SourceSnapshot {uid: 'hu:snapshot:blueprint-protocol-2026-10-04'}), (b:SourceLocator {uid: 'hu:locator:blueprint-protocol-2026-10-04-hbot-results'}) MERGE (a)-[r:HAS_LOCATOR]->(b);
MERGE (n:ProtocolStep:Entity {uid: 'hu:protocol-step:blueprint-hbot-course-v1'}) SET n += {id: 'blueprint-hbot-course-v1', createdAt: datetime('2026-10-04T01:00:00Z'), privacyClass: 'PUBLIC', entityType: 'ProtocolStep', stepKey: 'hbot-course', payloadHash: 'sha256:f28104af00773491bd51946e4a7c2b755cbd2dba2207b4737a7f72e79e80d852', name: 'HBOT course', stepKind: 'OTHER', requirementLevel: 'NOT_STATED', requirementBasis: 'NOT_STATED', speechAct: 'REPORTS_PRACTICE'};
MERGE (n:ProtocolEdition:VersionedState {uid: 'hu:protocol-edition:blueprint-observed-2026-10-04'}) SET n += {id: 'blueprint-observed-2026-10-04', createdAt: datetime('2026-10-04T01:00:00Z'), privacyClass: 'PUBLIC', stateType: 'ProtocolEdition', editionLabel: null, changeProvenance: 'SNAPSHOT_DIFF', payloadHash: 'sha256:9abf09a70d5b65b5f0efae85907214e07d1474f77b718fa20775cb8ad91ab788', payloadCanonicalizationVersion: 'W16-CANON-1', stepKeyAlignmentVersion: 'W16-STEPKEY-1'};
MATCH (a:ProtocolEdition {uid: 'hu:protocol-edition:blueprint-observed-2026-10-04'}), (b:ProtocolStep {uid: 'hu:protocol-step:blueprint-hbot-course-v1'}) MERGE (a)-[r:HAS_PROTOCOL_STEP]->(b) SET r += {orderIndex: 1};
MERGE (n:Assertion {uid: 'hu:assertion:blueprint-has-edition-2026-10-04'}) SET n += {predicate: 'HAS_PROTOCOL_EDITION', status: 'ACCEPTED', polarity: 'POSITIVE', recordedAt: datetime('2026-10-04T01:00:00Z'), recordedTo: null, contentHash: 'sha256:d0af9c3676af5c77a318c785e164419d7d7fc70147c5c0b1524b243630baa1f4', privacyClass: 'PUBLIC', validFrom: null, validFromPrecision: null, validFromBasis: 'OBSERVATION_ONLY', validTo: null, validToPrecision: null, validToBasis: 'UNKNOWN', speechAct: 'STATES', assertionBasis: 'UNSTATED'};
MATCH (a:Assertion {uid: 'hu:assertion:blueprint-has-edition-2026-10-04'}), (b:Protocol {uid: 'hu:protocol:blueprint-bryan-johnson'}) MERGE (a)-[r:HAS_SUBJECT]->(b);
MATCH (a:Assertion {uid: 'hu:assertion:blueprint-has-edition-2026-10-04'}), (b:ProtocolEdition {uid: 'hu:protocol-edition:blueprint-observed-2026-10-04'}) MERGE (a)-[r:HAS_OBJECT]->(b);
MATCH (a:Assertion {uid: 'hu:assertion:blueprint-has-edition-2026-10-04'}), (b:SourceLocator {uid: 'hu:locator:blueprint-protocol-2026-10-04-hbot-results'}) MERGE (a)-[r:SUPPORTED_BY]->(b);
MATCH (a:Protocol {uid: 'hu:protocol:blueprint-bryan-johnson'}), (b:ProtocolEdition {uid: 'hu:protocol-edition:blueprint-observed-2026-10-04'}), (x:Assertion {uid: 'hu:assertion:blueprint-has-edition-2026-10-04'}) MERGE (a)-[r:HAS_PROTOCOL_EDITION {relationshipUid: 'hu:rel:blueprint-edition-2026-10-04'}]->(b) SET r.assertionUid = x.uid, r.validFrom = x.validFrom, r.validFromPrecision = x.validFromPrecision, r.validFromBasis = coalesce(x.validFromBasis, 'UNKNOWN'), r.validTo = x.validTo, r.validToPrecision = x.validToPrecision, r.validToBasis = coalesce(x.validToBasis, 'UNKNOWN'), r.recordedFrom = x.recordedAt, r.recordedTo = x.recordedTo;

// Public, source-attributed Observation by a public person (allowed): implements DiagnosticResult; valueStatus REPORTED, no number given.
MERGE (n:Observation:InformationArtifact {uid: 'hu:observation:blueprint-hscrp-after-hbot'}) SET n += {id: 'blueprint-hscrp-after-hbot', createdAt: datetime('2026-10-04T01:00:00Z'), privacyClass: 'PUBLIC', artifactType: 'Observation', name: 'hsCRP after 60 HBOT sessions (self-reported)', observationType: 'PUBLISHED_SELF_REPORT', observedPopulation: 'protocol author, self-reported', resultKind: 'MEASURED', valueStatus: 'REPORTED', valueText: 'hsCRP below detectable levels', publishedAt: null};
MATCH (a:Observation {uid: 'hu:observation:blueprint-hscrp-after-hbot'}), (b:Metric {uid: 'hu:metric:hscrp'}) MERGE (a)-[r:MEASURES_METRIC]->(b);
MATCH (a:Observation {uid: 'hu:observation:blueprint-hscrp-after-hbot'}), (b:ProtocolEdition {uid: 'hu:protocol-edition:blueprint-observed-2026-10-04'}) MERGE (a)-[r:ABOUT_PROTOCOL]->(b);
MERGE (n:Assertion {uid: 'hu:assertion:bj-records-hscrp-observation'}) SET n += {predicate: 'RECORDS', status: 'ACCEPTED', polarity: 'POSITIVE', recordedAt: datetime('2026-10-04T01:00:00Z'), recordedTo: null, contentHash: 'sha256:b8c7ab0bf7a8bd30c5a7e6802d67c782216ca93184a50dd7389e9f63a76db28a', privacyClass: 'PUBLIC', speechAct: 'REPORTS_PRACTICE', assertionBasis: 'PERSONAL_EXPERIENCE', validFromBasis: 'UNKNOWN', validToBasis: 'UNKNOWN'};
MATCH (a:Assertion {uid: 'hu:assertion:bj-records-hscrp-observation'}), (b:Person {uid: 'hu:person:bryan-johnson'}) MERGE (a)-[r:HAS_SUBJECT]->(b);
MATCH (a:Assertion {uid: 'hu:assertion:bj-records-hscrp-observation'}), (b:Observation {uid: 'hu:observation:blueprint-hscrp-after-hbot'}) MERGE (a)-[r:HAS_OBJECT]->(b);
MATCH (a:Assertion {uid: 'hu:assertion:bj-records-hscrp-observation'}), (b:SourceLocator {uid: 'hu:locator:blueprint-protocol-2026-10-04-hbot-results'}) MERGE (a)-[r:SUPPORTED_BY]->(b);
MATCH (a:Assertion {uid: 'hu:assertion:bj-records-hscrp-observation'}), (b:Person {uid: 'hu:person:bryan-johnson'}) MERGE (a)-[r:ASSERTED_BY]->(b);
MATCH (a:Person {uid: 'hu:person:bryan-johnson'}), (b:Observation {uid: 'hu:observation:blueprint-hscrp-after-hbot'}), (x:Assertion {uid: 'hu:assertion:bj-records-hscrp-observation'}) MERGE (a)-[r:RECORDS {relationshipUid: 'hu:rel:bj-records-hscrp'}]->(b) SET r.assertionUid = x.uid, r.validFrom = x.validFrom, r.validFromPrecision = x.validFromPrecision, r.validFromBasis = coalesce(x.validFromBasis, 'UNKNOWN'), r.validTo = x.validTo, r.validToPrecision = x.validToPrecision, r.validToBasis = coalesce(x.validToBasis, 'UNKNOWN'), r.recordedFrom = x.recordedAt, r.recordedTo = x.recordedTo;

// LEAK PROBE 1 (expected V-520 + V-521): a private ProtocolInUse written into the shared graph without the fixture-only PrivateRecord label.
MERGE (n:ProtocolInUse:Entity {uid: 'hu:private-protocol-in-use:leak-probe-1'}) SET n += {id: 'leak-probe-1', privacyClass: 'private-personal', entityType: 'ProtocolInUse', createdAt: datetime('2026-10-04T01:00:00Z')};

// LEAK PROBE 2 (expected V-113 + V-534p): a shared edition pointing at the private adoption.
MATCH (e:ProtocolEdition {uid: 'hu:protocol-edition:blueprint-observed-2026-10-04'}), (n:ProtocolInUse {uid: 'hu:private-protocol-in-use:leak-probe-1'}) MERGE (e)-[:ADOPTED_IN_PRIVATE]->(n);

// LEAK PROBE 3 (expected V-524 + V-520 + V-521): a personal measurement collapsed into the public Observation label.
MERGE (n:Observation:PersonalMeasurement:InformationArtifact {uid: 'hu:private-personal-measurement:leak-probe-2'}) SET n += {id: 'leak-probe-2', privacyClass: 'private-personal', artifactType: 'PersonalMeasurement', valueNumber: 0.4, unitCode: 'mg/L', createdAt: datetime('2026-10-04T01:00:00Z')};

// LEAK PROBE 4 (expected V-521 + V-534p): a private deviation uid stored on a public step.
MATCH (s:ProtocolStep {uid: 'hu:protocol-step:blueprint-hbot-course-v1'}) SET s.lastDeviationUid = 'hu:private-protocol-deviation:leak-probe-3';

// Q-W16-07a (QS-6a defence in depth): 2-hop traversal from the public edition never returns a private node even while probes are present.
MATCH (s {uid: 'hu:protocol-edition:blueprint-observed-2026-10-04'})
WHERE NOT (s.uid STARTS WITH 'hu:private-' OR s.privacyClass = 'private-personal' OR s:PrivateRecord)
MATCH p = (s)(()-[r]-(n) WHERE NOT (n.uid STARTS WITH 'hu:private-' OR n.privacyClass = 'private-personal' OR n:PrivateRecord)){1,2}
RETURN count(DISTINCT last(nodes(p))) AS reachableNodes, any(x IN collect(DISTINCT last(nodes(p)).uid) WHERE x STARTS WITH 'hu:private-') AS reachesPrivate;

// Q-W16-07b (CQ-AX-22 shared part): which public edition did a public result/observation use; the private store sends only the edition uid.
MATCH (o:Observation)-[:ABOUT_PROTOCOL]->(e:ProtocolEdition) WHERE NOT o:PersonalMeasurement
MATCH (:Person)-[r:RECORDS]->(o)
RETURN o.uid AS observationUid, e.uid AS editionUid, r.assertionUid AS attribution, ('hu:protocol-edition:blueprint-observed-2026-10-04' = e.uid) AS sameEditionAsQueried;
