import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from lib import *

OUT = "/home/user/biotech-meta/docs/schema/ontology-lab/final-proposal-team/run-2026-10-04-fable51-01/workers/W16/fixtures"
HDR = """// W16 fixture {n}: {title}
// Run: run-2026-10-04-fable51-01 · worker W16 · generated by a scratchpad script; every statement binds its own nodes by uid.
// Nodes carry primary + archetype labels (D-001). Snapshot hashes use contentHashBasis SYNTHETIC_FIXTURE ('synthetic:<uid>');
// payloadHash values are real sha256 over the W16-CANON-1 JSON canonicalization of the fixture payload.
// Sources: {sources}
// Expected outcomes: see ../06-fixtures-and-queries.md section {n}. Validators: 00-w16-validators.cypher.
"""

def hdr(n, title, sources): return HDR.format(n=n, title=title, sources=sources)

# ------------------------------------------------------------------------------------------------
# F01 edition diff by stepKey: protocols.io "PBMCs isolation from CPT tube" V.1 -> V.2 (SOURCE_VERSIONED)
# ------------------------------------------------------------------------------------------------
def f01():
    fx = Fx("01", hdr("01", "edition diff by stepKey (protocols.io PBMC CPT V.1 -> V.2, SOURCE_VERSIONED)",
                      "W16-S05 protocols.io V.1 (PARTIAL_EXCERPT), W16-S04 protocols.io V.2 (PARTIAL_EXCERPT), retrieved 2026-10-04"))
    P = "hu:protocol:protocolsio-pbmc-cpt"
    fx.node("Protocol", P, {"name": "PBMCs isolation from CPT tube", "protocolType": "SAMPLE_COLLECTION_PROTOCOL",
                            "publicUrl": "https://www.protocols.io/view/pbmcs-isolation-from-cpt-tube-kxygxeqr4v8j"})
    fx.node("ToolOrInstrument", "hu:instrument:bd-vacutainer-cpt-tube", {"name": "BD Vacutainer CPT tube"})
    fx.node("ToolOrInstrument", "hu:instrument:swing-out-rotor-centrifuge", {"name": "Centrifuge with horizontal (swing-out) rotor"})
    fx.source("hu:source:protocolsio-pbmc-cpt-v1", "https://www.protocols.io/view/pbmcs-isolation-from-cpt-tube-kxygxeqr4v8j/v1",
              "PBMCs isolation from CPT tube V.1", "STANDARDS_DOCUMENT", "hu:snapshot:protocolsio-pbmc-cpt-v1-2026-10-04",
              "2026-10-04T01:05:00Z", "2026-10-04T01:05:00Z", "PARTIAL_EXCERPT", "hu:locator:protocolsio-pbmc-cpt-v1-steps",
              ("SECTION", "Steps (partial excerpt: centrifuge, aspirate, collect)"), publishedAt="2020-08-06T02:08:54Z")
    fx.source("hu:source:protocolsio-pbmc-cpt-v2", "https://www.protocols.io/view/pbmcs-isolation-from-cpt-tube-kxygxeqr4v8j/v2",
              "PBMCs isolation from CPT tube V.2", "STANDARDS_DOCUMENT", "hu:snapshot:protocolsio-pbmc-cpt-v2-2026-10-04",
              "2026-10-04T01:04:00Z", "2026-10-04T01:04:00Z", "PARTIAL_EXCERPT", "hu:locator:protocolsio-pbmc-cpt-v2-steps",
              ("SECTION", "Steps 1-5"), publishedAt="2022-07-27T09:54:35Z")
    slug = "protocolsio-pbmc-cpt"
    cent1 = Step(slug, "centrifuge-cpt-tube", {"name": "Centrifuge CPT tube", "stepKind": "OTHER", "stepKindRaw": "CENTRIFUGE",
                 "stepDescription": "Centrifuge tube/blood sample at Room temperature in a horizontal rotor (swing-out head) for a minimum of 00:10:00 at 1500 rpm to 1800 rpm.",
                 "durationMinutesMin": 10, "requirementLevel": "NOT_STATED", "requirementBasis": "NOT_STATED", "speechAct": "STATES",
                 "notReportedFields": ["durationMinutesMax"]},
                 employs=[("ToolOrInstrument", "hu:instrument:bd-vacutainer-cpt-tube"), ("ToolOrInstrument", "hu:instrument:swing-out-rotor-centrifuge")], version=1)
    asp1 = Step(slug, "aspirate-plasma-half", {"name": "Aspirate half of plasma", "stepKind": "OTHER", "stepKindRaw": "ASPIRATE",
                 "stepDescription": "After centrifugation, mononuclear cells and platelets will be in a whitish layer just under the plasma layer. Aspirate approximately half of the plasma without disturbing the cell layer.",
                 "requirementLevel": "NOT_STATED", "requirementBasis": "NOT_STATED", "speechAct": "STATES"}, version=1)
    col1 = Step(slug, "collect-cells", {"name": "Collect cells", "stepKind": "SAMPLE",
                 "stepDescription": "To collect the cells, open the BD Vacutainer CPT Tube and pipette (use Pasteur Pipette) the entire contents of the tube above the gel into a separate tube.",
                 "requirementLevel": "NOT_STATED", "requirementBasis": "NOT_STATED", "speechAct": "STATES"},
                 employs=[("ToolOrInstrument", "hu:instrument:bd-vacutainer-cpt-tube")], version=1)
    mix2 = Step(slug, "mix-by-inversion", {"name": "Mix by inversion", "stepKind": "OTHER", "stepKindRaw": "MIX",
                 "stepDescription": "Mix the blood sample immediately prior to centrifugation by gently inverting the tube 8 to 10 times.",
                 "totalOccurrencesMin": 8, "totalOccurrencesMax": 10, "requirementLevel": "NOT_STATED", "requirementBasis": "NOT_STATED", "speechAct": "STATES"}, version=2)
    cent2 = Step(slug, "centrifuge-cpt-tube", {"name": "Centrifuge CPT tube", "stepKind": "OTHER", "stepKindRaw": "CENTRIFUGE",
                 "stepDescription": "Centrifuge the CPT tube at 1500 rcf (Relative Centrifugal Force) in a horizontal rotor (swing-out head) for 00:30:00 at 20 C (Speed change of accel/decel: Soft).",
                 "durationMinutesMin": 30, "durationMinutesMax": 30, "requirementLevel": "NOT_STATED", "requirementBasis": "NOT_STATED", "speechAct": "STATES"},
                 employs=[("ToolOrInstrument", "hu:instrument:bd-vacutainer-cpt-tube"), ("ToolOrInstrument", "hu:instrument:swing-out-rotor-centrifuge")],
                 deps=[("mix-by-inversion", "REQUIRES_PRIOR_COMPLETION", {"lagMin": 0, "lagMax": 0, "lagUnit": "HOUR", "dependencyBasis": "STATED_BY_SOURCE"})], version=2)
    asp2 = Step(slug, "aspirate-plasma-half", {"name": "Aspirate half of plasma", "stepKind": "OTHER", "stepKindRaw": "ASPIRATE",
                 "stepDescription": "After centrifugation, PBMCs will be in a whitish layer just under the plasma layer. Using a Pasteur pipette, aspirate approximately half of the plasma without disturbing the PBMC cell layer.",
                 "requirementLevel": "NOT_STATED", "requirementBasis": "NOT_STATED", "speechAct": "STATES"},
                 deps=[("centrifuge-cpt-tube", "REQUIRES_PRIOR_COMPLETION", {"dependencyBasis": "STATED_BY_SOURCE"})], version=2)
    col2 = Step(slug, "collect-cells", {"name": "Collect cell layer", "stepKind": "SAMPLE",
                 "stepDescription": "Collect cell layer by pouring and transferring cell layer to a 50 mL size conical centrifuge tube with cap. Collection of cells immediately following centrifugation will yield best results.",
                 "requirementLevel": "NOT_STATED", "requirementBasis": "NOT_STATED", "speechAct": "STATES"},
                 deps=[("aspirate-plasma-half", "REQUIRES_PRIOR_COMPLETION", {"dependencyBasis": "STATED_BY_SOURCE"})], version=2)
    spin2 = Step(slug, "spin-down-collected", {"name": "Spin down collected mixture", "stepKind": "OTHER", "stepKindRaw": "CENTRIFUGE",
                 "stepDescription": "Spin down the collected mixture at 300 rcf for 00:15:00 at 20 C.", "durationMinutesMin": 15, "durationMinutesMax": 15,
                 "requirementLevel": "NOT_STATED", "requirementBasis": "NOT_STATED", "speechAct": "STATES"},
                 deps=[("collect-cells", "REQUIRES_PRIOR_COMPLETION", {"dependencyBasis": "STATED_BY_SOURCE"})], version=2)
    v1steps = [cent1, asp1, col1]; v2steps = [mix2, cent2, asp2, col2, spin2]
    for s in v1steps + v2steps: s.emit(fx)
    r2 = {s.key: s for s in v2steps}
    for s in v2steps: emit_deps(fx, s, r2)
    E1, E2 = "hu:protocol-edition:protocolsio-pbmc-cpt-v1", "hu:protocol-edition:protocolsio-pbmc-cpt-v2"
    edition(fx, E1, "V.1", "SOURCE_VERSIONED", [(cent1, {"sourceStepLabel": "1"}), (asp1, {"sourceStepLabel": "2"}), (col1, {"sourceStepLabel": "5"})],
            {"sourceVersionDate": D("2020-08-06"), "sourceVersionDateText": "Aug 05, 2020 (page); citation_publication_date 2020/08/06"})
    edition(fx, E2, "V.2", "SOURCE_VERSIONED", [(mix2, {"sourceStepLabel": "1"}), (cent2, {"sourceStepLabel": "2"}), (asp2, {"sourceStepLabel": "3"}),
            (col2, {"sourceStepLabel": "4"}), (spin2, {"sourceStepLabel": "5"})],
            {"sourceVersionDate": D("2022-07-27"), "sourceVersionDateText": "Jul 27, 2022"})
    attach(fx, P, E1, "hu:assertion:protocolsio-pbmc-cpt-has-v1", "hu:rel:protocolsio-pbmc-cpt-v1", "hu:locator:protocolsio-pbmc-cpt-v1-steps",
           DT("2020-08-06T00:00:00Z"), "DAY", "STATED_BY_SOURCE", DT("2022-07-27T00:00:00Z"), "DAY", "INFERRED")
    attach(fx, P, E2, "hu:assertion:protocolsio-pbmc-cpt-has-v2", "hu:rel:protocolsio-pbmc-cpt-v2", "hu:locator:protocolsio-pbmc-cpt-v2-steps",
           DT("2022-07-27T00:00:00Z"), "DAY", "STATED_BY_SOURCE", None, None, "UNKNOWN")
    fx.c("Q-W16-01 (CQ-PR-01): step-level diff of two editions by stepKey and payloadHash, with change provenance and capture completeness.\n"
         "A step missing from a PARTIAL capture is ADDED_OR_NOT_CAPTURED, never ADDED; order changes are reported separately.")
    fx.raw(DIFF_QUERY.replace("$old", "'" + E1 + "'").replace("$new", "'" + E2 + "'"))
    fx.write(f"{OUT}/01-edition-diff-by-stepkey.cypher")

DIFF_QUERY = """MATCH (old:ProtocolEdition {uid: $old}), (new:ProtocolEdition {uid: $new})
CALL { WITH old OPTIONAL MATCH (:Protocol)-[h:HAS_PROTOCOL_EDITION]->(old) OPTIONAL MATCH (a:Assertion {uid: h.assertionUid})-[:SUPPORTED_BY]->(:SourceLocator)<-[:HAS_LOCATOR]-(sn:SourceSnapshot)
       RETURN collect(DISTINCT sn.captureCompleteness) AS oldCapture }
CALL { WITH new OPTIONAL MATCH (:Protocol)-[h:HAS_PROTOCOL_EDITION]->(new) OPTIONAL MATCH (a:Assertion {uid: h.assertionUid})-[:SUPPORTED_BY]->(:SourceLocator)<-[:HAS_LOCATOR]-(sn:SourceSnapshot)
       RETURN collect(DISTINCT sn.captureCompleteness) AS newCapture }
CALL { WITH old OPTIONAL MATCH (old)-[r:HAS_PROTOCOL_STEP]->(s:ProtocolStep) RETURN collect({k: s.stepKey, h: s.payloadHash, o: r.orderIndex}) AS O }
CALL { WITH new OPTIONAL MATCH (new)-[r:HAS_PROTOCOL_STEP]->(s:ProtocolStep) RETURN collect({k: s.stepKey, h: s.payloadHash, o: r.orderIndex}) AS N }
WITH old, new, oldCapture, newCapture, O, N, any(c IN oldCapture WHERE c <> 'COMPLETE') AS oldPartial, any(c IN newCapture WHERE c <> 'COMPLETE') AS newPartial
UNWIND [x IN O | x.k] + [x IN N | x.k] AS stepKey
WITH DISTINCT old, new, oldPartial, newPartial, stepKey, head([x IN O WHERE x.k = stepKey]) AS o, head([x IN N WHERE x.k = stepKey]) AS n
RETURN stepKey,
       CASE WHEN o IS NULL AND oldPartial THEN 'ADDED_OR_NOT_CAPTURED' WHEN o IS NULL THEN 'ADDED'
            WHEN n IS NULL AND newPartial THEN 'REMOVED_OR_NOT_CAPTURED' WHEN n IS NULL THEN 'REMOVED'
            WHEN o.h = n.h THEN 'UNCHANGED' ELSE 'MODIFIED' END AS changeKind,
       o.o AS oldOrder, n.o AS newOrder, (o IS NOT NULL AND n IS NOT NULL AND o.o <> n.o) AS reordered,
       new.changeProvenance AS changeProvenance, old.editionLabel AS oldLabel, new.editionLabel AS newLabel
ORDER BY stepKey"""

# ------------------------------------------------------------------------------------------------
# F02 source changes dose/schedule without changing protocol identity (SNAPSHOT_DIFF) + third-party report
# ------------------------------------------------------------------------------------------------
def blueprint_base(fx):
    P = "hu:protocol:blueprint-bryan-johnson"
    fx.node("Protocol", P, {"name": "Bryan Johnson Protocol (Blueprint page)", "protocolType": "SUPPLEMENT_PROTOCOL",
                            "publicUrl": "https://blueprint.bryanjohnson.com/blogs/news/bryan-johnsons-protocol"})
    fx.node("Person", "hu:person:bryan-johnson", {"name": "Bryan Johnson"})
    return P

def f02():
    fx = Fx("02", hdr("02", "source changes dose/schedule without changing enduring identity (SNAPSHOT_DIFF vs SOURCE_VERSIONED vs THIRD_PARTY_REPORTED)",
                      "W16-S01 Blueprint live page 2026-10-04 (PARTIAL_EXCERPT of steps), W16-S02 Wayback capture 2026-01-24T05:28:36Z, W16-S03 NAD.com 2026-03-24"))
    P = blueprint_base(fx)
    fx.node("Organization", "hu:org:nad-com", {"name": "NAD.com"})
    for u, n in [("hu:substance:creatine", "creatine"), ("hu:substance:tadalafil", "tadalafil"), ("hu:substance:acarbose", "acarbose"),
                 ("hu:substance:candesartan", "candesartan"), ("hu:substance:rapamycin", "rapamycin (sirolimus)"),
                 ("hu:substance:nicotinamide-mononucleotide", "nicotinamide mononucleotide")]:
        fx.node("ChemicalSubstance", u, {"name": n})
    WB, LIVE = "hu:source:wayback-blueprint-protocol-20260124", "hu:source:blueprint-protocol-page"
    fx.source(LIVE, "https://blueprint.bryanjohnson.com/blogs/news/bryan-johnsons-protocol", "Bryan Johnson's Protocol", "SELF_DISCLOSURE_PAGE",
              "hu:snapshot:blueprint-protocol-2026-10-04", "2026-10-04T00:56:00Z", "2026-10-04T00:56:00Z", "PARTIAL_EXCERPT",
              "hu:locator:blueprint-protocol-2026-10-04-rx", ("SECTION", "My Rx stack; Rx / Prescriptions; Morning (5:25 am)"))
    fx.source(WB, "https://web.archive.org/web/20260124052836/https://blueprint.bryanjohnson.com/blogs/news/bryan-johnsons-protocol",
              "Bryan Johnson's Protocol (Wayback capture 2026-01-24)", "SELF_DISCLOSURE_PAGE", "hu:snapshot:blueprint-protocol-wayback-2026-01-24",
              "2026-01-24T05:28:36Z", "2026-10-04T00:58:00Z", "PARTIAL_EXCERPT", "hu:locator:blueprint-protocol-wayback-2026-01-24-rx",
              ("SECTION", "My Rx stack; Rx / Prescriptions; Morning (5:25 am)"))
    fx.source("hu:source:nadcom-johnson-2026", "https://www.nad.com/news/aging-guru-bryan-johnsons-supplement-list-for-2026",
              "Aging Guru Bryan Johnson's Supplement List for 2026", "NEWSLETTER", "hu:snapshot:nadcom-johnson-2026-10-04",
              "2026-10-04T01:07:00Z", "2026-10-04T01:07:00Z", "PARTIAL_EXCERPT", "hu:locator:nadcom-johnson-2026-key-points",
              ("TEXT_QUOTE", "These changes include taking NMN or NR six days a week, rather than seven; dropping rapamycin ... which he stopped in 2024"),
              publishedAt="2026-03-24T18:26:00Z")
    slug = "blueprint"
    def rx(key, name, sub, q, basis, text, version, occ=None, extra=None):
        props = {"name": name, "stepKind": "INGEST", "requirementLevel": "NOT_STATED", "requirementBasis": "NOT_STATED",
                 "speechAct": "REPORTS_PRACTICE", "scheduleText": text, "schedulePattern": "DAILY"}
        if occ: props.update({"occurrencesPerPeriodMin": occ, "occurrencesPerPeriodMax": occ, "occurrencePeriodUnit": "DAY"})
        props.update(extra or {})
        return Step(slug, key, props, uses=[("ChemicalSubstance", sub, {"quantity": q, "unitCode": "mg", "quantityBasis": basis,
                                                                           "massBasis": "UNSPECIFIED", "route": "oral", "verbatimDoseText": text})], version=version)
    cre1 = Step(slug, "creatine-pre-workout", {"name": "Creatine pre-workout drink", "stepKind": "INGEST", "requirementLevel": "NOT_STATED",
                "requirementBasis": "NOT_STATED", "speechAct": "REPORTS_PRACTICE", "timeOfDay": "MORNING", "timingText": "5:25 am (pre workout)",
                "scheduleText": "Creatine 2.5 g (Longevity Mix has 2.5 g for 5 g total)"},
                uses=[("ChemicalSubstance", "hu:substance:creatine", {"quantity": 2.5, "unitCode": "g", "quantityBasis": "PER_DOSE", "massBasis": "UNSPECIFIED",
                       "route": "oral", "verbatimDoseText": "Creatine 2.5 g (Longevity Mix has 2.5 g for 5 g total)"})], version=1)
    cre2 = Step(slug, "creatine-pre-workout", {"name": "Creatine pre-workout drink", "stepKind": "INGEST", "requirementLevel": "NOT_STATED",
                "requirementBasis": "NOT_STATED", "speechAct": "REPORTS_PRACTICE", "timeOfDay": "MORNING", "timingText": "5:25 am (pre workout)",
                "scheduleText": "Creatine 5 g (Longevity Mix has 2.5 g for 7.5 g total)"},
                uses=[("ChemicalSubstance", "hu:substance:creatine", {"quantity": 5.0, "unitCode": "g", "quantityBasis": "PER_DOSE", "massBasis": "UNSPECIFIED",
                       "route": "oral", "verbatimDoseText": "Creatine 5 g (Longevity Mix has 2.5 g for 7.5 g total)"})], version=2)
    tad1 = rx("tadalafil-daily", "Tadalafil daily", "hu:substance:tadalafil", 2.5, "PER_DAY", "Tadalafil 2.5 mg daily", 1)
    tad2 = rx("tadalafil-daily", "Tadalafil daily", "hu:substance:tadalafil", 5.0, "PER_DAY", "Tadalafil 5 mg daily", 2)
    aca1 = rx("acarbose-daily", "Acarbose", "hu:substance:acarbose", 200.0, "PER_DAY", "Acarbose 200 mg daily", 1)
    aca2 = rx("acarbose-daily", "Acarbose", "hu:substance:acarbose", 200.0, "PER_DOSE", "Acarbose 200 mg (Rx) (twice daily); Acarbose 400 mg daily", 2, occ=2)
    can = rx("candesartan-daily", "Candesartan", "hu:substance:candesartan", 8.0, "PER_DAY", "Candesartan 8 mg daily", 1)
    e1steps, e2steps = [cre1, tad1, aca1, can], [cre2, tad2, aca2, can]
    for s in [cre1, tad1, aca1, can, cre2, tad2, aca2]: s.emit(fx)
    E1, E2 = "hu:protocol-edition:blueprint-observed-2026-01-24", "hu:protocol-edition:blueprint-observed-2026-10-04"
    edition(fx, E1, None, "SNAPSHOT_DIFF", [(s, {"sectionLabel": "My Rx stack / Rx / Morning"}) for s in e1steps],
            {"sourceVersionDateText": "Written by Bryan Johnson 01.23.2026 (byline; unchanged in later captures, so not a version label)"})
    edition(fx, E2, None, "SNAPSHOT_DIFF", [(s, {"sectionLabel": "My Rx stack / Rx / Morning"}) for s in e2steps],
            {"sourceVersionDateText": "Written by Bryan Johnson 01.23.2026 (byline unchanged)"})
    attach(fx, P, E1, "hu:assertion:blueprint-has-edition-2026-01-24", "hu:rel:blueprint-edition-2026-01-24", "hu:locator:blueprint-protocol-wayback-2026-01-24-rx",
           DT("2026-01-23T00:00:00Z"), "DAY", "PUBLICATION_PROXY", None, None, "UNKNOWN", recordedAt="2026-10-04T01:10:00Z")
    attach(fx, P, E2, "hu:assertion:blueprint-has-edition-2026-10-04", "hu:rel:blueprint-edition-2026-10-04", "hu:locator:blueprint-protocol-2026-10-04-rx",
           None, None, "OBSERVATION_ONLY", None, None, "UNKNOWN", recordedAt="2026-10-04T01:10:00Z")
    fx.c("Authorship of the page (assertion-backed): the protocol's own asserter, used to classify reports as THIRD_PARTY_REPORTED.")
    fx.assertion("hu:assertion:blueprint-authored-by-bryan-johnson", "AUTHORED_PROTOCOL", ("Protocol", P), ("Person", "hu:person:bryan-johnson"),
                 {"speechAct": "STATES", "assertionBasis": "UNSTATED"}, ["hu:locator:blueprint-protocol-2026-10-04-rx"])
    fx.c("Third-party reports (NAD.com, 2026-03-24): Assertions, never editions. Rapamycin step ended in 2024 (YEAR precision); NMN/NR six days a week.")
    fx.assertion("hu:assertion:nadcom-rapamycin-stopped-2024", "PROTOCOL_INCLUDES_SUBSTANCE", ("Protocol", P), ("ChemicalSubstance", "hu:substance:rapamycin"),
                 {"validTo": DT("2024-01-01T00:00:00Z"), "validToPrecision": "YEAR", "validToBasis": "STATED_BY_SOURCE", "validFromBasis": "UNKNOWN",
                  "speechAct": "STATES", "assertionBasis": "THIRD_PARTY_ANECDOTE"}, ["hu:locator:nadcom-johnson-2026-key-points"], ("Organization", "hu:org:nad-com"))
    fx.assertion("hu:assertion:nadcom-nmn-six-days-a-week", "STEP_OCCURRENCES_PER_WEEK", ("Protocol", P), None,
                 {"valueNumber": 6.0, "unitCode": "/wk", "valueString": "NMN or NR 500 mg (6x/week)", "validFromBasis": "UNKNOWN", "validToBasis": "UNKNOWN",
                  "speechAct": "STATES", "assertionBasis": "THIRD_PARTY_ANECDOTE"}, ["hu:locator:nadcom-johnson-2026-key-points"], ("Organization", "hu:org:nad-com"))
    fx.c("NEGATIVE (expected V-530p row): an edition minted from the third-party report.")
    fx.node("ProtocolEdition", "hu:protocol-edition:blueprint-neg-from-nadcom-report", {"changeProvenance": "THIRD_PARTY_REPORTED",
            "payloadHash": sha("neg-third-party"), "editionLabel": None})
    fx.c("Q-W16-02a: the enduring identity is one Protocol node with two editions; the protocol uid and its properties did not change.")
    fx.raw(f"""MATCH (p:Protocol {{uid: '{P}'}})-[h:HAS_PROTOCOL_EDITION]->(e:ProtocolEdition)
RETURN p.uid AS protocolUid, count(e) AS editions, collect(e.changeProvenance) AS provenances""")
    fx.c("Q-W16-02b (CQ-PR-01): dose changes for the same stepKey across the two observed editions (declared dose, basis preserved).")
    fx.raw(f"""MATCH (e1:ProtocolEdition {{uid: '{E1}'}})-[:HAS_PROTOCOL_STEP]->(s1:ProtocolStep)-[u1:USES]->(x),
      (e2:ProtocolEdition {{uid: '{E2}'}})-[:HAS_PROTOCOL_STEP]->(s2:ProtocolStep)-[u2:USES]->(x)
WHERE s1.stepKey = s2.stepKey
RETURN s1.stepKey AS stepKey, s1 = s2 AS sameStepNode, u1.quantity AS oldQty, u1.quantityBasis AS oldBasis, u2.quantity AS newQty, u2.quantityBasis AS newBasis,
       s2.occurrencesPerPeriodMax AS newPerDay, u1.verbatimDoseText AS oldText, u2.verbatimDoseText AS newText
ORDER BY stepKey""")
    fx.c("Q-W16-02c (CQ-PR-01): change-provenance labelled history: editions plus third-party assertions; unobserved intervals stay unknown.")
    fx.raw(f"""MATCH (p:Protocol {{uid: '{P}'}})
CALL {{ WITH p MATCH (p)-[h:HAS_PROTOCOL_EDITION]->(e:ProtocolEdition)
       MATCH (a:Assertion {{uid: h.assertionUid}})-[:SUPPORTED_BY]->(:SourceLocator)<-[:HAS_LOCATOR]-(sn:SourceSnapshot)
       RETURN e.uid AS item, e.changeProvenance AS provenance, sn.observedAt AS observedAt, h.validFrom AS validFrom, h.validFromBasis AS validFromBasis,
              h.validTo AS validTo, h.validToBasis AS validToBasis
       UNION
       WITH p MATCH (a:Assertion)-[:HAS_SUBJECT]->(p) WHERE a.predicate <> 'HAS_PROTOCOL_EDITION' AND a.predicate <> 'AUTHORED_PROTOCOL'
       OPTIONAL MATCH (a)-[:ASSERTED_BY]->(who)
       OPTIONAL MATCH (au:Assertion {{predicate: 'AUTHORED_PROTOCOL'}})-[:HAS_SUBJECT]->(p)
       OPTIONAL MATCH (au)-[:HAS_OBJECT]->(author)
       WITH a, who, collect(author.uid) AS authors
       RETURN a.uid AS item, CASE WHEN who IS NULL OR who.uid IN authors THEN 'OWNER_STATED' ELSE 'THIRD_PARTY_REPORTED' END AS provenance,
              null AS observedAt, a.validFrom AS validFrom, a.validFromBasis AS validFromBasis, a.validTo AS validTo, a.validToBasis AS validToBasis }}
RETURN item, provenance, observedAt, validFrom, validFromBasis, validTo, validToBasis ORDER BY provenance, item""")
    fx.write(f"{OUT}/02-source-change-same-identity.cypher")

# ------------------------------------------------------------------------------------------------
# NICE CG185 lithium base (F03, F04, F11, F09)
# ------------------------------------------------------------------------------------------------
NP = "hu:protocol:nice-cg185-lithium-monitoring"
NE = "hu:protocol-edition:nice-cg185-lithium-2025-09-02"
def nice_base(fx):
    fx.node("Protocol", NP, {"name": "NICE CG185 lithium starting, monitoring and stopping recommendations", "protocolType": "MONITORING_PROTOCOL",
                             "publicUrl": "https://www.nice.org.uk/guidance/cg185/chapter/1-Recommendations"})
    fx.node("Organization", "hu:org:nice", {"name": "National Institute for Health and Care Excellence"})
    fx.node("Metric", "hu:metric:plasma-lithium-substance-concentration", {"name": "Lithium [Moles/volume] in Serum or Plasma"})
    fx.node("Metric", "hu:metric:egfr", {"name": "Estimated glomerular filtration rate"})
    fx.node("ChemicalSubstance", "hu:substance:lithium", {"name": "lithium"})
    fx.source("hu:source:nice-cg185-recommendations", "https://www.nice.org.uk/guidance/cg185/chapter/1-Recommendations",
              "Recommendations | Bipolar disorder: assessment and management | NICE", "REGULATORY_GUIDANCE",
              "hu:snapshot:nice-cg185-2026-10-04", "2026-10-04T01:02:00Z", "2026-10-04T01:02:00Z", "PARTIAL_EXCERPT",
              "hu:locator:nice-cg185-using-lithium", ("SECTION", "1.10 Using lithium: 1.10.14-1.10.26"))

def nice_attach(fx, steps, extra_payload=()):
    edition(fx, NE, "Last updated: 02 September 2025", "SOURCE_VERSIONED", steps,
            {"sourceVersionDate": D("2025-09-02"), "sourceVersionDateText": "Last updated: 02 September 2025"}, extra_payload)
    attach(fx, NP, NE, "hu:assertion:nice-cg185-has-edition-2025-09-02", "hu:rel:nice-cg185-edition-2025-09-02", "hu:locator:nice-cg185-using-lithium",
           DT("2025-09-02T00:00:00Z"), "DAY", "STATED_BY_SOURCE", None, None, "UNKNOWN")

def nice_steps(slug="nice-cg185"):
    base = Step(slug, "baseline-tests-when-starting", {"name": "Baseline tests when starting lithium", "stepKind": "TEST", "requirementLevel": "RECOMMENDED",
                "speechAct": "RECOMMENDS", "stepDescription": "measure the person's weight or BMI and arrange tests for urea and electrolytes including calcium, eGFR, thyroid function and a full blood count",
                "schedulePattern": "ONE_TIME", "timingText": "When starting lithium"})
    start = Step(slug, "start-lithium", {"name": "Start lithium", "stepKind": "ADMINISTER", "requirementLevel": "NOT_STATED", "requirementBasis": "NOT_STATED",
                 "speechAct": "STATES", "schedulePattern": "ONE_TIME"},
                 uses=[("ChemicalSubstance", "hu:substance:lithium", {"verbatimDoseText": "dose not stated in CG185 (titrated to plasma level)"})],
                 deps=[("baseline-tests-when-starting", "REQUIRES_RESULT_OF", {"dependencyBasis": "EDITORIAL_INFERENCE", "notes": "1.10.14 says 'When starting lithium'"})])
    titr = Step(slug, "plasma-lithium-titration-checks", {"name": "Plasma lithium after start and after each dose change", "stepKind": "TEST",
                "requirementLevel": "RECOMMENDED", "speechAct": "RECOMMENDS", "schedulePattern": "EVENT_DRIVEN", "cadenceUnit": "WEEK",
                "cadenceIntervalMin": 1, "cadenceIntervalMax": 1, "repeatUntilText": "weekly until the levels are stable",
                "scheduleText": "Measure plasma lithium levels 1 week after starting lithium and 1 week after every dose change, and weekly until the levels are stable."},
                employs=[], deps=[("start-lithium", "REQUIRES_PRIOR_COMPLETION", {"lagMin": 1, "lagMax": 1, "lagUnit": "WEEK", "dependencyBasis": "STATED_BY_SOURCE"})])
    y1 = Step(slug, "plasma-lithium-year1", {"name": "Plasma lithium every 3 months in the first year", "stepKind": "TEST", "requirementLevel": "RECOMMENDED",
              "speechAct": "RECOMMENDS", "schedulePattern": "RECURRING", "cadenceUnit": "MONTH", "cadenceIntervalMin": 3, "cadenceIntervalMax": 3,
              "durationDaysMin": 365, "durationDaysMax": 366, "scheduleText": "Measure the person's plasma lithium level every 3 months for the first year."},
              deps=[("start-lithium", "REQUIRES_PRIOR_COMPLETION", {"dependencyBasis": "STATED_BY_SOURCE"})])
    return base, start, titr, y1

# ------------------------------------------------------------------------------------------------
# F03 repeated step plus prerequisite
# ------------------------------------------------------------------------------------------------
def f03():
    fx = Fx("03", hdr("03", "repeated step plus prerequisite (NICE CG185 1.10.14-1.10.19; Blueprint HBOT 60 sessions)",
                      "W16-S06 NICE CG185 recommendations (PARTIAL_EXCERPT), W16-S01 Blueprint live page"))
    nice_base(fx)
    base, start, titr, y1 = nice_steps()
    steps = [base, start, titr, y1]
    for s in steps: s.emit(fx)
    r = {s.key: s for s in steps}
    for s in steps: emit_deps(fx, s, r)
    fx.node("Target", "hu:target:nice-cg185-plasma-lithium-0.6-0.8", {"name": "Plasma lithium 0.6-0.8 mmol/L (first-time lithium)", "lowerBound": 0.6, "upperBound": 0.8,
            "unitCode": "mmol/L", "targetText": "Aim to maintain plasma lithium level between 0.6 and 0.8 mmol per litre in people being prescribed lithium for the first time."})
    fx.edge("Target", "hu:target:nice-cg185-plasma-lithium-0.6-0.8", "FOR_METRIC", "Metric", "hu:metric:plasma-lithium-substance-concentration")
    nice_attach(fx, [(base, {"sourceStepLabel": "1.10.14"}), (start, {"sourceStepLabel": "1.10.14"}), (titr, {"sourceStepLabel": "1.10.15"}), (y1, {"sourceStepLabel": "1.10.19"})],
                ["hu:target:nice-cg185-plasma-lithium-0.6-0.8"])
    fx.edge("ProtocolEdition", NE, "HAS_TARGET", "Target", "hu:target:nice-cg185-plasma-lithium-0.6-0.8", {"orderIndex": 1})
    fx.c("Blueprint HBOT: repetition with a total count, a weekly frequency and a session length (no dependency loop).")
    P = blueprint_base(fx)
    fx.node("ToolOrInstrument", "hu:instrument:hpo-tech-hard-shell-chamber", {"name": "HPO Tech hard shell hyperbaric chamber"})
    hbot = Step("blueprint", "hbot-course", {"name": "HBOT course", "stepKind": "OTHER", "stepKindRaw": "HYPERBARIC_OXYGEN", "requirementLevel": "NOT_STATED",
                "requirementBasis": "NOT_STATED", "speechAct": "REPORTS_PRACTICE", "schedulePattern": "RECURRING", "totalOccurrencesMin": 60, "totalOccurrencesMax": 60,
                "occurrencesPerPeriodMin": 5, "occurrencesPerPeriodMax": 5, "occurrencePeriodUnit": "WEEK", "durationMinutesMin": 90, "durationMinutesMax": 90,
                "scheduleText": "Schedule: 60 sessions, 5 sessions per week, duration: 90 min (20 min followed by 5 min air break, repeat)."},
                employs=[("ToolOrInstrument", "hu:instrument:hpo-tech-hard-shell-chamber")])
    hbot.emit(fx)
    edition(fx, "hu:protocol-edition:blueprint-observed-2026-10-04", None, "SNAPSHOT_DIFF", [(hbot, {"sectionLabel": "HBOT Protocol"})])
    fx.c("NEGATIVE (expected V-528p ORDERING_CYCLE and V-527p SELF_DEPENDENCY): repetition encoded as a self-dependency in a separate edition.")
    neg = Step("nice-cg185-neg", "plasma-lithium-loop", {"name": "NEG quarterly lithium as self-loop", "stepKind": "TEST", "requirementLevel": "RECOMMENDED"})
    neg.emit(fx)
    edition(fx, "hu:protocol-edition:nice-cg185-neg-loop", "NEG", "SOURCE_VERSIONED", [(neg, {})])
    fx.edge("ProtocolStep", neg.uid, "DEPENDS_ON", "ProtocolStep", neg.uid, {"dependencyKind": "REQUIRES_PRIOR_COMPLETION"})
    fx.c("Q-W16-03 (CQ-PR-02): repeated steps with their repetition structure and prerequisites (kind, lag) in one edition.")
    fx.raw(f"""MATCH (e:ProtocolEdition {{uid: '{NE}'}})-[o:HAS_PROTOCOL_STEP]->(s:ProtocolStep)
OPTIONAL MATCH (s)-[d:DEPENDS_ON]->(t:ProtocolStep)
WITH s, o, collect(CASE WHEN t IS NULL THEN null ELSE {{on: t.stepKey, kind: d.dependencyKind, lag: toString(d.lagMin) + '..' + toString(d.lagMax) + ' ' + coalesce(d.lagUnit, '')}} END) AS prereqs
RETURN s.stepKey AS stepKey, o.sourceStepLabel AS rec, s.schedulePattern AS pattern, s.cadenceIntervalMin AS cadMin, s.cadenceIntervalMax AS cadMax, s.cadenceUnit AS unit,
       s.repeatUntilText AS repeatUntil, s.durationDaysMin AS courseDaysMin, prereqs ORDER BY o.orderIndex""")
    fx.c("Q-W16-03b: HBOT repetition fields.")
    fx.raw(f"""MATCH (s:ProtocolStep {{uid: '{hbot.uid}'}})-[:EMPLOYS]->(i)
RETURN s.stepKey AS stepKey, s.totalOccurrencesMin AS total, s.occurrencesPerPeriodMin AS perPeriod, s.occurrencePeriodUnit AS period, s.durationMinutesMin AS minutes, i.name AS instrument""")
    fx.write(f"{OUT}/03-repeated-step-plus-prerequisite.cypher")

# ------------------------------------------------------------------------------------------------
# F04 conditional branch plus missing condition
# ------------------------------------------------------------------------------------------------
GROUPS = [("older-people", "POPULATION", "older people"), ("interacting-drugs", "CO_INTERVENTION", "people taking drugs that interact with lithium"),
          ("renal-thyroid-risk", "CONDITION_PRESENT", "people who are at risk of impaired renal or thyroid function, raised calcium levels or other complications"),
          ("poor-symptom-control", "CONDITION_PRESENT", "people who have poor symptom control"),
          ("poor-adherence", "POPULATION", "people with poor adherence"),
          ("last-level-gte-0.8", "MEASUREMENT_THRESHOLD", "people whose last plasma lithium level was 0.8 mmol per litre or higher")]

EVAL_QUERY = """MATCH (e:ProtocolEdition {uid: $e})-[:HAS_PROTOCOL_STEP]->(s:ProtocolStep {requirementLevel: 'CONDITIONAL'})
MATCH (s)-[r:HAS_CONSTRAINT {constraintRole: 'APPLIES_WHEN'}]->(c:Constraint)
WITH s, coalesce(r.conditionGroup, c.uid) AS grp,
     CASE WHEN c.uid IN $trueFacts THEN (CASE WHEN coalesce(r.negated, false) THEN false ELSE true END)
          WHEN c.uid IN $falseFacts THEN (CASE WHEN coalesce(r.negated, false) THEN true ELSE false END)
          ELSE null END AS lit, c.uid AS cuid
WITH s, grp, collect({v: lit}) AS litMaps, collect(CASE WHEN lit IS NULL THEN cuid END) AS unknownFacts
WITH s, grp, [m IN litMaps | m.v] AS lits, unknownFacts
WITH s, unknownFacts, CASE WHEN any(x IN lits WHERE x = true) THEN 'T' WHEN all(x IN lits WHERE x = false) THEN 'F' ELSE 'U' END AS g
WITH s, collect(g) AS groups, [u IN collect(unknownFacts) | u] AS uf
RETURN s.stepKey AS stepKey,
       CASE WHEN 'F' IN groups THEN 'DOES_NOT_APPLY' WHEN all(x IN groups WHERE x = 'T') THEN 'APPLIES' ELSE 'UNKNOWN_MISSING_FACT' END AS applicability,
       reduce(acc = [], l IN uf | acc + l) AS missingFactConstraintUids
ORDER BY stepKey"""

def f04():
    fx = Fx("04", hdr("04", "conditional branch plus missing condition (NICE CG185 1.10.20 else-branch; Blueprint MRI disjunction)",
                      "W16-S06 NICE CG185, W16-S01 Blueprint live page (Routine Measurement)"))
    nice_base(fx)
    base, start, titr, y1 = nice_steps()
    for g, kind, text in GROUPS:
        props = {"name": text, "constraintKind": kind, "constraintText": text}
        if g == "last-level-gte-0.8": props.update({"comparator": "GTE", "thresholdValue": 0.8, "thresholdUnitCode": "mmol/L"})
        fx.node("Constraint", f"hu:constraint:nice-cg185-{g}", props)
    fx.edge("Constraint", "hu:constraint:nice-cg185-last-level-gte-0.8", "BASED_ON", "Metric", "hu:metric:plasma-lithium-substance-concentration")
    std = Step("nice-cg185", "plasma-lithium-after-year1-standard", {"name": "Plasma lithium every 6 months after year 1", "stepKind": "TEST", "requirementLevel": "CONDITIONAL",
               "speechAct": "RECOMMENDS", "schedulePattern": "RECURRING", "cadenceUnit": "MONTH", "cadenceIntervalMin": 6, "cadenceIntervalMax": 6,
               "scheduleText": "After the first year, measure plasma lithium levels every 6 months, or every 3 months for people in any of the following groups"},
               constraints=[(f"hu:constraint:nice-cg185-{g}", "APPLIES_WHEN", f"n{i}", True) for i, (g, _, _) in enumerate(GROUPS)],
               deps=[("plasma-lithium-year1", "REQUIRES_PRIOR_COMPLETION", {"dependencyBasis": "STATED_BY_SOURCE"}),
                     ("plasma-lithium-after-year1-intensive", "MUTUALLY_EXCLUSIVE_WITH", {"dependencyBasis": "STATED_BY_SOURCE"})])
    inten = Step("nice-cg185", "plasma-lithium-after-year1-intensive", {"name": "Plasma lithium every 3 months after year 1 (risk groups)", "stepKind": "TEST",
                 "requirementLevel": "CONDITIONAL", "speechAct": "RECOMMENDS", "schedulePattern": "RECURRING", "cadenceUnit": "MONTH", "cadenceIntervalMin": 3,
                 "cadenceIntervalMax": 3, "scheduleText": "or every 3 months for people in any of the following groups"},
                 constraints=[(f"hu:constraint:nice-cg185-{g}", "APPLIES_WHEN", "any-risk-group", False) for (g, _, _) in GROUPS],
                 deps=[("plasma-lithium-year1", "REQUIRES_PRIOR_COMPLETION", {"dependencyBasis": "STATED_BY_SOURCE"})])
    steps = [base, start, titr, y1, std, inten]
    for s in steps: s.emit(fx)
    r = {s.key: s for s in steps}
    for s in steps: emit_deps(fx, s, r)
    nice_attach(fx, [(s, {}) for s in steps])
    fx.c("Blueprint: 'Full body MRI annually (if over 40 or a family history of high risk)' = two APPLIES_WHEN constraints in ONE disjunction group.")
    P = blueprint_base(fx)
    fx.node("Constraint", "hu:constraint:blueprint-age-over-40", {"name": "over 40", "constraintKind": "POPULATION", "constraintText": "if over 40",
            "comparator": "GT", "thresholdValue": 40.0, "thresholdUnitCode": "a"})
    fx.node("Constraint", "hu:constraint:blueprint-family-history-high-risk", {"name": "family history of high risk", "constraintKind": "CONDITION_PRESENT",
            "constraintText": "a family history of high risk"})
    mri = Step("blueprint", "full-body-mri-annual", {"name": "Full body MRI annually", "stepKind": "TEST", "stepKindRaw": "IMAGING", "requirementLevel": "CONDITIONAL",
               "speechAct": "STATES", "schedulePattern": "RECURRING", "cadenceUnit": "MONTH", "cadenceIntervalMin": 12, "cadenceIntervalMax": 12,
               "scheduleText": "Full body MRI annually (if over 40 or a family history of high risk)"},
               constraints=[("hu:constraint:blueprint-age-over-40", "APPLIES_WHEN", "g1", False), ("hu:constraint:blueprint-family-history-high-risk", "APPLIES_WHEN", "g1", False)])
    mole_neg = Step("blueprint-neg", "mole-check-annual", {"name": "NEG conditional step with no condition", "stepKind": "TEST", "requirementLevel": "CONDITIONAL",
                    "scheduleText": "Mole check, annually"})
    mri.emit(fx); mole_neg.emit(fx)
    BE = "hu:protocol-edition:blueprint-observed-2026-10-04"
    edition(fx, BE, None, "SNAPSHOT_DIFF", [(mri, {"sectionLabel": "Routine Measurement", "sourceStepLabel": "2"})])
    fx.c("NEGATIVE (expected V-525p CONDITIONAL_STEP_WITHOUT_CONDITION): a CONDITIONAL step with no APPLIES_WHEN constraint (missing condition).")
    edition(fx, "hu:protocol-edition:blueprint-neg-missing-condition", "NEG", "SOURCE_VERSIONED", [(mole_neg, {})])
    fx.c("Q-W16-04a (CQ-PR-02): conditional steps with their CNF condition structure (group, negation, kind, threshold).")
    fx.raw(f"""MATCH (s:ProtocolStep {{requirementLevel: 'CONDITIONAL'}})-[r:HAS_CONSTRAINT]->(c:Constraint)
RETURN s.stepKey AS stepKey, r.constraintRole AS role, coalesce(r.conditionGroup, c.uid) AS orGroup, coalesce(r.negated, false) AS negated,
       c.constraintKind AS kind, c.comparator AS cmp, c.thresholdValue AS threshold, c.thresholdUnitCode AS unit
ORDER BY stepKey, orGroup, c.uid""")
    fx.c("Q-W16-04b: three-valued evaluation of the NICE branches against a HYPOTHETICAL non-personal fact set (in production the private store runs this\n"
         "with the person's facts; nothing is written back). Case 1: last level >= 0.8 true, the other five false.")
    t1 = "['hu:constraint:nice-cg185-last-level-gte-0.8']"
    f1 = "[" + ", ".join(f"'hu:constraint:nice-cg185-{g}'" for g, _, _ in GROUPS if g != "last-level-gte-0.8") + "]"
    fx.raw(EVAL_QUERY.replace("$e", f"'{NE}'").replace("$trueFacts", t1).replace("$falseFacts", f1))
    fx.c("Q-W16-04c: Case 2: four groups known false, 'older people' and 'poor adherence' not declared -> both branches UNKNOWN (missing fact), never DOES_NOT_APPLY.")
    f2 = "[" + ", ".join(f"'hu:constraint:nice-cg185-{g}'" for g, _, _ in GROUPS if g not in ("older-people", "poor-adherence")) + "]"
    fx.raw(EVAL_QUERY.replace("$e", f"'{NE}'").replace("$trueFacts", "[]").replace("$falseFacts", f2))
    fx.c("Q-W16-04d: Blueprint MRI disjunction with only 'family history' known true -> APPLIES although age is unknown.")
    fx.raw(EVAL_QUERY.replace("$e", f"'{BE}'").replace("$trueFacts", "['hu:constraint:blueprint-family-history-high-risk']").replace("$falseFacts", "[]"))
    fx.c("Q-W16-04e (CQ-PR-03, shared part): facts a person would have to declare before conditional steps of an edition can be evaluated.")
    fx.raw(f"""MATCH (e:ProtocolEdition {{uid: '{NE}'}})-[:HAS_PROTOCOL_STEP]->(s:ProtocolStep {{requirementLevel: 'CONDITIONAL'}})-[:HAS_CONSTRAINT]->(c:Constraint)
OPTIONAL MATCH (c)-[:BASED_ON]->(b)
RETURN c.uid AS constraintUid, c.constraintKind AS kind, collect(DISTINCT s.stepKey) AS gatesSteps, b.uid AS resolvableVia,
       CASE WHEN b IS NULL AND c.thresholdValue IS NULL THEN 'TEXT_ONLY_FACT' ELSE 'STRUCTURED_FACT' END AS factForm
ORDER BY constraintUid""")
    fx.write(f"{OUT}/04-conditional-branch-missing-condition.cypher")

# ------------------------------------------------------------------------------------------------
# F05 parallel steps (CONCURRENT_WITH); practice vs recommendation
# ------------------------------------------------------------------------------------------------
def f05():
    fx = Fx("05", hdr("05", "parallel steps CONCURRENT_WITH (Blueprint sauna + ice pack), practice vs recommendation, contraindications",
                      "W16-S01 Blueprint live page (Sauna; 7:30 am routine), W16-S02 Wayback capture"))
    P = blueprint_base(fx)
    fx.node("Constraint", "hu:constraint:blueprint-sauna-serious-heart-issues", {"name": "serious heart issues or uncontrolled blood pressure", "constraintKind": "CONDITION_PRESENT",
            "constraintText": "Have serious heart issues or uncontrolled blood pressure"})
    fx.node("Constraint", "hu:constraint:blueprint-sauna-pregnant", {"name": "pregnant", "constraintKind": "PHASE", "constraintText": "Are pregnant (consult your doctor)"})
    fx.node("Constraint", "hu:constraint:blueprint-sauna-beta-blockers", {"name": "taking beta blockers, stimulants, anticholinergics, or diuretics",
            "constraintKind": "CO_INTERVENTION", "constraintText": "Are taking medications such as beta blockers, stimulants, anticholinergics, or diuretics"})
    contra = [(c, "CONTRAINDICATED_WHEN", "avoid-if-any", False) for c in
              ["hu:constraint:blueprint-sauna-serious-heart-issues", "hu:constraint:blueprint-sauna-pregnant", "hu:constraint:blueprint-sauna-beta-blockers"]]
    sauna = Step("blueprint", "dry-sauna-daily", {"name": "Dry sauna (author practice)", "stepKind": "OTHER", "stepKindRaw": "SAUNA", "requirementLevel": "NOT_STATED",
                 "requirementBasis": "NOT_STATED", "speechAct": "REPORTS_PRACTICE", "schedulePattern": "DAILY", "occurrencesPerPeriodMin": 7, "occurrencesPerPeriodMax": 7,
                 "occurrencePeriodUnit": "WEEK", "durationMinutesMin": 20, "durationMinutesMax": 20, "timingText": "7:30 am",
                 "scheduleText": "Temperature: 200F (93C); Frequency: daily, 7 days a week; Duration: 20 minute sessions"}, constraints=contra)
    ice = Step("blueprint", "groin-ice-pack-during-sauna", {"name": "Ice pack on groin during sauna", "stepKind": "APPLY", "requirementLevel": "NOT_STATED",
               "requirementBasis": "NOT_STATED", "speechAct": "REPORTS_PRACTICE", "scheduleText": "Protection: Ice pack applied to the groin area to safeguard testicular and sperm health."},
               deps=[("dry-sauna-daily", "CONCURRENT_WITH", {"dependencyBasis": "STATED_BY_SOURCE"})])
    rehyd = Step("blueprint", "rehydrate-after-sauna", {"name": "Rehydrate after sauna", "stepKind": "INGEST", "requirementLevel": "NOT_STATED", "requirementBasis": "NOT_STATED",
                 "speechAct": "REPORTS_PRACTICE", "scheduleText": "Rehydration: 36 oz mineral supplemented water"},
                 deps=[("dry-sauna-daily", "REQUIRES_PRIOR_COMPLETION", {"lagMin": 0, "lagUnit": "HOUR", "dependencyBasis": "STATED_BY_SOURCE"})])
    tips = Step("blueprint", "sauna-reader-guidance", {"name": "Sauna guidance for readers", "stepKind": "OTHER", "stepKindRaw": "SAUNA", "requirementLevel": "RECOMMENDED",
                "speechAct": "RECOMMENDS", "schedulePattern": "WEEKLY", "occurrencesPerPeriodMin": 3, "occurrencesPerPeriodMax": 5, "occurrencePeriodUnit": "WEEK",
                "durationMinutesMin": 15, "durationMinutesMax": 20,
                "scheduleText": "Aim for 3 to 5 sauna sessions per week, lasting about 15 to 20 minutes each, at 175-194F (80-90C)"}, constraints=contra)
    steps = [sauna, ice, rehyd, tips]
    for s in steps: s.emit(fx)
    r = {s.key: s for s in steps}
    for s in steps: emit_deps(fx, s, r)
    BE = "hu:protocol-edition:blueprint-observed-2026-10-04"
    edition(fx, BE, None, "SNAPSHOT_DIFF", [(sauna, {"sectionLabel": "My sauna protocol"}), (ice, {"sectionLabel": "My sauna protocol"}),
                                           (rehyd, {"sectionLabel": "My sauna protocol"}), (tips, {"sectionLabel": "Tips for you"})])
    fx.c("NEGATIVE (expected V-531p EXCLUSIVE_AND_CONCURRENT_WITH): a second edition where the same pair is both concurrent and mutually exclusive.")
    a = Step("blueprint-neg", "red-light", {"name": "NEG red light", "stepKind": "APPLY", "requirementLevel": "OPTIONAL"},
             deps=[("shockwave", "CONCURRENT_WITH", None), ("shockwave", "MUTUALLY_EXCLUSIVE_WITH", None)])
    b = Step("blueprint-neg", "shockwave", {"name": "NEG shockwave", "stepKind": "APPLY", "requirementLevel": "OPTIONAL"})
    a.emit(fx); b.emit(fx)
    edition(fx, "hu:protocol-edition:blueprint-neg-contradiction", "NEG", "SOURCE_VERSIONED", [(a, {}), (b, {})])
    fx.edge("ProtocolStep", a.uid, "DEPENDS_ON", "ProtocolStep", b.uid, {"dependencyKind": "CONCURRENT_WITH"})
    fx.raw(f"MATCH (a:ProtocolStep {{uid: '{a.uid}'}}), (b:ProtocolStep {{uid: '{b.uid}'}}) CREATE (a)-[:DEPENDS_ON {{dependencyKind: 'MUTUALLY_EXCLUSIVE_WITH'}}]->(b)")
    fx.c("Q-W16-05a: parallel groups (CONCURRENT_WITH, symmetric) and sequence (ordering kinds) for one edition.")
    fx.raw(f"""MATCH (e:ProtocolEdition {{uid: '{BE}'}})-[:HAS_PROTOCOL_STEP]->(s:ProtocolStep)-[d:DEPENDS_ON]->(t:ProtocolStep)
RETURN s.stepKey AS step, d.dependencyKind AS kind, t.stepKey AS other,
       CASE d.dependencyKind WHEN 'CONCURRENT_WITH' THEN 'PARALLEL' WHEN 'MUTUALLY_EXCLUSIVE_WITH' THEN 'ALTERNATIVE' ELSE 'SEQUENTIAL' END AS structure
ORDER BY structure, step""")
    fx.c("Q-W16-05b: what the source RECOMMENDS to readers vs what the author REPORTS doing (a practice report is not a recommendation).")
    fx.raw(f"""MATCH (e:ProtocolEdition {{uid: '{BE}'}})-[:HAS_PROTOCOL_STEP]->(s:ProtocolStep)
WHERE s.stepKindRaw = 'SAUNA'
RETURN s.stepKey AS stepKey, s.speechAct AS speechAct, s.occurrencesPerPeriodMin AS perWeekMin, s.occurrencesPerPeriodMax AS perWeekMax,
       s.durationMinutesMin AS minMin, s.durationMinutesMax AS minMax ORDER BY speechAct""")
    fx.c("Q-W16-05c (CQ-RC-06 shared part): contraindication constraint uids that would BLOCK the sauna steps (any one suffices: one OR group).")
    fx.raw(f"""MATCH (s:ProtocolStep)-[r:HAS_CONSTRAINT {{constraintRole: 'CONTRAINDICATED_WHEN'}}]->(c:Constraint)
RETURN s.stepKey AS stepKey, r.conditionGroup AS orGroup, collect(c.uid) AS blockingConstraintUids ORDER BY stepKey""")
    fx.write(f"{OUT}/05-parallel-steps-concurrent.cypher")

# ------------------------------------------------------------------------------------------------
# F06 optional step omitted without declaring non-adherence
# ------------------------------------------------------------------------------------------------
def f06():
    fx = Fx("06", hdr("06", "optional step omitted without falsely declaring non-adherence (public template only)",
                      "INHERITED synthetic evening wind-down protocol (docs/schema/examples/recommendation-snapshot.cypher 1.12); SYNTHETIC public-host report"))
    P = "hu:protocol:synthetic-evening-wind-down"
    fx.node("Protocol", P, {"name": "Evening wind-down protocol (synthetic)", "protocolType": "SLEEP_PROTOCOL"})
    fx.node("Person", "hu:person:synthetic-podcast-host", {"name": "Synthetic Podcast Host"})
    fx.source("hu:source:synthetic-wind-down-protocol-page", "https://example.invalid/wind-down", "Evening wind-down protocol page (synthetic)", "SELF_DISCLOSURE_PAGE",
              "hu:snapshot:synthetic-wind-down-page-2026-03-01", "2026-03-01T12:00:00Z", "2026-03-01T12:00:00Z", "COMPLETE",
              "hu:locator:synthetic-wind-down-page-steps", ("SECTION", "Steps"))
    fx.source("hu:source:synthetic-sleep-podcast-episode-12", "https://example.invalid/sleep-podcast/12", "Synthetic sleep podcast, episode 12", "PODCAST_TRANSCRIPT_PAGE",
              "hu:snapshot:synthetic-sleep-podcast-12", "2026-03-05T00:00:00Z", "2026-03-05T00:00:00Z", "COMPLETE",
              "hu:locator:synthetic-sleep-podcast-12-q", ("TEXT_QUOTE", "I skip the screen-free hour most nights"))
    screen = Step("synthetic-wind-down", "screen-free-hour", {"name": "Screen-free hour before bed", "stepKind": "AVOID", "requirementLevel": "OPTIONAL",
                  "speechAct": "RECOMMENDS", "timeOfDay": "EVENING", "durationMinutesMin": 60, "durationMinutesMax": 60})
    bed = Step("synthetic-wind-down", "fixed-bedtime", {"name": "Fixed bedtime", "stepKind": "SLEEP", "requirementLevel": "ESSENTIAL", "speechAct": "RECOMMENDS", "timeOfDay": "BEDTIME"})
    for s in (screen, bed): s.emit(fx)
    E = "hu:protocol-edition:synthetic-evening-wind-down-e1"
    edition(fx, E, "v1", "SOURCE_VERSIONED", [(screen, {}), (bed, {})])
    attach(fx, P, E, "hu:assertion:synthetic-wind-down-edition-1", "hu:rel:synthetic-wind-down-ed1", "hu:locator:synthetic-wind-down-page-steps",
           DT("2025-09-01T00:00:00Z"), "MONTH", "STATED_BY_SOURCE", None, None, "UNKNOWN")
    fx.c("A PUBLIC person's published practice report about skipping the optional step: an Assertion (REPORTS_PRACTICE) about that person, not an adherence flag.")
    fx.assertion("hu:assertion:synthetic-host-skips-screen-free-hour", "REPORTS_PRACTICE_OF_STEP", ("Person", "hu:person:synthetic-podcast-host"),
                 ("ProtocolStep", screen.uid), {"polarity": "NEGATIVE", "speechAct": "REPORTS_PRACTICE", "assertionBasis": "PERSONAL_EXPERIENCE",
                                                "validFromBasis": "UNKNOWN", "validToBasis": "UNKNOWN"}, ["hu:locator:synthetic-sleep-podcast-12-q"],
                 ("Person", "hu:person:synthetic-podcast-host"))
    fx.c("NEGATIVE (expected V-534p rows): adherence written onto the public template and an execution edge into a public step.")
    neg = Step("synthetic-wind-down-neg", "screen-free-hour", {"name": "NEG step carrying adherence", "stepKind": "AVOID", "requirementLevel": "OPTIONAL",
               "omittedByUser": True, "adherence": "NON_ADHERENT"})
    neg.emit(fx)
    edition(fx, "hu:protocol-edition:synthetic-wind-down-neg", "NEG", "SOURCE_VERSIONED", [(neg, {})])
    fx.raw(f"MATCH (p:Person {{uid: 'hu:person:synthetic-podcast-host'}}), (s:ProtocolStep {{uid: '{screen.uid}'}}) MERGE (p)-[:OMITTED_STEP]->(s)")
    fx.c("Q-W16-06a: what the public template requires; an omitted OPTIONAL step is consistent with the template (no adherence verdict is computed).")
    fx.raw(f"""MATCH (e:ProtocolEdition {{uid: '{E}'}})-[:HAS_PROTOCOL_STEP]->(s:ProtocolStep)
RETURN s.stepKey AS stepKey, s.requirementLevel AS level, s.requirementBasis AS basis,
       CASE s.requirementLevel WHEN 'OPTIONAL' THEN 'OMISSION_CONSISTENT_WITH_TEMPLATE' WHEN 'ESSENTIAL' THEN 'TEMPLATE_REQUIRES' ELSE 'SEE_CONDITIONS' END AS templateReading
ORDER BY stepKey""")
    fx.c("Q-W16-06b: does the shared graph hold anyone's adherence for this edition? Expected: no adherence records; only a public practice report Assertion.")
    fx.raw(f"""MATCH (e:ProtocolEdition {{uid: '{E}'}})-[:HAS_PROTOCOL_STEP]->(s:ProtocolStep)
OPTIONAL MATCH (a:Assertion)-[:HAS_OBJECT]->(s)
RETURN s.stepKey AS stepKey, count(a) AS publicPracticeReports, 'ADHERENCE_NOT_IN_SHARED_GRAPH' AS adherence ORDER BY stepKey""")
    fx.write(f"{OUT}/06-optional-step-no-nonadherence.cypher")

# ------------------------------------------------------------------------------------------------
# F07 public research description vs private execution (leak probe)
# ------------------------------------------------------------------------------------------------
def f07():
    fx = Fx("07", hdr("07", "public description vs private execution kept outside the graph (LEAK PROBE: expected to FAIL V-113, V-520, V-521, V-524, V-534p)",
                      "W16-S01 Blueprint live page (HBOT results: 'Wiped out all systematic inflammation in my body, hsCRP below detectable levels.'); SYNTHETIC leak probes"))
    P = blueprint_base(fx)
    fx.node("Metric", "hu:metric:hscrp", {"name": "C reactive protein [Mass/volume] in Serum or Plasma by High sensitivity method"})
    fx.source("hu:source:blueprint-protocol-page", "https://blueprint.bryanjohnson.com/blogs/news/bryan-johnsons-protocol", "Bryan Johnson's Protocol", "SELF_DISCLOSURE_PAGE",
              "hu:snapshot:blueprint-protocol-2026-10-04", "2026-10-04T00:56:00Z", "2026-10-04T00:56:00Z", "PARTIAL_EXCERPT",
              "hu:locator:blueprint-protocol-2026-10-04-hbot-results", ("TEXT_QUOTE", "Wiped out all systematic inflammation in my body, hsCRP below detectable levels."))
    E = "hu:protocol-edition:blueprint-observed-2026-10-04"
    hbot = Step("blueprint", "hbot-course", {"name": "HBOT course", "stepKind": "OTHER", "requirementLevel": "NOT_STATED", "requirementBasis": "NOT_STATED", "speechAct": "REPORTS_PRACTICE"})
    hbot.emit(fx)
    edition(fx, E, None, "SNAPSHOT_DIFF", [(hbot, {})])
    attach(fx, P, E, "hu:assertion:blueprint-has-edition-2026-10-04", "hu:rel:blueprint-edition-2026-10-04", "hu:locator:blueprint-protocol-2026-10-04-hbot-results",
           None, None, "OBSERVATION_ONLY", None, None, "UNKNOWN")
    fx.c("Public, source-attributed Observation by a public person (allowed): implements DiagnosticResult; valueStatus REPORTED, no number given.")
    fx.node("Observation", "hu:observation:blueprint-hscrp-after-hbot", {"name": "hsCRP after 60 HBOT sessions (self-reported)", "observationType": "PUBLISHED_SELF_REPORT",
            "observedPopulation": "protocol author, self-reported", "resultKind": "MEASURED", "valueStatus": "REPORTED", "valueText": "hsCRP below detectable levels",
            "publishedAt": None})
    fx.edge("Observation", "hu:observation:blueprint-hscrp-after-hbot", "MEASURES_METRIC", "Metric", "hu:metric:hscrp")
    fx.edge("Observation", "hu:observation:blueprint-hscrp-after-hbot", "ABOUT_PROTOCOL", "ProtocolEdition", E)
    fx.assertion("hu:assertion:bj-records-hscrp-observation", "RECORDS", ("Person", "hu:person:bryan-johnson"), ("Observation", "hu:observation:blueprint-hscrp-after-hbot"),
                 {"speechAct": "REPORTS_PRACTICE", "assertionBasis": "PERSONAL_EXPERIENCE", "validFromBasis": "UNKNOWN", "validToBasis": "UNKNOWN"},
                 ["hu:locator:blueprint-protocol-2026-10-04-hbot-results"], ("Person", "hu:person:bryan-johnson"))
    fx.asserted_edge("Person", "hu:person:bryan-johnson", "RECORDS", "Observation", "hu:observation:blueprint-hscrp-after-hbot", "hu:assertion:bj-records-hscrp-observation",
                     "hu:rel:bj-records-hscrp")
    fx.c("LEAK PROBE 1 (expected V-520 + V-521): a private ProtocolInUse written into the shared graph without the fixture-only PrivateRecord label.")
    fx.raw("MERGE (n:ProtocolInUse:Entity {uid: 'hu:private-protocol-in-use:leak-probe-1'}) SET n += {id: 'leak-probe-1', privacyClass: 'private-personal', entityType: 'ProtocolInUse', createdAt: datetime('2026-10-04T01:00:00Z')}")
    fx.c("LEAK PROBE 2 (expected V-113 + V-534p): a shared edition pointing at the private adoption.")
    fx.raw(f"MATCH (e:ProtocolEdition {{uid: '{E}'}}), (n:ProtocolInUse {{uid: 'hu:private-protocol-in-use:leak-probe-1'}}) MERGE (e)-[:ADOPTED_IN_PRIVATE]->(n)")
    fx.c("LEAK PROBE 3 (expected V-524 + V-520 + V-521): a personal measurement collapsed into the public Observation label.")
    fx.raw("MERGE (n:Observation:PersonalMeasurement:InformationArtifact {uid: 'hu:private-personal-measurement:leak-probe-2'}) SET n += {id: 'leak-probe-2', privacyClass: 'private-personal', artifactType: 'PersonalMeasurement', valueNumber: 0.4, unitCode: 'mg/L', createdAt: datetime('2026-10-04T01:00:00Z')}")
    fx.c("LEAK PROBE 4 (expected V-521 + V-534p): a private deviation uid stored on a public step.")
    fx.raw(f"MATCH (s:ProtocolStep {{uid: '{hbot.uid}'}}) SET s.lastDeviationUid = 'hu:private-protocol-deviation:leak-probe-3'")
    fx.c("Q-W16-07a (QS-6a defence in depth): 2-hop traversal from the public edition never returns a private node even while probes are present.")
    fx.raw(f"""MATCH (s {{uid: '{E}'}})
WHERE NOT (s.uid STARTS WITH 'hu:private-' OR s.privacyClass = 'private-personal' OR s:PrivateRecord)
MATCH p = (s)(()-[r]-(n) WHERE NOT (n.uid STARTS WITH 'hu:private-' OR n.privacyClass = 'private-personal' OR n:PrivateRecord)){{1,2}}
RETURN count(DISTINCT last(nodes(p))) AS reachableNodes, any(x IN collect(DISTINCT last(nodes(p)).uid) WHERE x STARTS WITH 'hu:private-') AS reachesPrivate""")
    fx.c("Q-W16-07b (CQ-AX-22 shared part): which public edition did a public result/observation use; the private store sends only the edition uid.")
    fx.raw(f"""MATCH (o:Observation)-[:ABOUT_PROTOCOL]->(e:ProtocolEdition) WHERE NOT o:PersonalMeasurement
MATCH (:Person)-[r:RECORDS]->(o)
RETURN o.uid AS observationUid, e.uid AS editionUid, r.assertionUid AS attribution, ('{E}' = e.uid) AS sameEditionAsQueried""")
    fx.write(f"{OUT}/07-public-vs-private-leak-probe.cypher")

# ------------------------------------------------------------------------------------------------
# F08 device / assay / formulation version change referenced by a step
# ------------------------------------------------------------------------------------------------
def f08():
    fx = Fx("08", hdr("08", "device/assay/formulation version change referenced by a step (pinned vs floating binding)",
                      "W16-S01 Blueprint live page (Longevity Mix 1 scoop; HPO Tech chamber); SYNTHETIC formulation versions, assay versions and chamber model change"))
    P = blueprint_base(fx)
    fx.node("Product", "hu:product:blueprint-longevity-mix", {"name": "Blueprint Longevity Mix"})
    fx.node("ProductVariant", "hu:product-variant:blueprint-longevity-mix-blood-orange", {"name": "Longevity Mix - Blood Orange"})
    fx.node("FormulationVersion", "hu:formulation:longevity-mix-blood-orange-synthetic-f1", {"payloadHash": sha("f1"), "name": "SYNTHETIC formulation f1"})
    fx.node("FormulationVersion", "hu:formulation:longevity-mix-blood-orange-synthetic-f2", {"payloadHash": sha("f2"), "name": "SYNTHETIC formulation f2"})
    for f, rel, vf, vt in [("f1", "hu:rel:lm-f1", "2025-06-01T00:00:00Z", "2026-06-01T00:00:00Z"), ("f2", "hu:rel:lm-f2", "2026-06-01T00:00:00Z", None)]:
        fx.raw(f"""MATCH (v:ProductVariant {{uid: 'hu:product-variant:blueprint-longevity-mix-blood-orange'}}), (f:FormulationVersion {{uid: 'hu:formulation:longevity-mix-blood-orange-synthetic-{f}'}})
MERGE (v)-[r:HAS_FORMULATION_VERSION {{relationshipUid: '{rel}'}}]->(f)
SET r.assertionUid = 'hu:assertion:synthetic-lm-{f}', r.validFrom = datetime('{vf}'), r.validFromPrecision = 'DAY', r.validFromBasis = 'STATED_BY_SOURCE',
    r.validTo = {"datetime('" + vt + "')" if vt else 'null'}, r.validToPrecision = {"'DAY'" if vt else 'null'}, r.validToBasis = {"'STATED_BY_SOURCE'" if vt else "'UNKNOWN'"},
    r.recordedFrom = datetime('2026-10-04T01:00:00Z'), r.recordedTo = null""")
    fx.source("hu:source:blueprint-protocol-page", "https://blueprint.bryanjohnson.com/blogs/news/bryan-johnsons-protocol", "Bryan Johnson's Protocol", "SELF_DISCLOSURE_PAGE",
              "hu:snapshot:blueprint-protocol-2026-10-04", "2026-10-04T00:56:00Z", "2026-10-04T00:56:00Z", "PARTIAL_EXCERPT",
              "hu:locator:blueprint-protocol-2026-10-04-morning", ("SECTION", "Morning: 5:25 am (pre workout)"))
    fx.source("hu:source:wayback-blueprint-protocol-20260124", "https://web.archive.org/web/20260124052836/https://blueprint.bryanjohnson.com/blogs/news/bryan-johnsons-protocol",
              "Bryan Johnson's Protocol (Wayback 2026-01-24)", "SELF_DISCLOSURE_PAGE", "hu:snapshot:blueprint-protocol-wayback-2026-01-24", "2026-01-24T05:28:36Z",
              "2026-10-04T00:58:00Z", "PARTIAL_EXCERPT", "hu:locator:blueprint-protocol-wayback-2026-01-24-morning", ("SECTION", "Morning: 5:25 am (pre workout)"))
    mixf = Step("blueprint", "longevity-mix-pre-workout", {"name": "Longevity Mix drink", "stepKind": "INGEST", "requirementLevel": "NOT_STATED", "requirementBasis": "NOT_STATED",
                "speechAct": "REPORTS_PRACTICE", "timingText": "5:25 am (pre workout)"},
                uses=[("ProductVariant", "hu:product-variant:blueprint-longevity-mix-blood-orange", {"quantity": 1.0, "unitCode": "{scoop}", "quantityBasis": "PER_DOSE",
                       "massBasis": "MATERIAL_AS_IS", "route": "oral", "verbatimDoseText": "Blueprint Longevity Mix 1 scoop"})])
    mixp = Step("blueprint-synthetic-pinned", "longevity-mix-pre-workout", {"name": "Longevity Mix drink (SYNTHETIC pinned edition)", "stepKind": "INGEST",
                "requirementLevel": "NOT_STATED", "requirementBasis": "NOT_STATED", "speechAct": "REPORTS_PRACTICE"},
                uses=[("FormulationVersion", "hu:formulation:longevity-mix-blood-orange-synthetic-f1", {"quantity": 1.0, "unitCode": "{scoop}", "quantityBasis": "PER_DOSE",
                       "massBasis": "MATERIAL_AS_IS", "verbatimDoseText": "SYNTHETIC: formula f1, 1 scoop"})])
    fx.node("ToolOrInstrument", "hu:instrument:hpo-tech-hard-shell-chamber", {"name": "HPO Tech hard shell hyperbaric chamber"})
    fx.node("ToolOrInstrument", "hu:instrument:synthetic-soft-shell-chamber", {"name": "SYNTHETIC soft-shell chamber (model change)"})
    h1 = Step("blueprint", "hbot-course", {"name": "HBOT course", "stepKind": "OTHER", "requirementLevel": "NOT_STATED", "requirementBasis": "NOT_STATED", "speechAct": "REPORTS_PRACTICE"},
              employs=[("ToolOrInstrument", "hu:instrument:hpo-tech-hard-shell-chamber")], version=1)
    h2 = Step("blueprint", "hbot-course", {"name": "HBOT course", "stepKind": "OTHER", "requirementLevel": "NOT_STATED", "requirementBasis": "NOT_STATED", "speechAct": "REPORTS_PRACTICE"},
              employs=[("ToolOrInstrument", "hu:instrument:synthetic-soft-shell-chamber")], version=2)
    fx.node("LabTest", "hu:lab-test:synthetic-hscrp-lab-a", {"name": "hsCRP (SYNTHETIC lab A)"})
    fx.node("AssayVersion", "hu:assay-version:synthetic-hscrp-lab-a-2024", {"payloadHash": sha("av2024"), "name": "SYNTHETIC hsCRP assay 2024"})
    fx.node("AssayVersion", "hu:assay-version:synthetic-hscrp-lab-a-2025", {"payloadHash": sha("av2025"), "name": "SYNTHETIC hsCRP assay 2025 (new kit)"})
    draw = Step("blueprint", "routine-blood-draw", {"name": "Blood draw", "stepKind": "SAMPLE", "requirementLevel": "NOT_STATED", "requirementBasis": "NOT_STATED", "speechAct": "STATES",
                "cadenceUnit": "MONTH", "cadenceIntervalMin": 3, "cadenceIntervalMax": 6, "scheduleText": "Blood draw, every 3 to 6 months"},
                employs=[("LabTest", "hu:lab-test:synthetic-hscrp-lab-a")])
    for s in (mixf, mixp, h1, h2, draw): s.emit(fx)
    E1, E2 = "hu:protocol-edition:blueprint-observed-2026-01-24", "hu:protocol-edition:blueprint-observed-2026-10-04"
    edition(fx, E1, None, "SNAPSHOT_DIFF", [(mixf, {}), (h1, {}), (draw, {})])
    edition(fx, E2, None, "SNAPSHOT_DIFF", [(mixf, {}), (h2, {}), (draw, {})])
    edition(fx, "hu:protocol-edition:blueprint-synthetic-pinned", "SYNTHETIC-PINNED", "SOURCE_VERSIONED", [(mixp, {})])
    attach(fx, P, E1, "hu:assertion:blueprint-has-edition-2026-01-24", "hu:rel:blueprint-edition-2026-01-24", "hu:locator:blueprint-protocol-wayback-2026-01-24-morning",
           DT("2026-01-23T00:00:00Z"), "DAY", "PUBLICATION_PROXY", None, None, "UNKNOWN")
    attach(fx, P, E2, "hu:assertion:blueprint-has-edition-2026-10-04", "hu:rel:blueprint-edition-2026-10-04", "hu:locator:blueprint-protocol-2026-10-04-morning",
           None, None, "OBSERVATION_ONLY", None, None, "UNKNOWN")
    fx.c("Two public observations of the same metric produced by different assay versions (no ComparabilityAssessment).")
    for o, av, d in [("2024", "hu:assay-version:synthetic-hscrp-lab-a-2024", "2024-11-01T00:00:00Z"), ("2025", "hu:assay-version:synthetic-hscrp-lab-a-2025", "2025-03-01T00:00:00Z")]:
        fx.node("Observation", f"hu:observation:synthetic-hscrp-{o}", {"resultKind": "MEASURED", "valueNumber": 0.3 if o == "2024" else 0.2, "unitCode": "mg/L",
                "valueStatus": "REPORTED", "observedAt": DT(d), "observedPopulation": "protocol author, self-reported (SYNTHETIC values)"})
        fx.edge("Observation", f"hu:observation:synthetic-hscrp-{o}", "PRODUCED_BY_ASSAY_VERSION", "AssayVersion", av)
        fx.edge("Observation", f"hu:observation:synthetic-hscrp-{o}", "FROM_LAB_TEST", "LabTest", "hu:lab-test:synthetic-hscrp-lab-a")
        fx.assertion(f"hu:assertion:synthetic-bj-records-hscrp-{o}", "RECORDS", ("Person", "hu:person:bryan-johnson"), ("Observation", f"hu:observation:synthetic-hscrp-{o}"),
                     {"speechAct": "REPORTS_PRACTICE", "assertionBasis": "PERSONAL_EXPERIENCE", "validFromBasis": "UNKNOWN", "validToBasis": "UNKNOWN"},
                     ["hu:locator:blueprint-protocol-2026-10-04-morning"], ("Person", "hu:person:bryan-johnson"))
        fx.asserted_edge("Person", "hu:person:bryan-johnson", "RECORDS", "Observation", f"hu:observation:synthetic-hscrp-{o}", f"hu:assertion:synthetic-bj-records-hscrp-{o}",
                         f"hu:rel:synthetic-bj-records-hscrp-{o}")
    fx.c("Q-W16-08a: material binding of a step: PINNED when USES targets a FormulationVersion; otherwise the formulation in force at the edition's\n"
         "observation instant is RESOLVED_AS_OF via HAS_FORMULATION_VERSION (W04), never stored as if the source stated it.")
    fx.raw("""MATCH (e:ProtocolEdition)-[:HAS_PROTOCOL_STEP]->(s:ProtocolStep {stepKey: 'longevity-mix-pre-workout'})-[u:USES]->(x)
OPTIONAL MATCH (:Protocol)-[h:HAS_PROTOCOL_EDITION]->(e)
OPTIONAL MATCH (a:Assertion {uid: h.assertionUid})-[:SUPPORTED_BY]->(:SourceLocator)<-[:HAS_LOCATOR]-(sn:SourceSnapshot)
WITH e, s, x, sn.observedAt AS at
OPTIONAL MATCH (x)-[f:HAS_FORMULATION_VERSION]->(fv:FormulationVersion)
WHERE f.recordedTo IS NULL AND at IS NOT NULL AND f.validFrom <= at AND (f.validTo IS NULL OR at < f.validTo)
RETURN e.uid AS edition, [l IN labels(x) WHERE NOT l IN ['Entity', 'VersionedState']][0] AS usesLabel, at AS observedAt,
       CASE WHEN x:FormulationVersion THEN 'PINNED' WHEN fv IS NOT NULL THEN 'RESOLVED_AS_OF' ELSE 'UNRESOLVED' END AS binding,
       coalesce(CASE WHEN x:FormulationVersion THEN x.uid END, fv.uid) AS formulationUid
ORDER BY edition""")
    fx.c("Q-W16-08b: instrument change shows up as a MODIFIED step (new payloadHash, same stepKey) in the edition diff.")
    fx.raw(DIFF_QUERY.replace("$old", "'" + E1 + "'").replace("$new", "'" + E2 + "'"))
    fx.c("Q-W16-08c (INV-301 via W07 contract): can the two public hsCRP observations be compared on one axis?")
    fx.raw("""MATCH (o1:Observation {uid: 'hu:observation:synthetic-hscrp-2024'})-[:PRODUCED_BY_ASSAY_VERSION]->(a1),
      (o2:Observation {uid: 'hu:observation:synthetic-hscrp-2025'})-[:PRODUCED_BY_ASSAY_VERSION]->(a2)
OPTIONAL MATCH (c)-[:COMPARES]->(a1) WHERE (c)-[:COMPARES]->(a2) AND c.verdict IN ['COMPARABLE', 'COMPARABLE_WITH_CONVERSION']
RETURN a1 = a2 AS sameAssayVersion, c IS NOT NULL AS comparabilityAssessed,
       CASE WHEN a1 = a2 OR c IS NOT NULL THEN 'SAME_AXIS' ELSE 'NOT_ESTABLISHED' END AS comparability""")
    fx.write(f"{OUT}/08-device-assay-formulation-version-change.cypher")

# ------------------------------------------------------------------------------------------------
# F09 assertion-backed role/evidence attribution; CQ-PR-06
# ------------------------------------------------------------------------------------------------
def f09():
    fx = Fx("09", hdr("09", "assertion-backed role and evidence attribution per step (CQ-PR-06: component evidence does not establish the combined protocol)",
                      "W16-S06 NICE CG185 1.10.14; W16-S07 PubMed 28202779 (Wei et al. 2017); SYNTHETIC combined stack protocol"))
    nice_base(fx)
    base, start, titr, y1 = nice_steps()
    for s in (base, start, titr, y1): s.emit(fx)
    r = {s.key: s for s in (base, start, titr, y1)}
    for s in (base, start, titr, y1): emit_deps(fx, s, r)
    nice_attach(fx, [(base, {}), (start, {}), (titr, {}), (y1, {})])
    fx.c("Role attribution: authorship of the edition and the performer role of a step are Assertions (W00 kernel), not properties.")
    fx.assertion("hu:assertion:nice-authored-cg185-edition", "AUTHORED_PROTOCOL_EDITION", ("ProtocolEdition", NE), ("Organization", "hu:org:nice"),
                 {"speechAct": "STATES", "assertionBasis": "UNSTATED"}, ["hu:locator:nice-cg185-using-lithium"], ("Organization", "hu:org:nice"))
    fx.assertion("hu:assertion:nice-start-lithium-performer-role", "REQUIRES_PERFORMER_ROLE", ("ProtocolStep", start.uid), None,
                 {"valueString": "prescriber with a shared-care arrangement with the person's GP", "speechAct": "RECOMMENDS", "assertionBasis": "EXPERT_OPINION"},
                 ["hu:locator:nice-cg185-using-lithium"], ("Organization", "hu:org:nice"))
    fx.c("SYNTHETIC combined stack: an FMD step whose cited evidence is a real study of a 5-day FMD (Wei 2017), plus a sauna step with no cited evidence.")
    CP, CE = "hu:protocol:synthetic-combined-longevity-stack", "hu:protocol-edition:synthetic-combined-longevity-stack-e1"
    fx.node("Protocol", CP, {"name": "SYNTHETIC combined longevity stack", "protocolType": "EXPERIMENTAL_PROTOCOL"})
    fx.node("Publication", "hu:publication:pmid-28202779", {"name": "Fasting-mimicking diet and markers/risk factors for aging, diabetes, cancer, and cardiovascular disease",
            "publishedAt": DT("2017-02-15T00:00:00Z")})
    fx.node("Outcome", "hu:outcome:igf-1-reduction", {"name": "IGF-1 reduction"})
    fx.source("hu:source:synthetic-combined-stack-page", "https://example.invalid/combined-stack", "SYNTHETIC combined stack page", "SELF_DISCLOSURE_PAGE",
              "hu:snapshot:synthetic-combined-stack", "2026-10-04T00:00:00Z", "2026-10-04T00:00:00Z", "COMPLETE", "hu:locator:synthetic-combined-stack-refs",
              ("SECTION", "References"))
    fmd = Step("synthetic-combined", "fmd-5-day-monthly", {"name": "5-day fasting-mimicking diet, monthly for 3 months", "stepKind": "FAST", "requirementLevel": "ESSENTIAL",
               "speechAct": "RECOMMENDS", "schedulePattern": "CYCLIC", "cycleActiveDaysMin": 5, "cycleActiveDaysMax": 5, "cycleLengthDaysMin": 28, "cycleLengthDaysMax": 31,
               "cycleCountMin": 3, "cycleCountMax": 3, "scheduleText": "5 consecutive days per month for 3 months (as in the cited study)"})
    sau = Step("synthetic-combined", "sauna-weekly", {"name": "Sauna 3 to 5 times a week", "stepKind": "OTHER", "requirementLevel": "RECOMMENDED", "speechAct": "RECOMMENDS",
               "occurrencesPerPeriodMin": 3, "occurrencesPerPeriodMax": 5, "occurrencePeriodUnit": "WEEK"})
    for s in (fmd, sau): s.emit(fx)
    edition(fx, CE, "v1", "SOURCE_VERSIONED", [(fmd, {}), (sau, {})])
    attach(fx, CP, CE, "hu:assertion:synthetic-combined-has-e1", "hu:rel:synthetic-combined-e1", "hu:locator:synthetic-combined-stack-refs",
           DT("2026-10-01T00:00:00Z"), "DAY", "STATED_BY_SOURCE", None, None, "UNKNOWN")
    fx.assertion("hu:assertion:synthetic-fmd-step-cites-wei-2017", "CITES_EVIDENCE_FOR_STEP", ("ProtocolStep", fmd.uid), ("Publication", "hu:publication:pmid-28202779"),
                 {"speechAct": "STATES", "assertionBasis": "STUDY_RESULT"}, ["hu:locator:synthetic-combined-stack-refs"])
    fx.c("NEGATIVE (expected V-538p): a CALCULATED protocol-level efficacy assertion derived only from the step-level citation.")
    fx.assertion("hu:assertion:neg-combined-stack-effective", "PROTOCOL_EFFECTIVE_FOR", ("ProtocolEdition", CE), ("Outcome", "hu:outcome:igf-1-reduction"),
                 {"basisKind": "CALCULATED", "derivationRule": "NEG: inherit step evidence", "status": "PROPOSED"})
    fx.edge("Assertion", "hu:assertion:neg-combined-stack-effective", "DERIVED_FROM_ASSERTION", "Assertion", "hu:assertion:synthetic-fmd-step-cites-wei-2017")
    fx.c("Q-W16-09a (CQ-PR-06): evidence per step versus the protocol as a whole.")
    fx.raw(f"""MATCH (e:ProtocolEdition {{uid: '{CE}'}})-[:HAS_PROTOCOL_STEP]->(s:ProtocolStep)
OPTIONAL MATCH (a:Assertion {{predicate: 'CITES_EVIDENCE_FOR_STEP'}})-[:HAS_SUBJECT]->(s)
OPTIONAL MATCH (a)-[:HAS_OBJECT]->(pub)
RETURN 'STEP' AS level, s.stepKey AS item, collect(pub.uid) AS citedEvidence,
       CASE WHEN count(pub) = 0 THEN 'NO_STEP_EVIDENCE_CITED' ELSE 'STEP_EVIDENCE_CITED_NOT_ASSESSED_FOR_APPLICABILITY' END AS reading
UNION
MATCH (e:ProtocolEdition {{uid: '{CE}'}})
OPTIONAL MATCH (a:Assertion)-[:HAS_SUBJECT]->(e) WHERE a.predicate IN ['PROTOCOL_EFFECTIVE_FOR', 'SUPPORTED_BY_EVIDENCE'] AND coalesce(a.basisKind, '') <> 'CALCULATED'
RETURN 'PROTOCOL' AS level, e.uid AS item, collect(a.uid) AS citedEvidence,
       CASE WHEN count(a) = 0 THEN 'NO_PROTOCOL_LEVEL_EVIDENCE' ELSE 'PROTOCOL_LEVEL_EVIDENCE_PRESENT' END AS reading""")
    fx.c("Q-W16-09b: role attribution for steps and edition with asserter and locator.")
    fx.raw("""MATCH (a:Assertion)-[:HAS_SUBJECT]->(x) WHERE a.predicate IN ['AUTHORED_PROTOCOL_EDITION', 'REQUIRES_PERFORMER_ROLE']
OPTIONAL MATCH (a)-[:HAS_OBJECT]->(o) OPTIONAL MATCH (a)-[:ASSERTED_BY]->(who) OPTIONAL MATCH (a)-[:SUPPORTED_BY]->(l:SourceLocator)
RETURN a.predicate AS predicate, coalesce(x.stepKey, x.uid) AS subject, coalesce(o.uid, a.valueString) AS roleOrAgent, who.uid AS asserter, l.uid AS locator ORDER BY predicate""")
    fx.write(f"{OUT}/09-assertion-backed-role-evidence.cypher")

# ------------------------------------------------------------------------------------------------
# F10 3-6 month cadence range
# ------------------------------------------------------------------------------------------------
def f10():
    fx = Fx("10", hdr("10", "3-6 month cadence is a bounded range, never a midpoint (Blueprint 'Blood draw, every 3 to 6 months')",
                      "W16-S01 Blueprint live page and W16-S02 Wayback capture (identical text in both)"))
    P = blueprint_base(fx)
    fx.node("Metric", "hu:metric:hscrp", {"name": "hsCRP"})
    draw = Step("blueprint", "routine-blood-draw", {"name": "Blood draw", "stepKind": "SAMPLE", "requirementLevel": "NOT_STATED", "requirementBasis": "NOT_STATED", "speechAct": "STATES",
                "schedulePattern": "RECURRING", "cadenceUnit": "MONTH", "cadenceIntervalMin": 3, "cadenceIntervalMax": 6, "scheduleText": "Blood draw, every 3 to 6 months"})
    draw.emit(fx)
    fx.node("MeasurementPlan", "hu:measurement-plan:blueprint-routine-blood-draw", {"name": "Routine blood draw", "planTiming": "PERIODIC", "requiredForEvaluation": None,
            "cadenceMinDays": 90, "cadenceMaxDays": 183, "scheduleText": "Blood draw, every 3 to 6 months"})
    fx.edge("MeasurementPlan", "hu:measurement-plan:blueprint-routine-blood-draw", "TRACKS_METRIC", "Metric", "hu:metric:hscrp")
    E = "hu:protocol-edition:blueprint-observed-2026-10-04"
    edition(fx, E, None, "SNAPSHOT_DIFF", [(draw, {"sectionLabel": "Routine Measurement", "sourceStepLabel": "1"})], other_payload=["hu:measurement-plan:blueprint-routine-blood-draw"])
    fx.edge("ProtocolEdition", E, "HAS_MEASUREMENT_PLAN", "MeasurementPlan", "hu:measurement-plan:blueprint-routine-blood-draw", {"orderIndex": 1})
    fx.c("NEGATIVE (expected V-529b POSSIBLE_RANGE_COLLAPSE x2 and V-529p RANGE_INVERTED): midpoint/endpoint collapse and an inverted plan range.")
    neg = Step("blueprint-neg", "routine-blood-draw", {"name": "NEG collapsed range", "stepKind": "SAMPLE", "requirementLevel": "NOT_STATED", "cadenceUnit": "MONTH",
               "cadenceIntervalMin": 4, "cadenceIntervalMax": 4, "scheduleText": "Blood draw, every 3 to 6 months"})
    neg.emit(fx)
    edition(fx, "hu:protocol-edition:blueprint-neg-range", "NEG", "SOURCE_VERSIONED", [(neg, {})])
    fx.node("MeasurementPlan", "hu:measurement-plan:neg-collapsed", {"name": "NEG collapsed plan", "planTiming": "PERIODIC", "cadenceMinDays": 135, "cadenceMaxDays": 135,
            "scheduleText": "every 3 to 6 months"})
    fx.node("MeasurementPlan", "hu:measurement-plan:neg-inverted", {"name": "NEG inverted plan", "planTiming": "PERIODIC", "cadenceMinDays": 183, "cadenceMaxDays": 90})
    fx.c("Q-W16-10a: the cadence as stored: both bounds, unit and verbatim text.")
    fx.raw(f"""MATCH (e:ProtocolEdition {{uid: '{E}'}})-[:HAS_PROTOCOL_STEP]->(s:ProtocolStep)
OPTIONAL MATCH (e)-[:HAS_MEASUREMENT_PLAN]->(m:MeasurementPlan)
RETURN s.stepKey AS stepKey, s.cadenceIntervalMin AS minMonths, s.cadenceIntervalMax AS maxMonths, s.cadenceUnit AS unit, m.cadenceMinDays AS minDays, m.cadenceMaxDays AS maxDays, s.scheduleText AS text""")
    fx.c("Q-W16-10b: due window after a given public draw date (literal 2026-01-15): earliest/latest, never a single due date.")
    fx.raw("""MATCH (m:MeasurementPlan {uid: 'hu:measurement-plan:blueprint-routine-blood-draw'})
WITH m, date('2026-01-15') AS last
RETURN last AS lastDraw, last + duration({days: m.cadenceMinDays}) AS windowOpens, last + duration({days: m.cadenceMaxDays}) AS windowCloses,
       CASE WHEN date('2026-06-01') < last + duration({days: m.cadenceMinDays}) THEN 'NOT_YET_DUE'
            WHEN date('2026-06-01') <= last + duration({days: m.cadenceMaxDays}) THEN 'WITHIN_WINDOW' ELSE 'OVERDUE' END AS statusOn20260601""")
    fx.write(f"{OUT}/10-cadence-range-3-to-6-months.cypher")

# ------------------------------------------------------------------------------------------------
# F11 wait for lab result (REQUIRES_RESULT_OF)
# ------------------------------------------------------------------------------------------------
def f11():
    fx = Fx("11", hdr("11", "wait-for-lab-result dependency REQUIRES_RESULT_OF and a TREND review rule (NICE CG185 1.10.15, 1.10.22)",
                      "W16-S06 NICE CG185; INHERITED synthetic magnesium example (examples/recommendation-snapshot.cypher 1.12)"))
    nice_base(fx)
    base, start, titr, y1 = nice_steps()
    adj = Step("nice-cg185", "lithium-dose-adjustment", {"name": "Adjust lithium dose to target level", "stepKind": "ADJUST", "requirementLevel": "CONDITIONAL", "speechAct": "RECOMMENDS",
               "schedulePattern": "EVENT_DRIVEN", "scheduleText": "Aim to maintain plasma lithium level between 0.6 and 0.8 mmol per litre"},
               constraints=[("hu:constraint:nice-cg185-level-outside-target", "APPLIES_WHEN", None, False)],
               deps=[("plasma-lithium-titration-checks", "REQUIRES_RESULT_OF", {"dependencyBasis": "EDITORIAL_INFERENCE"})])
    fx.node("Constraint", "hu:constraint:nice-cg185-level-outside-target", {"name": "plasma lithium outside 0.6-0.8 mmol/L", "constraintKind": "MEASUREMENT_THRESHOLD",
            "comparator": "OUTSIDE_REFERENCE_RANGE", "constraintText": "level not between 0.6 and 0.8 mmol per litre (target, not a reference interval)"})
    fx.edge("Constraint", "hu:constraint:nice-cg185-level-outside-target", "BASED_ON", "Metric", "hu:metric:plasma-lithium-substance-concentration")
    steps = [base, start, titr, y1, adj]
    for s in steps: s.emit(fx)
    r = {s.key: s for s in steps}
    for s in steps: emit_deps(fx, s, r)
    fx.node("ProtocolAdjustmentRule", "hu:protocol-rule:nice-cg185-egfr-falling", {"name": "More frequent monitoring if renal function deteriorates", "triggerKind": "TREND",
            "triggerAction": "REVIEW", "ruleBasis": "STATED_BY_SOURCE",
            "ruleText": "Monitor lithium dose and plasma lithium levels more frequently if urea levels and creatinine levels become elevated, or eGFR falls over 2 or more tests, and assess the rate of deterioration of renal function."})
    fx.edge("ProtocolAdjustmentRule", "hu:protocol-rule:nice-cg185-egfr-falling", "RULE_TRIGGERED_BY", "Metric", "hu:metric:egfr")
    fx.edge("ProtocolAdjustmentRule", "hu:protocol-rule:nice-cg185-egfr-falling", "MODIFIES_STEP", "ProtocolStep", y1.uid)
    nice_attach(fx, [(s, {}) for s in steps], ["hu:protocol-rule:nice-cg185-egfr-falling"])
    fx.edge("ProtocolEdition", NE, "HAS_ADJUSTMENT_RULE", "ProtocolAdjustmentRule", "hu:protocol-rule:nice-cg185-egfr-falling", {"orderIndex": 1})
    fx.c("NEGATIVE (expected V-531p RESULT_DEPENDENCY_ON_NON_RESULT_STEP): waiting for the 'result' of an INGEST step; and (expected V-533p) a BellLabs policy rule marked PUBLIC without a PolicyVersion.")
    n1 = Step("neg", "take-capsule", {"name": "NEG take capsule", "stepKind": "INGEST", "requirementLevel": "OPTIONAL"})
    n2 = Step("neg", "after-capsule", {"name": "NEG waits for capsule result", "stepKind": "ADJUST", "requirementLevel": "OPTIONAL"},
              deps=[("take-capsule", "REQUIRES_RESULT_OF", None)])
    n1.emit(fx); n2.emit(fx)
    edition(fx, "hu:protocol-edition:neg-result-dependency", "NEG", "SOURCE_VERSIONED", [(n1, {}), (n2, {})])
    emit_deps(fx, n2, {"take-capsule": n1})
    fx.node("ProtocolAdjustmentRule", "hu:protocol-rule:neg-policy-rule-public", {"name": "NEG policy rule", "ruleBasis": "BELLLABS_SAFETY_POLICY", "triggerKind": "THRESHOLD_CROSSED"})
    fx.c("Q-W16-11a (CQ-PR-02/CQ-PR-03): for each step, the results it must wait for and the metrics those results measure.")
    fx.raw(f"""MATCH (e:ProtocolEdition {{uid: '{NE}'}})-[:HAS_PROTOCOL_STEP]->(s:ProtocolStep)-[d:DEPENDS_ON {{dependencyKind: 'REQUIRES_RESULT_OF'}}]->(t:ProtocolStep)
OPTIONAL MATCH (s)-[:HAS_CONSTRAINT]->(:Constraint)-[:BASED_ON]->(m:Metric)
RETURN s.stepKey AS waitingStep, t.stepKey AS waitsForResultOf, d.dependencyBasis AS basis, collect(DISTINCT m.uid) AS gatingMetrics ORDER BY waitingStep""")
    fx.c("Q-W16-11b (CQ-PR-04): review rules of the edition, what triggers them, which steps they modify; public triggers never write private decisions.")
    fx.raw(f"""MATCH (e:ProtocolEdition {{uid: '{NE}'}})-[:HAS_ADJUSTMENT_RULE]->(r:ProtocolAdjustmentRule)
OPTIONAL MATCH (r)-[:RULE_TRIGGERED_BY]->(m:Metric) OPTIONAL MATCH (r)-[:MODIFIES_STEP]->(s:ProtocolStep)
RETURN r.uid AS rule, r.triggerKind AS triggerKind, r.triggerAction AS action, r.ruleBasis AS basis, collect(DISTINCT m.uid) AS metrics, collect(DISTINCT s.stepKey) AS modifies""")
    fx.write(f"{OUT}/11-wait-for-lab-result.cypher")

# ------------------------------------------------------------------------------------------------
# F12 mutually exclusive steps
# ------------------------------------------------------------------------------------------------
def f12():
    fx = Fx("12", hdr("12", "mutually exclusive steps (Blueprint 'Either HBOT (90 min) or IHHT (42 min)'; 'NR (450 mg) or NMN (500 mg)')",
                      "W16-S01 Blueprint live page; W16-S02 Wayback capture (same text in both)"))
    P = blueprint_base(fx)
    fx.node("ChemicalSubstance", "hu:substance:nicotinamide-riboside", {"name": "nicotinamide riboside"})
    fx.node("ChemicalSubstance", "hu:substance:nicotinamide-mononucleotide", {"name": "nicotinamide mononucleotide"})
    hb = Step("blueprint", "hbot-session-9am", {"name": "HBOT session", "stepKind": "OTHER", "stepKindRaw": "HYPERBARIC_OXYGEN", "requirementLevel": "NOT_STATED", "requirementBasis": "NOT_STATED",
              "speechAct": "REPORTS_PRACTICE", "durationMinutesMin": 90, "durationMinutesMax": 90, "timingText": "9:00 am", "scheduleText": "9:00 am Either HBOT (90 min) or IHHT (42 min)."},
              deps=[("ihht-session-9am", "MUTUALLY_EXCLUSIVE_WITH", {"dependencyBasis": "STATED_BY_SOURCE"})])
    ih = Step("blueprint", "ihht-session-9am", {"name": "IHHT session", "stepKind": "OTHER", "stepKindRaw": "INTERMITTENT_HYPOXIA_HYPEROXIA", "requirementLevel": "NOT_STATED",
              "requirementBasis": "NOT_STATED", "speechAct": "REPORTS_PRACTICE", "durationMinutesMin": 42, "durationMinutesMax": 42, "timingText": "9:00 am",
              "scheduleText": "9:00 am Either HBOT (90 min) or IHHT (42 min)."})
    nr = Step("blueprint", "nad-precursor-nr", {"name": "Nicotinamide riboside", "stepKind": "INGEST", "requirementLevel": "NOT_STATED", "requirementBasis": "NOT_STATED",
              "speechAct": "REPORTS_PRACTICE", "timeOfDay": "MORNING"},
              uses=[("ChemicalSubstance", "hu:substance:nicotinamide-riboside", {"quantity": 450.0, "unitCode": "mg", "quantityBasis": "PER_DOSE", "massBasis": "UNSPECIFIED",
                     "route": "oral", "verbatimDoseText": "NR (450 mg) or NMN (500 mg)"})],
              deps=[("nad-precursor-nmn", "MUTUALLY_EXCLUSIVE_WITH", {"dependencyBasis": "STATED_BY_SOURCE"})])
    nm = Step("blueprint", "nad-precursor-nmn", {"name": "Nicotinamide mononucleotide", "stepKind": "INGEST", "requirementLevel": "NOT_STATED", "requirementBasis": "NOT_STATED",
              "speechAct": "REPORTS_PRACTICE", "timeOfDay": "MORNING"},
              uses=[("ChemicalSubstance", "hu:substance:nicotinamide-mononucleotide", {"quantity": 500.0, "unitCode": "mg", "quantityBasis": "PER_DOSE", "massBasis": "UNSPECIFIED",
                     "route": "oral", "verbatimDoseText": "NR (450 mg) or NMN (500 mg)"})])
    steps = [hb, ih, nr, nm]
    for s in steps: s.emit(fx)
    r = {s.key: s for s in steps}
    for s in steps: emit_deps(fx, s, r)
    E = "hu:protocol-edition:blueprint-observed-2026-10-04"
    edition(fx, E, None, "SNAPSHOT_DIFF", [(hb, {"sectionLabel": "Morning"}), (ih, {"sectionLabel": "Morning"}), (nr, {"sectionLabel": "Morning pills"}), (nm, {"sectionLabel": "Morning pills"})])
    fx.c("NEGATIVE (expected V-531p EXCLUSIVE_AND_REQUIRES_PRIOR_COMPLETION and EXCLUSIVE_PAIR_BOTH_ESSENTIAL): alternatives that are also ordered, and both essential.")
    a = Step("blueprint-neg", "nad-precursor-nr", {"name": "NEG NR", "stepKind": "INGEST", "requirementLevel": "ESSENTIAL"},
             deps=[("nad-precursor-nmn", "MUTUALLY_EXCLUSIVE_WITH", None), ("nad-precursor-nmn", "REQUIRES_PRIOR_COMPLETION", None)])
    b = Step("blueprint-neg", "nad-precursor-nmn", {"name": "NEG NMN", "stepKind": "INGEST", "requirementLevel": "ESSENTIAL"})
    a.emit(fx); b.emit(fx)
    edition(fx, "hu:protocol-edition:blueprint-neg-exclusive", "NEG", "SOURCE_VERSIONED", [(a, {}), (b, {})])
    fx.raw(f"MATCH (a:ProtocolStep {{uid: '{a.uid}'}}), (b:ProtocolStep {{uid: '{b.uid}'}}) CREATE (a)-[:DEPENDS_ON {{dependencyKind: 'MUTUALLY_EXCLUSIVE_WITH'}}]->(b)")
    fx.raw(f"MATCH (a:ProtocolStep {{uid: '{a.uid}'}}), (b:ProtocolStep {{uid: '{b.uid}'}}) CREATE (a)-[:DEPENDS_ON {{dependencyKind: 'REQUIRES_PRIOR_COMPLETION'}}]->(b)")
    fx.c("Q-W16-12: alternative sets in an edition (connected components over MUTUALLY_EXCLUSIVE_WITH), with each alternative's declared dose/duration.")
    fx.raw(f"""MATCH (e:ProtocolEdition {{uid: '{E}'}})-[:HAS_PROTOCOL_STEP]->(s:ProtocolStep)-[:DEPENDS_ON {{dependencyKind: 'MUTUALLY_EXCLUSIVE_WITH'}}]-(t:ProtocolStep)
WHERE (e)-[:HAS_PROTOCOL_STEP]->(t) AND s.stepKey < t.stepKey
OPTIONAL MATCH (s)-[us:USES]->() OPTIONAL MATCH (t)-[ut:USES]->()
RETURN s.stepKey AS alternativeA, t.stepKey AS alternativeB, coalesce(toString(us.quantity) + ' ' + us.unitCode, toString(s.durationMinutesMin) + ' min') AS a,
       coalesce(toString(ut.quantity) + ' ' + ut.unitCode, toString(t.durationMinutesMin) + ' min') AS b ORDER BY alternativeA""")
    fx.write(f"{OUT}/12-mutually-exclusive-steps.cypher")

# ------------------------------------------------------------------------------------------------
# F13 subprotocol edition binding (pinned vs floating)
# ------------------------------------------------------------------------------------------------
def f13():
    fx = Fx("13", hdr("13", "component/subprotocol relations with the edition-binding rule (PINNED INCLUDES_PROTOCOL vs FLOATING HAS_SUBPROTOCOL)",
                      "W16-S04/S05 protocols.io PBMC CPT V.1/V.2 (real versions and dates); SYNTHETIC parent workflows"))
    SP = "hu:protocol:protocolsio-pbmc-cpt"
    fx.node("Protocol", SP, {"name": "PBMCs isolation from CPT tube", "protocolType": "SAMPLE_COLLECTION_PROTOCOL"})
    for v, d, vt in [("v1", "2020-08-06", "2022-07-27"), ("v2", "2022-07-27", None)]:
        fx.source(f"hu:source:protocolsio-pbmc-cpt-{v}", f"https://www.protocols.io/view/pbmcs-isolation-from-cpt-tube-kxygxeqr4v8j/{v}", f"PBMCs isolation from CPT tube {v.upper()}",
                  "STANDARDS_DOCUMENT", f"hu:snapshot:protocolsio-pbmc-cpt-{v}-2026-10-04", "2026-10-04T01:05:00Z", "2026-10-04T01:05:00Z", "PARTIAL_EXCERPT",
                  f"hu:locator:protocolsio-pbmc-cpt-{v}-header", ("SECTION", "Version header"))
        fx.node("ProtocolEdition", f"hu:protocol-edition:protocolsio-pbmc-cpt-{v}", {"editionLabel": "V." + v[1], "changeProvenance": "SOURCE_VERSIONED", "payloadHash": sha(v),
                "sourceVersionDate": D(d)})
        attach(fx, SP, f"hu:protocol-edition:protocolsio-pbmc-cpt-{v}", f"hu:assertion:protocolsio-pbmc-cpt-has-{v}", f"hu:rel:protocolsio-pbmc-cpt-{v}",
               f"hu:locator:protocolsio-pbmc-cpt-{v}-header", DT(d + "T00:00:00Z"), "DAY", "STATED_BY_SOURCE",
               DT(vt + "T00:00:00Z") if vt else None, "DAY" if vt else None, "INFERRED" if vt else "UNKNOWN")
    fx.node("Protocol", "hu:protocol:synthetic-pinned-parent-workflow", {"name": "SYNTHETIC cohort sample workflow (pins PBMC V.2)", "protocolType": "WORKFLOW"})
    fx.node("Protocol", "hu:protocol:synthetic-floating-parent-workflow", {"name": "SYNTHETIC cohort sample workflow (links PBMC protocol without version)", "protocolType": "WORKFLOW"})
    fx.node("ProtocolEdition", "hu:protocol-edition:synthetic-pinned-parent-e1", {"editionLabel": "v1", "changeProvenance": "SOURCE_VERSIONED", "payloadHash": sha("pinned-parent")})
    fx.node("ProtocolEdition", "hu:protocol-edition:synthetic-floating-parent-e1", {"editionLabel": "v1", "changeProvenance": "SOURCE_VERSIONED", "payloadHash": sha("floating-parent")})
    fx.edge("ProtocolEdition", "hu:protocol-edition:synthetic-pinned-parent-e1", "INCLUDES_PROTOCOL", "ProtocolEdition", "hu:protocol-edition:protocolsio-pbmc-cpt-v2", {"orderIndex": 2})
    fx.edge("ProtocolEdition", "hu:protocol-edition:synthetic-floating-parent-e1", "HAS_SUBPROTOCOL", "Protocol", SP, {"orderIndex": 2})
    fx.c("Q-W16-13: which subprotocol edition does each parent include at a valid-time instant V (2021-06-01 and 2023-06-01)? PINNED is fixed; FLOATING is resolved as-of\n"
         "with the QS-2b validity classes and labelled RESOLVED_AS_OF.")
    fx.raw("""UNWIND [datetime('2021-06-01T00:00:00Z'), datetime('2023-06-01T00:00:00Z')] AS V
MATCH (pe:ProtocolEdition) WHERE pe.uid IN ['hu:protocol-edition:synthetic-pinned-parent-e1', 'hu:protocol-edition:synthetic-floating-parent-e1']
OPTIONAL MATCH (pe)-[:INCLUDES_PROTOCOL]->(pinned:ProtocolEdition)
OPTIONAL MATCH (pe)-[:HAS_SUBPROTOCOL]->(sp:Protocol)-[h:HAS_PROTOCOL_EDITION]->(fe:ProtocolEdition)
WHERE h.recordedTo IS NULL AND (h.validFrom IS NULL OR h.validFrom <= V) AND (h.validTo IS NULL OR V < h.validTo)
RETURN pe.uid AS parentEdition, toString(date(V)) AS validAt,
       CASE WHEN pinned IS NOT NULL THEN 'PINNED' WHEN fe IS NOT NULL THEN 'RESOLVED_AS_OF' ELSE 'UNRESOLVED' END AS binding,
       coalesce(pinned.editionLabel, fe.editionLabel) AS includedEdition,
       CASE WHEN fe IS NOT NULL AND h.validTo IS NULL THEN 'OPEN_END_UNVERIFIED' WHEN fe IS NOT NULL THEN 'KNOWN_WITHIN' END AS validityClass
ORDER BY parentEdition, validAt""")
    fx.write(f"{OUT}/13-subprotocol-edition-binding.cypher")

for f in (f01, f02, f03, f04, f05, f06, f07, f08, f09, f10, f11, f12, f13): f()
print("ok")
