// W22 fixture MP5: a crop derived from a label image retains region and snapshot provenance.
// MediaVariant CROPPED + MediaAnnotation + SourceLocator IMAGE_REGION + LOCATES_REGION (D-010, CL-011); the crop is
// generated by a MEDIA_TRANSFORMATION Activity that USED the ORIGINAL rendition and the region annotation.
// CQ-MD-C04, CQ-PV-02, CQ-PV-03. Seam W04: ProductLabelRegion REGION_HAS_DECLARATION LabelDeclaration; LABEL_FOR.
// Real record: Elysium product page lists '5_Basis_Carousel_SupplementFacts_SEP26...jpg' at width=1946 and width=416
// with alt text 'Supplement label with Elysium NR and PT content on a white background' (S09); the Supplement Facts
// HTML page states 'Elysium NR (Nicotinamide Riboside Chloride) 250 mg' (S10). The IMAGE content was NOT inspected
// (bytes not retrieved): region coordinates and the declaration's presence inside the image are SYNTHETIC.
// Run after (or together with) MP1, which creates the asset, its variants and the image snapshot; this file MERGEs the
// nodes it needs so it also runs alone.

MERGE (n:Product:Entity {uid: 'hu:product:elysium-basis'})
SET n.name = 'Basis', n.entityType = 'PRODUCT';

MERGE (n:ProductVariant:Entity {uid: 'hu:product-variant:basis-us-capsule-standard'})
SET n.name = 'Basis - US capsules', n.entityType = 'PRODUCT_VARIANT', n.jurisdiction = 'US';

MERGE (n:Organization:Entity {uid: 'hu:org:elysium-health-inc'})
SET n.name = 'Elysium Health', n.entityType = 'ORGANIZATION';

MERGE (n:Agent:Entity {uid: 'hu:agent:belllabs-w22-curator'})
SET n.name = 'BellLabs W22 media curator', n.entityType = 'AGENT', n.agentKind = 'MANUAL_AGENT';

MERGE (n:Agent:Entity {uid: 'hu:agent:belllabs-crop-tool-v1'})
SET n.name = 'BellLabs crop tool', n.entityType = 'AGENT', n.agentKind = 'AUTOMATED_AGENT', n.toolVersion = 'bl-crop-v1';

MERGE (n:Activity:Occurrence {uid: 'hu:activity:w22-curation-2026-10-04'})
SET n.occurrenceType = 'ACTIVITY', n.activityKind = 'EXTRACTION', n.startedAt = datetime('2026-10-04T01:10:00Z'), n.endedAt = datetime('2026-10-04T02:00:00Z'), n.methodVersion = 'w22-manual-media-curation-v0.1';

MERGE (n:Activity:Occurrence {uid: 'hu:activity:w22-crop-basis-supplement-facts-panel'})
SET n.occurrenceType = 'ACTIVITY', n.activityKind = 'MEDIA_TRANSFORMATION', n.startedAt = datetime('2026-10-04T02:50:00Z'), n.endedAt = datetime('2026-10-04T02:50:02Z'), n.methodVersion = 'bl-crop-v1';

MERGE (n:Activity:Occurrence {uid: 'hu:activity:w22-ocr-basis-supplement-facts-panel'})
SET n.occurrenceType = 'ACTIVITY', n.activityKind = 'TEXT_EXTRACTION', n.startedAt = datetime('2026-10-04T02:51:00Z'), n.endedAt = datetime('2026-10-04T02:51:05Z'), n.methodVersion = 'ocr-engine-unspecified-v0';

MATCH (a:Activity {uid: 'hu:activity:w22-crop-basis-supplement-facts-panel'}), (g:Agent {uid: 'hu:agent:belllabs-crop-tool-v1'})
MERGE (a)-[:WAS_ASSOCIATED_WITH]->(g);

// ---- The label image capture (same nodes as MP1).
MERGE (n:Source:Entity {uid: 'hu:source:elysium-cdn-basis-supplement-facts-w1946'})
SET n.entityType = 'SOURCE', n.canonicalUri = 'https://www.elysiumhealth.com/cdn/shop/files/5_Basis_Carousel_SupplementFacts_SEP26_1_1_33f99ab8-54b6-4178-b1fd-12c206b8064f.jpg?v=1790519922&width=1946', n.sourceKind = 'MEDIA_FILE';

MERGE (n:SourceSnapshot:InformationArtifact:LabelSnapshot {uid: 'hu:snapshot:elysium-cdn-basis-supplement-facts-w1946-synthetic'})
SET n.artifactType = 'SOURCE_SNAPSHOT', n.canonicalUri = 'https://www.elysiumhealth.com/cdn/shop/files/5_Basis_Carousel_SupplementFacts_SEP26_1_1_33f99ab8-54b6-4178-b1fd-12c206b8064f.jpg?v=1790519922&width=1946', n.retrievedAt = datetime('2026-10-04T02:00:00Z'),
    n.contentHash = 'sha256:dc65afc729347a6161f42190a9f665338ac2f44bec7b7c368fc29cdcb415e592', n.contentHashBasis = 'SYNTHETIC_FIXTURE', n.captureCompleteness = 'UNKNOWN', n.mimeType = 'image/jpeg', n.jurisdiction = 'US';

MATCH (s:Source {uid: 'hu:source:elysium-cdn-basis-supplement-facts-w1946'}), (ss:SourceSnapshot {uid: 'hu:snapshot:elysium-cdn-basis-supplement-facts-w1946-synthetic'})
MERGE (s)-[:HAS_SNAPSHOT]->(ss);

MERGE (m:MediaAsset:InformationArtifact {uid: 'hu:media-asset:elysium-basis-carousel-supplement-facts'})
SET m.artifactType = 'MEDIA_ASSET', m.assetType = 'IMAGE', m.mediaPurpose = 'LABEL_IMAGE', m.contentHash = 'sha256:dc65afc729347a6161f42190a9f665338ac2f44bec7b7c368fc29cdcb415e592', m.contentHashBasis = 'SYNTHETIC_FIXTURE';

MERGE (v:MediaVariant:InformationArtifact {uid: 'hu:media-variant:elysium-basis-supplement-facts-w1946'})
SET v.artifactType = 'MEDIA_VARIANT', v.variantKind = 'ORIGINAL', v.mediaFormat = 'JPEG', v.mimeType = 'image/jpeg', v.widthPx = 1946,
    v.contentHash = 'sha256:dc65afc729347a6161f42190a9f665338ac2f44bec7b7c368fc29cdcb415e592', v.contentHashBasis = 'SYNTHETIC_FIXTURE';

MERGE (v:MediaVariant:InformationArtifact {uid: 'hu:media-variant:elysium-basis-supplement-facts-w416'})
SET v.artifactType = 'MEDIA_VARIANT', v.variantKind = 'RESIZED', v.mediaFormat = 'JPEG', v.mimeType = 'image/jpeg', v.widthPx = 416,
    v.contentHash = 'sha256:425835749ee3773e041d1900338a4cd0260ff70d4542fcb7949c71a872787a97', v.contentHashBasis = 'SYNTHETIC_FIXTURE';

MATCH (m:MediaAsset {uid: 'hu:media-asset:elysium-basis-carousel-supplement-facts'}), (v1:MediaVariant {uid: 'hu:media-variant:elysium-basis-supplement-facts-w1946'}), (v2:MediaVariant {uid: 'hu:media-variant:elysium-basis-supplement-facts-w416'})
MERGE (m)-[:HAS_MEDIA_VARIANT]->(v1) MERGE (m)-[:HAS_MEDIA_VARIANT]->(v2);

// ---- Region annotation on the ORIGINAL rendition (coordinates in IMG-PX1 on the 1946 px raster; synthetic values).
MERGE (ann:MediaAnnotation:InformationArtifact {uid: 'hu:media-annotation:basis-supplement-facts-panel-w1946'})
SET ann.artifactType = 'MEDIA_ANNOTATION', ann.annotationType = 'BOUNDING_BOX', ann.normalizationVersion = 'IMG-PX1', ann.x = 310.0, ann.y = 240.0, ann.width = 1320.0, ann.height = 1180.0,
    ann.label = 'Supplement Facts panel (synthetic coordinates)';

MERGE (n:SourceLocator:InformationArtifact {uid: 'hu:locator:basis-supplement-facts-panel-image-region'})
SET n.artifactType = 'SOURCE_LOCATOR', n.selectorKind = 'IMAGE_REGION', n.mediaAnnotationUid = 'hu:media-annotation:basis-supplement-facts-panel-w1946', n.normalizationVersion = 'IMG-PX1';

MATCH (v:MediaVariant {uid: 'hu:media-variant:elysium-basis-supplement-facts-w1946'}), (ann:MediaAnnotation {uid: 'hu:media-annotation:basis-supplement-facts-panel-w1946'}),
      (ss:SourceSnapshot {uid: 'hu:snapshot:elysium-cdn-basis-supplement-facts-w1946-synthetic'}), (l:SourceLocator {uid: 'hu:locator:basis-supplement-facts-panel-image-region'}),
      (cur:Activity {uid: 'hu:activity:w22-curation-2026-10-04'})
MERGE (v)-[:HAS_ANNOTATION]->(ann) MERGE (ss)-[:HAS_LOCATOR]->(l) MERGE (l)-[:LOCATES_REGION]->(ann) MERGE (ann)-[:WAS_GENERATED_BY]->(cur) MERGE (l)-[:WAS_GENERATED_BY]->(cur);

// ---- ProductLabelRegion and the W04 label declaration it contains.
MERGE (r:ProductLabelRegion:InformationArtifact {uid: 'hu:label-region:basis-supplement-facts-panel'})
SET r.artifactType = 'PRODUCT_LABEL_REGION', r.labelRegionType = 'SUPPLEMENT_FACTS', r.extractedText = 'Elysium NR (Nicotinamide Riboside Chloride) 250 mg (OCR text, synthetic)';

MERGE (d:LabelDeclaration:InformationArtifact {uid: 'hu:label-declaration:basis-sf-image-elysium-nr-250mg'})
SET d.artifactType = 'LABEL_DECLARATION', d.verbatimText = 'Elysium NR (Nicotinamide Riboside Chloride) 250 mg', d.declarationKind = 'INGREDIENT_AMOUNT', d.panelOrder = 1;

MATCH (r:ProductLabelRegion {uid: 'hu:label-region:basis-supplement-facts-panel'}), (ann:MediaAnnotation {uid: 'hu:media-annotation:basis-supplement-facts-panel-w1946'}),
      (d:LabelDeclaration {uid: 'hu:label-declaration:basis-sf-image-elysium-nr-250mg'}), (ss:SourceSnapshot {uid: 'hu:snapshot:elysium-cdn-basis-supplement-facts-w1946-synthetic'}),
      (ocr:Activity {uid: 'hu:activity:w22-ocr-basis-supplement-facts-panel'})
MERGE (r)-[:FROM_ANNOTATION]->(ann)
MERGE (r)-[:REGION_HAS_DECLARATION {orderIndex: 1}]->(d)
MERGE (ss)-[:HAS_DECLARATION]->(d)
MERGE (d)-[:WAS_GENERATED_BY]->(ocr);

// W04 asserted LABEL_FOR (the label snapshot is the label of the US capsule variant), cited by the region locator.
MERGE (x:Assertion {uid: 'hu:assertion:w22-basis-sf-image-label-for-us-variant'})
SET x.predicate = 'LABEL_FOR', x.status = 'ACCEPTED', x.recordedAt = datetime('2026-10-04T02:52:00Z'), x.predicateClass = 'IDENTITY', x.validFromBasis = 'OBSERVATION_ONLY', x.validToBasis = 'UNKNOWN';

MATCH (x:Assertion {uid: 'hu:assertion:w22-basis-sf-image-label-for-us-variant'}), (ss:SourceSnapshot {uid: 'hu:snapshot:elysium-cdn-basis-supplement-facts-w1946-synthetic'}), (pv:ProductVariant {uid: 'hu:product-variant:basis-us-capsule-standard'}),
      (o:Organization {uid: 'hu:org:elysium-health-inc'}), (l:SourceLocator {uid: 'hu:locator:basis-supplement-facts-panel-image-region'}), (cur:Activity {uid: 'hu:activity:w22-curation-2026-10-04'})
MERGE (x)-[:HAS_SUBJECT]->(ss) MERGE (x)-[:HAS_OBJECT]->(pv) MERGE (x)-[:ASSERTED_BY]->(o) MERGE (x)-[:SUPPORTED_BY]->(l) MERGE (x)-[:WAS_GENERATED_BY]->(cur)
MERGE (ss)-[e:LABEL_FOR {relationshipUid: 'hu:rel:w22-basis-sf-image-label-for-us-variant'}]->(pv)
SET e.assertionUid = x.uid, e.validFromBasis = 'OBSERVATION_ONLY', e.validToBasis = 'UNKNOWN', e.recordedFrom = datetime('2026-10-04T02:52:00Z');

MATCH (p:Product {uid: 'hu:product:elysium-basis'}), (pv:ProductVariant {uid: 'hu:product-variant:basis-us-capsule-standard'})
MERGE (p)-[:HAS_VARIANT]->(pv);

// ---- The CROP: a new rendition of the same asset, generated by MEDIA_TRANSFORMATION that USED the ORIGINAL rendition and
// ---- the region annotation (and the locator, so the crop's citation path is recoverable without reading pixels).
MERGE (c:MediaVariant:InformationArtifact {uid: 'hu:media-variant:basis-supplement-facts-panel-crop'})
SET c.artifactType = 'MEDIA_VARIANT', c.variantKind = 'CROPPED', c.mediaFormat = 'PNG', c.mimeType = 'image/png', c.widthPx = 1320, c.heightPx = 1180,
    c.storageUri = 'urn:belllabs:media-store:basis-sf-panel-crop', c.contentHash = 'sha256:16323c1ae0e87f2455bf73d67889f1ba9f69a2395006909bf5f1737a02a41c0d', c.contentHashBasis = 'SYNTHETIC_FIXTURE';

MATCH (m:MediaAsset {uid: 'hu:media-asset:elysium-basis-carousel-supplement-facts'}), (c:MediaVariant {uid: 'hu:media-variant:basis-supplement-facts-panel-crop'}),
      (v:MediaVariant {uid: 'hu:media-variant:elysium-basis-supplement-facts-w1946'}), (ann:MediaAnnotation {uid: 'hu:media-annotation:basis-supplement-facts-panel-w1946'}),
      (l:SourceLocator {uid: 'hu:locator:basis-supplement-facts-panel-image-region'}), (act:Activity {uid: 'hu:activity:w22-crop-basis-supplement-facts-panel'}),
      (ocr:Activity {uid: 'hu:activity:w22-ocr-basis-supplement-facts-panel'})
MERGE (m)-[:HAS_MEDIA_VARIANT]->(c)
MERGE (c)-[:WAS_GENERATED_BY]->(act)
MERGE (act)-[:USED]->(v) MERGE (act)-[:USED]->(ann) MERGE (act)-[:USED]->(l)
MERGE (ocr)-[:USED]->(c);

// ---- NEGATIVE members: (n1) an annotation drawn on the CROP (crop coordinates) but cited through an IMAGE_REGION
// ---- locator on the ORIGINAL snapshot - coordinate frame and bytes differ (V-602, V-606); (n2) an IMAGE_REGION locator
// ---- that names an annotation uid but has no LOCATES_REGION edge (V-601).
MERGE (ann:MediaAnnotation:InformationArtifact {uid: 'hu:media-annotation:bad-nr-line-on-crop'})
SET ann.artifactType = 'MEDIA_ANNOTATION', ann.annotationType = 'BOUNDING_BOX', ann.normalizationVersion = 'IMG-PX1', ann.x = 20.0, ann.y = 300.0, ann.width = 1200.0, ann.height = 60.0, ann.label = 'NR line (crop coordinates)';

MERGE (n:SourceLocator:InformationArtifact {uid: 'hu:locator:bad-nr-line-region-on-original-snapshot'})
SET n.artifactType = 'SOURCE_LOCATOR', n.selectorKind = 'IMAGE_REGION', n.mediaAnnotationUid = 'hu:media-annotation:bad-nr-line-on-crop', n.normalizationVersion = 'IMG-PX1';

MERGE (n:SourceLocator:InformationArtifact {uid: 'hu:locator:bad-dangling-image-region'})
SET n.artifactType = 'SOURCE_LOCATOR', n.selectorKind = 'IMAGE_REGION', n.mediaAnnotationUid = 'hu:media-annotation:does-not-exist', n.normalizationVersion = 'IMG-PX1';

MATCH (c:MediaVariant {uid: 'hu:media-variant:basis-supplement-facts-panel-crop'}), (ann:MediaAnnotation {uid: 'hu:media-annotation:bad-nr-line-on-crop'}),
      (ss:SourceSnapshot {uid: 'hu:snapshot:elysium-cdn-basis-supplement-facts-w1946-synthetic'}), (l:SourceLocator {uid: 'hu:locator:bad-nr-line-region-on-original-snapshot'}),
      (l2:SourceLocator {uid: 'hu:locator:bad-dangling-image-region'})
MERGE (c)-[:HAS_ANNOTATION]->(ann) MERGE (ss)-[:HAS_LOCATOR]->(l) MERGE (l)-[:LOCATES_REGION]->(ann) MERGE (ss)-[:HAS_LOCATOR]->(l2);

MERGE (x:Assertion {uid: 'hu:assertion:bad-nr-declaration-cited-on-crop-region'})
SET x.predicate = 'DECLARATION_IDENTIFIES_MATERIAL', x.status = 'PROPOSED', x.recordedAt = datetime('2026-10-04T02:55:00Z'), x.predicateClass = 'IDENTITY';

MATCH (x:Assertion {uid: 'hu:assertion:bad-nr-declaration-cited-on-crop-region'}), (d:LabelDeclaration {uid: 'hu:label-declaration:basis-sf-image-elysium-nr-250mg'}), (l:SourceLocator {uid: 'hu:locator:bad-nr-line-region-on-original-snapshot'})
MERGE (x)-[:HAS_SUBJECT]->(d) MERGE (x)-[:SUPPORTED_BY]->(l);

// ---- Derivation job LABEL-REGION-PRODUCT-1: ABOUT_PRODUCT from the W04 LABEL_FOR on the snapshot whose IMAGE_REGION
// ---- locator LOCATES_REGION the region's annotation; the Product is reached through HAS_VARIANT.
MATCH (r:ProductLabelRegion)-[:FROM_ANNOTATION]->(ann:MediaAnnotation)<-[:LOCATES_REGION]-(l:SourceLocator {selectorKind: 'IMAGE_REGION'})<-[:HAS_LOCATOR]-(ss:SourceSnapshot)
MATCH (ss)-[lf:LABEL_FOR]->(pv:ProductVariant)<-[:HAS_VARIANT]-(p:Product)
WHERE lf.recordedTo IS NULL AND l.mediaAnnotationUid = ann.uid
MERGE (r)-[e:ABOUT_PRODUCT {derivationRule: 'LABEL-REGION-PRODUCT-1'}]->(p)
SET e.derivedFromAssertionUids = [lf.assertionUid], e.derivedAt = datetime('2026-10-04T03:00:00Z')
RETURN r.uid AS region, p.uid AS product;

// =====================================================================================================================
// Queries
// =====================================================================================================================

// Q-MP5-1 (CQ-MD-C04, CQ-PV-02, CQ-PV-03): full provenance of the crop - the activity, the original rendition, the
// region, the locator, the snapshot and the source, with byte equality between the original rendition and the snapshot.
// Expected 1 row.
MATCH (c:MediaVariant {uid: 'hu:media-variant:basis-supplement-facts-panel-crop'})-[:WAS_GENERATED_BY]->(act:Activity {activityKind: 'MEDIA_TRANSFORMATION'})
MATCH (act)-[:USED]->(orig:MediaVariant {variantKind: 'ORIGINAL'})-[:HAS_ANNOTATION]->(ann:MediaAnnotation)<-[:USED]-(act)
MATCH (ann)<-[:LOCATES_REGION]-(l:SourceLocator {selectorKind: 'IMAGE_REGION'})<-[:HAS_LOCATOR]-(ss:SourceSnapshot)<-[:HAS_SNAPSHOT]-(s:Source)
WHERE l.mediaAnnotationUid = ann.uid
OPTIONAL MATCH (reg:ProductLabelRegion)-[:FROM_ANNOTATION]->(ann)
RETURN c.uid AS crop, act.methodVersion AS cropMethod, orig.uid AS fromRendition, orig.contentHash = ss.contentHash AS originalEqualsCapture,
       [ann.x, ann.y, ann.width, ann.height] AS regionPx, ann.normalizationVersion AS frame, c.widthPx = toInteger(ann.width) AND c.heightPx = toInteger(ann.height) AS cropMatchesRegion,
       l.uid AS locator, ss.uid AS snapshot, ss.retrievedAt AS retrievedAt, s.canonicalUri AS source, reg.labelRegionType AS regionType;

// Q-MP5-2 (CQ-PV-02): which renditions the region coordinates are valid on. Only the 1946 px ORIGINAL; the publisher's
// 416 px rendition would need the region rescaled by 416/1946 and a new annotation, never reuse.
MATCH (m:MediaAsset {uid: 'hu:media-asset:elysium-basis-carousel-supplement-facts'})-[:HAS_MEDIA_VARIANT]->(v:MediaVariant)
OPTIONAL MATCH (v)-[:HAS_ANNOTATION]->(ann:MediaAnnotation {uid: 'hu:media-annotation:basis-supplement-facts-panel-w1946'})
RETURN v.uid AS rendition, v.variantKind AS kind, v.widthPx AS widthPx, ann IS NOT NULL AS regionDefinedHere
ORDER BY widthPx DESC;

// Q-MP5-3 (seam W04): declarations read from the region with the citation path; the derived ABOUT_PRODUCT shortcut.
MATCH (reg:ProductLabelRegion {uid: 'hu:label-region:basis-supplement-facts-panel'})-[:REGION_HAS_DECLARATION]->(d:LabelDeclaration)
MATCH (reg)-[:FROM_ANNOTATION]->(ann)<-[:LOCATES_REGION]-(l:SourceLocator)
OPTIONAL MATCH (reg)-[ap:ABOUT_PRODUCT]->(p:Product)
RETURN reg.uid AS region, d.verbatimText AS declaration, l.uid AS citeAs, p.uid AS aboutProduct, ap.derivationRule AS derivedBy;
