// W12 fixture 40: E. coli across lots (absent / not detected / not reported / not measured); release versus shelf-life criteria; decision rules
// Run run-2026-10-04-fable51-01, worker W12 (Opus 5.5). Generated by the W12 fixture generator (scratchpad gen.py);
// edit the generator, not this file. Every statement binds its own nodes by uid (no variable crosses ';').
// Load order: w12-00-base -> w12-10 -> w12-20 -> w12-30 -> w12-40 -> w12-90 (then optionally w12-negatives).
// Real sources carry contentHashBasis STORED_EXCERPT_TEXT over the excerpt files in fixtures/excerpts/ (sha256 of the
// stored file bytes); synthetic records carry SYNTHETIC_FIXTURE and canonicalUri urn:synthetic:w12:*.
// Uid tokens lot, test-sample, test-execution, test-method, measured-result, spec-criterion, pass-fail,
// lot-test-summary, coa, cert-program, cert-listing, cert-scope are PROPOSED (W12-SR-01); spec-version (W11),
// individual-unit (W15) and quantity-declaration (W04) are placeholders for those owners' tokens.
// Status: executed on embedded Neo4j 5.26.31 Community (see 06-fixtures-and-queries.md for counts).

// A. E. coli NOT_DETECTED (enumeration, LOD 10 CFU/g) on lot 70579. Lot 70918 has no E. coli execution at all: NOT MEASURED (no node is written).
// Lot P098-01: QUALITATIVE_ABSENT (fixture 10, Lab Z). Lot T25189001: NOT_REPORTED pass (fixture 10, real COA).
MERGE (n:TestSample:Entity {uid: 'hu:test-sample:synthetic-lab-z-70579'})
SET n.entityType = 'TEST_SAMPLE', n.privacyClass = 'PUBLIC', n.schemaVersion = 'w12-proposal-0.1', n.name = 'Lab Z sample of Basis lot 70579 (synthetic)', n.sampleCode = 'LZ-S-2026-0391', n.id = 'synthetic-lab-z-70579', n.createdAt = datetime('2026-10-04T02:00:00Z'), n.updatedAt = datetime('2026-10-04T02:00:00Z');

MATCH (x:TestSample {uid: 'hu:test-sample:synthetic-lab-z-70579'}), (y:ProductLot {uid: 'hu:lot:elysium-basis-70579'}), (who:TestingLaboratory {uid: 'hu:org:synthetic-lab-z'}), (l0:SourceLocator {uid: 'hu:locator:synthetic-lab-z-70579-header'})
MERGE (a:Assertion {uid: 'hu:assertion:w12-sample-from-lz-70579'})
SET a.predicate = 'SAMPLE_FROM', a.status = 'ACCEPTED', a.recordedAt = datetime('2026-10-04T02:00:00Z'), a.polarity = 'POSITIVE', a.contentHash = 'sha256:b4630941f4256840b0226ecb5b39003865dfafc9946450d782ac720ea8f55edb', a.validFromBasis = 'UNKNOWN', a.validToBasis = 'UNKNOWN', a.speechAct = 'STATES', a.privacyClass = 'PUBLIC', a.createdAt = datetime('2026-10-04T02:00:00Z'), a.updatedAt = datetime('2026-10-04T02:00:00Z')
MERGE (a)-[:HAS_SUBJECT]->(x)
MERGE (a)-[:HAS_OBJECT]->(y)
MERGE (a)-[:ASSERTED_BY]->(who)
MERGE (a)-[:SUPPORTED_BY]->(l0)
MERGE (x)-[r:SAMPLE_FROM {relationshipUid: 'hu:rel:w12-sample-from-lz-70579'}]->(y)
SET r.assertionUid = 'hu:assertion:w12-sample-from-lz-70579', r.recordedFrom = datetime('2026-10-04T02:00:00Z'), r.validFromBasis = 'UNKNOWN', r.validToBasis = 'UNKNOWN';

MERGE (n:TestExecution:Occurrence {uid: 'hu:test-execution:synthetic-lab-z-70579-ecoli'})
SET n.occurrenceType = 'TEST_EXECUTION', n.privacyClass = 'PUBLIC', n.schemaVersion = 'w12-proposal-0.1', n.name = 'Lab Z 70579 E. coli enumeration', n.testNameVerbatim = 'E. coli (enumeration)', n.status = 'COMPLETED', n.testPurpose = 'SURVEILLANCE', n.accreditationScopeStatus = 'WITHIN_SCOPE', n.subcontracted = false, n.id = 'synthetic-lab-z-70579-ecoli', n.createdAt = datetime('2026-10-04T02:00:00Z'), n.updatedAt = datetime('2026-10-04T02:00:00Z');

MATCH (x:TestExecution {uid: 'hu:test-execution:synthetic-lab-z-70579-ecoli'}), (y:TestSample {uid: 'hu:test-sample:synthetic-lab-z-70579'})
MERGE (x)-[r:TESTED_SAMPLE]->(y);

MATCH (x:TestExecution {uid: 'hu:test-execution:synthetic-lab-z-70579-ecoli'}), (y:TestMethod {uid: 'hu:test-method:synthetic-plate-count-e-coli'}), (who:TestingLaboratory {uid: 'hu:org:synthetic-lab-z'}), (l0:SourceLocator {uid: 'hu:locator:synthetic-lab-z-70579-ecoli'})
MERGE (a:Assertion {uid: 'hu:assertion:w12-used-method-lz-70579-ecoli'})
SET a.predicate = 'USED_METHOD', a.status = 'ACCEPTED', a.recordedAt = datetime('2026-10-04T02:00:00Z'), a.polarity = 'POSITIVE', a.contentHash = 'sha256:1bb5874c50682942bf50091aa2c5d3fb3ef776f7ac575e90dbba7333712683ca', a.validFromBasis = 'UNKNOWN', a.validToBasis = 'UNKNOWN', a.speechAct = 'STATES', a.privacyClass = 'PUBLIC', a.createdAt = datetime('2026-10-04T02:00:00Z'), a.updatedAt = datetime('2026-10-04T02:00:00Z')
MERGE (a)-[:HAS_SUBJECT]->(x)
MERGE (a)-[:HAS_OBJECT]->(y)
MERGE (a)-[:ASSERTED_BY]->(who)
MERGE (a)-[:SUPPORTED_BY]->(l0)
MERGE (x)-[r:USED_METHOD {relationshipUid: 'hu:rel:w12-used-method-lz-70579-ecoli'}]->(y)
SET r.assertionUid = 'hu:assertion:w12-used-method-lz-70579-ecoli', r.recordedFrom = datetime('2026-10-04T02:00:00Z'), r.validFromBasis = 'UNKNOWN', r.validToBasis = 'UNKNOWN';

MATCH (x:TestExecution {uid: 'hu:test-execution:synthetic-lab-z-70579-ecoli'}), (y:TestingLaboratory {uid: 'hu:org:synthetic-lab-z'}), (who:TestingLaboratory {uid: 'hu:org:synthetic-lab-z'}), (l0:SourceLocator {uid: 'hu:locator:synthetic-lab-z-70579-ecoli'})
MERGE (a:Assertion {uid: 'hu:assertion:w12-performed-by-lz-70579-ecoli'})
SET a.predicate = 'PERFORMED_BY_LAB', a.status = 'ACCEPTED', a.recordedAt = datetime('2026-10-04T02:00:00Z'), a.polarity = 'POSITIVE', a.contentHash = 'sha256:5257626bb6f1d79417c3c99b728e793bf2ef979929ea2a3a6754a1f14b542f65', a.validFromBasis = 'UNKNOWN', a.validToBasis = 'UNKNOWN', a.speechAct = 'STATES', a.privacyClass = 'PUBLIC', a.createdAt = datetime('2026-10-04T02:00:00Z'), a.updatedAt = datetime('2026-10-04T02:00:00Z')
MERGE (a)-[:HAS_SUBJECT]->(x)
MERGE (a)-[:HAS_OBJECT]->(y)
MERGE (a)-[:ASSERTED_BY]->(who)
MERGE (a)-[:SUPPORTED_BY]->(l0)
MERGE (x)-[r:PERFORMED_BY_LAB {relationshipUid: 'hu:rel:w12-performed-by-lz-70579-ecoli'}]->(y)
SET r.assertionUid = 'hu:assertion:w12-performed-by-lz-70579-ecoli', r.recordedFrom = datetime('2026-10-04T02:00:00Z'), r.validFromBasis = 'UNKNOWN', r.validToBasis = 'UNKNOWN';

MERGE (n:MeasuredResult:InformationArtifact {uid: 'hu:measured-result:synthetic-lab-z-70579-e-coli'})
SET n.artifactType = 'MEASURED_RESULT', n.privacyClass = 'PUBLIC', n.schemaVersion = 'w12-proposal-0.1', n.contentHash = 'sha256:eaf330e2a47e7dca4ca09f01d1eb6e4769becec753fa8093cf4cb17ad75b2a58', n.name = 'Lab Z 70579 E. coli < 10 CFU/g', n.analyte = 'E. coli', n.valueTextVerbatim = '< 10 CFU/g', n.unitCode = '[CFU]/g', n.limitOfDetection = 10.0, n.qualifier = 'NOT_DETECTED', n.id = 'synthetic-lab-z-70579-e-coli', n.createdAt = datetime('2026-10-04T02:00:00Z'), n.updatedAt = datetime('2026-10-04T02:00:00Z');

MATCH (x:TestExecution {uid: 'hu:test-execution:synthetic-lab-z-70579-ecoli'}), (y:MeasuredResult {uid: 'hu:measured-result:synthetic-lab-z-70579-e-coli'})
MERGE (x)-[r:PRODUCED_RESULT]->(y);

MATCH (x:MeasuredResult {uid: 'hu:measured-result:synthetic-lab-z-70579-e-coli'}), (y:SourceLocator {uid: 'hu:locator:synthetic-lab-z-70579-ecoli'})
MERGE (x)-[r:SUPPORTED_BY]->(y);

// Criterion printed with the enumeration result (found missing by V-W12-01 on the first run)
MERGE (n:SpecificationCriterion:VersionedState {uid: 'hu:spec-criterion:synthetic-lz-basis-e-coli-enumeration-nmt-10'})
SET n.stateType = 'SPECIFICATION_CRITERION', n.payloadHash = 'sha256:d7c83ffc0c891376b5732a1a11993a8c34e4f03c24c3de01a0a7297add0f22a5', n.privacyClass = 'PUBLIC', n.schemaVersion = 'w12-proposal-0.1', n.analyte = 'E. coli', n.comparator = 'NOT_MORE_THAN', n.threshold = 10.0, n.unitCode = '[CFU]/g', n.criterionText = 'E. coli (enumeration): < 10 CFU/g', n.criterionPurpose = 'RELEASE_AND_SHELF_LIFE', n.criterionBasis = 'INTERNAL', n.id = 'synthetic-lz-basis-e-coli-enumeration-nmt-10', n.createdAt = datetime('2026-10-04T02:00:00Z'), n.updatedAt = datetime('2026-10-04T02:00:00Z');

MATCH (x:SpecificationCriterion {uid: 'hu:spec-criterion:synthetic-lz-basis-e-coli-enumeration-nmt-10'}), (y:SpecificationVersion {uid: 'hu:spec-version:synthetic-lab-z-client-criteria-basis'})
MERGE (x)-[r:CRITERION_OF_SPECIFICATION]->(y);

MATCH (x:MeasuredResult {uid: 'hu:measured-result:synthetic-lab-z-70579-e-coli'}), (y:SpecificationCriterion {uid: 'hu:spec-criterion:synthetic-lz-basis-e-coli-enumeration-nmt-10'}), (who:TestingLaboratory {uid: 'hu:org:synthetic-lab-z'}), (l0:SourceLocator {uid: 'hu:locator:synthetic-lab-z-70579-ecoli'})
MERGE (a:Assertion {uid: 'hu:assertion:w12-evaluated-against-lz-70579-ecoli'})
SET a.predicate = 'EVALUATED_AGAINST', a.status = 'ACCEPTED', a.recordedAt = datetime('2026-10-04T02:00:00Z'), a.polarity = 'POSITIVE', a.contentHash = 'sha256:b45e6be4bd40998d87aa9fde9e056d3574d5b319ffad64d076d696d1115bbffa', a.validFromBasis = 'UNKNOWN', a.validToBasis = 'UNKNOWN', a.speechAct = 'STATES', a.privacyClass = 'PUBLIC', a.createdAt = datetime('2026-10-04T02:00:00Z'), a.updatedAt = datetime('2026-10-04T02:00:00Z')
MERGE (a)-[:HAS_SUBJECT]->(x)
MERGE (a)-[:HAS_OBJECT]->(y)
MERGE (a)-[:ASSERTED_BY]->(who)
MERGE (a)-[:SUPPORTED_BY]->(l0)
MERGE (x)-[r:EVALUATED_AGAINST {relationshipUid: 'hu:rel:w12-evaluated-against-lz-70579-ecoli'}]->(y)
SET r.assertionUid = 'hu:assertion:w12-evaluated-against-lz-70579-ecoli', r.recordedFrom = datetime('2026-10-04T02:00:00Z'), r.validFromBasis = 'UNKNOWN', r.validToBasis = 'UNKNOWN';

MERGE (n:CertificateOfAnalysis:InformationArtifact {uid: 'hu:coa:synthetic-lab-z-lz-2026-0415-00'})
SET n.artifactType = 'CERTIFICATE_OF_ANALYSIS', n.privacyClass = 'PUBLIC', n.schemaVersion = 'w12-proposal-0.1', n.contentHash = 'sha256:5dec6f7c262f16f94be533b44835bc2a76908128ff710b43064a911650bf6bd7', n.name = 'Certificate LZ-2026-0415-00 (synthetic)', n.certificateNumber = 'LZ-2026-0415-00', n.revisionNumber = '00', n.reportDate = datetime('2026-04-22T00:00:00Z'), n.reportDatePrecision = 'DAY', n.documentTitleVerbatim = 'Certificate of Analysis', n.signatureEvidence = 'ELECTRONIC_APPROVAL_STATEMENT', n.signer = 'Microbiology Lead (synthetic)', n.id = 'synthetic-lab-z-lz-2026-0415-00', n.createdAt = datetime('2026-10-04T02:00:00Z'), n.updatedAt = datetime('2026-10-04T02:00:00Z');

MATCH (x:CertificateOfAnalysis {uid: 'hu:coa:synthetic-lab-z-lz-2026-0415-00'}), (y:SourceLocator {uid: 'hu:locator:synthetic-lab-z-70579-header'})
MERGE (x)-[r:SUPPORTED_BY]->(y);

MATCH (x:CertificateOfAnalysis {uid: 'hu:coa:synthetic-lab-z-lz-2026-0415-00'}), (y:TestingLaboratory {uid: 'hu:org:synthetic-lab-z'}), (who:TestingLaboratory {uid: 'hu:org:synthetic-lab-z'}), (l0:SourceLocator {uid: 'hu:locator:synthetic-lab-z-70579-header'})
MERGE (a:Assertion {uid: 'hu:assertion:w12-coa-issued-by-lz-2026-0415-00'})
SET a.predicate = 'COA_ISSUED_BY', a.status = 'ACCEPTED', a.recordedAt = datetime('2026-10-04T02:00:00Z'), a.polarity = 'POSITIVE', a.contentHash = 'sha256:80f790e4b43832dec9c97d67a1b955899f121ca6c479bc2daf76c78e49b7167c', a.validFromBasis = 'UNKNOWN', a.validToBasis = 'UNKNOWN', a.speechAct = 'STATES', a.privacyClass = 'PUBLIC', a.createdAt = datetime('2026-10-04T02:00:00Z'), a.updatedAt = datetime('2026-10-04T02:00:00Z')
MERGE (a)-[:HAS_SUBJECT]->(x)
MERGE (a)-[:HAS_OBJECT]->(y)
MERGE (a)-[:ASSERTED_BY]->(who)
MERGE (a)-[:SUPPORTED_BY]->(l0)
MERGE (x)-[r:COA_ISSUED_BY {relationshipUid: 'hu:rel:w12-coa-issued-by-lz-2026-0415-00'}]->(y)
SET r.assertionUid = 'hu:assertion:w12-coa-issued-by-lz-2026-0415-00', r.recordedFrom = datetime('2026-10-04T02:00:00Z'), r.validFromBasis = 'UNKNOWN', r.validToBasis = 'UNKNOWN';

MATCH (x:CertificateOfAnalysis {uid: 'hu:coa:synthetic-lab-z-lz-2026-0415-00'}), (y:ProductLot {uid: 'hu:lot:elysium-basis-70579'}), (who:TestingLaboratory {uid: 'hu:org:synthetic-lab-z'}), (l0:SourceLocator {uid: 'hu:locator:synthetic-lab-z-70579-header'})
MERGE (a:Assertion {uid: 'hu:assertion:w12-coa-certifies-lz-0415-70579'})
SET a.predicate = 'CERTIFIES_RESULTS_FOR', a.status = 'ACCEPTED', a.recordedAt = datetime('2026-10-04T02:00:00Z'), a.polarity = 'POSITIVE', a.contentHash = 'sha256:90130b5cf995e0b38a0b877cc81cbf84842080e0c6e2264f3ef00b1a83455ddf', a.validFromBasis = 'UNKNOWN', a.validToBasis = 'UNKNOWN', a.speechAct = 'STATES', a.privacyClass = 'PUBLIC', a.createdAt = datetime('2026-10-04T02:00:00Z'), a.updatedAt = datetime('2026-10-04T02:00:00Z')
MERGE (a)-[:HAS_SUBJECT]->(x)
MERGE (a)-[:HAS_OBJECT]->(y)
MERGE (a)-[:ASSERTED_BY]->(who)
MERGE (a)-[:SUPPORTED_BY]->(l0)
MERGE (x)-[r:CERTIFIES_RESULTS_FOR {relationshipUid: 'hu:rel:w12-coa-certifies-lz-0415-70579'}]->(y)
SET r.assertionUid = 'hu:assertion:w12-coa-certifies-lz-0415-70579', r.recordedFrom = datetime('2026-10-04T02:00:00Z'), r.validFromBasis = 'UNKNOWN', r.validToBasis = 'UNKNOWN';

MATCH (x:CertificateOfAnalysis {uid: 'hu:coa:synthetic-lab-z-lz-2026-0415-00'}), (y:TestExecution {uid: 'hu:test-execution:synthetic-lab-z-70579-ecoli'}), (who:TestingLaboratory {uid: 'hu:org:synthetic-lab-z'}), (l0:SourceLocator {uid: 'hu:locator:synthetic-lab-z-70579-header'})
MERGE (a:Assertion {uid: 'hu:assertion:w12-coa-certifies-lz-0415-ecoli'})
SET a.predicate = 'CERTIFIES_RESULTS_FOR', a.status = 'ACCEPTED', a.recordedAt = datetime('2026-10-04T02:00:00Z'), a.polarity = 'POSITIVE', a.contentHash = 'sha256:869aebf15dd7495d74fe1078713bccbefee4a0b52808e276a45ec0352078403b', a.validFromBasis = 'UNKNOWN', a.validToBasis = 'UNKNOWN', a.speechAct = 'STATES', a.privacyClass = 'PUBLIC', a.createdAt = datetime('2026-10-04T02:00:00Z'), a.updatedAt = datetime('2026-10-04T02:00:00Z')
MERGE (a)-[:HAS_SUBJECT]->(x)
MERGE (a)-[:HAS_OBJECT]->(y)
MERGE (a)-[:ASSERTED_BY]->(who)
MERGE (a)-[:SUPPORTED_BY]->(l0)
MERGE (x)-[r:CERTIFIES_RESULTS_FOR {relationshipUid: 'hu:rel:w12-coa-certifies-lz-0415-ecoli'}]->(y)
SET r.assertionUid = 'hu:assertion:w12-coa-certifies-lz-0415-ecoli', r.recordedFrom = datetime('2026-10-04T02:00:00Z'), r.validFromBasis = 'UNKNOWN', r.validToBasis = 'UNKNOWN';

// B. One specification version with a tighter in-house RELEASE limit and a SHELF_LIFE limit (ICH Q6A 2.2 pattern); an 18-month stability result
MERGE (n:SpecificationVersion:VersionedState {uid: 'hu:spec-version:synthetic-basis-stability-spec-v1'})
SET n.stateType = 'SPECIFICATION_VERSION', n.payloadHash = 'sha256:2157a5e51b2f5156c26b823801c738a861c0afcab8c944f2b5b738cf871dfacf', n.privacyClass = 'PUBLIC', n.schemaVersion = 'w12-proposal-0.1', n.name = 'Basis release and shelf-life specification v1 (synthetic)', n.id = 'synthetic-basis-stability-spec-v1', n.createdAt = datetime('2026-10-04T02:00:00Z'), n.updatedAt = datetime('2026-10-04T02:00:00Z');

MERGE (n:SpecificationCriterion:VersionedState {uid: 'hu:spec-criterion:synthetic-basis-nrcl-release-nlt-275'})
SET n.stateType = 'SPECIFICATION_CRITERION', n.payloadHash = 'sha256:6b39d54cb4353dc1c8118d7516c86416e66510284ed5419f0ff54b0730bb149c', n.privacyClass = 'PUBLIC', n.schemaVersion = 'w12-proposal-0.1', n.analyte = 'Nicotinamide Riboside Chloride', n.comparator = 'NOT_LESS_THAN', n.threshold = 275.0, n.targetValue = 290.0, n.unitCode = 'mg/{serving}', n.quantityBasis = 'PER_SERVING', n.massBasis = 'SALT_FORM', n.criterionText = 'Release: NLT 275 mg/serving (target 290)', n.criterionPurpose = 'RELEASE', n.criterionBasis = 'INTERNAL', n.id = 'synthetic-basis-nrcl-release-nlt-275', n.createdAt = datetime('2026-10-04T02:00:00Z'), n.updatedAt = datetime('2026-10-04T02:00:00Z');

MATCH (x:SpecificationCriterion {uid: 'hu:spec-criterion:synthetic-basis-nrcl-release-nlt-275'}), (y:SpecificationVersion {uid: 'hu:spec-version:synthetic-basis-stability-spec-v1'})
MERGE (x)-[r:CRITERION_OF_SPECIFICATION]->(y);

MERGE (n:SpecificationCriterion:VersionedState {uid: 'hu:spec-criterion:synthetic-basis-nrcl-shelf-life-nlt-250'})
SET n.stateType = 'SPECIFICATION_CRITERION', n.payloadHash = 'sha256:be5460d644f580fc7398263a59dbb8f9887e6425d04a8e0f59f0bd29a230881a', n.privacyClass = 'PUBLIC', n.schemaVersion = 'w12-proposal-0.1', n.analyte = 'Nicotinamide Riboside Chloride', n.comparator = 'NOT_LESS_THAN', n.threshold = 250.0, n.unitCode = 'mg/{serving}', n.quantityBasis = 'PER_SERVING', n.massBasis = 'SALT_FORM', n.criterionText = 'Shelf-life: NLT 250 mg/serving', n.criterionPurpose = 'SHELF_LIFE', n.criterionBasis = 'INTERNAL', n.id = 'synthetic-basis-nrcl-shelf-life-nlt-250', n.createdAt = datetime('2026-10-04T02:00:00Z'), n.updatedAt = datetime('2026-10-04T02:00:00Z');

MATCH (x:SpecificationCriterion {uid: 'hu:spec-criterion:synthetic-basis-nrcl-shelf-life-nlt-250'}), (y:SpecificationVersion {uid: 'hu:spec-version:synthetic-basis-stability-spec-v1'})
MERGE (x)-[r:CRITERION_OF_SPECIFICATION]->(y);

// MANUFACTURED_UNDER asserted by the (synthetic) stability report; PROPOSED because a lab is not the specification owner
MATCH (x:ProductLot {uid: 'hu:lot:elysium-basis-70064'}), (y:SpecificationVersion {uid: 'hu:spec-version:synthetic-basis-stability-spec-v1'}), (who:TestingLaboratory {uid: 'hu:org:synthetic-lab-z'}), (l0:SourceLocator {uid: 'hu:locator:synthetic-lab-z-70064-stability'})
MERGE (a:Assertion {uid: 'hu:assertion:w12-manufactured-under-70064-synthetic-spec'})
SET a.predicate = 'MANUFACTURED_UNDER', a.status = 'PROPOSED', a.recordedAt = datetime('2026-10-04T02:00:00Z'), a.polarity = 'POSITIVE', a.contentHash = 'sha256:fe0980e9422a15af0dda8934a9220b2bb76cb50115120ea0d06d7c28332b6fc0', a.validFromBasis = 'UNKNOWN', a.validToBasis = 'UNKNOWN', a.speechAct = 'STATES', a.privacyClass = 'PUBLIC', a.createdAt = datetime('2026-10-04T02:00:00Z'), a.updatedAt = datetime('2026-10-04T02:00:00Z')
MERGE (a)-[:HAS_SUBJECT]->(x)
MERGE (a)-[:HAS_OBJECT]->(y)
MERGE (a)-[:ASSERTED_BY]->(who)
MERGE (a)-[:SUPPORTED_BY]->(l0)
MERGE (x)-[r:MANUFACTURED_UNDER {relationshipUid: 'hu:rel:w12-manufactured-under-70064-synthetic-spec'}]->(y)
SET r.assertionUid = 'hu:assertion:w12-manufactured-under-70064-synthetic-spec', r.recordedFrom = datetime('2026-10-04T02:00:00Z'), r.validFromBasis = 'UNKNOWN', r.validToBasis = 'UNKNOWN';

MERGE (n:TestSample:Entity {uid: 'hu:test-sample:synthetic-lab-z-70064-m18'})
SET n.entityType = 'TEST_SAMPLE', n.privacyClass = 'PUBLIC', n.schemaVersion = 'w12-proposal-0.1', n.name = 'Stability sample, lot 70064, month 18 (synthetic)', n.sampleCode = 'STB-70064-M18', n.samplingMethod = 'stability chamber pull, 25 °C/60 % RH (synthetic)', n.id = 'synthetic-lab-z-70064-m18', n.createdAt = datetime('2026-10-04T02:00:00Z'), n.updatedAt = datetime('2026-10-04T02:00:00Z');

MATCH (x:TestSample {uid: 'hu:test-sample:synthetic-lab-z-70064-m18'}), (y:ProductLot {uid: 'hu:lot:elysium-basis-70064'}), (who:TestingLaboratory {uid: 'hu:org:synthetic-lab-z'}), (l0:SourceLocator {uid: 'hu:locator:synthetic-lab-z-70064-stability'})
MERGE (a:Assertion {uid: 'hu:assertion:w12-sample-from-70064-m18'})
SET a.predicate = 'SAMPLE_FROM', a.status = 'ACCEPTED', a.recordedAt = datetime('2026-10-04T02:00:00Z'), a.polarity = 'POSITIVE', a.contentHash = 'sha256:0f110e7c61d396de0e93b53ce73319a192e2c16b99fdf7300a7a6bd2491124df', a.validFromBasis = 'UNKNOWN', a.validToBasis = 'UNKNOWN', a.speechAct = 'STATES', a.privacyClass = 'PUBLIC', a.createdAt = datetime('2026-10-04T02:00:00Z'), a.updatedAt = datetime('2026-10-04T02:00:00Z')
MERGE (a)-[:HAS_SUBJECT]->(x)
MERGE (a)-[:HAS_OBJECT]->(y)
MERGE (a)-[:ASSERTED_BY]->(who)
MERGE (a)-[:SUPPORTED_BY]->(l0)
MERGE (x)-[r:SAMPLE_FROM {relationshipUid: 'hu:rel:w12-sample-from-70064-m18'}]->(y)
SET r.assertionUid = 'hu:assertion:w12-sample-from-70064-m18', r.recordedFrom = datetime('2026-10-04T02:00:00Z'), r.validFromBasis = 'UNKNOWN', r.validToBasis = 'UNKNOWN';

MERGE (n:TestExecution:Occurrence {uid: 'hu:test-execution:synthetic-lab-z-70064-m18-potency'})
SET n.occurrenceType = 'TEST_EXECUTION', n.privacyClass = 'PUBLIC', n.schemaVersion = 'w12-proposal-0.1', n.name = 'Stability potency lot 70064 month 18', n.testNameVerbatim = 'Assay (stability, 18 months)', n.status = 'COMPLETED', n.testPurpose = 'STABILITY', n.accreditationScopeStatus = 'WITHIN_SCOPE', n.subcontracted = false, n.id = 'synthetic-lab-z-70064-m18-potency', n.createdAt = datetime('2026-10-04T02:00:00Z'), n.updatedAt = datetime('2026-10-04T02:00:00Z');

MATCH (x:TestExecution {uid: 'hu:test-execution:synthetic-lab-z-70064-m18-potency'}), (y:TestSample {uid: 'hu:test-sample:synthetic-lab-z-70064-m18'})
MERGE (x)-[r:TESTED_SAMPLE]->(y);

MATCH (x:TestExecution {uid: 'hu:test-execution:synthetic-lab-z-70064-m18-potency'}), (y:TestMethod {uid: 'hu:test-method:synthetic-lz-hplc-nr-003'}), (who:TestingLaboratory {uid: 'hu:org:synthetic-lab-z'}), (l0:SourceLocator {uid: 'hu:locator:synthetic-lab-z-70064-stability'})
MERGE (a:Assertion {uid: 'hu:assertion:w12-used-method-70064-m18'})
SET a.predicate = 'USED_METHOD', a.status = 'ACCEPTED', a.recordedAt = datetime('2026-10-04T02:00:00Z'), a.polarity = 'POSITIVE', a.contentHash = 'sha256:b2add8eb9bda247bdd9e9bbdc1ecabb2bc301adc43c3132f36dca025987149be', a.validFromBasis = 'UNKNOWN', a.validToBasis = 'UNKNOWN', a.speechAct = 'STATES', a.privacyClass = 'PUBLIC', a.createdAt = datetime('2026-10-04T02:00:00Z'), a.updatedAt = datetime('2026-10-04T02:00:00Z')
MERGE (a)-[:HAS_SUBJECT]->(x)
MERGE (a)-[:HAS_OBJECT]->(y)
MERGE (a)-[:ASSERTED_BY]->(who)
MERGE (a)-[:SUPPORTED_BY]->(l0)
MERGE (x)-[r:USED_METHOD {relationshipUid: 'hu:rel:w12-used-method-70064-m18'}]->(y)
SET r.assertionUid = 'hu:assertion:w12-used-method-70064-m18', r.recordedFrom = datetime('2026-10-04T02:00:00Z'), r.validFromBasis = 'UNKNOWN', r.validToBasis = 'UNKNOWN';

MATCH (x:TestExecution {uid: 'hu:test-execution:synthetic-lab-z-70064-m18-potency'}), (y:TestingLaboratory {uid: 'hu:org:synthetic-lab-z'}), (who:TestingLaboratory {uid: 'hu:org:synthetic-lab-z'}), (l0:SourceLocator {uid: 'hu:locator:synthetic-lab-z-70064-stability'})
MERGE (a:Assertion {uid: 'hu:assertion:w12-performed-by-70064-m18'})
SET a.predicate = 'PERFORMED_BY_LAB', a.status = 'ACCEPTED', a.recordedAt = datetime('2026-10-04T02:00:00Z'), a.polarity = 'POSITIVE', a.contentHash = 'sha256:7dd72280faeb1bf7b812db45d0c70e590410b2cce5f91db67185131a9a0d6513', a.validFromBasis = 'UNKNOWN', a.validToBasis = 'UNKNOWN', a.speechAct = 'STATES', a.privacyClass = 'PUBLIC', a.createdAt = datetime('2026-10-04T02:00:00Z'), a.updatedAt = datetime('2026-10-04T02:00:00Z')
MERGE (a)-[:HAS_SUBJECT]->(x)
MERGE (a)-[:HAS_OBJECT]->(y)
MERGE (a)-[:ASSERTED_BY]->(who)
MERGE (a)-[:SUPPORTED_BY]->(l0)
MERGE (x)-[r:PERFORMED_BY_LAB {relationshipUid: 'hu:rel:w12-performed-by-70064-m18'}]->(y)
SET r.assertionUid = 'hu:assertion:w12-performed-by-70064-m18', r.recordedFrom = datetime('2026-10-04T02:00:00Z'), r.validFromBasis = 'UNKNOWN', r.validToBasis = 'UNKNOWN';

MERGE (n:MeasuredResult:InformationArtifact {uid: 'hu:measured-result:synthetic-lab-z-70064-m18-potency'})
SET n.artifactType = 'MEASURED_RESULT', n.privacyClass = 'PUBLIC', n.schemaVersion = 'w12-proposal-0.1', n.contentHash = 'sha256:b81e5ecaa4aa6558d5b35a5a67561e9d83dbe9f76bb395613a9a5976a3ced1c9', n.name = 'Lot 70064 month-18 potency', n.analyte = 'Nicotinamide Riboside Chloride', n.value = 258.0, n.valueTextVerbatim = '258 mg/serving', n.unitCode = 'mg/{serving}', n.uncertainty = 9.0, n.uncertaintyKind = 'EXPANDED', n.coverageFactor = 2.0, n.qualifier = 'QUANTIFIED', n.quantityBasis = 'PER_SERVING', n.massBasis = 'SALT_FORM', n.amountReferent = 'LISTED_INGREDIENT_AS_LISTED', n.id = 'synthetic-lab-z-70064-m18-potency', n.createdAt = datetime('2026-10-04T02:00:00Z'), n.updatedAt = datetime('2026-10-04T02:00:00Z');

MATCH (x:TestExecution {uid: 'hu:test-execution:synthetic-lab-z-70064-m18-potency'}), (y:MeasuredResult {uid: 'hu:measured-result:synthetic-lab-z-70064-m18-potency'})
MERGE (x)-[r:PRODUCED_RESULT]->(y);

MATCH (x:MeasuredResult {uid: 'hu:measured-result:synthetic-lab-z-70064-m18-potency'}), (y:SourceLocator {uid: 'hu:locator:synthetic-lab-z-70064-stability'})
MERGE (x)-[r:SUPPORTED_BY]->(y);

MATCH (x:MeasuredResult {uid: 'hu:measured-result:synthetic-lab-z-70064-m18-potency'}), (y:SpecificationCriterion {uid: 'hu:spec-criterion:synthetic-basis-nrcl-shelf-life-nlt-250'}), (who:TestingLaboratory {uid: 'hu:org:synthetic-lab-z'}), (l0:SourceLocator {uid: 'hu:locator:synthetic-lab-z-70064-stability'})
MERGE (a:Assertion {uid: 'hu:assertion:w12-evaluated-against-70064-m18-shelf-life'})
SET a.predicate = 'EVALUATED_AGAINST', a.status = 'ACCEPTED', a.recordedAt = datetime('2026-10-04T02:00:00Z'), a.polarity = 'POSITIVE', a.contentHash = 'sha256:35306c391ad0962cbf8facc9f14cab450886916d514ccededd635057f1048bc5', a.validFromBasis = 'UNKNOWN', a.validToBasis = 'UNKNOWN', a.speechAct = 'STATES', a.privacyClass = 'PUBLIC', a.createdAt = datetime('2026-10-04T02:00:00Z'), a.updatedAt = datetime('2026-10-04T02:00:00Z')
MERGE (a)-[:HAS_SUBJECT]->(x)
MERGE (a)-[:HAS_OBJECT]->(y)
MERGE (a)-[:ASSERTED_BY]->(who)
MERGE (a)-[:SUPPORTED_BY]->(l0)
MERGE (x)-[r:EVALUATED_AGAINST {relationshipUid: 'hu:rel:w12-evaluated-against-70064-m18-shelf-life'}]->(y)
SET r.assertionUid = 'hu:assertion:w12-evaluated-against-70064-m18-shelf-life', r.recordedFrom = datetime('2026-10-04T02:00:00Z'), r.validFromBasis = 'UNKNOWN', r.validToBasis = 'UNKNOWN';

// C. Two decision rules, two verdicts on the same result and criterion; neither supersedes the other
MERGE (n:PassFailInterpretation:EvidenceAssessment {uid: 'hu:pass-fail:synthetic-70064-m18-shelf-life-simple'})
SET n.assessmentType = 'PASS_FAIL_INTERPRETATION', n.methodVersion = 'w12-pass-fail-evaluator/1;SIMPLE_ACCEPTANCE', n.status = 'ACCEPTED', n.recordedAt = datetime('2026-10-04T02:00:00Z'), n.privacyClass = 'PUBLIC', n.schemaVersion = 'w12-proposal-0.1', n.verdict = 'CONFORMS', n.verdictBasis = 'EVALUATED_FROM_RESULT', n.decisionRule = 'SIMPLE_ACCEPTANCE', n.resultValueReported = 'REPORTED', n.rationale = '258 >= 250 (uncertainty not applied)', n.id = 'synthetic-70064-m18-shelf-life-simple', n.createdAt = datetime('2026-10-04T02:00:00Z'), n.updatedAt = datetime('2026-10-04T02:00:00Z');

MATCH (x:PassFailInterpretation {uid: 'hu:pass-fail:synthetic-70064-m18-shelf-life-simple'}), (y:MeasuredResult {uid: 'hu:measured-result:synthetic-lab-z-70064-m18-potency'})
MERGE (x)-[r:INTERPRETS_RESULT]->(y);

MATCH (x:PassFailInterpretation {uid: 'hu:pass-fail:synthetic-70064-m18-shelf-life-simple'}), (y:SpecificationCriterion {uid: 'hu:spec-criterion:synthetic-basis-nrcl-shelf-life-nlt-250'})
MERGE (x)-[r:APPLIES_CRITERION]->(y);

MATCH (x:PassFailInterpretation {uid: 'hu:pass-fail:synthetic-70064-m18-shelf-life-simple'}), (y:TestExecution {uid: 'hu:test-execution:synthetic-lab-z-70064-m18-potency'})
MERGE (x)-[r:INTERPRETS_TESTING_OF]->(y);

MERGE (n:PassFailInterpretation:EvidenceAssessment {uid: 'hu:pass-fail:synthetic-70064-m18-shelf-life-guard-band'})
SET n.assessmentType = 'PASS_FAIL_INTERPRETATION', n.methodVersion = 'w12-pass-fail-evaluator/1;GUARD_BAND_EXPANDED_U', n.status = 'ACCEPTED', n.recordedAt = datetime('2026-10-04T02:00:00Z'), n.privacyClass = 'PUBLIC', n.schemaVersion = 'w12-proposal-0.1', n.verdict = 'INDETERMINATE', n.verdictBasis = 'EVALUATED_FROM_RESULT', n.decisionRule = 'GUARD_BAND_EXPANDED_U', n.resultValueReported = 'REPORTED', n.rationale = 'interval [249, 267] straddles 250', n.id = 'synthetic-70064-m18-shelf-life-guard-band', n.createdAt = datetime('2026-10-04T02:00:00Z'), n.updatedAt = datetime('2026-10-04T02:00:00Z');

MATCH (x:PassFailInterpretation {uid: 'hu:pass-fail:synthetic-70064-m18-shelf-life-guard-band'}), (y:MeasuredResult {uid: 'hu:measured-result:synthetic-lab-z-70064-m18-potency'})
MERGE (x)-[r:INTERPRETS_RESULT]->(y);

MATCH (x:PassFailInterpretation {uid: 'hu:pass-fail:synthetic-70064-m18-shelf-life-guard-band'}), (y:SpecificationCriterion {uid: 'hu:spec-criterion:synthetic-basis-nrcl-shelf-life-nlt-250'})
MERGE (x)-[r:APPLIES_CRITERION]->(y);

MATCH (x:PassFailInterpretation {uid: 'hu:pass-fail:synthetic-70064-m18-shelf-life-guard-band'}), (y:TestExecution {uid: 'hu:test-execution:synthetic-lab-z-70064-m18-potency'})
MERGE (x)-[r:INTERPRETS_TESTING_OF]->(y);

