// W12 fixture 00: base identities, sources, snapshots, locators, programs
// Run run-2026-10-04-fable51-01, worker W12 (Opus 5.5). Generated by the W12 fixture generator (scratchpad gen.py);
// edit the generator, not this file. Every statement binds its own nodes by uid (no variable crosses ';').
// Load order: w12-00-base -> w12-10 -> w12-20 -> w12-30 -> w12-40 -> w12-90 (then optionally w12-negatives).
// Real sources carry contentHashBasis STORED_EXCERPT_TEXT over the excerpt files in fixtures/excerpts/ (sha256 of the
// stored file bytes); synthetic records carry SYNTHETIC_FIXTURE and canonicalUri urn:synthetic:w12:*.
// Uid tokens lot, test-sample, test-execution, test-method, measured-result, spec-criterion, pass-fail,
// lot-test-summary, coa, cert-program, cert-listing, cert-scope are PROPOSED (W12-SR-01); spec-version (W11),
// individual-unit (W15) and quantity-declaration (W04) are placeholders for those owners' tokens.
// Status: executed on embedded Neo4j 5.26.31 Community (see 06-fixtures-and-queries.md for counts).

// Organizations (W01 identities used here; labels as in the 0.2.0 fixtures)
MERGE (n:Entity:Organization:LegalEntity {uid: 'hu:org:niagen-bioscience-inc'})
SET n.entityType = 'ORGANIZATION', n.privacyClass = 'PUBLIC', n.schemaVersion = 'w12-proposal-0.1', n.name = 'Niagen Bioscience, Inc.', n.legalName = 'Niagen Bioscience, Inc.', n.id = 'niagen-bioscience-inc', n.createdAt = datetime('2026-10-04T02:00:00Z'), n.updatedAt = datetime('2026-10-04T02:00:00Z');

MERGE (n:Entity:Organization:LegalEntity {uid: 'hu:org:elysium-health-inc'})
SET n.entityType = 'ORGANIZATION', n.privacyClass = 'PUBLIC', n.schemaVersion = 'w12-proposal-0.1', n.name = 'Elysium Health', n.legalName = 'Elysium Health, Inc.', n.id = 'elysium-health-inc', n.createdAt = datetime('2026-10-04T02:00:00Z'), n.updatedAt = datetime('2026-10-04T02:00:00Z');

MERGE (n:Entity:Organization {uid: 'hu:org:nsf-international'})
SET n.entityType = 'ORGANIZATION', n.privacyClass = 'PUBLIC', n.schemaVersion = 'w12-proposal-0.1', n.name = 'NSF International', n.id = 'nsf-international', n.createdAt = datetime('2026-10-04T02:00:00Z'), n.updatedAt = datetime('2026-10-04T02:00:00Z');

MERGE (n:Entity:Organization {uid: 'hu:org:synthetic-accreditation-body'})
SET n.entityType = 'ORGANIZATION', n.privacyClass = 'PUBLIC', n.schemaVersion = 'w12-proposal-0.1', n.name = 'Synthetic accreditation body (fixture only)', n.id = 'synthetic-accreditation-body', n.createdAt = datetime('2026-10-04T02:00:00Z'), n.updatedAt = datetime('2026-10-04T02:00:00Z');

// Testing laboratories: [TestingLaboratory, Organization, Entity]; accreditation is the lab's own verbatim statement
MERGE (n:TestingLaboratory:Organization:Entity {uid: 'hu:org:chromadex-analytics-inc'})
SET n.entityType = 'TESTING_LABORATORY', n.privacyClass = 'PUBLIC', n.schemaVersion = 'w12-proposal-0.1', n.name = 'ChromaDex Analytics, Inc.', n.accreditation = 'ChromaDex Analytics, Inc. is an ISO/IEC 17025:2017 accredited Chemical Testing Laboratory.', n.id = 'chromadex-analytics-inc', n.createdAt = datetime('2026-10-04T02:00:00Z'), n.updatedAt = datetime('2026-10-04T02:00:00Z');

MERGE (n:TestingLaboratory:Organization:Entity {uid: 'hu:org:synthetic-lab-z'})
SET n.entityType = 'TESTING_LABORATORY', n.privacyClass = 'PUBLIC', n.schemaVersion = 'w12-proposal-0.1', n.name = 'Synthetic Lab Z (fixture only)', n.id = 'synthetic-lab-z', n.createdAt = datetime('2026-10-04T02:00:00Z'), n.updatedAt = datetime('2026-10-04T02:00:00Z');

MERGE (n:Entity:Agent {uid: 'hu:agent:w12-fixture-curator'})
SET n.entityType = 'AGENT', n.privacyClass = 'PUBLIC', n.schemaVersion = 'w12-proposal-0.1', n.name = 'W12 fixture curator', n.agentKind = 'MANUAL_AGENT', n.id = 'w12-fixture-curator', n.createdAt = datetime('2026-10-04T02:00:00Z'), n.updatedAt = datetime('2026-10-04T02:00:00Z');

// Facility reused from filing-vs-capability.cypher (same uid) for the facility-GMP scope case
MERGE (n:Entity:Facility {uid: 'hu:facility:synthetic-supplement-plant'})
SET n.entityType = 'FACILITY', n.privacyClass = 'PUBLIC', n.schemaVersion = 'w12-proposal-0.1', n.name = 'Synthetic dietary supplement plant', n.facilityKind = 'MANUFACTURING_SITE', n.id = 'synthetic-supplement-plant', n.createdAt = datetime('2026-10-04T02:00:00Z'), n.updatedAt = datetime('2026-10-04T02:00:00Z');

// Products and variants (W04 identities; Basis uids equal elysium-basis.cypher)
MERGE (n:Entity:Product {uid: 'hu:product:tru-niagen'})
SET n.entityType = 'PRODUCT', n.privacyClass = 'PUBLIC', n.schemaVersion = 'w12-proposal-0.1', n.name = 'Tru Niagen', n.productKind = 'DIETARY_SUPPLEMENT', n.id = 'tru-niagen', n.createdAt = datetime('2026-10-04T02:00:00Z'), n.updatedAt = datetime('2026-10-04T02:00:00Z');

MERGE (n:Entity:ProductVariant {uid: 'hu:product-variant:tru-niagen-pro-500mg-us-capsule'})
SET n.entityType = 'PRODUCT_VARIANT', n.privacyClass = 'PUBLIC', n.schemaVersion = 'w12-proposal-0.1', n.name = 'TRU NIAGEN PRO 500mg capsules (US)', n.jurisdiction = 'US', n.dosageForm = 'CAPSULE', n.id = 'tru-niagen-pro-500mg-us-capsule', n.createdAt = datetime('2026-10-04T02:00:00Z'), n.updatedAt = datetime('2026-10-04T02:00:00Z');

MERGE (n:Entity:Product {uid: 'hu:product:elysium-basis'})
SET n.entityType = 'PRODUCT', n.privacyClass = 'PUBLIC', n.schemaVersion = 'w12-proposal-0.1', n.name = 'Basis', n.productKind = 'DIETARY_SUPPLEMENT', n.id = 'elysium-basis', n.createdAt = datetime('2026-10-04T02:00:00Z'), n.updatedAt = datetime('2026-10-04T02:00:00Z');

MERGE (n:Entity:ProductVariant {uid: 'hu:product-variant:basis-us-capsule-standard'})
SET n.entityType = 'PRODUCT_VARIANT', n.privacyClass = 'PUBLIC', n.schemaVersion = 'w12-proposal-0.1', n.name = 'Basis — US capsules', n.jurisdiction = 'US', n.dosageForm = 'CAPSULE', n.id = 'basis-us-capsule-standard', n.createdAt = datetime('2026-10-04T02:00:00Z'), n.updatedAt = datetime('2026-10-04T02:00:00Z');

MERGE (n:Entity:Source {uid: 'hu:source:truniagen-sample-coa-202511'})
SET n.entityType = 'SOURCE', n.canonicalUri = 'https://transparency.truniagen.com/assets/Sample-CoA-202511.pdf', n.title = 'Tru Niagen sample Certificate of Analysis (lot T25189001)', n.sourceKind = 'ORGANIZATION_WEBPAGE', n.publisherUid = 'hu:org:niagen-bioscience-inc', n.privacyClass = 'PUBLIC', n.createdAt = datetime('2026-10-04T02:00:00Z'), n.updatedAt = datetime('2026-10-04T02:00:00Z');

MERGE (n:Entity:Source {uid: 'hu:source:truniagen-transparency'})
SET n.entityType = 'SOURCE', n.canonicalUri = 'https://transparency.truniagen.com/', n.title = 'Tru Niagen transparency page', n.sourceKind = 'MARKETING_PAGE', n.publisherUid = 'hu:org:niagen-bioscience-inc', n.privacyClass = 'PUBLIC', n.createdAt = datetime('2026-10-04T02:00:00Z'), n.updatedAt = datetime('2026-10-04T02:00:00Z');

MERGE (n:Entity:Source {uid: 'hu:source:elysium-basis-lot-p098-01'})
SET n.entityType = 'SOURCE', n.canonicalUri = 'https://www.elysiumhealth.com/pages/basis-lot-info?lotNumber=P098-01', n.title = 'Basis Lot Info, lot P098-01', n.sourceKind = 'MANUFACTURER_LABEL_PAGE', n.publisherUid = 'hu:org:elysium-health-inc', n.privacyClass = 'PUBLIC', n.createdAt = datetime('2026-10-04T02:00:00Z'), n.updatedAt = datetime('2026-10-04T02:00:00Z');

MERGE (n:Entity:Source {uid: 'hu:source:nsf-info-listing-c0364723-306'})
SET n.entityType = 'SOURCE', n.canonicalUri = 'https://info.nsf.org/Certified/BannedSub/Listings.asp?Company=C0364723&Standard=306', n.title = 'NSF Product and Service Listings: Elysium Health, Certified for Sport', n.sourceKind = 'CERTIFICATION_LISTING', n.publisherUid = 'hu:org:nsf-international', n.privacyClass = 'PUBLIC', n.createdAt = datetime('2026-10-04T02:00:00Z'), n.updatedAt = datetime('2026-10-04T02:00:00Z');

MERGE (n:Entity:Source {uid: 'hu:source:nsfsport-listing-1786167'})
SET n.entityType = 'SOURCE', n.canonicalUri = 'https://www.nsfsport.com/certified-products/listing-detail.php?id=1786167', n.title = 'NSF Certified for Sport listing detail 1786167 (Basis)', n.sourceKind = 'CERTIFICATION_LISTING', n.publisherUid = 'hu:org:nsf-international', n.privacyClass = 'PUBLIC', n.createdAt = datetime('2026-10-04T02:00:00Z'), n.updatedAt = datetime('2026-10-04T02:00:00Z');

MERGE (n:Entity:Source {uid: 'hu:source:nsfsport-listing-1463170'})
SET n.entityType = 'SOURCE', n.canonicalUri = 'https://www.nsfsport.com/certified-products/listing-detail.php?id=1463170', n.title = 'NSF Certified for Sport listing detail 1463170 (Basis)', n.sourceKind = 'CERTIFICATION_LISTING', n.publisherUid = 'hu:org:nsf-international', n.privacyClass = 'PUBLIC', n.createdAt = datetime('2026-10-04T02:00:00Z'), n.updatedAt = datetime('2026-10-04T02:00:00Z');

MERGE (n:Entity:Source {uid: 'hu:source:chromadex-nr-surveillance-2025-06'})
SET n.entityType = 'SOURCE', n.canonicalUri = 'https://s205.q4cdn.com/770776702/files/doc_downloads/MarketSurveillance/2025/Quantitative-Analysis-of-Nicotinamide-Riboside-Consumer-Products-and-Counterfeit-Tru-Niagen-June-2025.pdf', n.title = 'Quantitative Analysis of Nicotinamide Riboside Consumer Products and Counterfeit Tru Niagen Products (June 2025)', n.sourceKind = 'ORGANIZATION_WEBPAGE', n.publisherUid = 'hu:org:niagen-bioscience-inc', n.privacyClass = 'PUBLIC', n.createdAt = datetime('2026-10-04T02:00:00Z'), n.updatedAt = datetime('2026-10-04T02:00:00Z');

MERGE (n:Entity:Source {uid: 'hu:source:synthetic-lab-z-coa-basis-p098-01'})
SET n.entityType = 'SOURCE', n.canonicalUri = 'urn:synthetic:w12:lab-z-coa-LZ-2026-0412', n.title = 'Synthetic Lab Z certificate LZ-2026-0412 (Basis lot P098-01)', n.sourceKind = 'ORGANIZATION_WEBPAGE', n.publisherUid = 'hu:org:synthetic-lab-z', n.privacyClass = 'PUBLIC', n.createdAt = datetime('2026-10-04T02:00:00Z'), n.updatedAt = datetime('2026-10-04T02:00:00Z');

MERGE (n:Entity:Source {uid: 'hu:source:synthetic-lab-z-coa-basis-70579'})
SET n.entityType = 'SOURCE', n.canonicalUri = 'urn:synthetic:w12:lab-z-coa-LZ-2026-0415', n.title = 'Synthetic Lab Z certificate LZ-2026-0415 (Basis lot 70579)', n.sourceKind = 'ORGANIZATION_WEBPAGE', n.publisherUid = 'hu:org:synthetic-lab-z', n.privacyClass = 'PUBLIC', n.createdAt = datetime('2026-10-04T02:00:00Z'), n.updatedAt = datetime('2026-10-04T02:00:00Z');

MERGE (n:Entity:Source {uid: 'hu:source:synthetic-lab-z-stability-basis-70064'})
SET n.entityType = 'SOURCE', n.canonicalUri = 'urn:synthetic:w12:lab-z-stability-LZ-STB-2026-07', n.title = 'Synthetic Lab Z stability report (Basis lot 70064, 18 months)', n.sourceKind = 'ORGANIZATION_WEBPAGE', n.publisherUid = 'hu:org:synthetic-lab-z', n.privacyClass = 'PUBLIC', n.createdAt = datetime('2026-10-04T02:00:00Z'), n.updatedAt = datetime('2026-10-04T02:00:00Z');

MERGE (n:Entity:Source {uid: 'hu:source:synthetic-nsf-455-2-listing'})
SET n.entityType = 'SOURCE', n.canonicalUri = 'urn:synthetic:w12:nsf-455-2-listing-synthetic-plant', n.title = 'Synthetic NSF/ANSI 455-2 GMP listing (synthetic plant)', n.sourceKind = 'CERTIFICATION_LISTING', n.publisherUid = 'hu:org:nsf-international', n.privacyClass = 'PUBLIC', n.createdAt = datetime('2026-10-04T02:00:00Z'), n.updatedAt = datetime('2026-10-04T02:00:00Z');

MERGE (n:Entity:Source {uid: 'hu:source:synthetic-17025-accreditation-lab-z'})
SET n.entityType = 'SOURCE', n.canonicalUri = 'urn:synthetic:w12:iso17025-accreditation-lab-z', n.title = 'Synthetic ISO/IEC 17025 accreditation certificate (Lab Z)', n.sourceKind = 'CERTIFICATION_LISTING', n.publisherUid = 'hu:org:synthetic-accreditation-body', n.privacyClass = 'PUBLIC', n.createdAt = datetime('2026-10-04T02:00:00Z'), n.updatedAt = datetime('2026-10-04T02:00:00Z');

MERGE (n:Entity:Source {uid: 'hu:source:synthetic-nsfsport-listing-1786167-later'})
SET n.entityType = 'SOURCE', n.canonicalUri = 'urn:synthetic:w12:nsfsport-1786167-later-capture', n.title = 'Synthetic later capture of NSF listing 1786167', n.sourceKind = 'CERTIFICATION_LISTING', n.publisherUid = 'hu:org:nsf-international', n.privacyClass = 'PUBLIC', n.createdAt = datetime('2026-10-04T02:00:00Z'), n.updatedAt = datetime('2026-10-04T02:00:00Z');

// Snapshots of real sources: hash over the stored excerpt file (STORED_EXCERPT_TEXT)
MERGE (n:InformationArtifact:SourceSnapshot {uid: 'hu:snapshot:truniagen-sample-coa-202511-2026-10-04'})
SET n.artifactType = 'SOURCE_SNAPSHOT', n.canonicalUri = 'https://transparency.truniagen.com/assets/Sample-CoA-202511.pdf', n.retrievedAt = datetime('2026-10-04T01:01:00Z'), n.observedAt = datetime('2026-10-04T01:01:00Z'), n.publishedAt = datetime('2025-09-03T00:00:00Z'), n.publishedAtPrecision = 'DAY', n.contentHash = 'sha256:0e42af23ba6bebe16dc75e9a32bf6f1cd5d4d85a65f0d2537544b7dd2aeb518b', n.contentHashBasis = 'STORED_EXCERPT_TEXT', n.captureCompleteness = 'COMPLETE', n.storageUri = 'docs/schema/ontology-lab/final-proposal-team/run-2026-10-04-fable51-01/workers/W12/fixtures/excerpts/truniagen-sample-coa-T25189001-2026-10-04.txt', n.privacyClass = 'PUBLIC', n.createdAt = datetime('2026-10-04T02:00:00Z'), n.updatedAt = datetime('2026-10-04T02:00:00Z');

MATCH (s:Source {uid: 'hu:source:truniagen-sample-coa-202511'}), (sn:SourceSnapshot {uid: 'hu:snapshot:truniagen-sample-coa-202511-2026-10-04'})
MERGE (s)-[:HAS_SNAPSHOT]->(sn);

MERGE (n:InformationArtifact:SourceSnapshot {uid: 'hu:snapshot:truniagen-transparency-2026-10-04'})
SET n.artifactType = 'SOURCE_SNAPSHOT', n.canonicalUri = 'https://transparency.truniagen.com/', n.retrievedAt = datetime('2026-10-04T01:00:00Z'), n.observedAt = datetime('2026-10-04T01:00:00Z'), n.contentHash = 'sha256:696852a77c0198de223b2114065a7320ed4e0a2146598a2e59a24181eb1f4d41', n.contentHashBasis = 'SYNTHETIC_FIXTURE', n.captureCompleteness = 'UNKNOWN', n.privacyClass = 'PUBLIC', n.createdAt = datetime('2026-10-04T02:00:00Z'), n.updatedAt = datetime('2026-10-04T02:00:00Z');

MATCH (s:Source {uid: 'hu:source:truniagen-transparency'}), (sn:SourceSnapshot {uid: 'hu:snapshot:truniagen-transparency-2026-10-04'})
MERGE (s)-[:HAS_SNAPSHOT]->(sn);

MERGE (n:InformationArtifact:SourceSnapshot {uid: 'hu:snapshot:elysium-basis-lot-p098-01-2026-10-04'})
SET n.artifactType = 'SOURCE_SNAPSHOT', n.canonicalUri = 'https://www.elysiumhealth.com/pages/basis-lot-info?lotNumber=P098-01', n.retrievedAt = datetime('2026-10-04T00:58:00Z'), n.observedAt = datetime('2026-10-04T00:58:00Z'), n.contentHash = 'sha256:75845543c817d81d68eb7773f14c95934542d8d5ce4adae4ccfddb7eac6f17e3', n.contentHashBasis = 'STORED_EXCERPT_TEXT', n.captureCompleteness = 'PARTIAL_EXCERPT', n.storageUri = 'docs/schema/ontology-lab/final-proposal-team/run-2026-10-04-fable51-01/workers/W12/fixtures/excerpts/elysium-basis-lot-P098-01-2026-10-04.txt', n.privacyClass = 'PUBLIC', n.createdAt = datetime('2026-10-04T02:00:00Z'), n.updatedAt = datetime('2026-10-04T02:00:00Z');

MATCH (s:Source {uid: 'hu:source:elysium-basis-lot-p098-01'}), (sn:SourceSnapshot {uid: 'hu:snapshot:elysium-basis-lot-p098-01-2026-10-04'})
MERGE (s)-[:HAS_SNAPSHOT]->(sn);

MERGE (n:InformationArtifact:SourceSnapshot {uid: 'hu:snapshot:nsf-info-listing-c0364723-306-2026-10-04'})
SET n.artifactType = 'SOURCE_SNAPSHOT', n.canonicalUri = 'https://info.nsf.org/Certified/BannedSub/Listings.asp?Company=C0364723&Standard=306', n.retrievedAt = datetime('2026-10-04T00:58:00Z'), n.observedAt = datetime('2026-10-04T00:58:00Z'), n.publishedAt = datetime('2026-10-03T04:15:00Z'), n.publishedAtPrecision = 'INSTANT', n.contentHash = 'sha256:13b615500991c121a0287c86291ef47b64f3081ac03c055a0e8967702a210edb', n.contentHashBasis = 'STORED_EXCERPT_TEXT', n.captureCompleteness = 'PARTIAL_EXCERPT', n.storageUri = 'docs/schema/ontology-lab/final-proposal-team/run-2026-10-04-fable51-01/workers/W12/fixtures/excerpts/nsf-info-listing-C0364723-306-2026-10-04.txt', n.privacyClass = 'PUBLIC', n.createdAt = datetime('2026-10-04T02:00:00Z'), n.updatedAt = datetime('2026-10-04T02:00:00Z');

MATCH (s:Source {uid: 'hu:source:nsf-info-listing-c0364723-306'}), (sn:SourceSnapshot {uid: 'hu:snapshot:nsf-info-listing-c0364723-306-2026-10-04'})
MERGE (s)-[:HAS_SNAPSHOT]->(sn);

MERGE (n:InformationArtifact:SourceSnapshot {uid: 'hu:snapshot:nsfsport-listing-1786167-2026-10-04'})
SET n.artifactType = 'SOURCE_SNAPSHOT', n.canonicalUri = 'https://www.nsfsport.com/certified-products/listing-detail.php?id=1786167', n.retrievedAt = datetime('2026-10-04T01:04:00Z'), n.observedAt = datetime('2026-10-04T01:04:00Z'), n.contentHash = 'sha256:ce56455817b6ef41181ad25b3de0cc8e1cd9c3b5d400526a12e0a394c3cab6ec', n.contentHashBasis = 'STORED_EXCERPT_TEXT', n.captureCompleteness = 'COMPLETE', n.storageUri = 'docs/schema/ontology-lab/final-proposal-team/run-2026-10-04-fable51-01/workers/W12/fixtures/excerpts/nsfsport-listing-1786167-2026-10-04.txt', n.privacyClass = 'PUBLIC', n.createdAt = datetime('2026-10-04T02:00:00Z'), n.updatedAt = datetime('2026-10-04T02:00:00Z');

MATCH (s:Source {uid: 'hu:source:nsfsport-listing-1786167'}), (sn:SourceSnapshot {uid: 'hu:snapshot:nsfsport-listing-1786167-2026-10-04'})
MERGE (s)-[:HAS_SNAPSHOT]->(sn);

MERGE (n:InformationArtifact:SourceSnapshot {uid: 'hu:snapshot:nsfsport-listing-1463170-2026-10-04'})
SET n.artifactType = 'SOURCE_SNAPSHOT', n.canonicalUri = 'https://www.nsfsport.com/certified-products/listing-detail.php?id=1463170', n.retrievedAt = datetime('2026-10-04T01:10:00Z'), n.observedAt = datetime('2026-10-04T01:10:00Z'), n.contentHash = 'sha256:e343cebd8adfe45874e15d6e8a00c96d1ce7fa6e69dd0e37146745ca62a09b88', n.contentHashBasis = 'STORED_EXCERPT_TEXT', n.captureCompleteness = 'PARTIAL_EXCERPT', n.storageUri = 'docs/schema/ontology-lab/final-proposal-team/run-2026-10-04-fable51-01/workers/W12/fixtures/excerpts/nsfsport-listing-1463170-2026-10-04.txt', n.privacyClass = 'PUBLIC', n.createdAt = datetime('2026-10-04T02:00:00Z'), n.updatedAt = datetime('2026-10-04T02:00:00Z');

MATCH (s:Source {uid: 'hu:source:nsfsport-listing-1463170'}), (sn:SourceSnapshot {uid: 'hu:snapshot:nsfsport-listing-1463170-2026-10-04'})
MERGE (s)-[:HAS_SNAPSHOT]->(sn);

MERGE (n:InformationArtifact:SourceSnapshot {uid: 'hu:snapshot:chromadex-nr-surveillance-2025-06-2026-10-04'})
SET n.artifactType = 'SOURCE_SNAPSHOT', n.canonicalUri = 'https://s205.q4cdn.com/770776702/files/doc_downloads/MarketSurveillance/2025/Quantitative-Analysis-of-Nicotinamide-Riboside-Consumer-Products-and-Counterfeit-Tru-Niagen-June-2025.pdf', n.retrievedAt = datetime('2026-10-04T01:00:00Z'), n.observedAt = datetime('2026-10-04T01:00:00Z'), n.publishedAt = datetime('2025-06-01T00:00:00Z'), n.publishedAtPrecision = 'MONTH', n.contentHash = 'sha256:b53c43ebac936a34ca2370303cafafa081db6a624bf3079b973f0bd1bb4a924e', n.contentHashBasis = 'STORED_EXCERPT_TEXT', n.captureCompleteness = 'PARTIAL_EXCERPT', n.storageUri = 'docs/schema/ontology-lab/final-proposal-team/run-2026-10-04-fable51-01/workers/W12/fixtures/excerpts/chromadex-nr-market-surveillance-2025-06.txt', n.privacyClass = 'PUBLIC', n.createdAt = datetime('2026-10-04T02:00:00Z'), n.updatedAt = datetime('2026-10-04T02:00:00Z');

MATCH (s:Source {uid: 'hu:source:chromadex-nr-surveillance-2025-06'}), (sn:SourceSnapshot {uid: 'hu:snapshot:chromadex-nr-surveillance-2025-06-2026-10-04'})
MERGE (s)-[:HAS_SNAPSHOT]->(sn);

// Synthetic snapshots (SYNTHETIC_FIXTURE); rev01 arrives later (temporal correction case)
MERGE (n:InformationArtifact:SourceSnapshot {uid: 'hu:snapshot:synthetic-lab-z-coa-basis-p098-01-rev00'})
SET n.artifactType = 'SOURCE_SNAPSHOT', n.canonicalUri = 'urn:synthetic:w12:lab-z-coa-LZ-2026-0412', n.retrievedAt = datetime('2026-10-04T01:30:00Z'), n.observedAt = datetime('2026-10-04T01:30:00Z'), n.contentHash = 'sha256:b0b3a68fdaf061008f7b8a407c233a66a0a893e37ee81569966a50eb9b0a385b', n.contentHashBasis = 'SYNTHETIC_FIXTURE', n.captureCompleteness = 'UNKNOWN', n.privacyClass = 'PUBLIC', n.createdAt = datetime('2026-10-04T02:00:00Z'), n.updatedAt = datetime('2026-10-04T02:00:00Z');

MATCH (s:Source {uid: 'hu:source:synthetic-lab-z-coa-basis-p098-01'}), (sn:SourceSnapshot {uid: 'hu:snapshot:synthetic-lab-z-coa-basis-p098-01-rev00'})
MERGE (s)-[:HAS_SNAPSHOT]->(sn);

MERGE (n:InformationArtifact:SourceSnapshot {uid: 'hu:snapshot:synthetic-lab-z-coa-basis-p098-01-rev01'})
SET n.artifactType = 'SOURCE_SNAPSHOT', n.canonicalUri = 'urn:synthetic:w12:lab-z-coa-LZ-2026-0412', n.retrievedAt = datetime('2026-10-04T02:45:00Z'), n.observedAt = datetime('2026-10-04T02:45:00Z'), n.contentHash = 'sha256:268136cea2e87caa95770cdc98ead48314090c6aecec20156d5bc1106520a6b8', n.contentHashBasis = 'SYNTHETIC_FIXTURE', n.captureCompleteness = 'UNKNOWN', n.privacyClass = 'PUBLIC', n.createdAt = datetime('2026-10-04T02:00:00Z'), n.updatedAt = datetime('2026-10-04T02:00:00Z');

MATCH (s:Source {uid: 'hu:source:synthetic-lab-z-coa-basis-p098-01'}), (sn:SourceSnapshot {uid: 'hu:snapshot:synthetic-lab-z-coa-basis-p098-01-rev01'})
MERGE (s)-[:HAS_SNAPSHOT]->(sn);

MERGE (n:InformationArtifact:SourceSnapshot {uid: 'hu:snapshot:synthetic-lab-z-coa-basis-70579'})
SET n.artifactType = 'SOURCE_SNAPSHOT', n.canonicalUri = 'urn:synthetic:w12:lab-z-coa-LZ-2026-0415', n.retrievedAt = datetime('2026-10-04T01:30:00Z'), n.observedAt = datetime('2026-10-04T01:30:00Z'), n.contentHash = 'sha256:cf3d37c1a01b6ff49ec37b8ee5fa1ece775bfc14232b71dffbd475464e0bcd93', n.contentHashBasis = 'SYNTHETIC_FIXTURE', n.captureCompleteness = 'UNKNOWN', n.privacyClass = 'PUBLIC', n.createdAt = datetime('2026-10-04T02:00:00Z'), n.updatedAt = datetime('2026-10-04T02:00:00Z');

MATCH (s:Source {uid: 'hu:source:synthetic-lab-z-coa-basis-70579'}), (sn:SourceSnapshot {uid: 'hu:snapshot:synthetic-lab-z-coa-basis-70579'})
MERGE (s)-[:HAS_SNAPSHOT]->(sn);

MERGE (n:InformationArtifact:SourceSnapshot {uid: 'hu:snapshot:synthetic-lab-z-stability-basis-70064'})
SET n.artifactType = 'SOURCE_SNAPSHOT', n.canonicalUri = 'urn:synthetic:w12:lab-z-stability-LZ-STB-2026-07', n.retrievedAt = datetime('2026-10-04T01:30:00Z'), n.observedAt = datetime('2026-10-04T01:30:00Z'), n.contentHash = 'sha256:ce728c161dd4103786455f583d41b9d7f76a12a39662d2cd45e98dab4ab8e90e', n.contentHashBasis = 'SYNTHETIC_FIXTURE', n.captureCompleteness = 'UNKNOWN', n.privacyClass = 'PUBLIC', n.createdAt = datetime('2026-10-04T02:00:00Z'), n.updatedAt = datetime('2026-10-04T02:00:00Z');

MATCH (s:Source {uid: 'hu:source:synthetic-lab-z-stability-basis-70064'}), (sn:SourceSnapshot {uid: 'hu:snapshot:synthetic-lab-z-stability-basis-70064'})
MERGE (s)-[:HAS_SNAPSHOT]->(sn);

MERGE (n:InformationArtifact:SourceSnapshot {uid: 'hu:snapshot:synthetic-nsf-455-2-listing'})
SET n.artifactType = 'SOURCE_SNAPSHOT', n.canonicalUri = 'urn:synthetic:w12:nsf-455-2-listing-synthetic-plant', n.retrievedAt = datetime('2026-10-04T01:30:00Z'), n.observedAt = datetime('2026-10-04T01:30:00Z'), n.contentHash = 'sha256:bc40b418457cfe8cae838c717a5b382b3e7b9111557ccf8a261d920738b6eb16', n.contentHashBasis = 'SYNTHETIC_FIXTURE', n.captureCompleteness = 'UNKNOWN', n.privacyClass = 'PUBLIC', n.createdAt = datetime('2026-10-04T02:00:00Z'), n.updatedAt = datetime('2026-10-04T02:00:00Z');

MATCH (s:Source {uid: 'hu:source:synthetic-nsf-455-2-listing'}), (sn:SourceSnapshot {uid: 'hu:snapshot:synthetic-nsf-455-2-listing'})
MERGE (s)-[:HAS_SNAPSHOT]->(sn);

MERGE (n:InformationArtifact:SourceSnapshot {uid: 'hu:snapshot:synthetic-17025-accreditation-lab-z'})
SET n.artifactType = 'SOURCE_SNAPSHOT', n.canonicalUri = 'urn:synthetic:w12:iso17025-accreditation-lab-z', n.retrievedAt = datetime('2026-10-04T01:30:00Z'), n.observedAt = datetime('2026-10-04T01:30:00Z'), n.contentHash = 'sha256:0b3c43fc47ac2a94e1b333d290abb316bed3958106e01b5b0cbc52e973d43c6c', n.contentHashBasis = 'SYNTHETIC_FIXTURE', n.captureCompleteness = 'UNKNOWN', n.privacyClass = 'PUBLIC', n.createdAt = datetime('2026-10-04T02:00:00Z'), n.updatedAt = datetime('2026-10-04T02:00:00Z');

MATCH (s:Source {uid: 'hu:source:synthetic-17025-accreditation-lab-z'}), (sn:SourceSnapshot {uid: 'hu:snapshot:synthetic-17025-accreditation-lab-z'})
MERGE (s)-[:HAS_SNAPSHOT]->(sn);

MERGE (n:InformationArtifact:SourceSnapshot {uid: 'hu:snapshot:synthetic-nsfsport-listing-1786167-later'})
SET n.artifactType = 'SOURCE_SNAPSHOT', n.canonicalUri = 'urn:synthetic:w12:nsfsport-1786167-later-capture', n.retrievedAt = datetime('2026-10-04T02:50:00Z'), n.observedAt = datetime('2026-10-04T02:50:00Z'), n.contentHash = 'sha256:237324497b2819f6bd8f048a00f4305e035bd2720927b27b40a3b41da44d1aba', n.contentHashBasis = 'SYNTHETIC_FIXTURE', n.captureCompleteness = 'UNKNOWN', n.privacyClass = 'PUBLIC', n.createdAt = datetime('2026-10-04T02:00:00Z'), n.updatedAt = datetime('2026-10-04T02:00:00Z');

MATCH (s:Source {uid: 'hu:source:synthetic-nsfsport-listing-1786167-later'}), (sn:SourceSnapshot {uid: 'hu:snapshot:synthetic-nsfsport-listing-1786167-later'})
MERGE (s)-[:HAS_SNAPSHOT]->(sn);

MERGE (n:InformationArtifact:SourceLocator {uid: 'hu:locator:truniagen-coa-t25189001-potency'})
SET n.artifactType = 'SOURCE_LOCATOR', n.uri = 'https://transparency.truniagen.com/assets/Sample-CoA-202511.pdf', n.selectorKind = 'PDF_PAGE', n.privacyClass = 'PUBLIC', n.exact = '| Potency | HPLC | Nicotinamide Riboside Chloride | NLT 500 mg/capsule | ☑ 555 mg/capsule |', n.quoteHash = 'sha256:0d0b3b8dde6da04fd0554f578d00ff351a9fc6929347a1a83a6c7e98ec1865a6', n.normalizationVersion = 'NFC-WS1', n.page = 1, n.createdAt = datetime('2026-10-04T02:00:00Z'), n.updatedAt = datetime('2026-10-04T02:00:00Z');

MATCH (sn:SourceSnapshot {uid: 'hu:snapshot:truniagen-sample-coa-202511-2026-10-04'}), (l:SourceLocator {uid: 'hu:locator:truniagen-coa-t25189001-potency'})
MERGE (sn)-[:HAS_LOCATOR]->(l);

MERGE (n:InformationArtifact:SourceLocator {uid: 'hu:locator:truniagen-coa-t25189001-lead'})
SET n.artifactType = 'SOURCE_LOCATOR', n.uri = 'https://transparency.truniagen.com/assets/Sample-CoA-202511.pdf', n.selectorKind = 'PDF_PAGE', n.privacyClass = 'PUBLIC', n.exact = '| Heavy Metals* | ICP-MS | Lead | NMT 0.5 ppm | ☑ Pass |', n.quoteHash = 'sha256:ac1c43a69776c0f15db4fd22725c8ffa138addfaae6ab7c2878018dc20c85dbb', n.normalizationVersion = 'NFC-WS1', n.page = 1, n.createdAt = datetime('2026-10-04T02:00:00Z'), n.updatedAt = datetime('2026-10-04T02:00:00Z');

MATCH (sn:SourceSnapshot {uid: 'hu:snapshot:truniagen-sample-coa-202511-2026-10-04'}), (l:SourceLocator {uid: 'hu:locator:truniagen-coa-t25189001-lead'})
MERGE (sn)-[:HAS_LOCATOR]->(l);

MERGE (n:InformationArtifact:SourceLocator {uid: 'hu:locator:truniagen-coa-t25189001-ecoli'})
SET n.artifactType = 'SOURCE_LOCATOR', n.uri = 'https://transparency.truniagen.com/assets/Sample-CoA-202511.pdf', n.selectorKind = 'PDF_PAGE', n.privacyClass = 'PUBLIC', n.exact = '| Microbial* | USP 2022 | E. coli | Absent/10g | ☑ Pass |', n.quoteHash = 'sha256:fce66daea43ff0f7c82f54aac2217512088f65176b5940145935dbac994c1b42', n.normalizationVersion = 'NFC-WS1', n.page = 1, n.createdAt = datetime('2026-10-04T02:00:00Z'), n.updatedAt = datetime('2026-10-04T02:00:00Z');

MATCH (sn:SourceSnapshot {uid: 'hu:snapshot:truniagen-sample-coa-202511-2026-10-04'}), (l:SourceLocator {uid: 'hu:locator:truniagen-coa-t25189001-ecoli'})
MERGE (sn)-[:HAS_LOCATOR]->(l);

MERGE (n:InformationArtifact:SourceLocator {uid: 'hu:locator:truniagen-coa-t25189001-nsf306'})
SET n.artifactType = 'SOURCE_LOCATOR', n.uri = 'https://transparency.truniagen.com/assets/Sample-CoA-202511.pdf', n.selectorKind = 'PDF_PAGE', n.privacyClass = 'PUBLIC', n.exact = '| Certified for Sport at NSF International† | NSF 306 | Banned Substances Panel | Pass | ☑ Pass |', n.quoteHash = 'sha256:2f664e0979f5262fd01850e58b38cbc6ec67cfc1c12b9e6f86bc3eace9c3fa6c', n.normalizationVersion = 'NFC-WS1', n.page = 1, n.createdAt = datetime('2026-10-04T02:00:00Z'), n.updatedAt = datetime('2026-10-04T02:00:00Z');

MATCH (sn:SourceSnapshot {uid: 'hu:snapshot:truniagen-sample-coa-202511-2026-10-04'}), (l:SourceLocator {uid: 'hu:locator:truniagen-coa-t25189001-nsf306'})
MERGE (sn)-[:HAS_LOCATOR]->(l);

MERGE (n:InformationArtifact:SourceLocator {uid: 'hu:locator:truniagen-coa-t25189001-header'})
SET n.artifactType = 'SOURCE_LOCATOR', n.uri = 'https://transparency.truniagen.com/assets/Sample-CoA-202511.pdf', n.selectorKind = 'PDF_PAGE', n.privacyClass = 'PUBLIC', n.exact = '| LOT NUMBER | T25189001 | | REPORT NUMBER | CDXA-RSS-11207-00 | | DATE OF MANUFACTURE | 08Jul2025 |', n.quoteHash = 'sha256:737cc8d2a35004fd73339506d77b3e133ff8507463216f8a74fe39dc3944f88a', n.normalizationVersion = 'NFC-WS1', n.page = 1, n.createdAt = datetime('2026-10-04T02:00:00Z'), n.updatedAt = datetime('2026-10-04T02:00:00Z');

MATCH (sn:SourceSnapshot {uid: 'hu:snapshot:truniagen-sample-coa-202511-2026-10-04'}), (l:SourceLocator {uid: 'hu:locator:truniagen-coa-t25189001-header'})
MERGE (sn)-[:HAS_LOCATOR]->(l);

MERGE (n:InformationArtifact:SourceLocator {uid: 'hu:locator:truniagen-coa-t25189001-product'})
SET n.artifactType = 'SOURCE_LOCATOR', n.uri = 'https://transparency.truniagen.com/assets/Sample-CoA-202511.pdf', n.selectorKind = 'PDF_PAGE', n.privacyClass = 'PUBLIC', n.exact = '| PRODUCT NAME | TRU NIAGEN® PRO 500mg 30ct |', n.quoteHash = 'sha256:7c7077b97b74ed895d42924019a26ff90a54df5a3abee902487959f6a38dc2b6', n.normalizationVersion = 'NFC-WS1', n.page = 1, n.createdAt = datetime('2026-10-04T02:00:00Z'), n.updatedAt = datetime('2026-10-04T02:00:00Z');

MATCH (sn:SourceSnapshot {uid: 'hu:snapshot:truniagen-sample-coa-202511-2026-10-04'}), (l:SourceLocator {uid: 'hu:locator:truniagen-coa-t25189001-product'})
MERGE (sn)-[:HAS_LOCATOR]->(l);

MERGE (n:InformationArtifact:SourceLocator {uid: 'hu:locator:truniagen-coa-t25189001-subcontract'})
SET n.artifactType = 'SOURCE_LOCATOR', n.uri = 'https://transparency.truniagen.com/assets/Sample-CoA-202511.pdf', n.selectorKind = 'PDF_PAGE', n.privacyClass = 'PUBLIC', n.exact = '*Testing performed at ISO 17025 accredited subcontracted laboratories.', n.quoteHash = 'sha256:832e432ae6dc36f22e1e91d936b9c36c690d9587daf496add6ae0ca754486ae7', n.normalizationVersion = 'NFC-WS1', n.page = 1, n.createdAt = datetime('2026-10-04T02:00:00Z'), n.updatedAt = datetime('2026-10-04T02:00:00Z');

MATCH (sn:SourceSnapshot {uid: 'hu:snapshot:truniagen-sample-coa-202511-2026-10-04'}), (l:SourceLocator {uid: 'hu:locator:truniagen-coa-t25189001-subcontract'})
MERGE (sn)-[:HAS_LOCATOR]->(l);

MERGE (n:InformationArtifact:SourceLocator {uid: 'hu:locator:truniagen-coa-t25189001-scope'})
SET n.artifactType = 'SOURCE_LOCATOR', n.uri = 'https://transparency.truniagen.com/assets/Sample-CoA-202511.pdf', n.selectorKind = 'PDF_PAGE', n.privacyClass = 'PUBLIC', n.exact = '†Test not in the scope of accreditation to ISO/IEC 17025:2017', n.quoteHash = 'sha256:49cf9d4ff75b309867ad3c1ddb1dca4fdc16b2a3b8f6843f34da0cf58e73a4d0', n.normalizationVersion = 'NFC-WS1', n.page = 1, n.createdAt = datetime('2026-10-04T02:00:00Z'), n.updatedAt = datetime('2026-10-04T02:00:00Z');

MATCH (sn:SourceSnapshot {uid: 'hu:snapshot:truniagen-sample-coa-202511-2026-10-04'}), (l:SourceLocator {uid: 'hu:locator:truniagen-coa-t25189001-scope'})
MERGE (sn)-[:HAS_LOCATOR]->(l);

MERGE (n:InformationArtifact:SourceLocator {uid: 'hu:locator:truniagen-coa-t25189001-expiry'})
SET n.artifactType = 'SOURCE_LOCATOR', n.uri = 'https://transparency.truniagen.com/assets/Sample-CoA-202511.pdf', n.selectorKind = 'PDF_PAGE', n.privacyClass = 'PUBLIC', n.exact = 'EXPIRATION DATE 07/2028 under the above conditions.', n.quoteHash = 'sha256:24c8ba43f965ee58bb945c176c137c17a8766fc7e7bab4d8b435626a030abbb8', n.normalizationVersion = 'NFC-WS1', n.page = 1, n.createdAt = datetime('2026-10-04T02:00:00Z'), n.updatedAt = datetime('2026-10-04T02:00:00Z');

MATCH (sn:SourceSnapshot {uid: 'hu:snapshot:truniagen-sample-coa-202511-2026-10-04'}), (l:SourceLocator {uid: 'hu:locator:truniagen-coa-t25189001-expiry'})
MERGE (sn)-[:HAS_LOCATOR]->(l);

MERGE (n:InformationArtifact:SourceLocator {uid: 'hu:locator:truniagen-coa-t25189001-affiliate'})
SET n.artifactType = 'SOURCE_LOCATOR', n.uri = 'https://transparency.truniagen.com/assets/Sample-CoA-202511.pdf', n.selectorKind = 'PDF_PAGE', n.privacyClass = 'PUBLIC', n.exact = 'ChromaDex Analytics, Inc. is an affiliate of Niagen Bioscience, Inc.', n.quoteHash = 'sha256:c2084d5ba26807b6b24bfb39b2f9445b037441a4d1b679878bfd3c8a9acc5254', n.normalizationVersion = 'NFC-WS1', n.page = 2, n.createdAt = datetime('2026-10-04T02:00:00Z'), n.updatedAt = datetime('2026-10-04T02:00:00Z');

MATCH (sn:SourceSnapshot {uid: 'hu:snapshot:truniagen-sample-coa-202511-2026-10-04'}), (l:SourceLocator {uid: 'hu:locator:truniagen-coa-t25189001-affiliate'})
MERGE (sn)-[:HAS_LOCATOR]->(l);

MERGE (n:InformationArtifact:SourceLocator {uid: 'hu:locator:truniagen-transparency-cgmp'})
SET n.artifactType = 'SOURCE_LOCATOR', n.uri = 'https://transparency.truniagen.com/', n.selectorKind = 'SECTION', n.privacyClass = 'PUBLIC', n.section = 'Quality: This product meet or exceeds the standards and expectations of the cGMP guidelines.', n.createdAt = datetime('2026-10-04T02:00:00Z'), n.updatedAt = datetime('2026-10-04T02:00:00Z');

MATCH (sn:SourceSnapshot {uid: 'hu:snapshot:truniagen-transparency-2026-10-04'}), (l:SourceLocator {uid: 'hu:locator:truniagen-transparency-cgmp'})
MERGE (sn)-[:HAS_LOCATOR]->(l);

MERGE (n:InformationArtifact:SourceLocator {uid: 'hu:locator:elysium-basis-lot-p098-01-header'})
SET n.artifactType = 'SOURCE_LOCATOR', n.uri = 'https://www.elysiumhealth.com/pages/basis-lot-info?lotNumber=P098-01', n.selectorKind = 'TEXT_QUOTE', n.privacyClass = 'PUBLIC', n.exact = 'Lot #P098-01 - Expiration date 12/2027', n.quoteHash = 'sha256:27b7987f5e5d41f331822786cd5da5c6492c7578b686b64e21908a2e32faa999', n.normalizationVersion = 'NFC-WS1', n.createdAt = datetime('2026-10-04T02:00:00Z'), n.updatedAt = datetime('2026-10-04T02:00:00Z');

MATCH (sn:SourceSnapshot {uid: 'hu:snapshot:elysium-basis-lot-p098-01-2026-10-04'}), (l:SourceLocator {uid: 'hu:locator:elysium-basis-lot-p098-01-header'})
MERGE (sn)-[:HAS_LOCATOR]->(l);

MERGE (n:InformationArtifact:SourceLocator {uid: 'hu:locator:elysium-basis-lot-p098-01-nr'})
SET n.artifactType = 'SOURCE_LOCATOR', n.uri = 'https://www.elysiumhealth.com/pages/basis-lot-info?lotNumber=P098-01', n.selectorKind = 'TEXT_QUOTE', n.privacyClass = 'PUBLIC', n.exact = 'Nicotinamide Riboside Chloride (NR) | Internal Specifications ≥ 250 mg/dose | Results* Conforms to internal specs', n.quoteHash = 'sha256:9802422c74ce41c8b6fb7e987ab5fcac5153af782726edeb6d4bd277c163d8e3', n.normalizationVersion = 'NFC-WS1', n.createdAt = datetime('2026-10-04T02:00:00Z'), n.updatedAt = datetime('2026-10-04T02:00:00Z');

MATCH (sn:SourceSnapshot {uid: 'hu:snapshot:elysium-basis-lot-p098-01-2026-10-04'}), (l:SourceLocator {uid: 'hu:locator:elysium-basis-lot-p098-01-nr'})
MERGE (sn)-[:HAS_LOCATOR]->(l);

MERGE (n:InformationArtifact:SourceLocator {uid: 'hu:locator:elysium-basis-lot-p098-01-heavy-metals'})
SET n.artifactType = 'SOURCE_LOCATOR', n.uri = 'https://www.elysiumhealth.com/pages/basis-lot-info?lotNumber=P098-01', n.selectorKind = 'TEXT_QUOTE', n.privacyClass = 'PUBLIC', n.exact = 'Heavy Metals | Internal Specifications ≤ 0.5 ppm | Results* Conforms to internal specs', n.quoteHash = 'sha256:317fbbc0937ad01e7695b7bc606b300b3b0b40a3d24f2ceb825661c9dab83ab0', n.normalizationVersion = 'NFC-WS1', n.createdAt = datetime('2026-10-04T02:00:00Z'), n.updatedAt = datetime('2026-10-04T02:00:00Z');

MATCH (sn:SourceSnapshot {uid: 'hu:snapshot:elysium-basis-lot-p098-01-2026-10-04'}), (l:SourceLocator {uid: 'hu:locator:elysium-basis-lot-p098-01-heavy-metals'})
MERGE (sn)-[:HAS_LOCATOR]->(l);

MERGE (n:InformationArtifact:SourceLocator {uid: 'hu:locator:elysium-basis-lot-p098-01-solvents'})
SET n.artifactType = 'SOURCE_LOCATOR', n.uri = 'https://www.elysiumhealth.com/pages/basis-lot-info?lotNumber=P098-01', n.selectorKind = 'TEXT_QUOTE', n.privacyClass = 'PUBLIC', n.exact = 'Residual Solvents | Internal Specifications ICH/USP guidelines | Results* Conforms to internal specs', n.quoteHash = 'sha256:2e3246c1fdf7bf0c2f1524d4cba71bded3497430d2f2deba041abb4e1abd237d', n.normalizationVersion = 'NFC-WS1', n.createdAt = datetime('2026-10-04T02:00:00Z'), n.updatedAt = datetime('2026-10-04T02:00:00Z');

MATCH (sn:SourceSnapshot {uid: 'hu:snapshot:elysium-basis-lot-p098-01-2026-10-04'}), (l:SourceLocator {uid: 'hu:locator:elysium-basis-lot-p098-01-solvents'})
MERGE (sn)-[:HAS_LOCATOR]->(l);

MERGE (n:InformationArtifact:SourceLocator {uid: 'hu:locator:elysium-basis-lot-p098-01-objectionable'})
SET n.artifactType = 'SOURCE_LOCATOR', n.uri = 'https://www.elysiumhealth.com/pages/basis-lot-info?lotNumber=P098-01', n.selectorKind = 'TEXT_QUOTE', n.privacyClass = 'PUBLIC', n.exact = 'Objectionable USP Organisms MICRO | Internal Specifications Absent | Results* Conforms to internal specs', n.quoteHash = 'sha256:e07033f3370d635aad38ec3b794018ed5c660209e0ee5326bbf6b41db90f32f9', n.normalizationVersion = 'NFC-WS1', n.createdAt = datetime('2026-10-04T02:00:00Z'), n.updatedAt = datetime('2026-10-04T02:00:00Z');

MATCH (sn:SourceSnapshot {uid: 'hu:snapshot:elysium-basis-lot-p098-01-2026-10-04'}), (l:SourceLocator {uid: 'hu:locator:elysium-basis-lot-p098-01-objectionable'})
MERGE (sn)-[:HAS_LOCATOR]->(l);

MERGE (n:InformationArtifact:SourceLocator {uid: 'hu:locator:elysium-basis-lot-p098-01-attribution'})
SET n.artifactType = 'SOURCE_LOCATOR', n.uri = 'https://www.elysiumhealth.com/pages/basis-lot-info?lotNumber=P098-01', n.selectorKind = 'TEXT_QUOTE', n.privacyClass = 'PUBLIC', n.exact = '*As confirmed by a third-party testing lab.', n.quoteHash = 'sha256:8852dddd250e0cc3812ef5e53f80e5f154a3f595d6e3b24a7ba713fe0b994d9d', n.normalizationVersion = 'NFC-WS1', n.createdAt = datetime('2026-10-04T02:00:00Z'), n.updatedAt = datetime('2026-10-04T02:00:00Z');

MATCH (sn:SourceSnapshot {uid: 'hu:snapshot:elysium-basis-lot-p098-01-2026-10-04'}), (l:SourceLocator {uid: 'hu:locator:elysium-basis-lot-p098-01-attribution'})
MERGE (sn)-[:HAS_LOCATOR]->(l);

MERGE (n:InformationArtifact:SourceLocator {uid: 'hu:locator:elysium-basis-lot-p098-01-lots-70579'})
SET n.artifactType = 'SOURCE_LOCATOR', n.uri = 'https://www.elysiumhealth.com/pages/basis-lot-info?lotNumber=P098-01', n.selectorKind = 'TEXT_QUOTE', n.privacyClass = 'PUBLIC', n.exact = '#70579 Exp. 10/2027', n.quoteHash = 'sha256:1c2cc936995b4074df44e7bbb0878dc24228b3edb6b9e2b9fb8293d790354632', n.normalizationVersion = 'NFC-WS1', n.createdAt = datetime('2026-10-04T02:00:00Z'), n.updatedAt = datetime('2026-10-04T02:00:00Z');

MATCH (sn:SourceSnapshot {uid: 'hu:snapshot:elysium-basis-lot-p098-01-2026-10-04'}), (l:SourceLocator {uid: 'hu:locator:elysium-basis-lot-p098-01-lots-70579'})
MERGE (sn)-[:HAS_LOCATOR]->(l);

MERGE (n:InformationArtifact:SourceLocator {uid: 'hu:locator:elysium-basis-lot-p098-01-lots-70918'})
SET n.artifactType = 'SOURCE_LOCATOR', n.uri = 'https://www.elysiumhealth.com/pages/basis-lot-info?lotNumber=P098-01', n.selectorKind = 'TEXT_QUOTE', n.privacyClass = 'PUBLIC', n.exact = '#70918 Exp. 12/2027', n.quoteHash = 'sha256:f282eeed678a533cbe9169e94aceed3062474c1efec0a4d8cf52c5f7297bd9f3', n.normalizationVersion = 'NFC-WS1', n.createdAt = datetime('2026-10-04T02:00:00Z'), n.updatedAt = datetime('2026-10-04T02:00:00Z');

MATCH (sn:SourceSnapshot {uid: 'hu:snapshot:elysium-basis-lot-p098-01-2026-10-04'}), (l:SourceLocator {uid: 'hu:locator:elysium-basis-lot-p098-01-lots-70918'})
MERGE (sn)-[:HAS_LOCATOR]->(l);

MERGE (n:InformationArtifact:SourceLocator {uid: 'hu:locator:elysium-basis-lot-p098-01-lots-70064'})
SET n.artifactType = 'SOURCE_LOCATOR', n.uri = 'https://www.elysiumhealth.com/pages/basis-lot-info?lotNumber=P098-01', n.selectorKind = 'TEXT_QUOTE', n.privacyClass = 'PUBLIC', n.exact = '#70064 Exp. 07/2027', n.quoteHash = 'sha256:2e0cf9fa917dd156f563e716f594da1dbc1358542e8a3ed802aafcbec0ad4c4b', n.normalizationVersion = 'NFC-WS1', n.createdAt = datetime('2026-10-04T02:00:00Z'), n.updatedAt = datetime('2026-10-04T02:00:00Z');

MATCH (sn:SourceSnapshot {uid: 'hu:snapshot:elysium-basis-lot-p098-01-2026-10-04'}), (l:SourceLocator {uid: 'hu:locator:elysium-basis-lot-p098-01-lots-70064'})
MERGE (sn)-[:HAS_LOCATOR]->(l);

MERGE (n:InformationArtifact:SourceLocator {uid: 'hu:locator:elysium-basis-lot-p098-01-lots-r110'})
SET n.artifactType = 'SOURCE_LOCATOR', n.uri = 'https://www.elysiumhealth.com/pages/basis-lot-info?lotNumber=P098-01', n.selectorKind = 'TEXT_QUOTE', n.privacyClass = 'PUBLIC', n.exact = '#R110-01 Exp. 11/2026', n.quoteHash = 'sha256:89733adc970ba2861bc3228ddd1cffcc42f2dc9266967834f33f9603e567bedb', n.normalizationVersion = 'NFC-WS1', n.createdAt = datetime('2026-10-04T02:00:00Z'), n.updatedAt = datetime('2026-10-04T02:00:00Z');

MATCH (sn:SourceSnapshot {uid: 'hu:snapshot:elysium-basis-lot-p098-01-2026-10-04'}), (l:SourceLocator {uid: 'hu:locator:elysium-basis-lot-p098-01-lots-r110'})
MERGE (sn)-[:HAS_LOCATOR]->(l);

MERGE (n:InformationArtifact:SourceLocator {uid: 'hu:locator:elysium-basis-lot-p098-01-lots-r173'})
SET n.artifactType = 'SOURCE_LOCATOR', n.uri = 'https://www.elysiumhealth.com/pages/basis-lot-info?lotNumber=P098-01', n.selectorKind = 'TEXT_QUOTE', n.privacyClass = 'PUBLIC', n.exact = '#R173-01 Exp. 01/2027', n.quoteHash = 'sha256:5ca45427f663567f7f0de67b68cac66d725c8d3fe6275afd68141fc0018258f9', n.normalizationVersion = 'NFC-WS1', n.createdAt = datetime('2026-10-04T02:00:00Z'), n.updatedAt = datetime('2026-10-04T02:00:00Z');

MATCH (sn:SourceSnapshot {uid: 'hu:snapshot:elysium-basis-lot-p098-01-2026-10-04'}), (l:SourceLocator {uid: 'hu:locator:elysium-basis-lot-p098-01-lots-r173'})
MERGE (sn)-[:HAS_LOCATOR]->(l);

MERGE (n:InformationArtifact:SourceLocator {uid: 'hu:locator:elysium-basis-lot-p098-01-lots-m259'})
SET n.artifactType = 'SOURCE_LOCATOR', n.uri = 'https://www.elysiumhealth.com/pages/basis-lot-info?lotNumber=P098-01', n.selectorKind = 'TEXT_QUOTE', n.privacyClass = 'PUBLIC', n.exact = '#M259-01 Manuf. 11/2024', n.quoteHash = 'sha256:98f8992f8d997fb2decaf4d50a61fd3277b9238dce84fd071b8a7bcf5b5c514a', n.normalizationVersion = 'NFC-WS1', n.createdAt = datetime('2026-10-04T02:00:00Z'), n.updatedAt = datetime('2026-10-04T02:00:00Z');

MATCH (sn:SourceSnapshot {uid: 'hu:snapshot:elysium-basis-lot-p098-01-2026-10-04'}), (l:SourceLocator {uid: 'hu:locator:elysium-basis-lot-p098-01-lots-m259'})
MERGE (sn)-[:HAS_LOCATOR]->(l);

MERGE (n:InformationArtifact:SourceLocator {uid: 'hu:locator:elysium-basis-lot-p098-01-lots-m099'})
SET n.artifactType = 'SOURCE_LOCATOR', n.uri = 'https://www.elysiumhealth.com/pages/basis-lot-info?lotNumber=P098-01', n.selectorKind = 'TEXT_QUOTE', n.privacyClass = 'PUBLIC', n.exact = '#M099-01 Manuf. 05/2024', n.quoteHash = 'sha256:bccf9256405db35d02966a3de6703c49f1e1c1db0e8d122ffe38dca34c243f66', n.normalizationVersion = 'NFC-WS1', n.createdAt = datetime('2026-10-04T02:00:00Z'), n.updatedAt = datetime('2026-10-04T02:00:00Z');

MATCH (sn:SourceSnapshot {uid: 'hu:snapshot:elysium-basis-lot-p098-01-2026-10-04'}), (l:SourceLocator {uid: 'hu:locator:elysium-basis-lot-p098-01-lots-m099'})
MERGE (sn)-[:HAS_LOCATOR]->(l);

MERGE (n:InformationArtifact:SourceLocator {uid: 'hu:locator:elysium-basis-lot-p098-01-lots-m062'})
SET n.artifactType = 'SOURCE_LOCATOR', n.uri = 'https://www.elysiumhealth.com/pages/basis-lot-info?lotNumber=P098-01', n.selectorKind = 'TEXT_QUOTE', n.privacyClass = 'PUBLIC', n.exact = '#M062-01 Manuf. 03/2024', n.quoteHash = 'sha256:0a65217ae8c41e9d859d278f28f53efc39b622b10914fdbbe5eb7fe403d4321b', n.normalizationVersion = 'NFC-WS1', n.createdAt = datetime('2026-10-04T02:00:00Z'), n.updatedAt = datetime('2026-10-04T02:00:00Z');

MATCH (sn:SourceSnapshot {uid: 'hu:snapshot:elysium-basis-lot-p098-01-2026-10-04'}), (l:SourceLocator {uid: 'hu:locator:elysium-basis-lot-p098-01-lots-m062'})
MERGE (sn)-[:HAS_LOCATOR]->(l);

MERGE (n:InformationArtifact:SourceLocator {uid: 'hu:locator:nsf-info-306-chester-basis-row'})
SET n.artifactType = 'SOURCE_LOCATOR', n.uri = 'https://info.nsf.org/Certified/BannedSub/Listings.asp?Company=C0364723&Standard=306', n.selectorKind = 'TEXT_QUOTE', n.privacyClass = 'PUBLIC', n.exact = 'Facility : Chester, NY Cellular Support/Men/Senior/Vitamin/Women | Basis | 70064 70579 70918 P098-01 70969 | Capsules | 2 capsules |', n.quoteHash = 'sha256:3f89cade1250cfd776ace476341fe28c796d9477430fc2d33341cb35a498e8c4', n.normalizationVersion = 'NFC-WS1', n.createdAt = datetime('2026-10-04T02:00:00Z'), n.updatedAt = datetime('2026-10-04T02:00:00Z');

MATCH (sn:SourceSnapshot {uid: 'hu:snapshot:nsf-info-listing-c0364723-306-2026-10-04'}), (l:SourceLocator {uid: 'hu:locator:nsf-info-306-chester-basis-row'})
MERGE (sn)-[:HAS_LOCATOR]->(l);

MERGE (n:InformationArtifact:SourceLocator {uid: 'hu:locator:nsf-info-306-windsor-basis-row'})
SET n.artifactType = 'SOURCE_LOCATOR', n.uri = 'https://info.nsf.org/Certified/BannedSub/Listings.asp?Company=C0364723&Standard=306', n.selectorKind = 'TEXT_QUOTE', n.privacyClass = 'PUBLIC', n.exact = 'Facility : Windsor, Ontario, Canada Vegetarian/Vitamin | Basis | M062-01 M099-01 M259-01 R1110-01 R173-01 | Capsule | 2 capsules |', n.quoteHash = 'sha256:ec01f340ac44bf469b628a4115fd59cb67c72c33541e29febc4f6e2d3d44e4f9', n.normalizationVersion = 'NFC-WS1', n.createdAt = datetime('2026-10-04T02:00:00Z'), n.updatedAt = datetime('2026-10-04T02:00:00Z');

MATCH (sn:SourceSnapshot {uid: 'hu:snapshot:nsf-info-listing-c0364723-306-2026-10-04'}), (l:SourceLocator {uid: 'hu:locator:nsf-info-306-windsor-basis-row'})
MERGE (sn)-[:HAS_LOCATOR]->(l);

MERGE (n:InformationArtifact:SourceLocator {uid: 'hu:locator:nsf-info-306-currency'})
SET n.artifactType = 'SOURCE_LOCATOR', n.uri = 'https://info.nsf.org/Certified/BannedSub/Listings.asp?Company=C0364723&Standard=306', n.selectorKind = 'TEXT_QUOTE', n.privacyClass = 'PUBLIC', n.exact = 'These NSF Official Listings are current as of Saturday, October 3, 2026 at 12:15 a.m. Eastern Time.', n.quoteHash = 'sha256:af8baf9ab2d13c38ee05f369ff37f125a75c1bc95cc2740c1312d5f8dd0375a2', n.normalizationVersion = 'NFC-WS1', n.createdAt = datetime('2026-10-04T02:00:00Z'), n.updatedAt = datetime('2026-10-04T02:00:00Z');

MATCH (sn:SourceSnapshot {uid: 'hu:snapshot:nsf-info-listing-c0364723-306-2026-10-04'}), (l:SourceLocator {uid: 'hu:locator:nsf-info-306-currency'})
MERGE (sn)-[:HAS_LOCATOR]->(l);

MERGE (n:InformationArtifact:SourceLocator {uid: 'hu:locator:nsfsport-1786167-lots'})
SET n.artifactType = 'SOURCE_LOCATOR', n.uri = 'https://www.nsfsport.com/certified-products/listing-detail.php?id=1786167', n.selectorKind = 'TEXT_QUOTE', n.privacyClass = 'PUBLIC', n.exact = '| Lot # | P098-01 70579 70918 70969 70064 |', n.quoteHash = 'sha256:5562c17ee26577615a1863534fe10d91befa609b20b7da0892c96f6304367b7f', n.normalizationVersion = 'NFC-WS1', n.createdAt = datetime('2026-10-04T02:00:00Z'), n.updatedAt = datetime('2026-10-04T02:00:00Z');

MATCH (sn:SourceSnapshot {uid: 'hu:snapshot:nsfsport-listing-1786167-2026-10-04'}), (l:SourceLocator {uid: 'hu:locator:nsfsport-1786167-lots'})
MERGE (sn)-[:HAS_LOCATOR]->(l);

MERGE (n:InformationArtifact:SourceLocator {uid: 'hu:locator:nsfsport-1463170-lots'})
SET n.artifactType = 'SOURCE_LOCATOR', n.uri = 'https://www.nsfsport.com/certified-products/listing-detail.php?id=1463170', n.selectorKind = 'TEXT_QUOTE', n.privacyClass = 'PUBLIC', n.exact = '| Lot # | R173-01M099-01R1110-01M259-01M062-01 |', n.quoteHash = 'sha256:5afc66fdb544f76aca1d44c682d29f98926ebd4bbdd3782a8cb89e0e3fc61d61', n.normalizationVersion = 'NFC-WS1', n.createdAt = datetime('2026-10-04T02:00:00Z'), n.updatedAt = datetime('2026-10-04T02:00:00Z');

MATCH (sn:SourceSnapshot {uid: 'hu:snapshot:nsfsport-listing-1463170-2026-10-04'}), (l:SourceLocator {uid: 'hu:locator:nsfsport-1463170-lots'})
MERGE (sn)-[:HAS_LOCATOR]->(l);

MERGE (n:InformationArtifact:SourceLocator {uid: 'hu:locator:chromadex-surveillance-basis-row'})
SET n.artifactType = 'SOURCE_LOCATOR', n.uri = 'https://s205.q4cdn.com/770776702/files/doc_downloads/MarketSurveillance/2025/Quantitative-Analysis-of-Nicotinamide-Riboside-Consumer-Products-and-Counterfeit-Tru-Niagen-June-2025.pdf', n.selectorKind = 'PDF_PAGE', n.privacyClass = 'PUBLIC', n.exact = '| Elysium Health | Basis | Capsule | 250 | 261 |', n.quoteHash = 'sha256:596fe2bdbe7201b23a208b4a408423208a6619ada6961538deb09417df182adc', n.normalizationVersion = 'NFC-WS1', n.page = 5, n.createdAt = datetime('2026-10-04T02:00:00Z'), n.updatedAt = datetime('2026-10-04T02:00:00Z');

MATCH (sn:SourceSnapshot {uid: 'hu:snapshot:chromadex-nr-surveillance-2025-06-2026-10-04'}), (l:SourceLocator {uid: 'hu:locator:chromadex-surveillance-basis-row'})
MERGE (sn)-[:HAS_LOCATOR]->(l);

MERGE (n:InformationArtifact:SourceLocator {uid: 'hu:locator:chromadex-surveillance-method'})
SET n.artifactType = 'SOURCE_LOCATOR', n.uri = 'https://s205.q4cdn.com/770776702/files/doc_downloads/MarketSurveillance/2025/Quantitative-Analysis-of-Nicotinamide-Riboside-Consumer-Products-and-Counterfeit-Tru-Niagen-June-2025.pdf', n.selectorKind = 'PDF_PAGE', n.privacyClass = 'PUBLIC', n.exact = 'Between February 2023 and June 2025, fifty US-based consumer products labeled as containing NR were purchased from Amazon and various brand websites and analyzed for NR content using a validated High Performance Liquid Chromatography (HPLC) method with a UV-Vis detector.', n.quoteHash = 'sha256:1a33185a25e696d261811b215cb2e9db0e25468c624344b533044da282e97376', n.normalizationVersion = 'NFC-WS1', n.page = 3, n.createdAt = datetime('2026-10-04T02:00:00Z'), n.updatedAt = datetime('2026-10-04T02:00:00Z');

MATCH (sn:SourceSnapshot {uid: 'hu:snapshot:chromadex-nr-surveillance-2025-06-2026-10-04'}), (l:SourceLocator {uid: 'hu:locator:chromadex-surveillance-method'})
MERGE (sn)-[:HAS_LOCATOR]->(l);

MERGE (n:InformationArtifact:SourceLocator {uid: 'hu:locator:synthetic-lab-z-p098-01-rev00-potency'})
SET n.artifactType = 'SOURCE_LOCATOR', n.uri = 'urn:synthetic:w12:lab-z-coa-LZ-2026-0412', n.selectorKind = 'SECTION', n.privacyClass = 'PUBLIC', n.section = 'rev 00: NR chloride 263 mg/serving, U = 11 mg (k = 2), method LZ-HPLC-NR-003 rev 2, spec NLT 250 mg/serving', n.createdAt = datetime('2026-10-04T02:00:00Z'), n.updatedAt = datetime('2026-10-04T02:00:00Z');

MATCH (sn:SourceSnapshot {uid: 'hu:snapshot:synthetic-lab-z-coa-basis-p098-01-rev00'}), (l:SourceLocator {uid: 'hu:locator:synthetic-lab-z-p098-01-rev00-potency'})
MERGE (sn)-[:HAS_LOCATOR]->(l);

MERGE (n:InformationArtifact:SourceLocator {uid: 'hu:locator:synthetic-lab-z-p098-01-rev00-ecoli'})
SET n.artifactType = 'SOURCE_LOCATOR', n.uri = 'urn:synthetic:w12:lab-z-coa-LZ-2026-0412', n.selectorKind = 'SECTION', n.privacyClass = 'PUBLIC', n.section = 'rev 00: E. coli Absent in 10 g (USP <2022>)', n.createdAt = datetime('2026-10-04T02:00:00Z'), n.updatedAt = datetime('2026-10-04T02:00:00Z');

MATCH (sn:SourceSnapshot {uid: 'hu:snapshot:synthetic-lab-z-coa-basis-p098-01-rev00'}), (l:SourceLocator {uid: 'hu:locator:synthetic-lab-z-p098-01-rev00-ecoli'})
MERGE (sn)-[:HAS_LOCATOR]->(l);

MERGE (n:InformationArtifact:SourceLocator {uid: 'hu:locator:synthetic-lab-z-p098-01-rev00-header'})
SET n.artifactType = 'SOURCE_LOCATOR', n.uri = 'urn:synthetic:w12:lab-z-coa-LZ-2026-0412', n.selectorKind = 'SECTION', n.privacyClass = 'PUBLIC', n.section = 'rev 00: certificate LZ-2026-0412-00, lot P098-01, signed by QA manager 2026-04-20', n.createdAt = datetime('2026-10-04T02:00:00Z'), n.updatedAt = datetime('2026-10-04T02:00:00Z');

MATCH (sn:SourceSnapshot {uid: 'hu:snapshot:synthetic-lab-z-coa-basis-p098-01-rev00'}), (l:SourceLocator {uid: 'hu:locator:synthetic-lab-z-p098-01-rev00-header'})
MERGE (sn)-[:HAS_LOCATOR]->(l);

MERGE (n:InformationArtifact:SourceLocator {uid: 'hu:locator:synthetic-lab-z-p098-01-rev01-potency'})
SET n.artifactType = 'SOURCE_LOCATOR', n.uri = 'urn:synthetic:w12:lab-z-coa-LZ-2026-0412', n.selectorKind = 'SECTION', n.privacyClass = 'PUBLIC', n.section = 'rev 01 (corrected transcription): NR chloride 236 mg/serving, U = 10 mg (k = 2)', n.createdAt = datetime('2026-10-04T02:00:00Z'), n.updatedAt = datetime('2026-10-04T02:00:00Z');

MATCH (sn:SourceSnapshot {uid: 'hu:snapshot:synthetic-lab-z-coa-basis-p098-01-rev01'}), (l:SourceLocator {uid: 'hu:locator:synthetic-lab-z-p098-01-rev01-potency'})
MERGE (sn)-[:HAS_LOCATOR]->(l);

MERGE (n:InformationArtifact:SourceLocator {uid: 'hu:locator:synthetic-lab-z-p098-01-rev01-header'})
SET n.artifactType = 'SOURCE_LOCATOR', n.uri = 'urn:synthetic:w12:lab-z-coa-LZ-2026-0412', n.selectorKind = 'SECTION', n.privacyClass = 'PUBLIC', n.section = 'rev 01: certificate LZ-2026-0412-01 supersedes -00, signed 2026-05-02', n.createdAt = datetime('2026-10-04T02:00:00Z'), n.updatedAt = datetime('2026-10-04T02:00:00Z');

MATCH (sn:SourceSnapshot {uid: 'hu:snapshot:synthetic-lab-z-coa-basis-p098-01-rev01'}), (l:SourceLocator {uid: 'hu:locator:synthetic-lab-z-p098-01-rev01-header'})
MERGE (sn)-[:HAS_LOCATOR]->(l);

MERGE (n:InformationArtifact:SourceLocator {uid: 'hu:locator:synthetic-lab-z-70579-ecoli'})
SET n.artifactType = 'SOURCE_LOCATOR', n.uri = 'urn:synthetic:w12:lab-z-coa-LZ-2026-0415', n.selectorKind = 'SECTION', n.privacyClass = 'PUBLIC', n.section = 'E. coli (enumeration) < 10 CFU/g (LOD 10 CFU/g)', n.createdAt = datetime('2026-10-04T02:00:00Z'), n.updatedAt = datetime('2026-10-04T02:00:00Z');

MATCH (sn:SourceSnapshot {uid: 'hu:snapshot:synthetic-lab-z-coa-basis-70579'}), (l:SourceLocator {uid: 'hu:locator:synthetic-lab-z-70579-ecoli'})
MERGE (sn)-[:HAS_LOCATOR]->(l);

MERGE (n:InformationArtifact:SourceLocator {uid: 'hu:locator:synthetic-lab-z-70579-header'})
SET n.artifactType = 'SOURCE_LOCATOR', n.uri = 'urn:synthetic:w12:lab-z-coa-LZ-2026-0415', n.selectorKind = 'SECTION', n.privacyClass = 'PUBLIC', n.section = 'certificate LZ-2026-0415-00, lot 70579, signed', n.createdAt = datetime('2026-10-04T02:00:00Z'), n.updatedAt = datetime('2026-10-04T02:00:00Z');

MATCH (sn:SourceSnapshot {uid: 'hu:snapshot:synthetic-lab-z-coa-basis-70579'}), (l:SourceLocator {uid: 'hu:locator:synthetic-lab-z-70579-header'})
MERGE (sn)-[:HAS_LOCATOR]->(l);

MERGE (n:InformationArtifact:SourceLocator {uid: 'hu:locator:synthetic-lab-z-70064-stability'})
SET n.artifactType = 'SOURCE_LOCATOR', n.uri = 'urn:synthetic:w12:lab-z-stability-LZ-STB-2026-07', n.selectorKind = 'SECTION', n.privacyClass = 'PUBLIC', n.section = '18-month stability: NR chloride 258 mg/serving, U = 9 mg (k = 2); release NLT 275, shelf-life NLT 250', n.createdAt = datetime('2026-10-04T02:00:00Z'), n.updatedAt = datetime('2026-10-04T02:00:00Z');

MATCH (sn:SourceSnapshot {uid: 'hu:snapshot:synthetic-lab-z-stability-basis-70064'}), (l:SourceLocator {uid: 'hu:locator:synthetic-lab-z-70064-stability'})
MERGE (sn)-[:HAS_LOCATOR]->(l);

MERGE (n:InformationArtifact:SourceLocator {uid: 'hu:locator:synthetic-nsf-455-2-scope'})
SET n.artifactType = 'SOURCE_LOCATOR', n.uri = 'urn:synthetic:w12:nsf-455-2-listing-synthetic-plant', n.selectorKind = 'SECTION', n.privacyClass = 'PUBLIC', n.section = 'NSF/ANSI 455-2 GMP: Synthetic dietary supplement plant', n.createdAt = datetime('2026-10-04T02:00:00Z'), n.updatedAt = datetime('2026-10-04T02:00:00Z');

MATCH (sn:SourceSnapshot {uid: 'hu:snapshot:synthetic-nsf-455-2-listing'}), (l:SourceLocator {uid: 'hu:locator:synthetic-nsf-455-2-scope'})
MERGE (sn)-[:HAS_LOCATOR]->(l);

MERGE (n:InformationArtifact:SourceLocator {uid: 'hu:locator:synthetic-17025-scope'})
SET n.artifactType = 'SOURCE_LOCATOR', n.uri = 'urn:synthetic:w12:iso17025-accreditation-lab-z', n.selectorKind = 'SECTION', n.privacyClass = 'PUBLIC', n.section = 'ISO/IEC 17025:2017 accreditation, chemical and microbiological testing: Synthetic Lab Z', n.createdAt = datetime('2026-10-04T02:00:00Z'), n.updatedAt = datetime('2026-10-04T02:00:00Z');

MATCH (sn:SourceSnapshot {uid: 'hu:snapshot:synthetic-17025-accreditation-lab-z'}), (l:SourceLocator {uid: 'hu:locator:synthetic-17025-scope'})
MERGE (sn)-[:HAS_LOCATOR]->(l);

MERGE (n:InformationArtifact:SourceLocator {uid: 'hu:locator:synthetic-nsfsport-1786167-later-lots'})
SET n.artifactType = 'SOURCE_LOCATOR', n.uri = 'urn:synthetic:w12:nsfsport-1786167-later-capture', n.selectorKind = 'SECTION', n.privacyClass = 'PUBLIC', n.section = 'Lot # P098-01 70579 70918 70969 70064 P120-01 (synthetic later capture)', n.createdAt = datetime('2026-10-04T02:00:00Z'), n.updatedAt = datetime('2026-10-04T02:00:00Z');

MATCH (sn:SourceSnapshot {uid: 'hu:snapshot:synthetic-nsfsport-listing-1786167-later'}), (l:SourceLocator {uid: 'hu:locator:synthetic-nsfsport-1786167-later-lots'})
MERGE (sn)-[:HAS_LOCATOR]->(l);

// Certification programmes (real names); what each certifies
MERGE (n:CertificationProgram:Entity {uid: 'hu:cert-program:nsf-certified-for-sport'})
SET n.entityType = 'CERTIFICATION_PROGRAM', n.privacyClass = 'PUBLIC', n.schemaVersion = 'w12-proposal-0.1', n.name = 'NSF Certified for Sport', n.standard = 'NSF Certification Guideline 306', n.certifiedObjectKind = 'LOT', n.id = 'nsf-certified-for-sport', n.createdAt = datetime('2026-10-04T02:00:00Z'), n.updatedAt = datetime('2026-10-04T02:00:00Z');

MERGE (n:CertificationProgram:Entity {uid: 'hu:cert-program:nsf-ansi-455-2-gmp'})
SET n.entityType = 'CERTIFICATION_PROGRAM', n.privacyClass = 'PUBLIC', n.schemaVersion = 'w12-proposal-0.1', n.name = 'NSF/ANSI 455-2 dietary supplement GMP certification', n.standard = 'NSF/ANSI 455-2', n.certifiedObjectKind = 'FACILITY', n.id = 'nsf-ansi-455-2-gmp', n.createdAt = datetime('2026-10-04T02:00:00Z'), n.updatedAt = datetime('2026-10-04T02:00:00Z');

MERGE (n:CertificationProgram:Entity {uid: 'hu:cert-program:synthetic-iso-17025-accreditation'})
SET n.entityType = 'CERTIFICATION_PROGRAM', n.privacyClass = 'PUBLIC', n.schemaVersion = 'w12-proposal-0.1', n.name = 'ISO/IEC 17025 laboratory accreditation (synthetic accreditation body)', n.standard = 'ISO/IEC 17025:2017', n.certifiedObjectKind = 'LABORATORY', n.id = 'synthetic-iso-17025-accreditation', n.createdAt = datetime('2026-10-04T02:00:00Z'), n.updatedAt = datetime('2026-10-04T02:00:00Z');

